### DISCUSSION TITLE
java.net.SocketTimeoutException: Read timed out while downloading libraries.

### DISCUSSION THREAD

**Discussion by KS-HTK** [itzg/docker-minecraft-server#1003] [Q&A] [answered]
I get this Issue:
```
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
        at net.minecraftforge.installer.DownloadUtils.getConnection(DownloadUtils.java:202)
        at net.minecraftforge.installer.DownloadUtils.downloadMirrors(DownloadUtils.java:252)
        at net.minecraftforge.installer.json.Install.getMirror(Install.java:116)
        at net.minecraftforge.installer.actions.ServerInstall.run(ServerInstall.java:53)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:127)
```
        
While trying to install a CurseForge Modpack using following Docker Compose:
```yaml
version: '3.6'
services:
  minecraft:
    container_name: val3
    image: itzg/minecraft-server:java8
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      VIEW_DISTANCE: "12"
      MOTD: "Valhelsia 3 Server"

      TYPE: "CURSEFORGE"
      VERSION: "1.16.5"
      CF_SERVER_MOD: "/modpacks/valhelsia3-server.zip"
      CF_BASE_DIR: "/data"
      FORCE_REDOWNLOAD: "true"
      REMOVE_OLD_MODS: "true"
      ENABLE_AUTOPAUSE: "true"
      AUTOPAUSE_TIMEOUT_EST: "7200"
      AUTOPAUSE_TIMEOUT_KN: "240"
      TZ: "Europe/Berlin"
      MEMORY: "10G"
      USE_AIKAR_FLAGS: "true"
    volumes:
      - "~/val3/data:/data"
      - "~/modpacks:/modpacks"
    restart: always
```

**Comment by itzg** [comment]
I'm afraid that's not something I can fix from the the image. As you've probably the noticed the failure is within the forge installer and is somehow influenced by network connectivity towards their library repo.

**Comment by itzg** [comment]
If you don't mind, I can convert this issue to a discussion to see if others have encountered and fixed this scenario.

**Comment by KS-HTK** [comment]
Thank you for the Info, changing this into a Discussion seems to be a good Idea.
I had tried to find a solution and have not found anything helpfull yet.
If terminating the `docker-compose` and then starting the docker container it just errors out saying to rerun the install script.
Is it possible to start the ServerStart.sh from within the Container?
Or is that what `docker start` is doing?

I was able to run the `ServerStart.bat` locally and did not run into this issue. It seems that the response to the first library download takes a lot longer than any subsequent ones. Is there a way to set a higher timeout for downloads or would the script of the Modpack have to do that?

**Comment by itzg** [comment]
> Is it possible to start the ServerStart.sh from within the Container?
Or is that what docker start is doing?

Yes, that's what it already does.

So, again, the start script provided by the modpack is beyond my control via the image.

Modpack scripts are inconsistent and some are broken, so you could also try

https://github.com/itzg/docker-minecraft-server#buggy-start-scripts

**Comment by KS-HTK** [comment]
This seems to be some other issue as `curl` is unable to download the forge files aswell.
I have created a `test` container running this compose:

```yaml
version: '3.6'
services:
  minecraft:
    container_name: test
    image: itzg/minecraft-server
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"

      TYPE: "FORGE"
      VERSION: "1.16.5"
      FORGEVERSION: "36.2.2"
      FORGE_INSTALLER_URL: "https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.2/forge-1.16.5-36.2.2-installer.jar"
      TZ: "Europe/Berlin"
      MAX_MEMORY: "4G"
      INIT_MEMORY: "1G"
    volumes:
      - "~/test/data:/data"
    restart: always
```
BTW: Not specifying the Download URL results in the non functioning URL: htt<span>ps:/</span>/maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.2<span style="color:red">**-1.16.5**</span>/forge-1.16.5-36.2.2<span style="color:red">**-1.16.5**</span>-installer.jar

I have experimented around a bit more. But I cant seem to pinpoint the problem.
First I tought it was the container networking. But attaching a `praqma/network-multitool` container to the `test_default` network seemd to be able to resolv hostnames and obtain files using `curl`.

The Out put of the `test` continer:
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Aug 16 21:14 /data'
[init] Resolved version given 1.16.5 into 1.16.5
[init] Resolving type given FORGE
[init] **********************************************************************
[init] WARNING: The image tag itzg/minecraft-server:java8 is recommended
[init]          since some mods require Java 8
[init]          Exception traces reporting ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader
[init]          can be fixed with java8
[init] **********************************************************************
[init] Downloading https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.2/forge-1.16.5-36.2.2-installer.jar ...
curl: (6) Could not resolve host: maven.minecraftforge.net
[init] Failed to download from given location https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.2/forge-1.16.5-36.2.2-installer.jar
```

So this seems to be a Issue with the docker Image? That seems odd. It did not resolve by removing the Image and redownloading.
I did try that.

**Comment by KS-HTK** [comment]
Did a lot more digging. I have come to the conclusion this must be somehow related to the container image.
But since I do not know much about docker images I can't continue debugging from this point on.

@itzg Here is what I have found out so far.
1.  As mentioned before: The generated Forge download links are wrong. Having an additional version number in them:
[htt<span>ps:/</span>/maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.2<span>***-1.16.5***</span>/forge-1.16.5-36.2.2<span>***-1.16.5***</span>-installer.jar](https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.2-1.16.5/forge-1.16.5-36.2.2-1.16.5-installer.jar)
This also applies to the 1.17.1 link generated by the container.
2. Something is wrong with file downloading in general.

Downloading the minecraft server jar from mojang works fine.
Running this compose is flawless.
```yml
version: '3.6'
services:
  minecraft:
    container_name: test
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "true"
    volumes:
      - "~/test/data:/data"
    restart: unless-stopped
```
Running this compose fails to download even the Forge installer even if provided with the correct link.
```yml
version: '3.6'
services:
  minecraft:
    container_name: test2
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.17.1"
      FORGEVERSION: "37.0.48"
      FORGE_INSTALLER: "https://maven.minecraftforge.net/net/minecraftforge/forge/1.17.1-37.0.48/forge-1.17.1-37.0.48-installer.jar"
    volumes:
      - "~/test2/data:/data"
    restart: unless-stopped
  ```
```
Recreating test2 ... done
Attaching to test2
test2        | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Aug 31 10:25 /data'
test2        | [init] Resolved version given 1.17.1 into 1.17.1
test2        | [init] Resolving type given FORGE
test2        | [init] ERROR: the given Forge installer doesn't exist : https://maven.minecraftforge.net/net/minecraftforge/forge/1.17.1-37.0.48/forge-1.17.1-37.0.48-installer.jar
test exited with code 2
```
I am not sure if the fix for this is also the solution for the original problem. But since I have the same Issue on different operating systems it seems to be related to the container.
