### DISCUSSION TITLE
How to install and run Dynmap in docker container

### DISCUSSION THREAD

**Discussion by Peterkal2112** [itzg/docker-minecraft-server#1007] [Q&A]
Hello,
I want to use plugin Dynmap with this docker container Minecraft server.
Do you, someone, know how to install it and what i need for it ??
sincerely,

**Comment by KS-HTK** [comment]
Requirements:
- Database (MySQL/MariaDB) I've only used MySQL though.
- Webserver
These could be run in docker container aswell.
The Mapfiles on the Webserver can get qute large so a bit of storage is required.

The config file of dynmap explains the process quite well.
Basically copy the `web` folder to the webserver and configure both the webfiles and plugin to use the same database.

A detailed Tutorial can be found here. Though I have not actually used it. So I dont know how good the tutorial is.
https://github.com/webbukkit/dynmap/issues/2609

**Comment by JurgenKuyper** [comment]
can't you just forward port 8123 through the container and it should work?

**Reply by KS-HTK** [reply]
Good Point. Haddn't tried that as my goal originally was to run Dynmap on a different Server altogether.
But yes, exposing that port should work aswell.

**Reply by MaxLevs** [reply]
But what if you have a bunch of servers with dynmap installed on every single one of them and you don't want to deal with all this ports?
That's the situation where you need a single entrypoint for all requests. Maybe you will just forward connection between servers' dynmap http-servers or maybe at this point you already want to have a dedicated frontend app to load all tiles yourself. And you can disigne it as you want too

**Comment by willis936** [comment]
I'm trying to solve this too.  I can get port 8123 out, but haven't gotten an nginx reverse proxy working yet.  Regardless, I want to use fast-cgi/php-fpm sockets for dynmap so the dynmap can run even when the minecraft server is decomissioned.  I've successfully done this for non-containerized minecraft servers.  I haven't figured out what dynmap tries to reach out to, which is what needs to be connected via docker.  Exposing ports 80, 443, and 9000 don't work.  Port 9000 doesn't work because I'm using the php-fpm sock solution.  If I switched to using port 9000 instead I'm sure it would work.  Does anyone know how to get php-fpm sock shared with a docker container?

I made a reddit post asking about this when I should have been sleeping after going at it for 10 hours.

https://reddit.com/r/admincraft/comments/12bcjk6/dynmap_external_webserver_on_a_112_itzg_docker/

**Reply by willis936** [reply]
My understanding is that there is no socket connection needed for external webserver, just the ability to write json files in the web directory.

When I shell into the docker container I can manually write files to the mounted web directory without issue, but the minecraft console says "permission denied" when trying to write json files.  When using the internal webserver it has no issue writing image files to the same mounted web directory, so I'm not sure why there is a permission issue.

**Reply by willis936** [reply]
The /data volume shows ownership of "minecraft" from within the container while the /web volume I added for dynmap shows ownership of "root".  I'm pretty sure this is the source of the headache.  I just need to figure out how to properly convey write permissions of the /web volume to the "minecraft" user that is running java.

**Reply by willis936** [reply]
Got it working.  The answer was running `chown -R 1000:1000` on the host web directory.  I checked uid by running `cat /etc/passwd` from within the container.

https://stackoverflow.com/questions/39397548/how-to-give-non-root-user-in-docker-container-access-to-a-volume-mounted-on-the

**Comment by trevoedwards** [comment]
> Got it working. The answer was running `chown -R 1000:1000` on the host web directory. I checked uid by running `cat /etc/passwd` from within the container.
> 
> https://stackoverflow.com/questions/39397548/how-to-give-non-root-user-in-docker-container-access-to-a-volume-mounted-on-the

Are you using docker-compose? If so, any chance you could share what your compose file looks like?

**Reply by willis936** [reply]
```
version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:${IMAGE_TAG:-java8-jdk}
    environment:
      TYPE: "FORGE"
      VERSION: "1.12.2"
      FORGE_VERSION: "14.23.5.2860"
      JVM_DD_OPTS: "fml.queryResult:confirm"
      MOTD: "GCP 1.6.3 Server"
      SERVER_NAME: "GCP 1.6.3 Server"
      EULA: "true"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "4G"
      TZ: "America/New_York"
      OPS: "[REDACTED]"
      WHITE_LIST_USERS: "[REDACTED]"
      DIFFICULTY: "peaceful"
      LEVEL_TYPE: "default"
      SEED: 1491928322975805150
      MAX_WORLD_SIZE: 4096
      MAX_PLAYERS: 10
      GUI: "false"
      ONLINE_MODE: "true"
      ENABLE_WHITE_LIST: "true"
      ALLOW_FLIGHT: "true"
      SIMULATION_DISTANCE: 12
      VIEW_DISTANCE: 12
      PLAYER_IDLE_TIMEOUT: 0
      SYNC_CHUNK_WRITES: "false"
      ENABLE_JMX: "false"
      USE_NATIVE_TRANSPORT: "true"
      USE_AIKAR_FLAGS: "true"
      SNOOPER_ENABLED: "false"
    ports:
      - "25565:25565"
    volumes:
      - /mnt/ram/gcp:/data
      - /var/www/html/dynmapgcp:/web
    stdin_open: true
    tty: true
    restart: unless-stopped
```
