### DISCUSSION TITLE
Azure + Ubuntu + OpenJDK 11 + Docker-compose = Unable to connect

### DISCUSSION THREAD

**Discussion by Lanttu42** [itzg/docker-minecraft-server#1014] [Q&A] [answered]
Hi everyone! 

I had this wonderful idea that I could make Minecraft server to my friends kids, but this wasn't the easiest job and I failed!

If you have any ideas which I could try, please share - Here's my current setup and installation procedure:

I am running Ubuntu 18.4. on Azure environment and it is supported with OpenJDK 11 (sudo apt install default-jre). 
- I made folder named "mine" under my useraccount
- I created docker-compose.yml which currently looks like this:
```
version: '3'
services:
  mc:
    image: itzg/minecraft-server:java11
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    environment:
      EULA: "TRUE"
    restart: always

```
- Originally it didn't have the :java11 docker switch and I moved data under data folder, so I could keep my server settings file and also check if the issue lies on that file. 
- I launched docker with docker-compose up -d
- Docker pulled necessary files, and populated data folder as expected
- I edited Azure Network security Group and allowed port 25565 ANY-ANY, All protocols 
- I also added 25575 as I found it from server settings (rcon port)

I tried to launch Minecraft PE on my iPhone. 
- Added server with IP -address
- It went under Other Server (as expected, I think?)
- It never got the PING and if I tried to connect, it says Unable to Connect

I tried also launch Minecraft Windows edition
- Added server with IP-address
- Unable to connect

iPhone version is updated to latest version. 
Windows version is updated to latest version.
I don't have any VPN or outgoing firewalls.

I can succesfully run Valheim, Factorio and couple of older games without any issues.
