### DISCUSSION TITLE
Don't have any command permissions with rcon-cli

### DISCUSSION THREAD

**Discussion by lccpianoman** [itzg/docker-minecraft-server#1089] [Q&A]
Hello,

I'd like to preface by saying I am newish to docker, but I've been learning a lot lately.

When I first installed a fresh installation of the image, I was able to access the console to my server fine with "docker exec -i minecraft-server_mc_1 rcon-cli". Upon uploading my own world and a few plugins, when I try to log into the console this way and run any command, it gives me "I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error". I am still able to send commands via "mc-send-to-console" just fine, but I would love to find a solution to my problem if possible. I have made sure to enable RCON in the server.properties and looked just about everywhere else I could think of. Any input/suggestions would be greatly appreciated!

-Luke

**Comment by itzg** [comment]
That's unusual for commands to get denied via rcon. Can you provide the compose file or docker run command you're using to create the container?

**Reply by lccpianoman** [reply]
Sure! I have it attached (converted to txt so github can support it). I'll also paste the contents here if that's a little easier:

```
version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: PAPER
      VERSION: 1.17.1
    ports:
      - 25565:25565
    volumes:
      - /srv/dev-disk-by-uuid-708595e8-c0b5-4215-9e90-d445385c9486/MinecraftServer/Test:/data
```

[docker-compose.txt](https://github.com/itzg/docker-minecraft-server/files/7411539/docker-compose.txt)

-Luke
