### DISCUSSION TITLE
How to pass arguments to the server jar

### DISCUSSION THREAD

**Discussion by foxii-cn** [itzg/docker-minecraft-server#1156] [Q&A] [answered]
for example `--forceUpgrade`
My English is'n very well...
Thanks

**Comment by itzg** [comment, marked as answer]
Are you using a docker compose file or `docker run` to create you container?

**Reply by foxii-cn** [reply]
sure
```yaml
version: '3.9'
services:
  minecraftserver:
    image: itzg/minecraft-server:java17
    ports:
      - 25565:25565
    environment:
      TYPE: FABRIC
      VERSION: "1.18"
      EULA: "TRUE"
      ICON: /data/fox.png
      OVERRIDE_ICON: "TRUE"
      DIFFICULTY: hard
      VIEW_DISTANCE: 16
      SPAWN_PROTECTION: 0
      JVM_OPTS: -javaagent:/data/authlib-injector.jar=https://littleskin.cn/api/yggdrasil
      MEMORY: 2G
      STOP_SERVER_ANNOUNCE_DELAY: 3
      ENABLE_ROLLING_LOGS: true
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /srv/minecraft-data:/data
```
