### DISCUSSION TITLE
How do I Change the Port of My Existing Server?

### DISCUSSION THREAD

**Discussion by Jacksinnh** [itzg/docker-minecraft-server#1249] [Q&A]
I moved in with a friend who already has a server so I need to change the port on mine. How do I go about doing that?

**Comment by itzg** [comment]
How do you currently have your container server configured?

**Comment by d3adb5** [comment]
Your approach somewhat depends on your server configuration. The server running in the container will always listen on port `25565` _while in the container_, but you have to export the port manually when creating the container with Docker.

An example exporting it to another port can be found in the following `docker-compose.yml`:

```yaml
version: "3"
services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server:java17-alpine
    environment:
      EULA: "true"
      MEMORY: "1024M"
      TYPE: "PAPER"
      LEVEL: "somelevelname"
      SERVER_NAME: "SomeServerName"
      DIFFICULTY: "normal"
      MAX_PLAYERS: "10"
      USER_AIKAR_FLAGS: "true"
    ports:
      - "3232:25565"
    volumes:
      - "/var/lib/minecraft:/data"
```

If you bring your server up using this Compose file, your server will be listening on local port `3232`.

You can disregard the other options if they don't apply to your use case. The relevant part of this file is:
```yaml
services:
  minecraft:
    ports:
      - "3232:25565"
```
