### DISCUSSION TITLE
[init] FTB server modpack /home/barel_elbaz/pokehaan.zip not found

### DISCUSSION THREAD

**Discussion by BarelElbaz** [itzg/docker-minecraft-server#1267] [Q&A]
I try to start a CURSEFORGE server with zipfile of mod pack but not matter however I place the modpack zip it says:
```[init] FTB server modpack /home/barel_elbaz/pokehaan.zip not found.```
 
My docker-compose.yaml:
```
version: "3.3"
services: 
    mcpe:
        image: itzg/minecraft-server:java8
        ports:
            - 25565:25565
        environment: 
            - EULA=TRUE
            - TYPE=CURSEFORGE
            - CF_SERVER_MOD=/home/barel_elbaz/pokehaan.zip
              # - FORGEVERSION=10.13.4.1614
            - VERSION=1.12.2
            - ONLINE_MODE=false
            - MEMORY=2G
            - EXEC_DIRECTLY=true
            - OVERRIDE_SERVER_PROPERTIES=true
            - ALLOW_FLIGHT=true
            - MOTD=Pixelmon_liam
            - OVERRIDE_SERVER_ICON=TRUE
            - ICON=https://www.google.com/url?sa=i&url=https%3A%2F%2Fcodakid.com%2Fminecraft-pixelmon%2F&psig=AOvVaw3lGuS3LMqeg2rQ3ctVRt6n&ust=1641762583488000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCIic26-Io_UCFQAAAAAdAAAAABAD
            - DIFFICULTY=peaceful
            - JVM_DD_OPTS=fml.queryResult:confirm
        tty: true
        stdin_open: true
        restart: unless-stopped
        volumes: 
            - './mc-data:/data'
            - './mods:/data/mods'
```
