### DISCUSSION TITLE
Running 2 containers with one docker-compose file causes 'WARN mc-server-runner sub-process failed {"exitCode": -1}' -error

### DISCUSSION THREAD

**Discussion by taeraeyttaejae** [itzg/docker-minecraft-server#1302] [Q&A] [answered]
When running a single docker container, there is no problems whatsoever at least to this point, but when running 2 parallel server containers launched with docker-compose, either one container dies with 'WARN mc-server-runner sub-process failed {"exitCode": -1}' -error message.

VM has 2/16gb of allocated RAM(2 minimum, 16 max) and 10 xeon cores(yeah minecraft is single core but still)
paste from my docker-compose yml(excluding pwd:s etc):

https://pastebin.com/h6bafUXR
paste from 'docker logs mc1' container:
https://pastebin.com/92jLwYzP

That much i have gathered, that this probably has something to do with Docker memory handling. I am running MC server with default memory settings, using 1G min 1G max(?) of RAM.

Excerpt from container logs when starting the server:
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 7 1000 1000 4096 Jan 23 10:48 /data'

[init] Resolved version given LATEST into 1.18.1

[init] Resolving type given VANILLA

[init] server.properties already created, skipping

[init] Checking for JSON files.

[init] Setting initial memory to 1G and max to 1G

[init] Starting the Minecraft server...

Folder contents:
xxxx@ubuntu-server:~/minecraft$ ls -lah
total 24K
drwxr-xr-x 4 root  root  4.0K Jan 24 14:35 .
drwxr-xr-x 9 xxxx xxxx 4.0K Jan 23 17:17 ..
-rw-r--r-- 1 xxxx xxxx  930 Jan 23 18:59 docker-compose.yml
drwxrwxr-x 7 xxxx xxxx 4.0K Jan 23 10:48 minecraft-server1
drwxrwxr-x 7 xxxx xxxx 4.0K Jan 23 12:12 minecraft-server2
-rwxr-xr-x 1 root  root   304 Jan 17 21:55 start_mc.sh

minecraft-server1 and 2 are folders that are mounted on containers' /data, they should be also backed up from here in the undeniably unsure future when my servers actually work...

Any ideas where to go next? I was burning midnight oil with this last night already.
What kind of additional details should i provide?

**Comment by itzg** [comment]
Your mc2 port mapping should be `25566:25565`; however that won't be the immediate cause. Can you provide the exact docker compose command you're using to bring them both up?

**Reply by taeraeyttaejae** [reply]
docker-compose -f docker-compose.yml up -d

**Reply by taeraeyttaejae** [reply]
and yes, i have corrected the port mappings after that paste. It seems that network is not the problem here but java in some...javaish way.

**Reply by taeraeyttaejae** [reply]
could the server.properties -files in /home/xxxx/minecraft/minecraft-server1(and2) -folders collide somehow with the environment variables here, as at least MOTD messages seem to come from those files?

**Comment by shotah** [comment]
@taeraeyttaejae were you able to just run 1 of the servers? The exit code seems interesting because it's still in world gen mode. So you've passed all the setup scripts. So is it trying to write the world data files and failing? I guess it'd be nice to verify it is something with 2 containers vs. 1 container.

**Reply by taeraeyttaejae** [reply]
I tried to run 2 separate containers, but i ran into same problem with same error message.

**Comment by shotah** [comment]
just tried two and one and its giving a corrupted world file in all cases. 

![image](https://user-images.githubusercontent.com/8572809/150831036-993cfcf4-6d09-47c5-bbb6-fac71c38640e.png)

**Reply by taeraeyttaejae** [reply]
ok this is good to hear, that someone else is having the same problem. 

Any ideas how i *should* run 2 LAN servers in relatively simple setup(proxmox ve, ubuntu 20.04 server)?

**Reply by shotah** [reply]
I think we need to wait for Itzg to reply. He may have more insight. I am unable to stand up 1 container at the moment.

**Reply by taeraeyttaejae** [reply]
Yeah I think this is an issue many people have ran into - at least my kids like to have separate survival and creative servers to choose from.

**Comment by itzg** [comment]
I'm thinking it's the health check timing out since two containers both building two world datas from scratch gets pretty intensive. I adjusted the compose file to use relative paths and default rcon settings, but increased the health check allowance and they eventually started:

```
version: "3"
services:
  mc1:
    image: itzg/minecraft-server
    container_name: mc1
    ports:
      - 25565:25565
    environment:
      MOTD: "Survival server"
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      restart: always
    volumes:
    - ./minecraft-server1:/data
    healthcheck:
      interval: 10s
      timeout: 30s
      retries: 24
      start_period: 30s
 
  mc2:
    image: itzg/minecraft-server
    container_name: mc2
    ports:
      - 25566:25565
    environment:
      MOTD: "Creative server"
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      restart: always
    volumes:
    - ./minecraft-server2:/data
    healthcheck:
      interval: 10s
      timeout: 30s
      retries: 24
      start_period: 30s
```

**Reply by shotah** [reply]
I tried adding depends_on as well. My local version (Which I normally don't use) isn't honoring it. 
```yaml
mc2:
     ...
     depends_on:
       - "mc1"
     ...
```
