### DISCUSSION TITLE
Mod Pack installation unsuccesfull

### DISCUSSION THREAD

**Discussion by luisced** [itzg/docker-minecraft-server#1503] [Q&A] [answered]
Hello everyone, I'm currently creating a Forge Server with 'Better Minecraft' Mod Pack 1.18.2 version. However, I'm struggling a bit, since Im not being able to see the mods in the server :(. It downloads the .zip file into the mod directory, but when I open the mod directory I only see the full Mod Pack with config, scripts, mods, etc. So the question that I have is if I need to only place the better Minecraft mods into the mods directory or if I need to leave all the Mod Pack folder inside there. I hope you can help me 🙂

This is my docker-compose file if needed

```
version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    container_name: modded_minecraft_server
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      OPS: "LuisGamer02031"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      SERVER_NAME: "MODDED SERVER"
      MEMORY: "6G"
      MODE: "SURVIVAL"
      ONLINE_MODE: "TRUE"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      ALLOW_NETHER: "TRUE"
      OVERRIDE_ICON: "TRUE"
      ICON: "https://cdn.vox-cdn.com/thumbor/8KxJUDwQsz5Qy-_HzZjtCTRR5PU=/0x164:1440x884/fit-in/1200x600/cdn.vox-cdn.com/uploads/chorus_asset/file/22310830/NmJgg.jpg"
      MOTD: "Welcome to the server!"
      MODPACK: "https://media.forgecdn.net/files/3765/708/Better+Minecraft+Server+Pack+%5bFABRIC%5d+v7.zip"
    volumes:
      - moddedminecraftdata:/data
      - ./mods:/mods:ro
    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  moddedminecraftdata:
    external: true

```
And this is what I get when entering the mods directory

![image](https://user-images.githubusercontent.com/63626850/166964150-4c741166-bf3c-486b-b0ed-b7c08ef3fb9a.png)

![image](https://user-images.githubusercontent.com/63626850/166964350-f951373c-c164-4f7b-86f4-ce33378259ad.png)
