### DISCUSSION TITLE
Trouble increasing server memory

### DISCUSSION THREAD

**Discussion by poperigby** [itzg/docker-minecraft-server#1657] [Q&A] [answered]
Hi, I'm trying to get my server to use more memory, but I'm running into problems.

Here's my current compose file:
```yaml
services:
  app:
    image: itzg/minecraft-server
    container_name: minecraft
    hostname: minecraft
    environment:
      - EULA=TRUE
      - TYPE=FABRIC
      - MODRINTH_PROJECTS=cloth-config,lithium,phosphor,krypton,servercore,crawl,repurposed-structures-fabric
      - MODS_FILE=/extras/mods.txt
      - REMOVE_OLD_MODS=TRUE
      - VERSION=1.19.1
      - MEMORY = 4G
    ports:
      - 25565:25565
    volumes:
      - data:/data
      - ./mods.txt:/extras/mods.txt
      - ./config:/data/config
    tty: true
    stdin_open: true
    mem_limit: 4G
    restart: unless-stopped
volumes:
  data:
```

The problem is, the memory stays at 1G: 
```
[init] Setting initial memory to 1G and max to 1G
```
