### DISCUSSION TITLE
Can't increase server memory

### DISCUSSION THREAD

**Discussion by Sundust2430** [itzg/docker-minecraft-server#1658] [Q&A]
I can't increase server memory,  i recreated container with
`MEMORY = 8G` included in docker-compose.yml
tried
`Docker run -e itzg/minecraft-server MEMORY = 8G`
i'm absolute noob in docker, i'm sorry if i'm doing something wrong.
I would be very grateful if someone could help me
here is my compose file
```
version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - minecraftdata:/data
      - /home/Minecraft/plugins:/plugins
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      OPS: "ButterNPants"
      ENABLE_WHITELIST: "FALSE"
      ENFORCE_WHITELIST: "FALSE"
      MEMORY = 8G :
    tty: true
    stdin_open: true
    restart: unless-stopped
volumes:
  minecraftdata:
  external: true

```
