### DISCUSSION TITLE
Server crashing without an error message

### DISCUSSION THREAD

**Discussion by poperigby** [itzg/docker-minecraft-server#1659] [Q&A]
I'm a having a lot of trouble diagnosing this crash, but it appears to be something to do with the server overloading.

`compose.yml`:
```yaml
services:
  app:
    image: itzg/minecraft-server
    container_name: minecraft
    hostname: minecraft
    environment:
      - EULA=TRUE
      - TYPE=FABRIC
      - MODRINTH_PROJECTS=cloth-config,lithium,phosphor,krypton,servercore,crawl,repurposed-structures-fabric,better-combat,memoryleakfix
      - MODS_FILE=/extras/mods.txt
      - REMOVE_OLD_MODS=TRUE
      - VERSION=1.19.1
      - MEMORY=6G
      - DEBUG=true
    ports:
      - 25565:25565
    volumes:
      - data:/data
      - ./mods.txt:/extras/mods.txt
      - ./config:/data/config
    tty: true
    stdin_open: true
    mem_limit: 6G
    restart: unless-stopped
volumes:
  data:
```
`mods.txt`:
```
https://mediafiles.forgecdn.net/files/3902/660/fabric-api-0.58.5%2B1.19.1.jar
https://mediafiles.forgecdn.net/files/3853/858/cloth-api-4.0.65.jar
https://github.com/RelativityMC/C2ME-fabric/releases/download/0.2.0%2Balpha.8/c2me-fabric-mc1.19-0.2.0+alpha.8.2.jar
https://mediafiles.forgecdn.net/files/3821/380/Mambience-5.2.0%2B1.19.jar
https://mediafiles.forgecdn.net/files/3902/643/Terralith_v2.3.3.jar
https://mediafiles.forgecdn.net/files/3887/669/fabric-language-kotlin-1.8.2%2Bkotlin.1.7.10.jar
https://mediafiles.forgecdn.net/files/3916/283/time-and-wind-ct-1.4.2%2B1.19.1.jar
https://mediafiles.forgecdn.net/files/3832/787/sleepwarp-1.2.0%2B1.19.jar
https://mediafiles.forgecdn.net/files/3842/567/inventorio-1.19-fabric-1.8.0.jar
https://mediafiles.forgecdn.net/files/3857/415/HungerStrike-1.19-7.0.0.jar
https://mediafiles.forgecdn.net/files/3907/320/Xaeros_Minimap_22.13.0_Fabric_1.19.1.jar
https://mediafiles.forgecdn.net/files/3918/562/mcdw-4.4.1-1.19.jar
https://mediafiles.forgecdn.net/files/3822/828/mcdar-1.5.0.jar
https://mediafiles.forgecdn.net/files/3864/870/mcda-2.1.1.jar
https://github.com/mjwells2002/ForgetMeChunk/releases/download/1.0.4/forgetmechunk-1.0.4-1.18.X-1.19.X.jar
```

Output log: https://gist.github.com/poperigby/e57ca87da845104c78f785279cf94906

**Comment by itzg** [comment]
If it created one, you might need to look at the crashlog file that Fabric (and other) server writes out.

**Reply by poperigby** [reply]
Where would the Fabric log be located?

**Reply by itzg** [reply]
It would be file the server created in the data directory. It'll say something about crash log in its name.

**Reply by poperigby** [reply]
This is interesting. I don't think it's generating a crash log. The game just crashed, but a new crash log wasn't created. Only a regular log was created, but that's just the one I linked.

**Reply by itzg** [reply]
Can you add `DEBUG_MEMORY: "true"` and provide that output?

**Reply by poperigby** [reply]
This is bizarre, I set `- DEBUG_MEMORY="true"`, but it's still just giving me these last 3 lines of output:
```
[17:58:46] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 9212ms or 184 ticks behind
2022-08-09T17:59:05.561Z        WARN    mc-server-runner        Minecraft server process failed {"exitCode": -1}
2022-08-09T17:59:05.822Z        INFO    mc-server-runner        Done
```

**Reply by itzg** [reply]
Actually can you provide the "[init]" log lines just before it kicks off the server. The memory info is displayed there.

**Reply by poperigby** [reply]
Here's the whole log when I have `DEBUG_MEMORY` enabled. Did I enable it incorrectly?

https://gist.github.com/poperigby/d00040cc4a15786d901deb95a96115bc

**Reply by itzg** [reply]
Yeah, it didn't seem to pick it up. What does your compose file look like? Did you make sure to `docker compose up` to apply the changes?

**Reply by poperigby** [reply]
Yep. I did `docker compose up -d`. Here's my compose file:
```
services:
  app:
    image: itzg/minecraft-server
    container_name: minecraft
    hostname: minecraft
    environment:
      - EULA=TRUE
      - TYPE=FABRIC
      - MODRINTH_PROJECTS=cloth-config,lithium,phosphor,krypton,servercore,crawl,repurposed-structures-fabric,better-combat,memoryleakfix
      - MODS_FILE=/extras/mods.txt
      - REMOVE_OLD_MODS=TRUE
      - VERSION=1.19.1
      - MEMORY=6G
      # - DEBUG=TRUE
      - DEBUG_MEMORY="true"
    ports:
      - 25565:25565
    volumes:
      - data:/data
      - ./mods.txt:/extras/mods.txt
      - ./config:/data/config
    tty: true
    stdin_open: true
    mem_limit: 6G
    restart: unless-stopped
volumes:
  data:
```
