### DISCUSSION TITLE
Server in k8s not using the assigned memory limit

### DISCUSSION THREAD

**Discussion by unruha** [itzg/docker-minecraft-server#1661] [Q&A] [answered]
I'm running a server in a pod in managed Kubernetes (Oracle OKE). In the YAML file for the server, I set a memory request of 4GB and a memory limit of 4GB as seen below. I unset the `MEMORY` env variable to use the default heap size of `1G`.

However, I've noticed that the pod is never using most of the memory limit assigned to it. According to the Kubernetes Metrics Server, the pod is only ever using up to around `1300MB` of memory (metrics server output attached below). The CPU limit seems to be behaving as expected as it caps out at 1 CPU core.

Even when the server is under load and loading chunks, the memory usage never goes far above 1300MB. This has been causing lag on the server and trigging this server log `Can't keep up! Is the server overloaded? Running 2025ms or 40 ticks behind`.

I'm fairly sure its not a CPU bottleneck because even when the CPU usage is not at the limit, the memory still will not go above 1300MB. I examined the "memory limit" section of the docs but haven't found anything that may be causing this.

Any help is appreciated!

YAML for Statefulset and Service:
```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mc-vanilla1
spec:
  replicas: 1
  serviceName: mc-vanilla1-svc
  selector:
    matchLabels:
      app: mc-vanilla1
  template:
    metadata:
      labels:
        app: mc-vanilla1
    spec:
      containers:
        - image: itzg/minecraft-server
          name: mc-vanilla
          env:
            - name: EULA
              value: "true"
          ports:
            - containerPort: 25565
              name: main
          resources:
            requests:
              cpu: "1"
              memory: "4Gi"
            limits:
              cpu: "1"
              memory: "4Gi"
          readinessProbe:
            exec:
              command: ["/usr/local/bin/mc-monitor", "status", "--host", "localhost"]
            initialDelaySeconds: 180
            periodSeconds: 10
            failureThreshold: 12
          livenessProbe:
            exec:
              command:
              - mcstatus
              - localhost
              - ping
            initialDelaySeconds: 180
            periodSeconds: 5
          volumeMounts:
            - mountPath: /data
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mc-vanilla1-svc
  annotations:
    "mc-router.itzg.me/defaultServer": ""
spec:
  selector:
    app: mc-vanilla1
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
```

Kubernetes metrics server:
```
POD             NAME         CPU(cores)   MEMORY(bytes)
mc-vanilla1-0   mc-vanilla   1000m        1302Mi
```
```
POD             NAME         CPU(cores)   MEMORY(bytes)
mc-vanilla1-0   mc-vanilla   316m         1303Mi
```
