### DISCUSSION TITLE
k8s modded server can't find the forge version

### DISCUSSION THREAD

**Discussion by IllusiveBagel** [itzg/docker-minecraft-server#1675] [Q&A] [answered]
I have been running a server for about a month and it crashed last night now says it can't find the forge version. The server has crashed in the past and restarted fine i'm not sure what has changed.

Log:
```
chmod: changing permissions of '/data': Operation not permitted
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 18 0 0 4096 Aug 15 09:34 /data'
[init] Resolved version given 1.18.2 into 1.18.2 and major version 1.18
[init] Resolving type given FORGE
Invalid value for --forge-version
Usage: mc-image-helper install-forge [-hV] [--force-reinstall]
[--forge-version=<forgeVersion>]
--minecraft-version=<minecraftVersion>
[--output-directory=DIR]
[--results-file=<resultsFile>]
--force-reinstall
--forge-version=<forgeVersion>
A specific Forge version or to auto-resolve the
version provide 'latest' or 'recommended'. Default
value is recommended
-h, --help Show this help message and exit.
--minecraft-version=<minecraftVersion>
--output-directory=DIR
--results-file=<resultsFile>
A key=value file suitable for scripted environment
variables. Currently includes
SERVER: the entry point jar or script
-V, --version Print version information and exit.
[init] ERROR failed to install forge
```
server.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: minecraft-modded
  name: minecraft-modded
spec:
  selector:
    matchLabels:
      run: minecraft-modded
  template:
    metadata:
      labels:
        run: minecraft-modded
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: minecraft-modded
          image: itzg/minecraft-server
          env:
            - name: EULA
              value: "TRUE"
            - name: MOTD
              value: All The Mods 7 Server
            - name: TYPE
              value: FORGE
            - name: VERSION
              value: 1.18.2
            - name: GENERIC_PACK
              value: Server-Files-0.4.23.zip
            - name: FORGEVERSION
              value: 40.1.60
            - name: MEMORY
              value: "6G"
          ports:
          - containerPort: 25565
          volumeMounts:
            - name: world
              mountPath: /data
      volumes:
      - name: world
        persistentVolumeClaim:
          claimName: minecraft-modded
```
