### DISCUSSION TITLE
docker-compose setup: Velocity proxy refuses to connect to Paper hub world on same machine

### DISCUSSION THREAD

**Discussion by klaribot** [itzg/docker-minecraft-server#1703] [Q&A] [answered]
Alright, so I have a bit of an advanced problem I've been struggling to solve for the past 5 hours or so.

I'm building a larger-scale Minecraft network using Docker Compose (or preparing to anyway), and I'm trying to find out why the Velocity container is refusing to forward players to the Hub container.

Here's my `docker-compose.yml`:
```yaml
version: '3.8'

services:

  #######################################################
  # hub Profile - The main Minecraft hub world. Includes a Velocity proxy configured for modern forwarding, and a void world running on Paper.

  main-proxy:
    hostname: main-proxy
    container_name: main-proxy
    profiles: ["hub"]
    image: itzg/bungeecord:java17
    ports:
      - "25565:25565"
    environment:
      UID: 1002 #Minecraft user
      GID: 1003 #Minecraft group
      TYPE: VELOCITY
      VELOCITY_VERSION: latest
      MEMORY: 512m
      JVM_XX_OPTS: "-XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15"
      PLUGINS: https://github.com/ViaVersion/ViaVersion/releases/download/4.4.2/ViaVersion-4.4.2.jar,https://github.com/ViaVersion/ViaBackwards/releases/download/4.4.2/ViaBackwards-4.4.2.jar
    restart: always
    volumes:
      - ./servers/main-proxy:/server
    links:
      - main-hub

  main-hub:
    hostname: main-hub
    container_name: main-hub
    profiles: ["hub"]
    image: itzg/minecraft-server:java17
    ports:
      - "30065:25565"
    environment:
      UID: 1002 #Minecraft user
      GID: 1003 #Minecraft group
      TYPE: PAPER
      VERSION: latest
      MEMORY: 1024m
      USE_AIKAR_FLAGS: "TRUE"
      EULA: "TRUE"
      SPIGET_RESOURCES: 19254,27448,25391,102902 #ViaVersion, ViaBackwards, VoidGen, NoEncryption
      #EXEC_DIRECTLY: true
      # enable env variable replacement
      REPLACE_ENV_VARIABLES: "true"
      # define an optional prefix for env variables we want to replace
      ENV_VARIABLE_PREFIX: "CFG_"
      # actual variables
      CFG_FORWARDING_SECRET_FILE: "/forwarding.secret"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./servers/main-hub:/data
secrets:
  forwarding_secret:
    file: /forwarding.secret
```

`velocity.toml` already knows about the forwarding.secret file (at least it should?):
```toml
. . .

# If you are using modern or BungeeGuard IP forwarding, configure a file that contains a unique secret here.
# The file is expected to be UTF-8 encoded and not empty.
forwarding-secret-file = "forwarding.secret"

. . .
```

 and `paper-global.yml` is configured to have an environment variable replaced at container start:
```yaml
. . .

proxies:
  bungee-cord:
    online-mode: false
  proxy-protocol: false
  velocity:
    enabled: true
    online-mode: true
    secret: ${CFG_FORWARDING_SECRET_FILE}

. . .
```

This SHOULD *just work*, right?

In testing, it does not.

```
main-proxy  | [06:55:36 INFO]: [connected player] Klari (/{IP REDACTED}) has connected
main-proxy  | [06:55:36 ERROR]: [connected player] Klari (/{IP REDACTED}): unable to connect to server main-hub
main-proxy  | io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: main-hub/172.28.0.2:30065
main-proxy  | Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
main-proxy  |   at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155) ~[velocity-3.1.2-SNAPSHOT-179.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
main-proxy  |   at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128) ~[velocity-3.1.2-SNAPSHOT-179.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
main-proxy  |   at io.netty.channel.unix.Socket.finishConnect(Socket.java:359) ~[velocity-3.1.2-SNAPSHOT-179.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
main-proxy  |   at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710) ~[velocity-3.1.2-SNAPSHOT-179.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
main-proxy  |   at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687) ~[velocity-3.1.2-SNAPSHOT-179.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
main-proxy  |   at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[velocity-3.1.2-SNAPSHOT-179.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
main-proxy  |   at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:489) ~[velocity-3.1.2-SNAPSHOT-179.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
main-proxy  |   at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[velocity-3.1.2-SNAPSHOT-179.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
main-proxy  |   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.1.2-SNAPSHOT-179.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
main-proxy  |   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.2-SNAPSHOT-179.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
main-proxy  |   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.2-SNAPSHOT-179.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
main-proxy  |   at java.lang.Thread.run(Thread.java:833) [?:?]
main-proxy  | [06:55:36 INFO]: [connected player] Klari (/{IP REDACTED}) has disconnected: Unable to connect you to main-hub. Please try again later.
```

...although I'm 100% expecting to be pointed towards an obvious and/or incomplete misconfiguration in my config.
Any feedback would be appreciated to the highest degree. :pray:

**Comment by itzg** [comment, marked as answer]
This might be a question better asked on Velocity forums. 

Without knowing Velocity, all I can question is
- Why is velocity trying port 30065 of the main-hub host?
- Docker mounts secrets under the path `/run/secrets` but I'm not seeing that path mentioned anywhere

**Reply by klaribot** [reply]
Velocity is trying port 30065 because I've explicitly mapped internal port 25565 on the main-hub container to use port 30065 externally.

in `docker-compose.yml`:
```yaml
{. . .}

main-hub:

  {. . .}

  ports:
    - "30065:25565"

  {. . .}
```
in `main-proxy/velocity.toml`:
```toml
{. . .}

[servers]
	# Configure your servers here. Each key represents the server's name, and the value
	# represents the IP address of the server to connect to.
	main-hub = "main-hub:30065"

	{. . .}

	# In what order we should try servers when a player logs in or is kicked from a server.
	try = ["main-hub"]

	{. . .}
```
Velocity itself will bind to 25565, and send connections coming in from 25565 back out to the network on 30065. Paper will be listening on its own internal 25565, which will be mapped by docker to port 30065 externally.

I also noticed, that when using `REPLACE_ENV_VARIABLES`, and defining a `CFG_` with a `_FILE` suffix, it didn't replace the variable with the *contents* of `forwarding.secret` in `paper-global.yml`, it only replaced the variable with the *file path*:

`paper-global.yml`
```yaml
{. . .}
proxies:
  bungee-cord:
    online-mode: false
  proxy-protocol: false
  velocity:
    enabled: true
    online-mode: true
    secret: /forwarding.secret  #<-- Was originally ${CFG_FORWARDING_SECRET_FILE} 
    {. . .}
```

`forwarding.secret` is in the root project directory, on the same level as the `docker-compose.yml`.

Would I have to manually bind-mount the forwarding.secret to each container? I would've thought suffixing a replaceable config with `_FILE` (found in an itzg/bungeecord example on the github) would take the contents of the file to replace the config value with.

I will repost on the Velocity forums.

**Reply by itzg** [reply]
That's half your problem. The external port is **external**. The container port within the docker network is still 25565 for main-hub. In fact you don't (and probably shouldn't) even need to declare a port mapping for that container. Refer to [the example](https://github.com/itzg/docker-bungeecord/blob/master/docs/docker-compose.yml). 

As for the secret, you cannot pick the path. It will put it under `/run/secrets` so you need to set that velocity `secret` with the correct path. See https://docs.docker.com/engine/swarm/secrets/#how-docker-manages-secrets

**Reply by itzg** [reply]
Also, the use of the `_FILE` feature is incorrect, which is understandable since the docs do seem confusing now that I look again. The variable to be substituted in the file must not have that suffix, such as

```
secret: ${CFG_FORWARDING_SECRET}
```

When it sees a variable named `CFG_FORWARDING_SECRET_FILE` is declared, it will use the contents of that referenced file.

**Reply by itzg** [reply]
I updated [the documentation about `_FILE` variables](https://github.com/itzg/docker-minecraft-server#replacing-variables-inside-configs:~:text=If%20you%20want%20to%20use%20a%20file%27s%20content%20for%20value%2C%20such%20as%20when%20using%20secrets%20mounted%20as%20files).

**Reply by klaribot** [reply]
> That's half your problem. The external port is **external**. The container port within the docker network is still 25565 for main-hub. In fact you don't (and probably shouldn't) even need to declare a port mapping for that container. Refer to [the example](https://github.com/itzg/docker-bungeecord/blob/master/docs/docker-compose.yml).
> 
> As for the secret, you cannot pick the path. It will put it under `/run/secrets` so you need to set that velocity `secret` with the correct path. See https://docs.docker.com/engine/swarm/secrets/#how-docker-manages-secrets

Really?
I thought that each container had its own internal network and that everything had to be routed externally.
How will I guarantee that every container will be able to connect on its own port, even if a given server container is on a completely different machine?

And thank you for the `_FILE` clarification! :D

**Reply by klaribot** [reply]
New configuration, new problems.

`docker-compose.yml`
```yaml
version: '3.8'

services:
  # hub Profile - The main Minecraft hub world. Includes a Velocity proxy configured for modern forwarding, and a void world running on Paper.
  main-proxy:
    hostname: main-proxy
    container_name: main-proxy
    profiles: ["hub"]
    image: itzg/bungeecord:java17
    ports:
      - "25565:25577"
    environment:
      UID: 1002 #Minecraft user
      GID: 1003 #Minecraft group
      TYPE: VELOCITY
      VELOCITY_VERSION: latest
      MEMORY: 512m
      JVM_XX_OPTS: "-XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15"
      PLUGINS: https://github.com/ViaVersion/ViaVersion/releases/download/4.4.2/ViaVersion-4.4.2.jar,https://github.com/ViaVersion/ViaBackwards/releases/download/4.4.2/ViaBackwards-4.4.2.jar
    secrets:
      - forwarding_secret
    restart: always
    volumes:
      - ./servers/main-proxy:/server
    links:
      - main-hub

  main-hub:
    hostname: main-hub
    container_name: main-hub
    profiles: ["hub"]
    image: itzg/minecraft-server:java17
    #ports:
    #  - "30065:25565"
    environment:
      UID: 1002 #Minecraft user
      GID: 1003 #Minecraft group
      TYPE: PAPER
      VERSION: latest
      MEMORY: 1024m
      USE_AIKAR_FLAGS: "TRUE"
      EULA: "TRUE"
      SPIGET_RESOURCES: 19254,27448,25391,102902 #ViaVersion, ViaBackwards, VoidGen, NoEncryption
      #EXEC_DIRECTLY: true
      # enable env variable replacement
      REPLACE_ENV_VARIABLES: "true"
      # define an optional prefix for env variables we want to replace
      ENV_VARIABLE_PREFIX: "CFG_"
      # actual variables
      CFG_FORWARDING_SECRET_FILE: "/run/secrets/forwarding.secret"
    secrets:
      - forwarding_secret
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./servers/main-hub:/data
secrets:
  forwarding_secret:
    file: forwarding.secret
```

`velocity.toml`
```toml
forwarding-secret-file = "${CFG_FORWARDING_SECRET_FILE}"
```

`paper-global.yml`
```yaml
proxies:
  bungee-cord:
    online-mode: false
  proxy-protocol: false
  velocity:
    enabled: true
    online-mode: true
    secret: ${CFG_FORWARDING_SECRET}
```

The new problem:
```
main-hub    | [mc-image-helper] 23:19:10.068 ERROR : Failed to process directory=/data: /run/secrets/forwarding.secret
main-hub exited with code 2
main-hub    | [init] Running as uid=1002 gid=1003 with /data as 'drwxrwxr-x 9 1002 1003 4096 Sep  1 23:13 /data'
main-proxy  | [23:19:11 INFO]: Booting up Velocity 3.1.2-SNAPSHOT (git-6547ccaa-b179)...
main-proxy  | [23:19:11 INFO]: Loading localizations...
main-proxy  | [23:19:11 INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 1.1.x (Linux x86_64) ciphers
main-proxy  | [23:19:11 ERROR]: Unable to read/load/save your velocity.toml. The server will shut down.
main-proxy  | java.lang.RuntimeException: The forwarding-secret-file does not exists.
main-proxy  |   at com.velocitypowered.proxy.config.VelocityConfiguration.read(VelocityConfiguration.java:499) ~[velocity-3.1.2-SNAPSHOT-179.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
main-proxy  |   at com.velocitypowered.proxy.VelocityServer.doStartupConfigLoad(VelocityServer.java:311) ~[velocity-3.1.2-SNAPSHOT-179.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
main-proxy  |   at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:217) ~[velocity-3.1.2-SNAPSHOT-179.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
main-proxy  |   at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[velocity-3.1.2-SNAPSHOT-179.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
main-proxy exited with code 1
```

Do I now need to replace mounting the entire `/data` directory with the individual `/config` and `/plugins` mounts, etc.?
