### DISCUSSION TITLE
Error "found unexpected end of stream"

### DISCUSSION THREAD

**Discussion by Thunder1723** [itzg/docker-minecraft-server#1747] [Q&A]
I pasted my docker compose yml below and I cannot figure out this problem.  I am new to using docker but not linux.  I haven't finsished making the file yet but I want to make sure I can get it to work before adding more into it.
```
version: "3.8"
services:
  mc:
    image: itzg/minecraft-server
    container_name: PurPur
    ports:
      - 60000:60000
    environment:
     OVERRIDE_SERVER_PROPERTIES: true
     TYPE: PURPUR
     PURPUR_BUILD: LATEST
     FORCE_REDOWNLOAD: true
     DIFFICULTY: normal
     SNOOPER_ENABLED: false
     SERVER_NAME: Serber
     MEMORY: 8G
     JVM_OPTS: "there are a lot of flags here"
     TZ: America/Chicago
    tty: true
    stdin_open: true
    restart: unless-stopped
   volumes:
      - /mnt/Minecraft:/data

```
