### DISCUSSION TITLE
AutoPause & Monitor

### DISCUSSION THREAD

**Discussion by foenyx-dev** [itzg/docker-minecraft-server#1833] [Q&A] [answered]
Hi,
Are AutoPause & Monitor incompatible ?
Every time Java process is paused, monitor wake it up.

```
monitor     | 2022-11-20T00:04:30.873Z  DEBUG   mc-monitor/prom_collector.go:112        pinging  {"host": "minecraft", "port": "25565"}
minecraft   | [Autopause loop] No client connected since startup / knocked - pausing
minecraft   | [01:04:33] [RCON Listener #1/INFO]: Thread RCON Client /127.0.0.1 started
minecraft   | [01:04:33] [Server thread/INFO]: 7o[Rcon: Saved the game]
minecraft   | [01:04:33] [RCON Client /127.0.0.1 #12/INFO]: Thread RCON Client /127.0.0.1 shutting down
minecraft   | [2022-11-20T01:04:33+01:00] [Autopause] Pausing Java process
monitor     | 2022-11-20T00:05:00.876Z  DEBUG   mc-monitor/prom_collector.go:112        pinging  {"host": "minecraft", "port": "25565"}
minecraft   | [01:05:00] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 27581ms or 551 ticks behind
minecraft   | [Autopause loop] Server was knocked from 172.18.0.8 - waiting for clients or timeout
```

**Comment by itzg** [comment, marked as answer]
External (to the container) monitoring? Yes it's "incompatible" since all it knows is to reach out to the server port.

**Reply by foenyx-dev** [reply]
Yes, I guess, my conf (I talk about itzg/mc-monitor):

```yaml
minecraft:
    image: itzg/minecraft-server
    restart: "unless-stopped"
    container_name: "minecraft"
    ports:
      - 8123:8123
      - 25565:25565
    environment:
      EULA: true
      INIT_MEMORY: "1G"
      MAX_MEMORY: "32G"
      TYPE: "PUFFERFISH"
      MODS: "https://mediafilez.forgecdn.net/files/3922/624/worldedit-bukkit-7.2.12.jar,https://mediafilez.forgecdn.net/files/3677/516/worldguard-bukkit-7.0.7-dist.jar"
      SPIGET_RESOURCES: "274,57242,81534,84278"
      OPS: "Foenyyx,DreamInBlack"
      JVM_OPTS: "--add-modules=jdk.incubator.vector"
      USE_AIKAR_FLAGS: true
      ENABLE_ROLLING_LOGS: true
      TZ: "Europe/Paris"
      USE_SIMD_FLAGS: true
      LOG_TIMESTAMP: true
      ENABLE_COMMAND_BLOCK: true
      MOTD: "§l§cFoenyx§r §nserver"
      MAX_TICK_TIME: -1
      ENABLE_AUTOPAUSE: true
      AUTOPAUSE_TIMEOUT_INIT: 120
      AUTOPAUSE_TIMEOUT_EST: 60
      OVERRIDE_SERVER_PROPERTIES: true
      SNOOPER_ENABLED: false
      PLAYER_IDLE_TIMEOUT: 5
      JVM_DD_OPTS: "disable.watchdog:true"
    tty: true
    stdin_open: true
    volumes:
      - ./minecraft-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.tcp.routers.minecraft.entrypoints=minecraft"
      - "traefik.tcp.routers.minecraft.rule=HostSNI(`*`)"
      - "traefik.tcp.services.minecraft.loadbalancer.server.port=25565"
      - "traefik.http.routers.dynmap.rule=Host(`dynmap.${DOMAIN}`)"
      - "traefik.http.routers.dynmap.service=dynmap"
      - "traefik.http.routers.dynmap.entrypoints=https"
      - "traefik.http.routers.dynmap.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dynmap.tls=true"
      - "traefik.http.services.dynmap.loadbalancer.server.port=8123"
    networks:
      - traefik

  monitor:
    restart: "unless-stopped"
    image: itzg/mc-monitor
    container_name: "monitor"
    command: export-for-prometheus
    environment:
      EXPORT_SERVERS: minecraft
      DEBUG: true
    depends_on:
      - minecraft
    networks:
      - traefik
```

So monitor wake up autopause when it try to get data.
I need to do a choice so
