### DISCUSSION TITLE
Dual-line MOTD with docker-compose

### DISCUSSION THREAD

**Discussion by Ahptt** [itzg/docker-minecraft-server#1852] [Q&A] [answered]
Hello, this is a rather minor issue but I'm unable to perform a line break in my MOTD. Also, when manually editing a MOTD in the server.properties, I'm able to add spaces to center my MOTD. When my docker-compose runs, the spaces aren't passed along. After passing the below MOTD in my compose file, half of the message is oddly placed further down the server.properties file.

[docker-compose.yml](https://gist.github.com/Ahptt/e4f95322368e87189b691171a572b02c)
[server.properties](https://gist.github.com/Ahptt/10ebfc41c0adb9c31594d0c691bd5077)

**Comment by itzg** [comment, marked as answer]
~~Newlines in server properties values need an extra backslash to escape the backslash~~ 😃

This
```yaml
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MOTD: "line one\nline two"
    ports:
      - "25565:25565"
```

results in
![image](https://user-images.githubusercontent.com/988985/205943539-1df7d097-70b0-41ea-8daf-baed2c5f68ca.png)
