### DISCUSSION TITLE
FORGE Server won't start

### DISCUSSION THREAD

**Discussion by little-method** [itzg/docker-minecraft-server#1866] [Q&A] [answered]
I ran the following Docker Compose to start FORGE Server.
```yaml
version: '3.7'

services:
  # https://github.com/itzg/docker-minecraft-server
  mc:
    image: itzg/minecraft-server:java8-multiarch
    ports:
      - 25565:25565
    environment:
      VERSION: 1.12.2
      EULA: "TRUE"
      TYPE: "FORGE"
      MEMORY: "4G"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      SERVER_NAME: "mc-galacticraft"
      MODE: "survival"
      DIFFICULTY: "normal"
      MAX_PLAYERS: 5
      OVERRIDE_OPS: "TRUE"
      OPS: ""
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      FORCE_REDOWNLOAD: "TRUE"
      GUI: "FALSE"
    tty: true
    stdin_open: true
    volumes:
      - /share/Public/minecraft/servers/galacticraft/volume:/data
    networks:
      - internal

  # https://github.com/rapiz1/rathole
  port_forwarding:
    depends_on:
      - mc
    image: rapiz1/rathole
    restart: unless-stopped
    command: ["--client", "/app/client.toml"]
    tty: true
    volumes:
      - /share/Public/minecraft/servers/galacticraft/client.toml:/app/client.toml
    networks:
      - internal

networks:
  internal:
```

However, FORGE Server does not start with the following error.
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 4 1000 100 4096 Dec 18 03:23 /data'
[init] Resolved version given 1.12.2 into 1.12.2 and major version 1.12
[init] Resolving type given FORGE
[mc-image-helper] 03:25:20.893 INFO  : Forge version 14.23.5.2859 for minecraft version 1.12.2 is already installed
[init] Creating server properties in /data/server.properties
[init] Enabling whitelist functionality
[init] Setting mode
[init] Recreating ops.json file at server startup
[init] Setting initial memory to 4G and max to 4G
[init] Starting the Minecraft server...
Error: Unable to access jarfile /data/forge-1.12.2-14.23.5.2859.jar
2022-12-18T03:25:28.144Z        WARN    mc-server-runner        Minecraft server process failed {"exitCode": 1}
2022-12-18T03:25:28.145Z        INFO    mc-server-runner        Done
```

Do I need to pre-download `forge-1.12.2-14.23.5.2859.jar`?
