### DISCUSSION TITLE
Unable to run on Mac (Ventura 13.2) and Docker Desktop 4.16.2

### DISCUSSION THREAD

**Discussion by Intecpsp** [itzg/docker-minecraft-server#1926] [Q&A]
### Describe the problem

This was running when I was on Docker Desktop 4.15.X. After updating Docker Desktop, I am now getting the below error:

`[init] Running as uid=1000 gid=1000 with /data as 'd---rwx--- 16 1000 1000 512 Jan 24 13:27 /data'`
`/start-utils: line 202: /data/eula.txt: Permission denied`

I am using the docker-compose template from [here](https://github.com/itzg/docker-minecraft-server#attaching-data-directory-to-host-filesystem). And I have even tried the SELinux note below it to no avail.

Something else interesting is that the `minecraft-data` folder permissions is being reset to 470 (after I manually set it to 755 when the server is attempting to start up

### Container definition

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
```

### Container logs

```
minecraft-java-mc-1  | + export HOME=/data
minecraft-java-mc-1  | + HOME=/data
minecraft-java-mc-1  | ++ id -u
minecraft-java-mc-1  | ++ id -g
minecraft-java-mc-1  | ++ ls -lnd /data
minecraft-java-mc-1  | + log 'Running as uid=1000 gid=1000 with /data as '\''d---rwx--- 16 1000 1000 512 Jan 24 13:27 /data'\'''
minecraft-java-mc-1  | + local oldState
minecraft-java-mc-1  | ++ shopt -po xtrace
minecraft-java-mc-1  | + oldState='set -o xtrace'
minecraft-java-mc-1  | + shopt -u -o xtrace
minecraft-java-mc-1  | [init] 2023-01-25 21:23:55+00:00 Running as uid=1000 gid=1000 with /data as 'd---rwx--- 16 1000 1000 512 Jan 24 13:27 /data'
minecraft-java-mc-1  | + '[' '!' -e /data/eula.txt ']'
minecraft-java-mc-1  | + isTrue TRUE
minecraft-java-mc-1  | + case "${1,,}" in
minecraft-java-mc-1  | + return 0
minecraft-java-mc-1  | + writeEula
minecraft-java-mc-1  | ++ date
minecraft-java-mc-1  | + echo '# Generated via Docker
minecraft-java-mc-1  | # Wed 25 Jan 2023 09:23:55 PM UTC
minecraft-java-mc-1  | eula=true
minecraft-java-mc-1  | '
minecraft-java-mc-1  | /start-utils: line 202: /data/eula.txt: Permission denied
minecraft-java-mc-1  | + log 'ERROR: unable to write eula to /data. Please make sure attached directory is writable by uid=1000'
minecraft-java-mc-1  | + local oldState
minecraft-java-mc-1  | ++ shopt -po xtrace
minecraft-java-mc-1  | + oldState='set -o xtrace'
minecraft-java-mc-1  | + shopt -u -o xtrace
minecraft-java-mc-1  | [init] 2023-01-25 21:23:55+00:00 ERROR: unable to write eula to /data. Please make sure attached directory is writable by uid=1000
minecraft-java-mc-1  | + exit 2
minecraft-java-mc-1 exited with code 2
```
