### DISCUSSION TITLE
Help setting up Fabric Server and cobblemon mod

### DISCUSSION THREAD

**Discussion by xdinterface** [itzg/docker-minecraft-server#2039] [Q&A]
I am trying to setup a Fabric server running the cobblemod mod. 
The server itself seems to be running but i disconnect the moment i try to join my server.
i gen an `Internal Exception: io.netty.handler.codec.DecoderExeption: Unknown serizalizer type 26`
I have setup the server without any mods running perfectly fine.

Here is the docker-compose.yaml im using: 
```
version: "3.8"

services:
  minecraft:
    container_name: cobblemon
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    environment:
      UID: 1000
      GID: 1000
      EULA: "TRUE"
      REPLACE_ENV_VARIABLES: "TRUE"
      INIT_MEMORY: 4G
      MAX_MEMORY: 8G
      TYPE: FABRIC
      VERSION: 1.19.2
      #CONSOLE: "FALSE"
      #SEED:
      DIFFICULTY: normal
      MOTD: "HI"
      PVP: "FALSE"
      MAX_PLAYERS: 20
      MODRINTH_PROJECTS: cobblemon
    ports:
      - 25565:25565
    volumes:
      - /home/pi/minecraft/cobblemon:/data
```
     
I tried to specify the cobblemon project version i am using but no difference. The server is up and running but i can't connect from mac or windows.

The server does not throw any error and just informs about the player connecting and disconnecting so it seems to be an error on the client side. And yes i am using the correct java version 1.19.2.

Any ideas how to solve this?
