### DISCUSSION TITLE
Failing to access Curseforge API

### DISCUSSION THREAD

**Discussion by Ozuhan** [itzg/docker-minecraft-server#2122] [Q&A] [answered]
Hello,

I'm trying to get a server running with a modpack (The 1.12.2 Pack) and the container keeps failing with a problem apparently due to my API key according to the logs. The key is fine though, directly copied it and tested if it was valid with a request in Postman. Here's my docker-compose .yml

```
version: '3.8'

services:
  minecraft_server_1-12-2pack:
    image: itzg/minecraft-server:java8-multiarch
    volumes:
    - ./modpacks:/modpacks:ro
    - data:/data
    environment:
      CF_API_KEY: "API_KEY_HERE"
      VERSION: 1.12.2
      EULA: "true"
      TYPE: AUTO_CURSEFORGE
      CF_SLUG: the-1122-pack
    ports:
      - "25565:25565"

volumes:
  data: {}
```

And here's the logs:

```[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 May  9 09:37 /data'
[init] Resolved version given 1.12.2 into 1.12.2 and major version 1.12
[init] Resolving type given AUTO_CURSEFORGE
[mc-image-helper] 10:05:37.574 ERROR : Invalid parameter provided for 'install-curseforge' command: Access to https://api.curseforge.com/v1 is forbidden. Make sure to set CF_API_KEY to a valid API key from https://console.curseforge.com/
[init] ERROR failed to auto-install CurseForge modpack```
