### DISCUSSION TITLE
JMX Profiling with VisualVM

### DISCUSSION THREAD

**Discussion by Tidsuo** [itzg/docker-minecraft-server#2169] [Q&A]
I have been try for the past two days to get VisualVM to connect and monitor the Java process within the Docker container. Any help or troubleshooting steps would be greatly appreciated!

<details>
  <summary>Docker Compose</summary>

  ```
  version: "3"

services:
  gtnh:
    image: itzg/minecraft-server:java19
    container_name: gregtechNH
    hostname: gregtechNH
    env_file:
      - ./.env

    ports:
    - "25565:25565"
    - "7091:7091/tcp"

    environment:
      TZ: ${TZ}
      TYPE: FORGE
      VERSION: 1.7.10
      FORGE_VERSION: 10.13.4.1614
      JVM_OPTS: -Dfml.readTimeout=180 @java9args.txt
      GENERIC_PACK: http://downloads.gtnewhorizons.com/ServerPacks/GT_New_Horizons_2.3.0_Server_Java_17-19.zip
      MEMORY: 4G
      ENABLE_ROLLING_LOGS: true
      GUI: false
      LOG_TIMESTAMP: true
      
      OVERRIDE_SERVER_PROPERTIES: false
      SKIP_GENERIC_PACK_UPDATE_CHECK: true
      ENABLE_JMX: true
      JMX_HOST: 10.70.24.10
      
      EULA: "TRUE"
      
    volumes:
      - '/shares/games/gtnh230:/data'

    tty: true
    stdin_open: true
    restart: unless-stopped
  ```
</details>

In VisualVM I entered the same IP address appended with the port 7091 under the "Add JMX connection" option that I set for the JMX_HOST environment variable.
![image](https://github.com/itzg/docker-minecraft-server/assets/10763193/760634fc-bb19-45e2-b317-1eebd5e3d5fe)
