### DISCUSSION TITLE
Unable to connect to server running on docker

### DISCUSSION THREAD

**Discussion by EnmaDarei** [itzg/docker-minecraft-server#2231] [Q&A] [answered]
I installed the server on a docker container using docker composer. Every time I try to run it it seems to start fine, but eventually it just shows "unhealthy" and I get the message "failed to ping localhost:25565 : could not connect to Minecraft server: dial tcp 127.0.0.1:25565: connect: connection refused"

**Comment by itzg** [comment]
You'll need to provide info such as your compose file, the startup logs, and any manual changes you made to configuration such as `server.properties`.

**Reply by EnmaDarei** [reply]
Sure, I've attached the log file. I didn't change anything in the configuration besides setting eula to true in the eula.txt

The docker compose file looks like this
```
    minecraft:
      container_name: minecraft
      image: itzg/minecraft-server
      ports:
        - 25565:25565
      environment:
        EULA: "TRUE"
      tty: true
      stdin_open: true
      volumes:
        - /home/enma/docker/minecraft:/data
```

[_minecraft_logs.txt](https://github.com/itzg/docker-minecraft-server/files/11780567/_minecraft_logs.txt)
