### DISCUSSION TITLE
Is Autopause working right?

### DISCUSSION THREAD

**Discussion by HIX4123** [itzg/docker-minecraft-server#2394] [Q&A] [answered]
I'm using the Autopause. Autopause begins fine, but it restarts instead of resuming when the user connects to the server.

I read the documentation well and input the required environments. I have everything related to Autopause in one place.

```
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: TRUE
    stdin_open: TRUE
    ports:
      - "19132:19132/udp"
      - "19132:19132/tcp"
    environment:
      #OS Options
      MAX_MEMORY: 4G

      #Server
      TYPE: PURPUR
      PURPUR_BUILD: LATEST
      EULA: "TRUE"
      VERSION: LATEST
      MOTD: "제발 죽지 말아줘 서버야"
      DIFFICULTY: HARD
      MAX_PLAYERS: 15
      ALLOW_NETHER: TRUE
      ANNOUNCE_PLAYER_ACHIEVEMENTS: TRUE
      ENABLE_COMMAND_BLOCK: TRUE
      FORCE_GAMEMODE: FALSE
      HARDCORE: FALSE
      MAX_BUILD_HEIGHT: 317
      SPAWN_ANIMALS: TRUE
      SPAWN_MONSTERS: TRUE
      SPAWN_NPCS: TRUE
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 7
      MODE: SURVIVAL
      PVP: TRUE
      ALLOW_FLIGHT: TRUE
      SERVER_NAME: "ARK_SERVER"
      SERVER_PORT: 19132
      PLAYER_IDLE_TIMEOUT: 7
      ENTITY_BROADCAST_RANGE_PERCENTAGE: 100
      FUNCTION_PERMISSION_LEVEL: 4
      OP_PERMISSION_LEVEL: 4
      PREVENT_PROXY_CONNECTIONS: FALSE
      SIMULATION_DISTANCE: 4
      EXEC_DIRECTLY: FALSE
      STOP_SERVER_ANNOUNCE_DELAY: 1
      #Custom Resource Pack
      
      #Whitelist
      
      #Rcon
      
      #Autopause
      ENABLE_AUTOPAUSE: TRUE
      MAX_TICK_TIME: -1
      JVM_DD_OPTS: "disable.watchdog true"
      
      #Autostop
      
      #Curseforge

    volumes:
      - ./data:/data

      - ./plugins:/data/plugins
      - ./datapacks:/data/world/datapacks
      
    restart: unless-stopped

```
