### DISCUSSION TITLE
Server isn't loading modpacks

### DISCUSSION THREAD

**Discussion by vladbejenaru** [itzg/docker-minecraft-server#2406] [Q&A] [answered]
Hi There, I try to make a minecraft server for my son and of course it should be a Forge server. He would like very much to have this modpack https://www.curseforge.com/minecraft/modpacks/guns-nukes-and-planes2-0/files active. I guess my issue is very similar with this one: https://github.com/itzg/docker-minecraft-server/issues/2314 but I cannot exactly point on what is not functioning... here is my compose file:

```
mcforge:
    image: itzg/minecraft-server
    container_name: mcforge
    ports:
      - 25566:25565
    environment:
      DEBUG: "TRUE"
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: 1.20.1
      FORGE_VERSION: LATEST

      MODE: "creative"
      MOTD: "Sons Forge Server"
      MEMORY: "4G"
      GENERIC_PACK: "/modpacks/Guns-Nukes-And-Planes.zip"
    restart: unless-stopped
    volumes:
      - /virt/mcforge:/data
      - ./modpacks:/modpacks:ro
```

what I have also tried (variation):

```
    TYPE: "CURSEFORGE"
    TYPE: "AUTO_CURSEFORGE"
    MODE: "survival"#      CF_API_KEY: heresomerandomeapikeythatIhavedeletedhaha
    CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/guns-nukes-and-planes2-0"
    CF_MODPACK_ZIP: "/data/mods/Guns-Nukes-And-Planes.zip"
    USE_MODPACK_START_SCRIPT: "false"
    FTB_LEGACYJAVAFIXER: "true"
    CF_SERVER_MOD: Guns-Nukes-And-Planes.zip
    CF_SERVER_MOD: SkyFactory+4-4.2.4.zip
    MODPACK: Guns-Nukes-And-Planes.zip
    CF_SLUG: "guns-nukes-and-planes2-0"
    CURSEFORGE_FILES: |
       guns-nukes-and-planes2-0
```

Here are the logs:
[mcforge-logs.txt](https://github.com/itzg/docker-minecraft-server/files/12784418/mcforge-logs.txt)

**Comment by itzg** [comment, marked as answer]
Started with this

```yaml
version: "3.8"

services: 
  mcforge:
    image: itzg/minecraft-server
    environment:
      EULA: true
      MOD_PLATFORM: AUTO_CURSEFORGE
      # assuming populated .env file in same directory
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/guns-nukes-and-planes2-0"
    ports:
    - "25565:25565"
    volumes:
    - ./data:/data
```

But that modpack dislikes automation:

```
issue2406-mcforge-1  | [mc-image-helper] 22:42:22.482 ERROR : 'install-curseforge' command failed. Version is 1.36.0
issue2406-mcforge-1  | me.itzg.helpers.errors.GenericException: The modpack authors have indicated this file is not allowed for project distribution. Please download the client zip file from https://www.curseforge.com/minecraft/modpacks/guns-nukes-and-planes2-0 and pass via CF_MODPACK_ZIP environment variable or place in downloads repo directory.
```

So, I downloaded the file from https://www.curseforge.com/minecraft/modpacks/guns-nukes-and-planes2-0/files/4623303, created a new directory called "modpacks" next to the compose file, dropped it in there, and used this

```yaml
version: "3.8"

services: 
  mcforge:
    image: itzg/minecraft-server
    environment:
      EULA: true
      MOD_PLATFORM: AUTO_CURSEFORGE
      # assuming populated .env file in same directory
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/guns-nukes-and-planes2-0"
      CF_MODPACK_ZIP: /modpacks/Guns-Nukes-And-Planes.zip
      MEMORY: 4G
    ports:
    - "25565:25565"
    volumes:
    - ./data:/data
    - ./modpacks:/modpacks:ro
```

My directory looks like this

<img width="221" alt="image" src="https://github.com/itzg/docker-minecraft-server/assets/988985/e040ed7d-400b-4499-9324-eabb57faf921">
