### DISCUSSION TITLE
Please help me diagnose why my server crashes, I have basically nothing to go off of

### DISCUSSION THREAD

**Discussion by xane256** [itzg/docker-minecraft-server#2411] [General]
The problem:
- My SMP server sometimes crashes when a player logs off. Sometimes its me, sometimes other players.
- It happens approximately every 2 days, and most of the time logging out does not cause crash
- **When the server crashes, there's no crash log generated, and no information printed to the server logs or docker logs** I've attached my latest docker-compose logs where I set the environment variables `DEBUG`, `DEBUG_EXEC` and `DEBUG_MEMORY` to `TRUE`. Unfortunately there is no stack trace or other crash info.
- I have a very minimal set of mods (carpet and a few similar mods used for technical vanilla Minecraft)
- I have another server instance running with a larger set of mods that seemingly doesn't have this problem

I'd really like to diagnose this because I want to start using world eaters and fancier storage systems which can be corrupted / damaged if chunks are suddenly unloaded.

The Big Question:
- How can I get into the JVM or some other enhanced debug logging mode where I could actually get an idea of what the issue / problematic mod might be? Im not sure if it's an issue with a mod, a file permission issue, or the ARM architecture.

System:
- macOS 64-bit ARM

[log-8-5-23.log](https://github.com/itzg/docker-minecraft-server/files/12829598/log-8-5-23.log)

Any ideas?

**Comment by itzg** [comment]
This isn't really the right forum to ask about server crashes. You should probably ask around on support communities specific to the mod loader.

Container wise you can add whatever JVM args are needed and add additional port mappings, such as attaching a debugger. I can further help with that specifically if you still have questions there.

**Reply by xane256** [reply]
Yes please! It's hard to reproduce and only happens every few days so extra logging and debug tools are what I'm interested in.

I previously tried changing the entrypoint to bash and then manually invoking the start script hoping to see more in stdout, but that didn't give me any extra info. But I can do that to prevent the container stopping when the server exits.

**Reply by itzg** [reply]
I'm sorry, I think you misunderstood my offer. Here's **how** to pass JVM args that you find you will need for debugging

https://docker-minecraft-server.readthedocs.io/en/latest/configuration/jvm-options/#extra-jvm-options

Additional port mappings are juat standard docker. 

Otherwise, please contact other support forums for advice about how to debug server crashes. It is not docker specific at that point.

**Reply by xane256** [reply]
Thanks for the tip! I discovered the issue was that Docker Desktop had too low a "memory limit" setting which limits the total memory that containers can collectively use.

**Comment by PlexSheep** [comment]
I might have the same thing. The server starts as I would expect it to, and mysteriously crashes after some time. It's gotten really regular by now. Without anything having been logged many seconds, it goes like this:

```
minecraft  | [18:31:45 INFO]: <own PlexSheep> lets see when it crashes again :/
minecraft  | 2023-11-10T18:32:30.104Z   WARN    mc-server-runner        Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.     {"exitCode": -1}
minecraft  | 2023-11-10T18:32:30.106Z   INFO    mc-server-runner        Done
```

After that, I'd expect to get a crash report, but I don't have one. There is no information to work here for me.

My compose file for reference:
```yml
version: "3"

networks:
    snowboard:
        name: snowboard
        external: true

services:
  minecraft:
    networks:
      - snowboard
    image: itzg/minecraft-server
    container_name: minecraft
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      tty: true
      stdin_open: true
      VERSION: 1.19.4
      MOTD: "PlexSheep's personal server"
      DIFFICULTY: normal
      OPS: PlexSheep
      ICON: https://static.cscherr.de/images/profile/profile.png
      MAX_PLAYERS: 20
      MAX_WORLD_SIZE: 65536 # radius in blocks to border
      SPAWN_PROTECTION: 0
      SERVER_NAME: PlexServ
      MEMORY: 4G
      TYPE: "PAPER"
      UID: 1003
      GID: 1005
      # EssentialsX (needs preload) 9089, Vault, LuckPerms
      SPIGET_RESOURCES: 28140,34315
      DEBUG: true
      DEBUG_MEMORY: true
      DEBUG_EXEC: true
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 5s
      retries: 20
    volumes:
      - /srv/minecraft/data:/data
```

**The solution?**
Now, after spending another while, the server crashes seem to have stopped after removing the treecapacitator plugin, which was called legacy in the logs. I still wonder if this will make my server stable again, but for now it seems to work at least. I'm also still confused that there was no crash report.

**Update**
Nope, didn't work. The same thing is happening still.
```
...
minecraft  | [18:47:57 INFO]: PlexSheep joined the game
minecraft  | [18:47:57 INFO]: PlexSheep[/77.23.183.200:51062] logged in with entity id 284 at ([world]40.7759294482224, 53.0, -60.42827776908737)
^[^[minecraft  | 2023-11-10T18:52:55.783Z       WARN    mc-server-runner        Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.     {"exitCode": -1}
minecraft  | 2023-11-10T18:52:55.844Z   INFO    mc-server-runner        Done
minecraft exited with code 0
```
I don't get it.

[server.log](https://github.com/itzg/docker-minecraft-server/files/13322407/server.log)

**Reply by itzg** [reply]
That certainly sounds annoying. Unfortunately I don't have anything to add other than what I already said above: https://github.com/itzg/docker-minecraft-server/discussions/2411#discussioncomment-7209375

**Reply by PlexSheep** [reply]
I just noticed that my compose File has bad mappings, specifically the tty and stout items. That seems to have fixed it, but I'm cautious to declare that fixed it.

This is the new compose File:
```yml
version: "3"

networks:
    snowboard:
        name: snowboard
        external: true

services:
  minecraft:
    networks:
      - snowboard
    image: itzg/minecraft-server
    container_name: minecraft
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: 1.19.4
      MOTD: "PlexSheep's personal server"
      DIFFICULTY: normal
      OPS: PlexSheep
      ICON: https://static.cscherr.de/images/profile/profile.png
      MAX_PLAYERS: 20
      MAX_WORLD_SIZE: 65536 # radius in blocks to border
      SPAWN_PROTECTION: 0
      SERVER_NAME: PlexServ
      MEMORY: 4G
      TYPE: "PAPER"
      UID: 1003
      GID: 1005
      # EssentialsX (needs preload) 9089, Vault, LuckPerms, smooth timber
      SPIGET_RESOURCES: 28140,34315,39965
      DEBUG: false
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 5s
      retries: 20
    volumes:
      - /srv/minecraft/data:/data

```
Update: A Day later, it seems to work. My problem was the docker-compose file
