### DISCUSSION TITLE
Having an issue with custom configs

### DISCUSSION THREAD

**Discussion by nadrojisk** [itzg/docker-minecraft-server#2465] [Q&A] [answered]
Hi! I noticed that during the image startup it uses some default configs for bukkit, spigot, etc. Is there a way for me to pass a custom config? I'm essentially just trying to turn on bungee in the spigot config.. I see that you can pass server properties via env values and I saw some issues where you talked about potentially adding that in the future for other configs.

**Comment by itzg** [comment, marked as answer]
The [config path](https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/#optional-plugins-mods-and-config-attach-points) and [these features](https://docker-minecraft-server.readthedocs.io/en/latest/configuration/interpolating/) allow for providing and customizing various config files. 

FYI those default config files are created by the respective server software itself and not the image startup, which is why it is awkward to "modify" those since they don't exist at first container startup.

**Reply by nadrojisk** [reply]
I attempted to use the config path with modifying the environment variables, but it was not working as intended. 
This is the setup I am using. I also attempted leaving the dest env default, and that also didn't work.

<img width="314" alt="image" src="https://github.com/itzg/docker-minecraft-server/assets/37343577/2e26088e-4e87-4d68-91a2-758a02145811">


```
version: '3.5'
services:
  mc_survival:
    container_name: mc_survival
    build:
      context: ../minecraft-world/
    restart: 'unless-stopped'
    networks:
      minecraft-net:
        aliases:
          - 'mc_survival'
          - 'survival'
    environment:
      DIFFICULTY: 'normal'
      VANILLATWEAKS_SHARECODE: 'wkNXI0'
      MODE: 0

      # SERVER CONFIG
      MAX_WORLD_SIZE: 250000
      LEVEL_TYPE: 'default'
    volumes:
      - ${MINECRAFT_DIR}/worlds/mc-survival/data:/data
    tty: true
    stdin_open: true

networks:
  minecraft-net:
    external:
      name: minecraft-net
```

```
FROM itzg/minecraft-server:latest

ENV VERSION='1.20.2'

# Configure Server with Default Values
ENV   EULA='TRUE' \
      TYPE='PURPUR' \
      ONLINE_MODE='FALSE' \
      ANNOUNCE_PLAYER_ACHIEVEMENTS='FALSE' \
      MAX_PLAYERS=50 \
      MEMORY='2G' \
      VIEW_DISTANCE='32' \
      COPY_CONFIG_DEST=/data \
      COPY_CONFIG_SRC=resources/config \
      ENFORCE_WHITELIST='TRUE' 
```

**Reply by nadrojisk** [reply]
Realized that I misunderstood `/config` and `COPY_CONFIG_SRC`. I assumed those were referring to the local file system, not the container. Corrected with the following:

<img width="226" alt="image" src="https://github.com/itzg/docker-minecraft-server/assets/37343577/9f3b9585-7a6b-474c-a4a1-ef6b3040f024">

```
version: '3.5'
services:
  mc_survival:
    container_name: mc_survival
    build:
      context: minecraft-world
    restart: 'unless-stopped'
    networks:
      minecraft-net:
        aliases:
          - 'mc_survival'
          - 'survival'
    environment:
      DIFFICULTY: 'normal'
      VANILLATWEAKS_SHARECODE: 'wkNXI0'
      MODE: 0

      # SERVER CONFIG
      MAX_WORLD_SIZE: 250000
      LEVEL_TYPE: 'default'
    volumes:
      - ${MINECRAFT_DIR}/worlds/mc-survival/data:/data
      - ./minecraft-world/config/:/config/
```
