### DISCUSSION TITLE
rcon-cli: Always getting `Error executing: <command> (null)`

### DISCUSSION THREAD

**Discussion by Alestrix** [itzg/docker-minecraft-server#2495] [Q&A] [answered]
I assume this is a misconfiguration on my side as nobody else seems to have this issue.

I run the minecraft image with TYPE=FOLIA (I have 24 vcores available at low clock speed, so I need the multithreading) via a docker compose file. Due to client requirements (according to my son "optipac" or similar is not compatible with 1.20.2) I need to run version 1.20.1.

RCON is properly started according to the logs:
```
$ docker logs mc | grep RCON | grep -v "RCON Client"
*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://papermc.io/downloads/paper ***
[20:12:52] [Server thread/INFO]: Thread RCON Listener started
[20:12:52] [Server thread/INFO]: RCON running on 0.0.0.0:25575
```

 I am ignoring the warning as I have pulled and deployed this image just two days ago, so I assume it has to do with the VERSION=1.20.1.

When I try to issue an rcli command via docker exec, I get this:
```
$ docker exec -ti  mc rcon-cli list
Error executing: list (null)
```

`rcon-cli` is properly authenticating to the server as I get an authentication error if I run `rcon-cli` with `--password` and use an incorrect password.

The only thing I see on the console (`docker logs -f mc`) when I run the `rcon-cli` command is this:
```
[20:27:35] [RCON Listener #1/INFO]: Thread RCON Client /127.0.0.1 started
[20:27:35] [RCON Client /127.0.0.1 #10/INFO]: Thread RCON Client /127.0.0.1 shutting down
```

The same thing happens when I connect in interactive mode:
```
$ docker exec -ti mc rcon-cli
> /help
Error executing: /help (null)
> help
Error executing: help (null)
> list
Error executing: list (null)
> quit
Error executing: quit (null)
> :q
Error executing: :q (null)
> :quit
Error executing: :quit (null)
> ^C
```

Then the console shows this:
```
[20:34:16] [RCON Listener #1/INFO]: Thread RCON Client /127.0.0.1 started
[20:34:35] [RCON Client /127.0.0.1 #12/INFO]: Thread RCON Client /127.0.0.1 shutting down
```

For completeness sake here's my docker-compose:
```
version: "3.3"

services:
  mc:
    image: itzg/minecraft-server:stable
    ports:
    - "25567:25565"
    user: 1000:1000
    container_name: mc
    environment:
      UID: 1000
      GID: 1000
      MEMORY: 2560M
      TZ: "Europe/Berlin"
      ENABLE_ROLLING_LOGS: "true"
      USE_AIKAR_FLAGS: "true"
      MOTD: ~~redacted~~
      DIFFICULTY: "hard"
      SNOOPER_ENABLED: "false"
      PREVENT_PROXY_CONNECTIONS: "false"
      STOP_SERVER_ANNOUNCE_DELAY: 30
      GUI: "false"
      ENABLE_WHITELIST: "true"
      WHITELIST: ~~redacted~~
      RCON_PASSWORD: ~~redacted~~
      EULA: "TRUE"
      TYPE: FOLIA
      VERSION: 1.20.1
    volumes:
    - /opt/docker-mc/data:/data
    - /opt/docker-mc/mods:/mods:ro
```
