### DISCUSSION TITLE
what modpacks for forge are you guys running?

### DISCUSSION THREAD

**Discussion by slyfox1186** [itzg/docker-minecraft-server#2566] [General]
I have been having issues getting the modpacks to install on the client even though I am sourcing the same modpack for both the server and client. The server ends up missing modpacks and I was wondering if anyone had some advice on a good modpack that I could install.

**Comment by slyfox1186** [comment]
I wanted to share a modpack that I got to work.

`NAME: ALL THE MODS 9 (ATM 9)`

```
version: '3.8'

services:
  mc-forge:
    image: itzg/minecraft-server:java17
    environment:
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "false"
      EULA: "true"
      CF_SERVER_MOD: https://mediafilez.forgecdn.net/files/4985/960/Server-Files-0.2.34.zip # ALL THE MODS 9 (ATM 9)
      DIFFICULTY: "normal"
      ENABLE_QUERY: "true"
      ENABLE_RCON: "false"
      MAX_TICK_TIME: 120000
      MEMORY: 12G
      MAX_PLAYERS: 50
      MOTD: > 
        Jeffy Boy's Minecraft Server
        No griefing, stealing, destroying, or killing other players. You will be banned!
      PVP: "FALSE"
      TYPE: CURSEFORGE
      REMOVE_OLD_MODS: "false"
      SERVER_NAME: "GET REKT"
      VIEW_DISTANCE: 15
    ports:
      - "25565:25565"
    volumes:
      - ./modpacks:/modpacks:ro
      - ./minecraft-forge:/data
```

I also created a backup script to save a backup using crontab.

```
#!/usr/bin/env bash

clear

#
# Define variables
#

time_stamp=$(date +%H.%M-%m.%d.%Y)
source_dir="$HOME"/minecraft-forge
backup_file='minecraft-forge'
backup_dir="/path/to/backup/folder/$backup_file-$time_stamp"
id='c740d0a1bf82'

#
# STOP THE DOCKER IMAGE
#

printf "%s\n\n" "Stopping the Docker Image: $backup_file..."
sudo docker stop $id

#
# CREATE A TIMESTAMPED BACKUP FOLDER 
#

if [ ! -d $backup_dir ]; then
    mkdir -p $backup_dir
fi

#
# CREATE A TIMESTAMPED BACKUP FOLDER 
#

printf "%s\n\n" "Creating the backup..."
cp -r $source_dir $backup_dir

#
# CREATE A TIMESTAMPED BACKUP FOLDER 
#

printf "%s\n\n" "Starting $backup_file..."
sudo docker start $id

printf "%s\n\n" "Backup completed. Backup saved in: $backup_dir"
```
