### DISCUSSION TITLE
Unable to get API key

### DISCUSSION THREAD

**Discussion by emy3** [itzg/docker-minecraft-server#2588] [Q&A] [answered]
Hi I am having issues while trying to update atm9 server. I was previously on 0.2.32 and wanted to update to the latest modpack version.
I updated the CF_PAGE_URL to the new modpack version and also updated CF_FILE_MATCHER to the version to grab.

When I run docker compose up on the yml I get : 
'Invalid parameter provided for 'install-curseforge' command: Access to https://api.curseforge.com is forbidden. Make sure to set CF_API_KEY to a valid API key from https://console.curseforge.com/'

It worked previously when I created on 20 DEC 2023. I do have the .env in the same directory as the yml.
The api key on curseforge console is also updated/regenerated.

Any help/guidance is appreciated thank you.

Docker compose file
```
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      MOD_PLATFORM: AUTO_CURSEFORGE
      # allocate from https://console.curseforge.com/ and set in .env file
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5016013
      CF_FILENAME_MATCHER: "0.2.36"
      CF_FORCE_SYNCHRONIZE: true
      MEMORY: 16G
    volumes:
      - mc-data:/data
      - ../downloads:/downloads
  # Since Docker's default volume driver creates volumes owned by root, this
  # init container will change ownership to match final UID of mc service, above
  init-filebrowser:
    image: filebrowser/filebrowser
    entrypoint: sh -c
    command:
      - "chown -R 1000: /database"
    restart: "no"
    volumes:
      - filebrowser-db:/database
  filebrowser:
    image: filebrowser/filebrowser
    depends_on:
      init-filebrowser:
        condition: service_completed_successfully
    user: "1000:1000"
    environment:
      FB_DATABASE: /database/filebrowser.db
    volumes:
      # Default FB_ROOT is /srv
      # In this example, the left-side needs to be the same as /data volume of mc service
      - mc-data:/srv
      - filebrowser-db:/database
    ports:
      - "25580:80"

volumes:
  mc-data: {}
  filebrowser-db: {}
```

Container log
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 22 1000 1000 4096 Jan 12 12:11 /data'

[mc-image-helper] 12:34:37.411 ERROR : Invalid parameter provided for 'install-curseforge' command: Access to https://api.curseforge.com is forbidden. Make sure to set CF_API_KEY to a valid API key from https://console.curseforge.com/

[init] ERROR failed to auto-install CurseForge modpack
```
