### DISCUSSION TITLE
Example of installing a single curseforge mod

### DISCUSSION THREAD

**Discussion by fisher60** [itzg/docker-minecraft-server#2603] [Q&A]
Hello, I see that support was added a few months ago for adding curseforge mods from a single mod file, but this does not appear to be fully documented. Can someone please provide help with achieving this, preferably in the context of docker-compose?

It does not appear that I can specify a mod URL on curseforge using a URL to a mod such as this https://www.curseforge.com/minecraft/mc-mods/knight-quest/files/4587515

I have also tried the `downloads` volume mount, but there does not seem to be any env var I can set that will allow the image to utilize the downloads volume, instead I get an error that the slug, file, etc cannot be found on curseforge.

I have tried a few different settings, but this is my current docker-compose

```yaml
services:
  mc:
    image: itzg/minecraft-server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${RCON_PORT}:${RCON_PORT}
      - ${DYNMAP_PORT}:8123
    env_file:
      - .env
    environment:
      EULA: "TRUE"
      TYPE: AUTO_CURSEFORGE
      CF_SLUG: KnightQuest1.2.7.Patch.jar
    tty: true
    stdin_open: true
    restart: unless-stopped
    healthcheck:
      test: bash -x mc-health
    volumes:
      - ./data:/data
      - ./downloads:/downloads
      ```

**Comment by itzg** [comment]
Can you let me know what was lacking from the documentation here

https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/curseforge-files/

**Reply by fisher60** [reply]
Hello, I apologize, I had not discovered this page. When looking for this answer, I saw the documentation here https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/ and was confused regarding how to install individual mods from a URL or from a local file.

With that said, perhaps the docs you linked could use some more specific examples. I.e I rewrote my docker-compose according to the linked docs and I get immediate errors.

```yaml
services:
  mc:
    image: itzg/minecraft-server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${RCON_PORT}:${RCON_PORT}
    env_file:
      - .env
    environment:
      EULA: "true"
      TYPE: AUTO_CURSEFORGE
      VERSION: 1.19.4
      CURSEFORGE_FILES: |
        knight-quest
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data
```
This compose file seems correct to me and uses the slug for the desired mod.
This gives the following error.
```
A modpack page URL or slug identifier is required
[init] ERROR failed to auto-install CurseForge modpack
```
      
I am famous for user-errors, but it seems either I or the docs are missing a needed explanation as to how to get this working.
