### DISCUSSION TITLE
Mismatched Mod Channel List on many modpacks via docker-compose - but not when manually installed

### DISCUSSION THREAD

**Discussion by AlexanderNZ** [itzg/docker-minecraft-server#2604] [Q&A]
Hi all,

I'm trying to work out how to host a minecraft server with docker compose. I'm not sure if this is a bug or something I'm doing wrong and would be greatful for advice. When I install and run ATM9 via docker compose (example to follow) and log in using ATM9 managed via CurseForge client, the client fails to connect to the server and yields a `Connection closed - mismatched mod channel list` error.

When I manually install the server files and run it via CLI I am able to successfully connect and load the world.
This feels like an issue either with docker compose, with `itzg/minecraft-server` (least likely) or an issue with the way I am trying to use both of these tools together (most likely). Can anyone spot anything I am doing wrong?

Steps to reproduce:

1.  Download All the Mods 9 (https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5036838) with `wget https://www.curseforge.com/api/v1/mods/715572/files/5036871/download` 
2. Extract Server files
3. Install with `java -jar forge-1.20.1-47.2.19-installer.jar --installServer` and set eula to true
4. Run `run.sh`
5. Wait for world to generate and connect (successful)

6. Then install via docker compose:
```
version: "3"

services:
  minecraft:
    container_name: minecraftserver
    image: ${IMAGE:-itzg/minecraft-server}
    user: "1000:1000"
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: "1.20.1"
      MODPACK: "https://www.curseforge.com/api/v1/mods/715572/files/5036871/download"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      JVM_XX_OPTS: -Xms12G -Xmx16G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
      MAX_MEMORY: 16G
      MAX_PLAYERS: 10
      MOTD: "ATM9 for Toby, Dominic and Dad"
      OPS: alexandernz
    ports:
      - 25565:25565
    volumes:
      - /minecraft/modpacks/atm/9/docker:/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped  
```
7. Wait for pack to install and world to generate, and then connect via the same client (connection fails)

This feels like a permissions issue, like maybe the mod pack cannot detect the jar files and so doesn't load them, but that doesn't explain that I can see those files being processed in the log output and there are no errors to indicate the server had any issues.

Anyone have any ideas about what might be going on here?
