### DISCUSSION TITLE
Should one report the problems with the automatic installation for mods or add them directly as a pull request to cf-exclude-include.json?

### DISCUSSION THREAD

**Discussion by JanisPlayer** [itzg/docker-minecraft-server#2616] [Q&A] [answered]
I have a question about the AUTO_CURSEFORGE function for mods. So, I understood one thing, automatic installation saves absolutely no time for modpacks where client and server mods are different. Apparently, you can use CF_EXCLUDE_MODS and CF_FORCE_INCLUDE_MODS to adjust mods that don't belong and mods that do belong.

However, there is also the [cf-exclude-include.json](https://github.com/itzg/docker-minecraft-server/blob/master/files/cf-exclude-include.json). Should one create this file only for oneself, or should mods be added with a pull request? [Engineer's Life 2](https://www.curseforge.com/minecraft/modpacks/engineers-life-2) is one such mod that cost me a lot of time for this reason.

Anyway, I don't want to manually search for and exclude every mod from the list by Project ID. For this, I needed a file sync program to compare the differences in the mod folder. Anyway, I didn't feel like wasting more than 2 hours with a bunch of crashes, and then I found the old approach. Yes, this method works significantly faster and better; the server was immediately up.

So, since I don't want to consider the time completely wasted, I'm sharing my information for the modpack. Maybe it helps someone to create a CF_EXCLUDE_INCLUDE_FILE so that this mod also runs.

For those who want to get Docker running, I recommend the following Docker Compose:

```yaml
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java8-multiarch
    environment:
      EULA: "TRUE"
      TYPE: "CURSEFORGE"
      VERSION: "1.16.5"
      CF_API_KEY: '<$$You$$API$$Key$$ or  ${CF_API_KEY}>'
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/engineers-life-2/files/4984975"
      CF_SERVER_MOD: "Serverpack.zip"
      CF_EXCLUDE_MODS: "297038, 325020, 270441, 287443"
      MAX_MEMORY: "4G"
      OPS: "<your_name>"
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
```

Simply download [EL2-Serverpack-1.18a](https://www.curseforge.com/minecraft/modpacks/engineers-life-2/files/4985013) and move it to the data directory, naming it `Serverpack.zip`.

Here is the promised information for the modpack:

List of all missing mods:

```
BetterDefaultBiomes-1.16.4+-Alpha 2.6.1.jar (Cannot be loaded..)
betterendforge-1.16.5-1.6.3.jar (Cannot be loaded.)
Controlling-7.0.0.29.jar
CTM-MC1.16.1-1.1.2.6.jar
JustEnoughResources-1.16.5-0.12.1.128.jar
modernfix-forge-5.11.0+mc1.16.5.jar
moreoverlays-1.18.19-mc1.16.5.jar
MouseTweaks-2.14-mc1.16.2.jar
namepain-1.5.0 forge-1.16.x.jar
nerb-1.16.5-0.3.1-FORGE.jar (Cannot be loaded.)
starlight-1.2.jar (Cannot be loaded.)
Tips-1.16.5-4.0.18.jar
WailaHarvestability-mc1.16.x-forge-1.1.15.jar
```

Mods that could not be downloaded are listed in MODS_NEED_DOWNLOAD.txt:

| Mod                      | Version Name                               | Filename                                      | Download page                                                                    |
|--------------------------|---------------------------------------|-------------------------------------------|---------------------------------------------------|
| BetterEnd (Forge)        | betterendforge-1.16.5-1.6.3           | betterendforge-1.16.5-1.6.3.jar           | [Download](https://www.curseforge.com/minecraft/mc-mods/betterend-forge-port/files/3467948) |
| BetterDefaultBiomes      | BetterDefaultBiomes-1.16.4+-Alpha 2.6.1 | BetterDefaultBiomes-1.16.4+-Alpha 2.6.1.jar | [Download](https://www.curseforge.com/minecraft/mc-mods/better-default-biomes/files/3570618) |
| Starlight x Create       | Starlight x Create - v1.2             | starlight-1.2.jar                        | [Download](https://www.curseforge.com/minecraft/mc-mods/starlight-x-create/files/3583654)   |
| Not Enough Recipe Bo...  | nerb-1.16.5-0.3.1-FORGE               | nerb-1.16.5-0.3.1-FORGE.jar               | [Download](https://www.curseforge.com/minecraft/mc-mods/notenoughrecipebook/files/4750581)  |

List of all mods that should not be in the server pack:

```
betteranimalmodels-1.16.5-5.6.0-forge.jar (Crash)
BetterF3-1.1.3-forge-1.16.5.jar
BH-Menu-1.16.5-1.3.jar
CraftPresence-Forge-1.16.5-Release-1.8.9.jar (Crash)
drippyloadingscreen_forge_1.5.1_MC_1.16.2-1.16.5.jar
Durability101-forge-1.16-0.0.4.jar (Crash)
ezzoom-1.16.4-1.1.1.jar
fancymenu_2.3.7_MC_1.16.2-1.16.5.jar
ItemPhysicLite_v1.4.8_mc1.16.5.jar (Crash)
konkrete_forge_1.3.3_MC_1.16.2-1.16.5.jar
lootbeams-1.16.5-release-july1722.jar
modernfix-forge-5.11.1+mc1.16.5.jar (This mod is fine, it's just a different version.)
nopotionshift_1.16.4-1.6.1.jar
sodium-forge-2.9.10+rev.ea6353c.jar
textrue_embeddium_options-0.1.2+mc1.16.5.jar
```
