### DISCUSSION TITLE
Internal Exception io.netty.channel.unix.Errors.NativeIoException: syscall:read(...)() failed: Connection reset by peer

### DISCUSSION THREAD

**Discussion by Mocpy** [itzg/docker-minecraft-server#2669] [Q&A]
Hello,
my server crash after some things and it show this error: **Internal Exception io.netty.channel.unix.Errors.NativeIoException: syscall:read(...)() failed: Connection reset by peer. Does anyone know how to fix it?**

My docker compose file:
```yaml
version: '3'
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    volumes:
      - /mnt/elements/mc-fabric/data:/data
      - /mnt/elements/mc-fabric/mods:/mods
    ports:
      - "25565:25565"
      - "24454:24454/udp"
      - "8123:8123"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.20.1"
      MAX_MEMORY: "6G"
      INIT_MEMORY: "5G"
      MEMORY: 5G
      ONLINE_MODE: "FALSE"
      DIFFICULTY: "normal"
      JVM_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled"
      SERVER_VIEW_DISTANCE: 16
      SERVER_LOG_LEVEL: debug
    deploy:
      resources:
        limits:
          memory: 5G
    tty: true
    stdin_open: true
    restart: unless-stopped
volumes:
  minecraftdata:
    external: true
```
List of mods I'm using:
- BetterThirdPerson-Fabric-1.20-1.9.0.jar
- Bookshelf-Fabric-1.20.1-20.1.8.jar
- Clumps-fabric-1.20.1-12.0.0.3.jar
- Dynmap-3.6-fabric-1.20.jar
- Emojiful-Fabric-1.20.1-4.2.0.jar
- EnchantmentDescriptions-Fabric-1.20.1-17.0.13.jar
- Jade-1.20-fabric-11.7.0.jar
- RegionsUnexploredFabric-0.5.3.3+1.20.1.jar
- TerraBlender-fabric-1.20.1-3.0.1.2.jar
- YungsApi-1.20-Fabric-4.0.2.jar
- YungsBetterDesertTemples-1.20-Fabric-3.0.3.jar
- YungsBetterDungeons-1.20-Fabric-4.0.3.jar
- YungsBetterJungleTemples-1.20-Fabric-2.0.4.jar
- YungsBetterNetherFortresses-1.20-Fabric-2.0.5.jar
- YungsBetterOceanMonuments-1.20-Fabric-3.0.4.jar
- YungsBetterStrongholds-1.20-Fabric-4.0.3.jar
- Zoomify-2.11.2.jar
- advancednetherite-fabric-2.0.2-1.20.1.jar
- appleskin-fabric-mc1.20.1-2.5.1.jar
- architectury-9.1.12-fabric.jar
- betterchunkloading-fabric-1.20.1-2.6.jar
- capes-1.5.2+1.20-fabric.jar
- cardinal-components-api-5.2.2.jar
- carryon-fabric-1.20.1-2.1.2.7.jar
- chat_heads-0.10.30-fabric-1.20.jar
- cloth-config-11.1.118-fabric.jar
- create-fabric-0.5.1-d-build.1161+mc1.20.1.jar
- creeperoverhaul-3.0.1-fabric.jar
- cupboard-fabric-1.20.1-2.2.jar
- fabric-api-0.91.0+1.20.1.jar
- fabric-chunkpregen-0.3.7.jar
- fabric-language-kotlin-1.10.17+kotlin.1.9.22.jar
- farmers-delight-fabric-1.4.3.jar
- fastpaintings-1.20-1.2.3-fabric.jar
- framework-fabric-1.20.1-0.6.16.jar
- geckolib-fabric-1.20.1-4.4.jar
- goblintraders-fabric-1.20.1-1.9.3.jar
- immersive_armors-1.6.1+1.20.1-fabric.jar
- ironchests-5.0.2-fabric.jar
- itemcollectors-1.1.9-fabric-mc1.20.jar
- jei-1.20.1-fabric-15.2.0.27.jar
- journeymap-1.20.1-5.9.18-fabric.jar
- lazydfu-0.1.3.jar
- letmedespawn-fabric-1.20.x-1.2.0.jar
- lithium-fabric-mc1.20.1-0.11.2.jar
- lootr-1.20-0.7.29.75.jar
- mcw-lights-1.0.6-mc1.20.1fabric.jar
- mighty_mail-fabric-1.20.1-1.0.14.jar
- moonlight-1.20-2.8.87-fabric.jar
- moremobvariants-fabric+1.20-1.2.2.jar
- naturalist-fabric-4.0.3-1.20.1.jar
- plushies-1.4.0-fabric.jar
- resourcefulconfig-fabric-1.20.1-2.1.2.jar
- smoothchunk-fabric-1.20.1-3.5.jar
- supermartijn642configlib-1.1.8a-fabric-mc1.20.jar
- supermartijn642corelib-1.1.16-fabric-mc1.20.1.jar
- supplementaries-1.20-2.7.29-fabric.jar
- travelers-backpack-1.20.1-9.1.9.jar
- trinkets-3.7.1.jar
- voicechat-fabric-1.20.1-2.4.32.jar
- yet-another-config-lib-fabric-3.2.1+1.20.jar
