### DISCUSSION TITLE
Server showing up twice

### DISCUSSION THREAD

**Discussion by totalitarian** [itzg/docker-minecraft-server#2688] [Q&A] [answered]
Hi. any reason my server shows up twice under lan games?

```
version: '3.8'
services:
  mc:
    image: itzg/minecraft-server
    container_name: paper
    environment:
      EULA: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 10
      MEMORY: 4G
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
    ports:
      - "25565:25565"
      - "19132:19132/udp"

    volumes:
      - /home/minecraft/data:/data
    restart: unless-stopped
    network_mode: host
```
