### DISCUSSION TITLE
Incomplete command error using Minecraft server commands via Docker attach

### DISCUSSION THREAD

**Discussion by aligoldenhat** [itzg/docker-minecraft-server#2925] [Q&A]
Hi please help me to fix this
certain commands (e.g., /kick, /locate, /op) return an "Unknown or incomplete command" error. However, commands like /help work.

```
/locate
[12:55:53] [Server thread/INFO]: Unknown or incomplete command, see below for error
[13:02:49] [Server thread/INFO]: locate<--[HERE]
```

docker-compose.yaml is 
```
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    volumes:
      - ./data:/data
```
