### DISCUSSION TITLE
Skyfactory 4 Problem

### DISCUSSION THREAD

**Discussion by Leo-Berman** [itzg/docker-minecraft-server#3033] [Q&A] [answered]
[crash-2024-08-05_16.33.48-server.txt](https://github.com/user-attachments/files/16500392/crash-2024-08-05_16.33.48-server.txt)
[docker-compose.yml.txt](https://github.com/user-attachments/files/16500405/docker-compose.yml.txt)

I'm currently having an issue setting up a skyfactory 4 server. I'm currently debugging and I'm not sure if its a bug in the container or if I'm doing something wrong. Help is super appreciated. I've attached logs and my docker compose files

**Comment by Leo-Berman** [comment, marked as answer]
I downloaded the mods folder manually and copied it over. That and increasing the memory size seemed to do the trick and now I just gotta set the world correctly which I'm sure is in the docs!

**Reply by Leo-Berman** [reply]
also had to change server.properties:

 generator-settings={"Topography-Preset"\:"Sky Factory 4"}

**Reply by itzg** [reply]
FYI you can also set that with https://docker-minecraft-server.readthedocs.io/en/latest/configuration/server-properties/#level-type-and-generator-settings

**Reply by Leo-Berman** [reply]
I know this is a late response but thanks for the followup!

**Comment by NoPanicBanick** [comment]
net.minecraftforge.fml.common.MissingModsException: Mod wailastages (Waila Stages) requires [waila]

If you ended up here because of the above (see the attached server.txt on the post), another solution is to use the [CURSEFORGE_FILES ](https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/curseforge-files/) variable to force the download of the missing mod.  My loose understanding is that waila got renamed to "hwyla" and for some reason it's not resolving in the Waila Stages mod.  In my case, I'm using kuberentes to host the server and the deployment looks something like this.  Note: A statefulset is probably a better choice here but live your life.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: your-namespace
spec:
  selector:
    matchLabels:
      app: minecraft
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:java8
        env:
        - name: CF_API_KEY
          value: "{your-curseforge-key-here}"
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "AUTO_CURSEFORGE"
        - name: CF_PAGE_URL
          value: "https://www.curseforge.com/minecraft/modpacks/skyfactory-4"
        - name: CURSEFORGE_FILES
          value: "https://www.curseforge.com/minecraft/mc-mods/hwyla"
        - name: MEMORY
          value: "8G"
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
        - name: minecraft-data
          mountPath: /data
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data
```
