### DISCUSSION TITLE
Autopausing knocked in loop

### DISCUSSION THREAD

**Discussion by attssystem** [itzg/docker-minecraft-server#3036] [Q&A] [answered]
Hi :)

I'm using this docker image with this compose file :
```
name: minecraft
services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    ports:
      - 25565:25565
    volumes:
      - ./data:/data
    environment:
      VERSION: "1.21"
      INIT_MEMORY: "512M"
      MAX_MEMORY: "2048M"
      EULA: "TRUE"
      ENABLE_AUTOPAUSE: "TRUE"
      MAX_TICK_TIME: "-1"
      # Aggressive for tests
      AUTOPAUSE_TIMEOUT_INIT: "10"
      AUTOPAUSE_TIMEOUT_EST: "1"
    restart: always
```

Autopause seems working at first glance but in fact it always get knocked :
```
minecraft  | [2024-08-10T14:04:13+00:00] [Autopause] Pausing Java process
minecraft  | [14:04:44] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 30946ms or 618 ticks behind
minecraft  | [Autopause loop] Server was knocked - waiting for clients or timeout
minecraft  | [Autopause loop] No client connected since startup / knocked - pausing
minecraft  | [14:06:48] [RCON Listener #1/INFO]: Thread RCON Client /0:0:0:0:0:0:0:1 started
minecraft  | [14:06:48] [Server thread/INFO]: [Rcon: Saved the game]
minecraft  | [14:06:48] [RCON Client /0:0:0:0:0:0:0:1 #12/INFO]: Thread RCON Client /0:0:0:0:0:0:0:1 shutting down
minecraft  | [2024-08-10T14:06:48+00:00] [Autopause] Pausing Java process
minecraft  | [14:07:40] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 52284ms or 1045 ticks behind
minecraft  | [Autopause loop] Server was knocked - waiting for clients or timeout
minecraft  | [Autopause loop] No client connected since startup / knocked - pausing
minecraft  | [14:09:43] [RCON Listener #1/INFO]: Thread RCON Client /0:0:0:0:0:0:0:1 started
minecraft  | [14:09:43] [Server thread/INFO]: [Rcon: Saved the game]
minecraft  | [14:09:43] [RCON Client /0:0:0:0:0:0:0:1 #13/INFO]: Thread RCON Client /0:0:0:0:0:0:0:1 shutting down
minecraft  | [2024-08-10T14:09:43+00:00] [Autopause] Pausing Java process
```

It looks like the java process isnt properly paused and raises warning because of overloading (kinda logic if the server is supposed to be paused).

By bashing into the container, the pausing mechanism put the java process in Tl state which seems ok and then the above warn message wakes the server up again and again.

I tried with longer delays, with `JVM_DD_OPTS: "disable.watchdog=true"` but nothing change. Also tried server 1.19.2 which worked a few month ago.

Do you hava any idea ?
