### DISCUSSION TITLE
Client-only mods not being properly excluded

### DISCUSSION THREAD

**Discussion by danialborta** [itzg/docker-minecraft-server#3073] [Q&A]
Using AUTO_CURSEFORGE with a local modpack.zip didn't work so switched to using a curseforge-generated manifest.json. The modpack is custom, so it includes client mods, but I was under the impression that the [automatic filtering](https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#exclude-client-mods) would filter the client mods out. Tried manually excluding some, but the server still tries to load them (e.g. Oculus, which you can see in the error message below.

What am I doing wrong?

Compose:

```
services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - minecraftdata:/data
      - /home/Minecraft/manifests:/manifests:ro
    ports:
      - 25565:25565
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      SERVER_NAME: <>
      TYPE: AUTO_CURSEFORGE
      OPS: <>
      MEMORY: 12G
      MOTD: "Hello, gamers!"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      WHITELIST: |<>
      VERSION: 1.20.1
      CF_API_KEY: <>
      CF_SLUG: "custom"
      CF_MODPACK_MANIFEST: /manifests/manifest.json
      CF_EXCLUDE_MODS: |
        oculus
        journeymap-integration
    restart: unless-stopped
volumes:
  minecraftdata:
    external: true
```

The server will also fail to start and then auto-restart and loop forever. I'm only pasting one loop in for brevity.
Full error logs: https://pastebin.com/MmkbLUi9

Section that makes me believe it's loading client-side mods and crashing:

> Crash Report UUID: 42b691fe-abc6-44ae-92c8-f52367187dad
> 	FML: 47.3
> 	Forge: net.minecraftforge:47.3.0[15:42:50] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
> net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
> 	Oculus (oculus) has failed to load correctly
> §7java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
> ]
> 	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:246) ~[fmlcore-1.20.1-47.3.0.jar%23272!/:?] {}
> 	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:210) ~[fmlcore-1.20.1-47.3.0.jar%23272!/:?] {}
> 	at java.util.Optional.ifPresent(Unknown Source) ~[?:?] {re:mixin}
> 	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:210) ~[fmlcore-1.20.1-47.3.0.jar%23272!/:?] {}
> 	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:183) ~[fmlcore-1.20.1-47.3.0.jar%23272!/:?] {}
> 	at java.lang.Iterable.forEach(Unknown Source) ~[?:?] {re:mixin}
> 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[fmlcore-1.20.1-47.3.0.jar%23272!/:?] {}
> 	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:30) ~[forge-1.20.1-47.3.0-universal.jar%23276!/:?] {re:classloading}
> 	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23271!/:?] {re:mixin,re:classloading,pl:mixin:A}
> 	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar%2369!/:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.3.0.jar%2369!/:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.3.0.jar%2369!/:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
> 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
> 2024-09-16T15:42:51.220Z	INFO	mc-server-runner	Done

I restorted to using the manifest.json because the zip file method with "TYPE: FORGE" wasn't working, and I'm not publishing this modpack. If I need to manually remove client-side mods from the json let me know but seems tedious.

Cheers for any help!
