### DISCUSSION TITLE
Server fails to start, seemingly from API rate limit while downloading mods?

### DISCUSSION THREAD

**Discussion by DawsonHelms1** [itzg/docker-minecraft-server#3101] [Q&A]
Trying to get started with a modpack for some friends. Server starts and begins to download mods from the pack, but every single time gets rate limited and fails. If I rerun, it loops over the already downloaded mods and hits the limit again. I saw in another post that disabling `restart: unless-stopped` was suggested, and I have done so. Also removed and repulled the container image, with no change in behavior. Any ideas here?

![image](https://github.com/user-attachments/assets/91dccc5b-ad90-41f3-b823-212cb07f8c80)

**Comment by T-Bone1999** [comment]
Also receiving same error :(

**Reply by T-Bone1999** [reply]
I am attempting connecting all the mods 10
https://www.curseforge.com/minecraft/modpacks/all-the-mods-10/files/5807241
Hitting the same API error message

Should I also check in with modrinth also?
Looks like a very recent pack.
I can run the server outside of docker, but I am trying to dabble with docker to expand my knowledge.
Appreciate the support!

**Reply by itzg** [reply]
It downloaded fine for me using:

```yaml
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: true
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-10/files/5807241
      CF_API_KEY: ${CF_API_KEY}
      MEMORY: 4G
    ports:
      - "25565:25565"
    volumes:
      - data:/data

volumes:
  data:
```

however, it fails during startup do some vague issue with sodium being missing, as it should be due to be client-only:

```
Exception in thread "main" java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/caffeinemc/mods/sodium/client/services/PlatformRuntimeInformation
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
Caused by: java.lang.NoClassDefFoundError: net/caffeinemc/mods/sodium/client/services/PlatformRuntimeInformation
	at TRANSFORMER/sodium_extra@0.6.0-beta.3+mc1.21.1/me.flashyreese.mods.sodiumextra.client.SodiumExtraClientMod.mixinConfig(SodiumExtraClientMod.java:79)
	at TRANSFORMER/sodium_extra@0.6.0-beta.3+mc1.21.1/me.flashyreese.mods.sodiumextra.mixin.SodiumExtraMixinConfigPlugin.createConfig(SodiumExtraMixinConfigPlugin.java:13)
	at TRANSFORMER/sodium_extra@0.6.0-beta.3+mc1.21.1/net.caffeinemc.caffeineconfig.AbstractCaffeineConfigMixinPlugin.onLoad(AbstractCaffeineConfigMixinPlugin.java:16)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:790)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:94)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:57)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:190)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.base/java.lang.Class.forName(Unknown Source)
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.ImmediateWindowHandler$DummyProvider.lambda$updateModuleReads$1(ImmediateWindowHandler.java:173)
	at java.base/java.util.Optional.map(Unknown Source)
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.ImmediateWindowHandler$DummyProvider.updateModuleReads(ImmediateWindowHandler.java:173)
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:94)
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.FMLLoader.beforeStart(FMLLoader.java:160)
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:115)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.caffeinemc.mods.sodium.client.services.PlatformRuntimeInformation
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:216)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:216)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 38 more
```

**Reply by itzg** [reply]
With these exclusions it fixed it:

```yaml
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: true
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-10/files/5807241
      CF_API_KEY: ${CF_API_KEY}
      CF_EXCLUDE_MODS: |
        reeses-sodium-options
        sodium-extra
      MEMORY: 4G
    ports:
      - "25565:25565"
    volumes:
      - data:/data

volumes:
  data:
```
