### DISCUSSION TITLE
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'euphoria_patcher'!

### DISCUSSION THREAD

**Discussion by TornaxO7** [itzg/docker-minecraft-server#3134] [Q&A] [answered]
Hi there! I don't know if this is the correct place to ask this but I'm getting an error if I try to setup [BM2](https://modrinth.com/modpack/better-mc-fabric-bmc2/version/v25).

Here are the logs: https://pastebin.com/RuXn8FDH

and here's my `docker-compose.yml`:
```yml
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "49200:25565"
    environment:
      EULA: "TRUE"
      TYPE: "MODRINTH"
      MODRINTH_MODPACK: https://modrinth.com/modpack/better-mc-fabric-bmc2/version/v25
      MAX_PLAYERS: 2
      MAX_MEMORY: "16G"
    volumes:
      - ./data:/data
```

# Reproduction steps
1. Create the `docker-compose.ym` as shown above
2. Start the server with `podman-compose up -d`
3. (optional) Show logs with `podman-compose logs -f`
4. Wait until the error pops up.

Does anyone know what I'm doing wrong?
![pikaThink](https://github.com/user-attachments/assets/d7b3346d-c020-469f-bb40-464589d742d4)

**Comment by itsPenzi** [comment]
Hi,

looking at the [docs](https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/modrinth-modpacks/), it seems you used the `MODRINTH_MODPACK` environment variable wrong.

Here is the `docker-compose.yml` I used for testing:
```yml
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "49200:25565"
    environment:
      EULA: "TRUE"
      TYPE: "MODRINTH"
      MODRINTH_MODPACK: "shFhR8Vx"      #Modrinth project ID
      MODRINTH_VERSION: "SH0rTaJc"      #specific version of project, in this case v25
      MAX_PLAYERS: 2
      MAX_MEMORY: "16G"
    volumes:
      - ./data:/data
```

**Reply by TornaxO7** [reply, marked as answer]
> looking at the [docs](https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/modrinth-modpacks/), it seems you used the MODRINTH_MODPACK environment variable wrong.

I know what you mean, but in [this section](https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/modrinth-modpacks/#modpack-version) it's saying:

> Instead of auto resolving, a specific version of modpack file can be specified **by passing the version's page URL to MODRINTH_MODPACK**, such as https://modrinth.com/modpack/cobblemon-fabric/version/1.3.2

so I think that it should be fine? Because it works for another modrinth modpack:

```yaml
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "49200:25565"
      - "24454:24454/udp"
    environment:
      EULA: "TRUE"
      TYPE: "MODRINTH"
      MODRINTH_MODPACK: "https://modrinth.com/modpack/landscapes-reimagined-genesis/version/3.2"
      MODRINTH_PROJECTS: melody:2o0oW8Yv
      MAX_PLAYERS: 4
      MAX_MEMORY: "16G"
    volumes:
      - ./data:/data
```
and it works.

Nevertheless, thank you for your response :)
