### DISCUSSION TITLE
Integrated MC - Current Auto CurseForge build/setup

### DISCUSSION THREAD

**Discussion by Heat5ource** [itzg/docker-minecraft-server#3154] [Show and tell]
Howdy folks,
Been a lerker for a while now and finally feel confident in what I have been doing lately and wanted to share with the class!

I have a few personally owned HPE Proliant Gen10's at home. All of them are running Proxmox and are linked together. I suspect many will not have this setup, so this will be it's own category.

On the ProxMox, I have a VM running Ubuntu 22.04 with a basic Docker installation, Docker-Compose, Portainer as a GUI interface for Docker, and [Matchbooklab's local-persist](https://github.com/MatchbookLab/local-persist) on the base OS.

Through Portainer, I am creating a stack (which uses a docker-compose to create and mange images), with the following config:

```
####
#Created and posted by Heat5ource@github
#this calls the version of docker and is just a habit of mine at this point
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    restart: unless-stopped
    
    ports:
      - "25565:25565"

    environment:
      CF_FORCE_REINSTALL_MODLOADER: false
      EULA: true
      
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      # allocate from https://console.curseforge.com/ and set in .env file
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: integrated-minecraft
      MEMORY: 32G
      # recommended memory of at least 8GB, edit to what you like
      ALLOW_FLIGHT: true
      MOTD: "§l§cMessage Of The Day"
      MAX_PLAYERS: 15
      VIEW_DISTANCE: 14
      SPAWN_PROTECTION: 0
      # 0 will disable spawn protection, 1 will enable
      SERVER_NAME: "SERVER NAME"
      CF_EXCLUDE_MODS: 1063296
      # We need to disable enhanced_boss_bars-1.20.1-1.0.0 and this needs to be done this late in the config in order to work
      
      #OPS: |
        # [need to lookup your MID?](https://mcuuid.net)
        # you can provide a list of users you want OP'd, I personally put in my minecraft ID instead of username
    volumes:
      - autoforge-data:/data
volumes:
  autoforge-data:
    driver: local-persist
    driver_opts:
      mountpoint: /FILEPATH/
      # you must create the folder first
```

This process has been a long time of learning error codes for java and docker containers over the last year of learning about docker and how it all works! But once it works, this is one of the most simplist ways to automate minecraft servers out there instead of buying a server online.

I am lazy.
I don't like spending money when I don't have to.
I will automate everything if I can.

Use my experience to your advantage!
Cheers
