### DISCUSSION TITLE
Paper MC  & CurseForge: How to download bukkit plugins w/ auto updates?

### DISCUSSION THREAD

**Discussion by Cameronsplaze** [itzg/docker-minecraft-server#3155] [Q&A] [answered]
I've tried different variations of:

```yaml
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: true
      TYPE: PAPER
      CF_API_KEY: <REDACTED>
      CURSEFORGE_FILES: |
        https://www.curseforge.com/minecraft/bukkit-plugins/grief-prevention
        # Also tried just:
        grief-prevention
```
And I can't get the `grief-prevention` (or any other plugin) downloaded to the server. It errors with:

```
mc-1  | [mc-image-helper] 09:11:31.570 ERROR : Invalid parameter provided for 'curseforge-files' command: Unable to find match in latest files for https://www.curseforge.com/minecraft/bukkit-plugins/grief-prevention
```

Maybe it's because the plugin is for `1.21`, and I'm on `1.21.3`? That feels like a stretch though, and I can't find the `mc-image-helper` script anywhere to check. I really don't want to hard-code a file either, if it's possible. I have auto-backups, so I'm okay with risking auto-updates in the name of less maintenance.

---

I've also tried the Modrinth path, but it isn't able to find the [sleep](https://modrinth.com/datapack/sleep) datapack with:

```yaml
    MODRINTH_PROJECTS: |
      sleep
      afk-announcer
      griefprevention
```

I'm guessing because it's a datapack? But I'd like CursedForge more if it's an option anyways, they have a lot more options for plugins.

---

I also tried Spigot with `SPIGET_RESOURCES: 68139,1884` for SinglePlayerSleep and GriefPrevention respectively, but 1884 GriefPrevention takes you to a external site, so the download fails.

Those were the three main options I saw [in the docs here](https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/). Anyone have an idea what I might be missing? Thank you for your time!
