### DISCUSSION TITLE
Why is server.properties getting overwritten?

### DISCUSSION THREAD

**Discussion by spirledaxis** [itzg/docker-minecraft-server#3266] [Q&A] [answered]
im running a server with rlcraft installed:

```
services:
  mc:
    container_name: rlcraft
    image: itzg/minecraft-server:java8-multiarch
    environment:
      EULA: true
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: #key
      CF_SLUG: rlcraft
      CF_FILENAME_MATCHER: 2.9.3
      CF_FORCE_SYNCHRONIZE: true
      MEMORY: 8G
      OPS: "ops"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      USE_AIKAR_FLAGS: true 
      VERSION: "1.12.2"

    volumes:
      - /home/user/minecraft_worlds/rlcraft:/data
    ports:
      - "25565:25565"
    restart: unless-stopped
   ```
   
   But when I try to edit server.properites when the container is stopped, when I restart the container it goes back to its default values. Theres a date at the top, which I think shows when it was last edited. Currently its ``#Mon Jan 20 03:38:29 UTC 2025``, but I also saw ``#Updated 2025-01-20T03:18:33.641Z by mc-image-helper`` before. How do I stop the server from overwriting my server.properties?

**Comment by itzg** [comment]
It shouldn't be going back to defaults, but I am curious which properties you think are. 

To avoid it touching that file then refer to https://docker-minecraft-server.readthedocs.io/en/latest/configuration/server-properties/

![image](https://github.com/user-attachments/assets/e67d0c8c-8062-47f3-b046-d0dcec0c4d4f)

**Comment by itzg** [comment, marked as answer]
Thanks for providing the compose setup...that helped tremendously.

It's because the modpack includes its own server.properties

![image](https://github.com/user-attachments/assets/49fd83d5-1487-4822-98d6-a692b6a0ce58)

Exclude that file using

https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#excluding-overrides-files

**Reply by spirledaxis** [reply]
That works, thank you. For anyone else on this thread, heres my final docker-compose.yml:

```
services:
  mc:
    container_name: rlcraft
    image: itzg/minecraft-server:java8-multiarch
    environment:
      EULA: true
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: #key
      CF_SLUG: rlcraft
      CF_FILENAME_MATCHER: 2.9.3
      CF_FORCE_SYNCHRONIZE: true
      MEMORY: 8G
      OPS: #ops
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      USE_AIKAR_FLAGS: true
      OVERRIDE_SERVER_PROPERTIES: false
      SKIP_SERVER_PROPERTIES: true
      CF_OVERRIDES_EXCLUSIONS: server.properties
      VERSION: "1.12.2"

    volumes:
      - /home/user/minecraft_worlds/rlcraft:/data
    ports:
      - "25565:25565"
    restart: unless-stopped
    ```

**Comment by spirledaxis** [comment]
This was my previous comment, in response to itzg, im making it again since I leaked a bit of personal info:

It does go back to defaults. After running docker compose up -d, and then turning off the container, I edit server.properties to set pvp to false. Then, when starting the container again, once the server is online, pvp goes back to true. I think the container overwrites since it also sets allow-flight=true and enable-command-block=true, even though in a normal server these would be off by default, but rl craft needs these on. I've added OVERRIDE_SERVER_PROPERTIES to my docker compose, same issue:
```
services:
  mc:
    container_name: rlcraft
    image: itzg/minecraft-server:java8-multiarch
    environment:
      EULA: true
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: #key
      CF_SLUG: rlcraft
      CF_FILENAME_MATCHER: 2.9.3
      CF_FORCE_SYNCHRONIZE: true
      MEMORY: 8G
      OPS: "ops"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      USE_AIKAR_FLAGS: true
      OVERRIDE_SERVER_PROPERTIES: false
      SKIP_SERVER_PROPERTIES: true
      VERSION: "1.12.2"

    volumes:
      - /home/user/minecraft_worlds/rlcraft:/data
    ports:
      - "25565:25565"
    restart: unless-stopped
```
When starting the server, I see: docker logs rlcraft | grep "server.properties"
[init] server.properties already created and managed manually

So not sure why its still being overwritten.
Then I added the skip server properties, giving me:
[init] Skipping setup of server.properties

Same issue
