### DISCUSSION TITLE
Install multiple modpacks from txt file?

### DISCUSSION THREAD

**Discussion by redjax** [itzg/docker-minecraft-server#3277] [Q&A] [answered]
I have read [this page of the documentation] multiple times and tried a number of things, and I'm not sure what I'm missing, but I can't seem to get my `AUTO_CURSEFORGE` server to automatically download mods.

This is my `./mods/test.txt`:

```text
jei
journeymap
```

And my `compose.yml`:

```yaml
---
services:

  mc-server:
    image: itzg/minecraft-server
    container_name: ${MC_SERV_CONTAINER_NAME:-mc-server_auto-forge}
    restart: unless-stopped
    ## Comment if using mc-router container
    ports:
      - ${MC_SERV_PORT:-25565}:25565
    tty: ${MC_SERV_TTY:-true}
    stdin_open: true
    environment:
      TYPE: ${MC_SERV_TYPE:-AUTO_CURSEFORGE}
      MODE: ${MC_SERV_GAME_MODE:-survival}
      MOTD: ${MC_SERV_MOTD:-Welcome to the Neoforge server!}
      EULA: "TRUE"
      DIFFICULTY: ${MC_SERV_DIFFICULTY:-normal}
      # https://github.com/itzg/docker-minecraft-server#memory-limit
      MEMORY: ${MC_SERV_MEMORY:-4G}
      ## Uncomment this to import a saved game from the defined WORLDS dir
      # WORLD: /worlds/${MC_SERV_WORLD}
      MAX_PLAYERS: ${MC_SERV_MAX_PLAYERS:-20}
      MAX_WORLD_SIZE: ${MC_SERV_MAX_WORLD_SIZE:-10000}
      ALLOW_NETHER: ${MC_SERV_ALLOW_NETHER:-true}
      ENABLE_COMMAND_BLOCK: ${MC_SERV_COMMAND_BLOCK:-true}
      MAX_BUILD_HEIGHT: ${MC_SERV_MAX_BUILD_HEIGHT:-256}
      ## https://github.com/itzg/docker-minecraft-server/blob/master/README.md#max-tick-time
      MAX_TICK_TIME: ${MC_SERV_MAX_TICK_TIME:-60000}
      SNOOPER: false
      VIEW_DISTANCE: ${MC_SERV_VIEW_DISTANCE:-10}
      # LEVEL_SEED: ${MC_SERV_SEED:-""}
      PVP: ${MC_SERV_PVP:-true}
      ## https://github.com/itzg/docker-minecraft-server/blob/master/README.md#online-mode
      ONLINE_MODE: ${MC_SERV_ONLINE_MODE:-true}
      WHITELIST_FILE: /extras/whitelist.json
      WHITELIST_ENABLED: ${MC_SERV_WHITELIST_ENABLE:-false}
      OVERRIDE_WHITELIST: true
      MODS_FILE: /extras/mods.txt
      ## Curse Forge API key is empty by default.
      #  Get a key at https://console.curseforge.com/#/api-keys
      CF_API_KEY: ${MC_SERVER_CURSE_FORGE_API_KEY}
      CURSEFORGE_FILES: "@/extras/mods.txt"
      # CURSEFORGE_FILES: |
      #   cloth-config
      #   just-enough-resources-jer
      #   just-enough-professions-jep
      #   create-steam-n-rails
      #   justenoughbreeding
      #   farmers-structures
      #   waystones
      #   comforts
      #   towns-and-towers
      #   structory
      #   explorers-compass
      #   moogs-voyager-structures
      #   explorify
      #   goblin-traders
      #   formations-nether
      #   simply-swords
      #   formations-overworld
      #   villages-and-pillages
      #   immersive-aircraft
      #   explorations
      #   jei
      #   modernfix
      #   mobtimizations
      #   fastboot
      #   load-my-chunks
      #   blinkload
      #   safe-harvest
      #   clumps
      #   connectivity
      #   smooth-chunk-save
    volumes:
      - ${MC_SERV_DATA_DIR:-./data/minecraft-server}:/data
      # - ${MC_SERVER_WORLD_IMPORT_DIR:-./worlds}:/worlds:ro
      - ${MC_SERVER_MODS_FILE:-./mods/default.txt}:/extras/mods.txt
      - ${MC_SERVER_WHITELIST_FILE:-./whitelist.json}:/extras/whitelist.json
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 5s
      retries: 20

```

When I try to run this stack, I get the following errors:

```shell
mc-server_auto-forge  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 2 1000 1000 4096 Jan 24 04:54 /data'
mc-server_auto-forge  | A modpack page URL or slug identifier is required
mc-server_auto-forge  | [init] [ERROR] Failed to auto-install CurseForge modpack
```

I used this container a while back and I remember being able to install multiple mod files. Any help pointing out what I'm doing wrong will be appreciated :)

**Comment by redjax** [comment]
I did a search with different keywords and may have found my answer [here](https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/curseforge-files/), if I can get things to work with that answer, I will close this thread

**Reply by redjax** [reply]
This answer got me a little closer, but I'm getting a new error now. I updated the docker compose stack:

```yaml
---
services:

  mc-server:
    image: itzg/minecraft-server
    container_name: ${MC_SERV_CONTAINER_NAME:-mc-server_auto-forge}
    restart: unless-stopped
    ## Comment if using mc-router container
    ports:
      - ${MC_SERV_PORT:-25565}:25565
    tty: ${MC_SERV_TTY:-true}
    stdin_open: true
    environment:
      VERSION: ${MC_SERVER_VERSION:-LATEST}
      NEOFORGE_VERSION: ${MC_SERVER_NEOFORGE_VERSION:-latest}
      TYPE: ${MC_SERV_TYPE:-NEOFORGE}
      MODE: ${MC_SERV_GAME_MODE:-survival}
      MOTD: ${MC_SERV_MOTD:-Welcome to the Neoforge server!}
      EULA: "TRUE"
      DIFFICULTY: ${MC_SERV_DIFFICULTY:-normal}
      # https://github.com/itzg/docker-minecraft-server#memory-limit
      MEMORY: ${MC_SERV_MEMORY:-4G}
      ## Uncomment this to import a saved game from the defined WORLDS dir
      # WORLD: /worlds/${MC_SERV_WORLD}
      MAX_PLAYERS: ${MC_SERV_MAX_PLAYERS:-20}
      MAX_WORLD_SIZE: ${MC_SERV_MAX_WORLD_SIZE:-10000}
      ALLOW_NETHER: ${MC_SERV_ALLOW_NETHER:-true}
      ENABLE_COMMAND_BLOCK: ${MC_SERV_COMMAND_BLOCK:-true}
      MAX_BUILD_HEIGHT: ${MC_SERV_MAX_BUILD_HEIGHT:-256}
      ## https://github.com/itzg/docker-minecraft-server/blob/master/README.md#max-tick-time
      MAX_TICK_TIME: ${MC_SERV_MAX_TICK_TIME:-60000}
      SNOOPER: false
      VIEW_DISTANCE: ${MC_SERV_VIEW_DISTANCE:-10}
      # LEVEL_SEED: ${MC_SERV_SEED:-""}
      PVP: ${MC_SERV_PVP:-true}
      ## https://github.com/itzg/docker-minecraft-server/blob/master/README.md#online-mode
      ONLINE_MODE: ${MC_SERV_ONLINE_MODE:-true}
      WHITELIST_FILE: /extras/whitelist.json
      WHITELIST_ENABLED: ${MC_SERV_WHITELIST_ENABLE:-false}
      OVERRIDE_WHITELIST: true
      MODS_FILE: /extras/mods.txt
      ## Curse Forge API key is empty by default.
      #  Get a key at https://console.curseforge.com/#/api-keys
      CF_API_KEY: ${MC_SERVER_CURSE_FORGE_API_KEY}
      # CURSEFORGE_FILES: |
      #   https://www.curseforge.com/minecraft/mc-mods/jei/download/5626488
      # CURSEFORGE_FILES: |
      #   cloth-config
      #   just-enough-resources-jer
      #   just-enough-professions-jep
      #   create-steam-n-rails
      #   justenoughbreeding
      #   farmers-structures
      #   waystones
      #   comforts
      #   towns-and-towers
      #   structory
      #   explorers-compass
      #   moogs-voyager-structures
      #   explorify
      #   goblin-traders
      #   formations-nether
      #   simply-swords
      #   formations-overworld
      #   villages-and-pillages
      #   immersive-aircraft
      #   explorations
      #   jei
      #   modernfix
      #   mobtimizations
      #   fastboot
      #   load-my-chunks
      #   blinkload
      #   safe-harvest
      #   clumps
      #   connectivity
      #   smooth-chunk-save
    volumes:
      - ${MC_SERV_DATA_DIR:-./data/minecraft-server}:/data
      # - ${MC_SERVER_WORLD_IMPORT_DIR:-./worlds}:/worlds:ro
      - ${MC_SERVER_MODS_FILE:-./mods/default.txt}:/extras/mods.txt
      - ${MC_SERVER_WHITELIST_FILE:-./whitelist.json}:/extras/whitelist.json
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 5s
      retries: 20
```

And my mods.txt file:

```txt
https://www.curseforge.com/minecraft/mc-mods/jei
```

But now I'm getting this error:

```shell
mc-server_auto-forge  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 4 1000 1000 4096 Jan 24 05:05 /data'
mc-server_auto-forge  | [init] Resolving type given NEOFORGE
mc-server_auto-forge  | [mc-image-helper] 05:10:26.881 INFO  : NeoForge version 21.1.107 for minecraft version 1.21.1 is already installed
mc-server_auto-forge  | [mc-image-helper] 05:10:29.118 ERROR : 'mcopy' command failed. Version is 1.40.11
mc-server_auto-forge  | me.itzg.helpers.http.FailedRequestException: HTTP request of https://www.curseforge.com/minecraft/mc-mods/jei failed with 403 Forbidden: Extracting filename
mc-server_auto-forge  |         at me.itzg.helpers.http.FetchBuilderBase.lambda$failedRequestMono$2(FetchBuilderBase.java:220)
mc-server_auto-forge  |         Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
mc-server_auto-forge  | Error has been observed at the following site(s):
mc-server_auto-forge  |         *_______________________________________________________________checkpoint ⇢ Fetch HEAD of requested file
mc-server_auto-forge  |         |_ checkpoint(Retrieving https://www.curseforge.com/minecraft/mc-mods/jei) ⇢ at me.itzg.helpers.sync.MulitCopyCommand.processRemoteSource(MulitCopyCommand.java:248)
mc-server_auto-forge  | Original Stack Trace:
mc-server_auto-forge  |                 at me.itzg.helpers.http.FetchBuilderBase.lambda$failedRequestMono$2(FetchBuilderBase.java:220)
mc-server_auto-forge  |                 at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
mc-server_auto-forge  |                 at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097)
mc-server_auto-forge  |                 at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onComplete(FluxDefaultIfEmpty.java:134)
mc-server_auto-forge  |                 at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:223)
mc-server_auto-forge  |                 at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:275)
mc-server_auto-forge  |                 at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:128)
mc-server_auto-forge  |                 at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:211)
mc-server_auto-forge  |                 at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
mc-server_auto-forge  |                 at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097)
mc-server_auto-forge  |                 at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118)
mc-server_auto-forge  |                 at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
mc-server_auto-forge  |                 at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
mc-server_auto-forge  |                 at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:413)
mc-server_auto-forge  |                 at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:455)
mc-server_auto-forge  |                 at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:509)
mc-server_auto-forge  |                 at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:817)
mc-server_auto-forge  |                 at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:115)
mc-server_auto-forge  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
mc-server_auto-forge  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
mc-server_auto-forge  |                 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
mc-server_auto-forge  |                 at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
mc-server_auto-forge  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
mc-server_auto-forge  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
mc-server_auto-forge  |                 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
mc-server_auto-forge  |                 at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
mc-server_auto-forge  |                 at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
mc-server_auto-forge  |                 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
mc-server_auto-forge  |                 at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
mc-server_auto-forge  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
mc-server_auto-forge  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
mc-server_auto-forge  |                 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
mc-server_auto-forge  |                 at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1503)
mc-server_auto-forge  |                 at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1366)
mc-server_auto-forge  |                 at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1415)
mc-server_auto-forge  |                 at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
mc-server_auto-forge  |                 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
mc-server_auto-forge  |                 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
mc-server_auto-forge  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
mc-server_auto-forge  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
mc-server_auto-forge  |                 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
mc-server_auto-forge  |                 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
mc-server_auto-forge  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
mc-server_auto-forge  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
mc-server_auto-forge  |                 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
mc-server_auto-forge  |                 at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
mc-server_auto-forge  |                 at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501)
mc-server_auto-forge  |                 at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
mc-server_auto-forge  |                 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
mc-server_auto-forge  |                 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
mc-server_auto-forge  |                 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
mc-server_auto-forge  |                 at java.base/java.lang.Thread.run(Unknown Source)
mc-server_auto-forge  |         Suppressed: java.lang.Exception: #block terminated with an error
mc-server_auto-forge  |                 at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:104)
mc-server_auto-forge  |                 at reactor.core.publisher.Mono.block(Mono.java:1779)
mc-server_auto-forge  |                 at me.itzg.helpers.sync.MulitCopyCommand.call(MulitCopyCommand.java:83)
mc-server_auto-forge  |                 at me.itzg.helpers.sync.MulitCopyCommand.call(MulitCopyCommand.java:33)
mc-server_auto-forge  |                 at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
mc-server_auto-forge  |                 at picocli.CommandLine.access$1500(CommandLine.java:148)
mc-server_auto-forge  |                 at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
mc-server_auto-forge  |                 at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
mc-server_auto-forge  |                 at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
mc-server_auto-forge  |                 at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
mc-server_auto-forge  |                 at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
mc-server_auto-forge  |                 at picocli.CommandLine.execute(CommandLine.java:2174)
mc-server_auto-forge  |                 at me.itzg.helpers.McImageHelper.main(McImageHelper.java:169)
```
