### DISCUSSION TITLE
[AUTOPAUSE] Why can't wake up with `knock localhost 25575` in pause?

### DISCUSSION THREAD

**Discussion by MusclePr** [itzg/docker-minecraft-server#3285] [Q&A] [answered]
I have a question about technical interest.

# Why can't wake up with `knock localhost 25575` in pause?

log: (paused)
```log
sandbox  | [2025-01-27T17:38:11+09:00] [Autopause] Pausing Java process
```
Send knock commands...
```shell
$ docker exec -it sandbox knock localhost 25575
$ docker exec -it sandbox knock localhost 25575
$ docker exec -it sandbox knock localhost 25575
$ docker exec -it sandbox knock localhost 25575
$ docker exec -it sandbox knock localhost 25575
```
But, no response in log.
```shell
sandbox  | [2025-01-27T17:38:11+09:00] [Autopause] Pausing Java process
```

# Why can wake up by rcon in pause?
I send any command by rcon to wake up.
```shell
$ docker exec -it sandbox rcon-cli list
There are 0 of a max of 20 players online: 
```
log: (wake up)
```log
sandbox  | [17:45:16 WARN]: Can't keep up! Is the server overloaded? Running 425559ms or 8511 ticks behind
sandbox  | [17:45:16 INFO]: Thread RCON Client /0:0:0:0:0:0:0:1 started
sandbox  | [17:45:16 INFO]: Thread RCON Client /0:0:0:0:0:0:0:1 shutting down
sandbox  | [Autopause loop] Server was knocked - waiting for clients or timeout
```

The Knock command responded while running.
```shell
$ docker exec -it sandbox knock localhost 25575
```
log: (running)
```log
sandbox  | [17:47:03 INFO]: Thread RCON Client /0:0:0:0:0:0:0:1 started
sandbox  | [17:47:03 INFO]: Thread RCON Client /0:0:0:0:0:0:0:1 shutting down
```

# Environment
compose.yml
```yaml
services:
  mc:
    image: "itzg/minecraft-server:latest"
    container_name: "sandbox"
    environment:
      TZ: "Asia/Tokyo"
      EULA: "true"
      SERVER_NAME: "Sandbox"
      TYPE: "paper"
      ENABLE_AUTOPAUSE: "true"
      JVM_DD_OPTS: "disable.watchdog:true"
      AUTOPAUSE_TIMEOUT_EST: 10
      AUTOPAUSE_TIMEOUT_INIT: 30
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"
```
