### DISCUSSION TITLE
Does `CURSEFORGE_FILES` work for a KETTING server?

### DISCUSSION THREAD

**Discussion by MauriceNino** [itzg/docker-minecraft-server#3288] [Q&A] [answered]
I am using the same config, that I used for a `NEOFORGE` server, except that I set the type to `KETTING` instead.

Here is an anonymized version of my `docker-compose`:

```yml
minecraft:
  image: itzg/minecraft-server
  stdin_open: true
  tty: true
  networks:
    - minecraft
  ports:
    - "25565:25565" # main server port
    - "24454:24454/udp" # simple voice chat
  expose:
    - 8100
  volumes:
    - ./minecraft:/data
  environment:
    TYPE: KETTING
    VERSION: "1.20.1"
    EULA: "TRUE"
    SERVER_NAME: "xxxxxxxxxxxxxx"
    MOTD: "xxxxxxxxxxxxx"
    OPS: |
      xxxxxxxxx
      xxxxx
    ENABLE_WHITELIST: "true"
    ONLINE_MODE: "true"
    INIT_MEMORY: 1G
    MAX_MEMORY: 8G
    TZ: "Europe/Vienna"
    CF_API_KEY: xxxxxxxxxxxxxxx
    CURSEFORGE_FILES: |
      curios
      geckolib
      patchouli
      ars-nouveau
      ... and many more
```

Unfortunately, I get the following error in the console:

```
[mc-image-helper] 10:32:01.561 ERROR : Invalid parameter provided for 'curseforge-files' command: Default category is required to resolve curios
```

Is there some variable to provide the default category (which I assume would be neoforge)? I didn't really find it in the docs. But then again, `CURSEFORGE_FILES` also isn't mentioned in the docs on the variables page, which confuses me a bit.

Appreciate any help!
