### DISCUSSION TITLE
The server version provided by Modrinth is a .zip file, and the server cannot be created.

### DISCUSSION THREAD

**Discussion by zzcabc** [itzg/docker-minecraft-server#3296] [Q&A] [answered]
我是一名来自中国的玩家，英语水平不是很好
I am a player from China, and my English proficiency is not very high.

modpack的链接是[zombie-invade-100-days](https://modrinth.com/modpack/zombie-invade-100-days/version/2.1)
The modpack link is [zombie-invade-100-days](https://modrinth.com/modpack/zombie-invade-100-days/version/2.1)

该服务器版本提供的是.zip文件
The server version provided is a .zip file.

经测试，容器启动会下载.mrpack文件，该文件是客户端文件，含有客户端mod，导致服务器启动出错
Through testing, it was found that the container downloads a .mrpack file, which is a client-side file containing client mods, causing the server startup to fail.

如何指定链接 如：[Zombie Invade 100 Days 2.0 [server].zip](https://cdn.modrinth.com/data/l9m9tuPN/versions/IyLHiIBF/Zombie%20Invade%20100%20Days%202.0%20%5Bserver%5D.zip) 指定服务器版本下载
How to specify the link, for example: [Zombie Invade 100 Days 2.0 [server].zip](https://cdn.modrinth.com/data/l9m9tuPN/versions/IyLHiIBF/Zombie%20Invade%20100%20Days%202.0%20%5Bserver%5D.zip), to specify the server version for download.

密码不重要，我使用tailscale和朋友组局域网
The password is not important; I use Tailscale to set up a local network with my friends.

docker-compose.yaml 内容如下
The content of the docker-compose.yaml file is as follows.
```yaml
version: '3'

networks:
  mc_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.4.0/24
          gateway: 172.18.4.1

services:
  mc:
    image: itzg/minecraft-server
    # 容器名称
    container_name: zombie_100day
    restart: unless-stopped
    tty: true
    networks:
      mc_network:
        ipv4_address: 172.18.4.2
    volumes:
      # 服务器数据存放位置
      - /home/zhaocheng/docker/mc-server/data/zombie_100day:/data
      # 服务器mod存放位置
      - /home/zhaocheng/docker/mc-server/mods/zombie_100day:/mods
      # 服务器插件路径
      - /home/zhaocheng/docker/mc-server/plugin/zombie_100day:/plugin
      # 下载路径
      - /home/zhaocheng/docker/mc-server/donwloads/zombie_100day:/downloads
    ports:
      # 服务器端口
      - 25565:25565
      # 服务器RCON端口
      - 25575:25575
    environment:
      UID: "1000"
      GID: "1000"
      TZ: "Asia/Shanghai"
      EULA: "TRUE"

      # 启动时是否移除MOD
      REMOVE_OLD_MODS: "FALSE"
      # 设置初始内存
      INIT_MEMORY: "1G"
      # 设置最大内存
      MAX_MEMORY: "4G"

      JVM_OPTS: "-javaagent:authlib-injector-1.2.5.jar=littleskin.cn"
      
      # 服务器类型
      TYPE: "MODRINTH"
      # 设置服务器登录消息
      MOTD: "欢迎来到Zombie Invade 100 Days的服务器"
      # 设置难度级别
      DIFFICULTY: "hard"
      # 可以加入服务器的玩家的最大数量
      MAX_PLAYERS: "8"
      # 正版验证
      ONLINE_MODE: "TRUE"
      # 服务器名称
      SERVER_NAME: "Zombie Invade 100 Days"
      # 服务器端口
      SERVER_PORT: "25565"

      # 整合包提供平台 Modrinth
      MODRINTH_MODPACK: "zombie-invade-100-days"
      

      # MODPACK: ""
      # 资源包位置
      RESOURCE_PACK: ""
      # 在客户端上强制使用资源包
      RESOURCE_PACK_ENFORCE: "FALSE"
      # 是否启用自动暂停
      ENABLE_AUTOPAUSE: "TRUE"
      # 客户端断连时间
      AUTOPAUSE_TIMEOUT_EST: "3600"
      AUTOPAUSE_KNOCK_INTERFACE: "eth0"
      # 是否启用自动关闭服务器
      ENABLE_AUTOSTOP: "FALSE"
      # 启用/禁用RCON支持
      ENABLE_RCON: "TRUE"
      # RCON密码
      RCON_PASSWORD: "zzc19990105."
      # RCON的端口
      RCON_PORT: 25575
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  rcon-web:
    image: itzg/rcon
    container_name: mc-rcon
    restart: unless-stopped
    tty: true
    networks:
      mc_network:
        ipv4_address: 172.18.4.3
    volumes:
      - ./rcon_web:/opt/rcon-web-admin/db
    environment:
      UID: "1000"
      GID: "1000"
      TZ: "Asia/Shanghai"
      RWA_USERNAME: "admin"
      RWA_PASSWORD: "admin"
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: "172.18.4.2"
      RWA_RCON_PORT: 25575
      RWA_RCON_PASSWORD: "zzc19990105."
    ports:
      - 4326:4326
      - 4327:4327
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"

```
