### DISCUSSION TITLE
Datapacks Help on Docker Minecraft server

### DISCUSSION THREAD

**Discussion by Wh0sWalker** [itzg/docker-minecraft-server#3302] [Q&A]
Hello there, I recently set up a Proxmox server and created a VM with Ubuntu server to host a Minecraft server using Docker. I followed this [LinuxBTW Video](https://youtu.be/CpmsLOX-7DE?si=2oerjnfQJNzLesJu) and used [SetupMC](https://setupmc.com/java-server/) to generate this Docker Compose file:
```
services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "LATEST"
      MEMORY: "7G"
      MAX_PLAYERS: "10"
      MOTD: "GET YOUR MONEY UP, NOT YOUR FUNNY UP!"
      DIFFICULTY: "3"
      SIMULATION_DISTANCE: "12"
      VIEW_DISTANCE: "12"
      SPAWN_PROTECTION: "0"
      OPS: MinecraftNameHere
      ENABLE_WHITELIST: "true"
      WHITELIST: MinecraftNameHere
    volumes:
      - "./data:/data"
```
I want to add [ChunkLock](https://modrinth.com/datapack/chunklock), but don't understand the steps do it, mainly how to get a "ZIP file URL" or zip file on the server like stated in the [Datapack instructions](https://docker-minecraft-server.readthedocs.io/en/latest/misc/world-data/#datapacks). I've also seen [wiligl's discution](https://github.com/itzg/docker-minecraft-server/discussions/1988) about loading datapacks, [StrangeJaguar55's Reddit post](https://www.reddit.com/user/StrangeJaguar55/) on datapack installation, the [Docker Minecraft server - Data directory page](https://docker-minecraft-server.readthedocs.io/en/latest/data-directory/), and obviously the [Docker Minecraft server - World data page](https://docker-minecraft-server.readthedocs.io/en/latest/misc/world-data/). But I still don't understand how to Install and load datapacks into my server, so any help on the matter and the steps to take would be greatly apricated. I am fairly new to servers and networking, so feel free to be brutally honest in you feedback and recommendations, I don't mind. Thanks!

**Comment by itzg** [comment]
Since the Modrinth automation, https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/modrinth/, supports datapacks, I would suggest using:

```yaml
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: true
      TYPE: paper
      VERSION: 1.21.4
      MODRINTH_PROJECTS: datapack:chunklock
```
