### DISCUSSION TITLE
How to stop NeoForge and mods from updating on startup?

### DISCUSSION THREAD

**Discussion by gregops** [itzg/docker-minecraft-server#3340] [Q&A] [answered]
Hi all, after the first successful startup of the MC server container, I'd like to prevent any further NeoForge and mods/packs updates, I'd like it to simply start with the same versions/data as it already has from the first run. I can't find an option to do that though, is that possible?

I.e. stop this from happening when for example the container crashed and is restarted:
```
[mc-image-helper] 19:02:58.864 INFO  : Re-installing Forge due to version change from MC 1.21.1/Forge 21.1.116 to MC 1.21.1/Forge 21.1.119
[mc-image-helper] 19:02:58.981 INFO  : Running NeoForge 21.1.119 installer for Minecraft 1.21.1. This might take a while...
```

And similarly with this starting to update all the mods
```
[mc-image-helper] 19:02:51.411 INFO  : Processing modpack 'All the Mods 10-2.36' (all-the-mods-10) @ 925200:6201429
```

My compose file is the following:
```
services:
  mc:
    container_name: mc
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      VERSION: "1.21.1"
      MEMORY: "8G"
      TZ: "Europe/London"
      DIFFICULTY: "easy"
      ALLOW_FLIGHT: "true"
      MAX_PLAYERS: 10
      GUI: "false"
      PVP: "false"
      ONLINE_MODE: "false"
      SERVER_NAME: "My MC Server"
      CF_API_KEY: "<key>"
      TYPE: "AUTO_CURSEFORGE"
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-10
      RCON_CMDS_STARTUP: |-
        gamerule drowningDamage false
        gamerule enderPearlsVanishOnDeath false
        gamerule fallDamage false
        gamerule freezeDamage false
        gamerule keepInventory true
        gamerule lavaSourceConversion true
    volumes:
      - ./data-1.21.1-all-the-mods-10:/data
```

Thanks!
