### DISCUSSION TITLE
Can't get a TrueNAS CurseForge server running (NeoForge is trivial, though?)

### DISCUSSION THREAD

**Discussion by Skiddywinks** [itzg/docker-minecraft-server#3356] [Q&A] [answered]
Hi all. I am trying to run a minecolonies server on my TrueNAS for my nephew (and his father/my brother, and I), and the community app seemed like the most sensible way to do it. Said app uses this image, so I have been poring over the documentation (which is really rather good I should add). 

The modpack is built on Minecraft 1.21.1 at the moment, and is hosted on CurseForge. The CurseForge client reflects the same, and says it is using the NeoForge modloader (compared to the Forge version).

Getting a generic NeoForge server running is easy, and I can connect with no issues. However, I think I am messing up installing modpacks on it. Are certain variables required? I've tried setting MODPACK_PLATFORM to both CURSEFORGE (noticed it is now deprecated, but figured I would try manual modpack loading) and AUTO_CURSEFORGE, have stuck the API key in to CF_API_KEY (with double $'s), and pointed the app to the relevant CF entry using CF_PAGE_URL. 

At this point I thought I would just try a CurseForge TYPE server (presumably replacing NeoForge as the loader), but using the same basic config as NeoForge to try and just get a generic vanilla server running before progressing to trying to load a modpack and I just cannot get it running. Anything other than a vanilla NeoForge server has the app rapidly fail deploying, go back to stopped, and try a few more times before just giving up. 

I'm using Java 21 Hotspot for the NeoForge variety, but have tried basically all Ubuntu Java versions for CF and have been having zero luck. 

Am I missing something really obvious? I can't seem to find any logs in TrueNAS that might let me know why the app keeps creaming in, but I'm also having no luck there.

**Comment by itzg** [comment]
It's likely that modpack has some lingering client mods that yet haven't been declared in the global exclude list. 

Setting MODPACK_PLATFORM to AUTO_CURSEFORGE is indeed the correct path to follow. With that you don't need to bother declaring the modloader (or Minecraft version) since it'll pick that up from modpack metadata. 

Locating and sharing the logs would be great next. I know you said that you hadn't located that yet, but really that's where the cause will be described.

**Reply by Skiddywinks** [reply]
Ah, good lead. I'll look in to it. 

Also try finding these bloody logs. 

Thank you!

**Reply by itzg** [reply]
FWIW, this compose file seems to work (without yet having connected a client to it):

```yaml
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: true
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      # Allocate API key from https://console.curseforge.com/
      # and set in .env file making sure to double up dollar signs, such as
      # CF_API_KEY=$$2a$$10$$....
      # Refer to https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#api-key
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/minecolonies-official/files/6196075
      MEMORY: 4G
    volumes:
      # use managed volume, but could be changed to host directory binding like ./data
      - mc-data:/data
    ports:
      - "25565:25565"
volumes:
  # remove this if using host directory binding
  mc-data:
```
