### DISCUSSION TITLE
[AutoPause] Server periodically wakes & re-pauses with no players

### DISCUSSION THREAD

**Discussion by nv1602** [itzg/docker-minecraft-server#3444] [Q&A] [answered]
I’m seeing AutoPause repeatedly getting "knocked” and then immediately pausing again—even though no one ever connects. I suspect Docker’s healthcheck may be triggering these wakes, I'm not entirely sure though. I've read some similar ish discussions, but I never came across what exactly it was that is triggering this, so I want to know

What exactly do you think is causing this behavior?
I there a known workaround or proper fix?
## reproducing the issue
- I used this docker compose file(I changed the autopause time to debug, I tried turning on debug mode as well but that flooded the logs and made it less clear to me)
```yml
services:
  restore-backup:
    # INIT-container: restores newest .tgz into ./data if empty
    image: itzg/mc-backup
    restart: "no"
    entrypoint: ["/bin/sh", "/usr/local/bin/restore-entrypoint.sh"]
    volumes:
        - "./data:/data"
        - "./mc-backups:/backups:ro"
        - "./rclone.conf:/config/rclone/rclone.conf:ro"
        - "./restore-entrypoint.sh:/usr/local/bin/restore-entrypoint.sh"

  mc:
    image: itzg/minecraft-server:latest
    depends_on:
     restore-backup:
        condition: service_completed_successfully
    tty: true
    stdin_open: true
    restart: unless-stopped
    stop_grace_period: 2m
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    environment:
      EULA: "TRUE"
      # Using fabric and downloading from modrinth
      TYPE: "MODRINTH"
      VERSION: "LATEST" # You could also just put in `1.21.5`
      MODRINTH_LOADER: "fabric"
      MODRINTH_MODPACK: "adrenaline"
      MODRINTH_DEFAULT_VERSION_TYPE: "alpha"
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      # AUTOPAUSE
      ENABLE_AUTOPAUSE: "TRUE"  # let the JVM pause when idle (saves CPU/network)
      MAX_TICK_TIME: "-1"       # turn off the vanilla watchdog so pause doesn’t kill it
      AUTOPAUSE_TIMEOUT_EST: "1"
      AUTOPAUSE_TIMEOUT_INIT: "1"
      AUTOPAUSE_TIMEOUT_KN: "1"
      # RCON
      RCON_ENABLE: "true"
      RCON_PASSWORD: ""
      # Basic settings for the server
      MOTD: "a"
      SEED: "-1224392421609163985"
      MEMORY: "12288M"
      DIFFICULTY: "3"
      ALLOW_FLIGHT: "true"
      VIEW_DISTANCE: "8"
      SNOOPER_ENABLED: "false"
      SPAWN_PROTECTION: "0"
      SIMULATION_DISTANCE: "5"
      USE_AIKAR_FLAGS: "true"
      SYNC_CHUNK_WRITES: "false"
      INITIAL_ENABLED_PACKS: vanilla,minecart_improvements
      # Set myself as op and whitelist from the start
      OPS: |-
        ***
      # ENABLE_WHITELIST: "true"
      # WHITELIST: |-
      #   ***
      # These are all the mods
      MODRINTH_PROJECTS: |-
        geyser
        floodgate
        spark
        chunky
        terralith
        hearths
        mes-moogs-end-structures
        unwrecked-ships
        dungeons-and-taverns-woodland-mansion-replacement
        dungeons-and-taverns-swamp-hut-overhaul
        dungeons-and-taverns-pillager-outpost-overhaul
        revamped-shipwrecks
        dungeons+
        dungeons-and-taverns-jungle-temple-overhaul
        dungeons-and-taverns-desert-temple-overhaul
        dungeons-and-taverns-stronghold-overhaul
        dungeons-and-taverns
        hopo-better-mineshaft
        hopo-better-ruined-portals
        towns-and-towers
        structory-towers
        structory
        explorify
        dynamic-torches
        void-totem
        death-backup
        scaffolding-drops-nearby
        mastercutter
        netherportalfix
        anvil-restoration
        better-beacon-placement
        better-conduit-placement
        better-spawner-control
        bigger-sponge-absorption-radius
        conduits-prevent-drowned
        crying-portals
        double-doors
        easy-elytra-takeoff
        extended-bone-meal
        fixed-anvil-repair-cost
        move-minecarts
        move-boats
        no-hostiles-around-campfire
        no-animal-tempt-delay
        respawning-shulkers
      MODRINTH_ALLOWED_VERSION_TYPE: "alpha"
      # This includes:
      # - Fast Leaf Decay
      # - More Effective Tools
      # - Multiplayer Sleep
      # - Armored Elytra
      # - XP Bottling
      # - Silk touch Budding Amethyst
      # - Graves
      # - AFK Display
      # - Nether Portal Coords
      # - Homes, Spawn, TPA
      VANILLATWEAKS_SHARECODE: "QSn8f2"
    volumes:
      - "./data:/data"

  backups:
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    pre_stop:
      - command: ["backup","now"]  # run final backup before stopping container
    environment:
      # ── Backup timing ──
      BACKUP_INTERVAL: "12h"        # twice per day
      INITIAL_DELAY: "0"            # no extra wait once mc is healthy
      BACKUP_ON_STARTUP: "true"     # immediate backup on first start

      # ── Retention ──
      PRUNE_BACKUPS_DAYS: 7         # keep last week

      # ── Rclone → Google Drive ──
      BACKUP_METHOD: rclone
      RCLONE_REMOTE: gdrive         # name of your Drive remote
      RCLONE_DEST_DIR: mc-backups   # folder in Drive (created if needed)
      DEST_DIR: /backups
      RCLONE_COMPRESS_METHOD: gzip

      # ── RCON settings ──
      RCON_HOST: mc
      RCON_PORT: 25575
      RCON_PASSWORD: "***"

    volumes:
      - "./data:/data:ro"          # read-only world data
      - "./mc-backups:/backups"    # temp staging for .tgz files
      # Copy your rclone config here (INI format):
      #   cp ~/.config/rclone/rclone.conf ./rclone.conf
      - "./rclone.conf:/config/rclone/rclone.conf:ro"

  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.15
    network_mode: host
    environment:
      - SECRET_KEY=***
```
- the `restore-entrypoint.sh` file is just this piece of code:
```sh
#!/bin/sh
set -e

SRC_DIR="/data"
DEST_DIR="/mc-backups"

# Check if data directory is empty
if [ -z "$(ls -A "$SRC_DIR" 2>/dev/null)" ]; then
  echo "Data directory is empty. Checking for backups..."

  # Try to find the latest backup in Google Drive
  latest=$(rclone lsf gdrive:mc-backups \
    --config /config/rclone/rclone.conf \
    | grep '\.tgz$' \
    | sort \
    | tail -n1)

  if [ -n "$latest" ]; then
    echo "Found backup $latest, downloading..."
    rclone copy "gdrive:mc-backups/$latest" "$DEST_DIR" \
      --config /config/rclone/rclone.conf
  else
    echo "No .tgz backups found in Google Drive."
  fi

  echo "Attempting restore using restore-tar-backup..."
  exec restore-tar-backup
else
  echo "Data directory is not empty. Skipping restore."
fi
```
- do `sudo docker compose up -d`
- do `sudo docker compose logs -f mc`
- leave the server idle(no players)
- wait for the server to pause
- after a while, the server will report that it was knocked
- then it will time out after having no activity, pausing again
- then it will be knocked again
- and so on...
## logging the issue
- I did the usual `sudo docker compose up -d` inside the folder.
- I then saved the logs of the container `sudo docker compose logs -t mc > mc-capture.txt`
- I exexc'd bash inside the mc docker container, installed tcpdump and ran `sudo tcpdump -i any -vvv -X 'tcp port 25565 or udp port 19132' \ -w mc-capture.pcap`
- then saved it to a text file with `tcpdump -nn -tttt -r ~/mc-capture.pcap -vvv -X > ~/mc-capture.txt`

here's a snippet for the output for the docker log
```
mc-1  | 2025-05-11T08:44:07.664823833Z [2025-05-11T08:44:07+00:00] [Autopause] Pausing Java process
mc-1  | 2025-05-11T08:44:29.426538139Z [08:44:29] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 21740ms or 434 ticks behind
mc-1  | 2025-05-11T08:44:32.701007036Z [Autopause loop] Server was knocked - waiting for clients or timeout
mc-1  | 2025-05-11T08:46:32.797703822Z [Autopause loop] No client connected since startup / knocked - pausing
mc-1  | 2025-05-11T08:46:32.804967664Z [08:46:32] [RCON Listener #1/INFO]: Thread RCON Client /0:0:0:0:0:0:0:1 started
mc-1  | 2025-05-11T08:46:32.833054801Z [08:46:32] [Server thread/INFO]: [Rcon: Saved the game]
mc-1  | 2025-05-11T08:46:32.833226122Z [08:46:32] [RCON Client /0:0:0:0:0:0:0:1 #16/INFO]: Thread RCON Client /0:0:0:0:0:0:0:1 shutting down
mc-1  | 2025-05-11T08:46:32.837220999Z [2025-05-11T08:46:32+00:00] [Autopause] Pausing Java process
```
here's a snippet for the output of tcpdump
```
2025-05-11 08:44:07.625446 lo    In  IP6 (flowlabel 0xe669f, hlim 64, next-header TCP (6) payload length: 32) ::1.35878 > ::1.25565: Flags [.], cksum 0x0028 (incorrect -> 0x87e7), seq 24, ack 125, win 512, options [nop,nop,TS val 1897519641 ecr 1897519641], length 0
	0x0000:  600e 669f 0020 0640 0000 0000 0000 0000  `.f....@........
	0x0010:  0000 0000 0000 0001 0000 0000 0000 0000  ................
	0x0020:  0000 0000 0000 0001 8c26 63dd 3460 0bf6  .........&c.4`..
	0x0030:  6a3e bbd5 8010 0200 0028 0000 0101 080a  j>.......(......
	0x0040:  7119 da19 7119 da19                      q...q...
2025-05-11 08:44:29.383010 eth0  In  IP (tos 0x0, ttl 64, id 50192, offset 0, flags [DF], proto TCP (6), length 60)
    172.20.0.1.33120 > 172.20.0.2.25565: Flags [S], cksum 0x585a (incorrect -> 0x2ca1), seq 1744093546, win 64240, options [mss 1460,sackOK,TS val 692883545 ecr 0,nop,wscale 7], length 0
	0x0000:  4500 003c c410 4000 4006 1e80 ac14 0001  E..<..@.@.......
	0x0010:  ac14 0002 8160 63dd 67f4 c16a 0000 0000  .....`c.g..j....
	0x0020:  a002 faf0 585a 0000 0204 05b4 0402 080a  ....XZ..........
	0x0030:  294c 9059 0000 0000 0103 0307            )L.Y........
2025-05-11 08:44:29.383022 eth0  Out IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    172.20.0.2.25565 > 172.20.0.1.33120: Flags [S.], cksum 0x585a (incorrect -> 0x3b0b), seq 2715145129, ack 1744093547, win 65160, options [mss 1460,sackOK,TS val 2720978494 ecr 692883545,nop,wscale 7], length 0
	0x0000:  4500 003c 0000 4000 4006 e290 ac14 0002  E..<..@.@.......
	0x0010:  ac14 0001 63dd 8160 a1d5 d3a9 67f4 c16b  ....c..`....g..k
	0x0020:  a012 fe88 585a 0000 0204 05b4 0402 080a  ....XZ..........
	0x0030:  a22e d63e 294c 9059 0103 0307            ...>)L.Y....
2025-05-11 08:44:29.383039 eth0  In  IP (tos 0x0, ttl 64, id 50193, offset 0, flags [DF], proto TCP (6), length 52)
    172.20.0.1.33120 > 172.20.0.2.25565: Flags [.], cksum 0x5852 (incorrect -> 0x666a), seq 1, ack 1, win 502, options [nop,nop,TS val 692883545 ecr 2720978494], length 0
	0x0000:  4500 0034 c411 4000 4006 1e87 ac14 0001  E..4..@.@.......
	0x0010:  ac14 0002 8160 63dd 67f4 c16b a1d5 d3aa  .....`c.g..k....
	0x0020:  8010 01f6 5852 0000 0101 080a 294c 9059  ....XR......)L.Y
	0x0030:  a22e d63e                                ...>
2025-05-11 08:44:29.432752 eth0  In  IP (tos 0x0, ttl 64, id 41820, offset 0, flags [DF], proto TCP (6), length 60)
    172.20.0.1.33128 > 172.20.0.2.25565: Flags [S], cksum 0x585a (incorrect -> 0x0474), seq 791159339, win 64240, options [mss 1460,sackOK,TS val 692883594 ecr 0,nop,wscale 7], length 0
	0x0000:  4500 003c a35c 4000 4006 3f34 ac14 0001  E..<.\@.@.?4....
	0x0010:  ac14 0002 8168 63dd 2f28 222b 0000 0000  .....hc./("+....
	0x0020:  a002 faf0 585a 0000 0204 05b4 0402 080a  ....XZ..........
	0x0030:  294c 908a 0000 0000 0103 0307            )L..........
2025-05-11 08:44:29.432765 eth0  Out IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    172.20.0.2.25565 > 172.20.0.1.33128: Flags [S.], cksum 0x585a (incorrect -> 0x5c82), seq 229907957, ack 791159340, win 65160, options [mss 1460,sackOK,TS val 2720978544 ecr 692883594,nop,wscale 7], length 0
	0x0000:  4500 003c 0000 4000 4006 e290 ac14 0002  E..<..@.@.......
	0x0010:  ac14 0001 63dd 8168 0db4 1df5 2f28 222c  ....c..h..../(",
	0x0020:  a012 fe88 585a 0000 0204 05b4 0402 080a  ....XZ..........
	0x0030:  a22e d670 294c 908a 0103 0307            ...p)L......
2025-05-11 08:44:29.432776 eth0  In  IP (tos 0x0, ttl 64, id 41821, offset 0, flags [DF], proto TCP (6), length 52)
    172.20.0.1.33128 > 172.20.0.2.25565: Flags [.], cksum 0x5852 (incorrect -> 0x87e0), seq 1, ack 1, win 502, options [nop,nop,TS val 692883595 ecr 2720978544], length 0
	0x0000:  4500 0034 a35d 4000 4006 3f3b ac14 0001  E..4.]@.@.?;....
	0x0010:  ac14 0002 8168 63dd 2f28 222c 0db4 1df6  .....hc./(",....
	0x0020:  8010 01f6 5852 0000 0101 080a 294c 908b  ....XR......)L..
	0x0030:  a22e d670                                ...p
2025-05-11 08:44:29.632732 eth0  In  IP (tos 0x0, ttl 64, id 41822, offset 0, flags [DF], proto TCP (6), length 411)
    172.20.0.1.33128 > 172.20.0.2.25565: Flags [P.], cksum 0x59b9 (incorrect -> 0x879f), seq 1:360, ack 1, win 502, options [nop,nop,TS val 692883794 ecr 2720978544], length 359
	0x0000:  4500 019b a35e 4000 4006 3dd3 ac14 0001  E....^@.@.=.....
	0x0010:  ac14 0002 8168 63dd 2f28 222c 0db4 1df6  .....hc./(",....
	0x0020:  8018 01f6 59b9 0000 0101 080a 294c 9152  ....Y.......)L.R
	0x0030:  a22e d670 3332 008b f48f 18c0 29e6 9427  ...p32......)..'
	0x0040:  7484 8841 8ec9 a33c 7640 e2da d148 c555  t..A...<v@...H.U
	0x0050:  3155 0001 4969 ad33 3230 0068 d076 3627  1U..Ii.320.h.v6'
	0x0060:  af22 07e1 89c8 cb5e 24bf 0c62 f374 1632  .".....^$..b.t.2
	0x0070:  8693 61b4 1e65 ac7e 6540 9a9d f008 7bec  ..a..e.~e@....{.
	0x0080:  5dc4 750c a3d3 6691 6a68 54bc 5de9 5f56  ].u...f.jhT.]._V
	0x0090:  466f 70f0 751c b6a6 2dbb ae39 e05f e615  Fop.u...-..9._..
	0x00a0:  d64f 7209 49b2 9eeb f4b6 301d 672c f882  .Or.I.....0.g,..
	0x00b0:  0eb9 eb6c 9951 f0eb ed4c 295c 6cf1 bc9c  ...l.Q...L)\l...
	0x00c0:  b77c da29 187e 50d7 6e9a d592 1bbe e769  .|.).~P.n......i
	0x00d0:  d6eb ba6f 7eff 485d 2ed7 d98e b00b 6c02  ...o~.H]......l.
	0x00e0:  41bb 1ee0 9a22 2f29 4a5b 6586 0405 c5c8  A...."/)J[e.....
	0x00f0:  043c 57bf f7b1 00b7 4a7b d679 945d 4133  .<W.....J{.y.]A3
	0x0100:  e6ab aab5 8148 94b3 4b69 5a86 c8d6 b100  .....H..KiZ.....
	0x0110:  50b8 e75c 5dd4 85fb 34fb 5eec 4d73 fced  P..\]...4.^.Ms..
	0x0120:  9bd9 66bc 8396 aa49 6b67 bba5 b0f1 3bb0  ..f....Ikg....;.
	0x0130:  1972 c098 7279 2715 4ae4 e8ce d75a be22  .r..ry'.J....Z."
	0x0140:  0a6f 8fb3 b944 6f8c 239f c3f3 bdff 64c2  .o...Do.#.....d.
	0x0150:  4f22 65d0 8812 93e7 511a 6398 595b e1d1  O"e.....Q.c.Y[..
	0x0160:  5135 df80 174d 1f58 b067 a7ea 1873 d356  Q5...M.X.g...s.V
	0x0170:  c015 c57c c316 8060 e1b4 c45b 1053 e00f  ...|...`...[.S..
	0x0180:  095f 4e0f d54b 7a50 a7b1 2168 efa5 f0c4  ._N..KzP..!h....
	0x0190:  376f 8c84 b6cb 7af3 ba82 36              7o....z...6
2025-05-11 08:44:29.632740 eth0  Out IP (tos 0x0, ttl 64, id 25607, offset 0, flags [DF], proto TCP (6), length 52)
    172.20.0.2.25565 > 172.20.0.1.33128: Flags [.], cksum 0x5852 (incorrect -> 0x84e6), seq 1, ack 360, win 507, options [nop,nop,TS val 2720978743 ecr 692883794], length 0
	0x0000:  4500 0034 6407 4000 4006 7e91 ac14 0002  E..4d.@.@.~.....
	0x0010:  ac14 0001 63dd 8168 0db4 1df6 2f28 2393  ....c..h..../(#.
	0x0020:  8010 01fb 5852 0000 0101 080a a22e d737  ....XR.........7
	0x0030:  294c 9152                                )L.R
2025-05-11 08:44:29.632764 eth0  In  IP (tos 0x0, ttl 64, id 41823, offset 0, flags [DF], proto TCP (6), length 52)
    172.20.0.1.33128 > 172.20.0.2.25565: Flags [F.], cksum 0x5852 (incorrect -> 0x84e9), seq 360, ack 1, win 502, options [nop,nop,TS val 692883795 ecr 2720978743], length 0
	0x0000:  4500 0034 a35f 4000 4006 3f39 ac14 0001  E..4._@.@.?9....
	0x0010:  ac14 0002 8168 63dd 2f28 2393 0db4 1df6  .....hc./(#.....
	0x0020:  8011 01f6 5852 0000 0101 080a 294c 9153  ....XR......)L.S
	0x0030:  a22e d737                                ...7
2025-05-11 08:44:29.633084 eth0  Out IP (tos 0x0, ttl 64, id 25608, offset 0, flags [DF], proto TCP (6), length 52)
    172.20.0.2.25565 > 172.20.0.1.33128: Flags [F.], cksum 0x5852 (incorrect -> 0x84e2), seq 1, ack 361, win 507, options [nop,nop,TS val 2720978744 ecr 692883795], length 0
	0x0000:  4500 0034 6408 4000 4006 7e90 ac14 0002  E..4d.@.@.~.....
	0x0010:  ac14 0001 63dd 8168 0db4 1df6 2f28 2394  ....c..h..../(#.
	0x0020:  8011 01fb 5852 0000 0101 080a a22e d738  ....XR.........8
	0x0030:  294c 9153                                )L.S
2025-05-11 08:44:29.633111 eth0  In  IP (tos 0x0, ttl 64, id 41824, offset 0, flags [DF], proto TCP (6), length 52)
    172.20.0.1.33128 > 172.20.0.2.25565: Flags [.], cksum 0x5852 (incorrect -> 0x84e7), seq 361, ack 2, win 502, options [nop,nop,TS val 692883795 ecr 2720978744], length 0
	0x0000:  4500 0034 a360 4000 4006 3f38 ac14 0001  E..4.`@.@.?8....
	0x0010:  ac14 0002 8168 63dd 2f28 2394 0db4 1df7  .....hc./(#.....
	0x0020:  8010 01f6 5852 0000 0101 080a 294c 9153  ....XR......)L.S
	0x0030:  a22e d738                                ...8
2025-05-11 08:44:29.652650 eth0  In  IP (tos 0x0, ttl 64, id 50194, offset 0, flags [DF], proto TCP (6), length 52)
    172.20.0.1.33120 > 172.20.0.2.25565: Flags [F.], cksum 0x5852 (incorrect -> 0x655c), seq 1, ack 1, win 502, options [nop,nop,TS val 692883814 ecr 2720978494], length 0
	0x0000:  4500 0034 c412 4000 4006 1e86 ac14 0001  E..4..@.@.......
	0x0010:  ac14 0002 8160 63dd 67f4 c16b a1d5 d3aa  .....`c.g..k....
	0x0020:  8011 01f6 5852 0000 0101 080a 294c 9166  ....XR......)L.f
	0x0030:  a22e d63e                                ...>
2025-05-11 08:44:29.652762 eth0  Out IP (tos 0x0, ttl 64, id 44099, offset 0, flags [DF], proto TCP (6), length 52)
    172.20.0.2.25565 > 172.20.0.1.33120: Flags [.], cksum 0x5852 (incorrect -> 0x6446), seq 1, ack 2, win 510, options [nop,nop,TS val 2720978764 ecr 692883814], length 0
	0x0000:  4500 0034 ac43 4000 4006 3655 ac14 0002  E..4.C@.@.6U....
	0x0010:  ac14 0001 63dd 8160 a1d5 d3aa 67f4 c16c  ....c..`....g..l
	0x0020:  8010 01fe 5852 0000 0101 080a a22e d74c  ....XR.........L
	0x0030:  294c 9166                                )L.f
2025-05-11 08:44:29.652837 eth0  Out IP (tos 0x0, ttl 64, id 44100, offset 0, flags [DF], proto TCP (6), length 52)
    172.20.0.2.25565 > 172.20.0.1.33120: Flags [F.], cksum 0x5852 (incorrect -> 0x6445), seq 1, ack 2, win 510, options [nop,nop,TS val 2720978764 ecr 692883814], length 0
	0x0000:  4500 0034 ac44 4000 4006 3654 ac14 0002  E..4.D@.@.6T....
	0x0010:  ac14 0001 63dd 8160 a1d5 d3aa 67f4 c16c  ....c..`....g..l
	0x0020:  8011 01fe 5852 0000 0101 080a a22e d74c  ....XR.........L
	0x0030:  294c 9166                                )L.f
2025-05-11 08:44:29.652858 eth0  In  IP (tos 0x0, ttl 64, id 50195, offset 0, flags [DF], proto TCP (6), length 52)
    172.20.0.1.33120 > 172.20.0.2.25565: Flags [.], cksum 0x5852 (incorrect -> 0x644c), seq 2, ack 2, win 502, options [nop,nop,TS val 692883815 ecr 2720978764], length 0
	0x0000:  4500 0034 c413 4000 4006 1e85 ac14 0001  E..4..@.@.......
	0x0010:  ac14 0002 8160 63dd 67f4 c16c a1d5 d3ab  .....`c.g..l....
	0x0020:  8010 01f6 5852 0000 0101 080a 294c 9167  ....XR......)L.g
	0x0030:  a22e d74c                                ...L
2025-05-11 08:44:32.699087 lo    In  IP6 (flowlabel 0xbfbce, hlim 64, next-header TCP (6) payload length: 40) ::1.45110 > ::1.25565: Flags [S], cksum 0x0030 (incorrect -> 0xbf3f), seq 788045495, win 65476, options [mss 65476,sackOK,TS val 1897544715 ecr 0,nop,wscale 7], length 0
	0x0000:  600b fbce 0028 0640 0000 0000 0000 0000  `....(.@........
	0x0010:  0000 0000 0000 0001 0000 0000 0000 0000  ................
	0x0020:  0000 0000 0000 0001 b036 63dd 2ef8 9eb7  .........6c.....
	0x0030:  0000 0000 a002 ffc4 0030 0000 0204 ffc4  .........0......
	0x0040:  0402 080a 711a 3c0b 0000 0000 0103 0307  ....q.<.........
2025-05-11 08:44:32.699094 lo    In  IP6 (flowlabel 0x9ed01, hlim 64, next-header TCP (6) payload length: 40) ::1.25565 > ::1.45110: Flags [S.], cksum 0x0030 (incorrect -> 0x826a), seq 1038700993, ack 788045496, win 65464, options [mss 65476,sackOK,TS val 1897544715 ecr 1897544715,nop,wscale 7], length 0
	0x0000:  6009 ed01 0028 0640 0000 0000 0000 0000  `....(.@........
	0x0010:  0000 0000 0000 0001 0000 0000 0000 0000  ................
	0x0020:  0000 0000 0000 0001 63dd b036 3de9 51c1  ........c..6=.Q.
	0x0030:  2ef8 9eb8 a012 ffb8 0030 0000 0204 ffc4  .........0......
	0x0040:  0402 080a 711a 3c0b 711a 3c0b 0103 0307  ....q.<.q.<.....
2025-05-11 08:44:32.699101 lo    In  IP6 (flowlabel 0xbfbce, hlim 64, next-header TCP (6) payload length: 32) ::1.45110 > ::1.25565: Flags [.], cksum 0x0028 (incorrect -> 0xa900), seq 1, ack 1, win 512, options [nop,nop,TS val 1897544715 ecr 1897544715], length 0
	0x0000:  600b fbce 0020 0640 0000 0000 0000 0000  `......@........
	0x0010:  0000 0000 0000 0001 0000 0000 0000 0000  ................
	0x0020:  0000 0000 0000 0001 b036 63dd 2ef8 9eb8  .........6c.....
	0x0030:  3de9 51c2 8010 0200 0028 0000 0101 080a  =.Q......(......
	0x0040:  711a 3c0b 711a 3c0b                      q.<.q.<.
2025-05-11 08:44:32.699138 lo    In  IP6 (flowlabel 0xbfbce, hlim 64, next-header TCP (6) payload length: 54) ::1.45110 > ::1.25565: Flags [P.], cksum 0x003e (incorrect -> 0x88c7), seq 1:23, ack 1, win 512, options [nop,nop,TS val 1897544715 ecr 1897544715], length 22
	0x0000:  600b fbce 0036 0640 0000 0000 0000 0000  `....6.@........
	0x0010:  0000 0000 0000 0001 0000 0000 0000 0000  ................
	0x0020:  0000 0000 0000 0001 b036 63dd 2ef8 9eb8  .........6c.....
	0x0030:  3de9 51c2 8018 0200 003e 0000 0101 080a  =.Q......>......
	0x0040:  711a 3c0b 711a 3c0b 1300 ffff ffff 0f09  q.<.q.<.........
	0x0050:  6c6f 6361 6c68 6f73 7463 dd01 0100       localhostc....
2025-05-11 08:44:32.699143 lo    In  IP6 (flowlabel 0x9ed01, hlim 64, next-header TCP (6) payload length: 32) ::1.25565 > ::1.45110: Flags [.], cksum 0x0028 (incorrect -> 0xa8ea), seq 1, ack 23, win 512, options [nop,nop,TS val 1897544715 ecr 1897544715], length 0
	0x0000:  6009 ed01 0020 0640 0000 0000 0000 0000  `......@........
	0x0010:  0000 0000 0000 0001 0000 0000 0000 0000  ................
	0x0020:  0000 0000 0000 0001 63dd b036 3de9 51c2  ........c..6=.Q.
	0x0030:  2ef8 9ece 8010 0200 0028 0000 0101 080a  .........(......
	0x0040:  711a 3c0b 711a 3c0b                      q.<.q.<.
2025-05-11 08:44:32.699524 lo    In  IP6 (flowlabel 0x9ed01, hlim 64, next-header TCP (6) payload length: 155) ::1.25565 > ::1.45110: Flags [P.], cksum 0x00a3 (incorrect -> 0x512e), seq 1:124, ack 23, win 512, options [nop,nop,TS val 1897544715 ecr 1897544715], length 123
	0x0000:  6009 ed01 009b 0640 0000 0000 0000 0000  `......@........
	0x0010:  0000 0000 0000 0001 0000 0000 0000 0000  ................
	0x0020:  0000 0000 0000 0001 63dd b036 3de9 51c2  ........c..6=.Q.
	0x0030:  2ef8 9ece 8018 0200 00a3 0000 0101 080a  ................
	0x0040:  711a 3c0b 711a 3c0b 7a00 787b 2276 6572  q.<.q.<.z.x{"ver
	0x0050:  7369 6f6e 223a 7b22 6e61 6d65 223a 2231  sion":{"name":"1
	0x0060:  2e32 312e 3522 2c22 7072 6f74 6f63 6f6c  .21.5","protocol
	0x0070:  223a 3737 307d 2c22 656e 666f 7263 6573  ":770},"enforces
	0x0080:  5365 6375 7265 4368 6174 223a 7472 7565  SecureChat":true
	0x0090:  2c22 6465 7363 7269 7074 696f 6e22 3a22  ,"description":"
	0x00a0:  6122 2c22 706c 6179 6572 7322 3a7b 226d  a","players":{"m
	0x00b0:  6178 223a 3230 2c22 6f6e 6c69 6e65 223a  ax":20,"online":
	0x00c0:  307d 7d                                  0}}
2025-05-11 08:44:32.699529 lo    In  IP6 (flowlabel 0xbfbce, hlim 64, next-header TCP (6) payload length: 32) ::1.45110 > ::1.25565: Flags [.], cksum 0x0028 (incorrect -> 0xa86f), seq 23, ack 124, win 512, options [nop,nop,TS val 1897544715 ecr 1897544715], length 0
	0x0000:  600b fbce 0020 0640 0000 0000 0000 0000  `......@........
	0x0010:  0000 0000 0000 0001 0000 0000 0000 0000  ................
	0x0020:  0000 0000 0000 0001 b036 63dd 2ef8 9ece  .........6c.....
	0x0030:  3de9 523d 8010 0200 0028 0000 0101 080a  =.R=.....(......
	0x0040:  711a 3c0b 711a 3c0b                      q.<.q.<.
2025-05-11 08:44:32.699571 lo    In  IP6 (flowlabel 0xbfbce, hlim 64, next-header TCP (6) payload length: 32) ::1.45110 > ::1.25565: Flags [F.], cksum 0x0028 (incorrect -> 0xa86e), seq 23, ack 124, win 512, options [nop,nop,TS val 1897544715 ecr 1897544715], length 0
	0x0000:  600b fbce 0020 0640 0000 0000 0000 0000  `......@........
	0x0010:  0000 0000 0000 0001 0000 0000 0000 0000  ................
	0x0020:  0000 0000 0000 0001 b036 63dd 2ef8 9ece  .........6c.....
	0x0030:  3de9 523d 8011 0200 0028 0000 0101 080a  =.R=.....(......
	0x0040:  711a 3c0b 711a 3c0b                      q.<.q.<.
2025-05-11 08:44:32.699600 lo    In  IP6 (flowlabel 0x9ed01, hlim 64, next-header TCP (6) payload length: 32) ::1.25565 > ::1.45110: Flags [F.], cksum 0x0028 (incorrect -> 0xa86d), seq 124, ack 24, win 512, options [nop,nop,TS val 1897544715 ecr 1897544715], length 0
	0x0000:  6009 ed01 0020 0640 0000 0000 0000 0000  `......@........
	0x0010:  0000 0000 0000 0001 0000 0000 0000 0000  ................
	0x0020:  0000 0000 0000 0001 63dd b036 3de9 523d  ........c..6=.R=
	0x0030:  2ef8 9ecf 8011 0200 0028 0000 0101 080a  .........(......
	0x0040:  711a 3c0b 711a 3c0b                      q.<.q.<.
2025-05-11 08:44:32.699608 lo    In  IP6 (flowlabel 0xbfbce, hlim 64, next-header TCP (6) payload length: 32) ::1.45110 > ::1.25565: Flags [.], cksum 0x0028 (incorrect -> 0xa86d), seq 24, ack 125, win 512, options [nop,nop,TS val 1897544715 ecr 1897544715], length 0
	0x0000:  600b fbce 0020 0640 0000 0000 0000 0000  `......@........
	0x0010:  0000 0000 0000 0001 0000 0000 0000 0000  ................
	0x0020:  0000 0000 0000 0001 b036 63dd 2ef8 9ecf  .........6c.....
	0x0030:  3de9 523e 8010 0200 0028 0000 0101 080a  =.R>.....(......
	0x0040:  711a 3c0b 711a 3c0b                      q.<.q.<.
```

## More info
Here are all the complete logs, if you want to indulge:
[mc-container-logs.txt](https://github.com/user-attachments/files/20154582/mc-container-logs.txt)
[tcpdump-logs.txt](https://github.com/user-attachments/files/20154583/tcpdump-logs.txt)
oh and the full tcp dump:
https://drive.proton.me/urls/S6G9PDDYJW#I6rxNlSxQJKG
