### DISCUSSION TITLE
Unable to install and remove old mods when using .mrpack with different mods

### DISCUSSION THREAD

**Discussion by islamzaoui** [itzg/docker-minecraft-server#3499] [Q&A]
Hi

I can't update my custom modepack after changing `MODRINTH_MODPACK` and restarting the server

```yaml
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - '25565:25565'
      - "24454:24454/udp"
    environment:
      EULA: true
      TYPE: MODRINTH
      MODRINTH_MODPACK: 'https://raw.githubusercontent.com/IslamZaoui/minecraft-stuff/refs/heads/main/Fabulously%20Optimized%20%2B%2B%201.1.0.mrpack'
      DIFFICULTY: hard
      SEED: 2073625095
      ONLINE_MODE: false
      MAX_MEMORY: 3G
    volumes:
      - './data:/data'

```
