### DISCUSSION TITLE
Server overloaded, but hardware barely used.

### DISCUSSION THREAD

**Discussion by joryirving** [itzg/docker-minecraft-server#944] [General]
Hi there, running a vanilla server in docker.
Windows 10, WSL2 with an ubuntu backend.
HP Z820, Dual-Xeon E5-2680
64GB DDR3 RAM
No other containers runnning.

I'm running into an issue where Windows shows maybe 11% CPU usage, with spikes to 70%, however docker/Vmmem never exceeds ~10% total, but when I go the container stats, I spike from 50-200% CPU usage, and get constant console errors stating:

```
[15:29:47] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 4943ms or 98 ticks behind
[15:30:09] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 7761ms or 155 ticks behind
[15:30:30] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5486ms or 109 ticks behind
[15:31:02] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2029ms or 40 ticks behind
[15:31:26] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 8537ms or 170 ticks behind
[15:31:43] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2649ms or 52 ticks behind
[15:32:04] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5831ms or 116 ticks behind
[15:32:23] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 3914ms or 78 ticks behind
[15:32:45] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 7204ms or 144 ticks behind
```

This only happens when I have 4-5 players connected. I've increased the MEMORY to 4G, and it alleviated the issue when only 3 players were connected, but obviously, I don't want to feed it something like 16GB just so like 6 people can play.

![image](https://user-images.githubusercontent.com/46251616/106671802-44cb9c80-656c-11eb-8ef3-96dd540f97a8.png)
![image](https://user-images.githubusercontent.com/46251616/106671844-5319b880-656c-11eb-9d21-29e68970737f.png)
![image](https://user-images.githubusercontent.com/46251616/106671881-5dd44d80-656c-11eb-89cd-5f54cae24572.png)

Docker run command was:
`docker run -d --init --name=minecraft-vanilla -e EULA=true -v ~/docker/minecraft:/data -p 25565:25565 --restart=always -e TZ=America/Edmonton -e ENABLE_AUTOPAUSE=TRUE -e MEMORY=4G itzg/minecraft-server:latest`

![image](https://user-images.githubusercontent.com/46251616/106672007-96742700-656c-11eb-9af3-7600f9f6f8a1.png)

**Comment by joryirving** [comment]
Should also mention, using the progrium/stress docker container, I can successfully engage all 32threads.

![image](https://user-images.githubusercontent.com/46251616/106674880-477cc080-6571-11eb-86f4-6243e7b29894.png)

**Comment by itzg** [comment]
I'm sorry, I'm not able to help with performance issues. Please report those issues to Mojang since the container ultimately just exec's the java process against the minecraft server jar. 

My guess is that the minecraft server, like most game engines, is primarily single threaded. As such, it's doesn't matter if you throw 32 cores at it, it's going to max out one of those cores. As such, your findings with progrium/stress indeed confirm the WSL2 VM is making proper use of your hardware; however, those findings don't translate to Mojang's implementation of the minecraft server.

You may want to try some of the [other image tags](https://github.com/itzg/docker-minecraft-server#running-minecraft-server-on-different-java-version), such as `itzg/minecraft-server:adopt15` to see if using a newer version of Java happens to perform differently. You may also want to try some different `TYPE`s like `PAPER`.

**Comment by joryirving** [comment]
I found this link: https://github.com/itzg/docker-minecraft-server/issues/466#issuecomment-605677829 and tried the activeprocessor count, which initially I thought may be working, but didn't actually solve the issue.
I rebooted the host, and recreated the container with a docker-compose, and on re-creation, I saw the `CPU Usage` spike to 800%, which means it should be using 8 cores. I'm hopeful it was Java using that, and not just docker itself. I'm hoping to get some friends on there to stress test, as it seems to happen when people are in multiple different chunks.

For reference, I'm also trying the adopt13 tag, and here is my current docker-compose.

```
version: '3'
services:
  vanilla:
    image: itzg/minecraft-server:adopt13
    ports:
      - "25565:25565"
    volumes:
      - ~/docker/minecraft:/data
    environment:
      EULA: "TRUE"
      TZ: "America/Edmonton"
      ENABLE_AUTOPAUSE: "TRUE"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "4G"
      MAX_PLAYERS: 15
    deploy:
      resources:
        limits:
          cpus: 8
          memory: 4G
        reservations:
          cpus: 2
          memory: 1G
    restart: always
```

I'm curious what kind of hardware people are running for larger servers? I wouldn't think that a 5 person vanilla server with no mods could max out a core that easily.

**Comment by flololan** [comment]
any news on this? did setting cpus help?

**Comment by joryirving** [comment]
It didn't appear to use any more than 3 cores. One for the main java process, and 1-2 for cleanup and such. 

I found that my issue was disk I/O. My Ubuntu vhdx was sitting on a platter disc (HDD) to save space on the primary SSD. I ended up tossing in an old 120GB SATA SSD, migrating the WSL installation to that SSD, and then starting up the server (which was running off the /home/user directory within the Ubuntu WSL).

That appears to have resolved everything.

**Comment by flololan** [comment]
Hmm ok. We just had a horrible server launch with Forge-Server. VPS with 10 cores and 60Gb ram. Ram was barely used (around 15gb) and except one core it the rest was more or less idle... the vps uses an ssd... dedicated hardware is not an option sadly

**Comment by joryirving** [comment]
What OS is docker running on?

**Comment by flololan** [comment]
ubuntu 20.04.2

**Comment by flololan** [comment]
If you want to see my docker-compose/stack (cleaned up):

```
version: '3'

services:
  minecraft-server:
    ports:
     - "25565:25565"
    volumes:
      - "mcserver:/data"    

    environment:
      MEMORY: "50G"
      MAX_PLAYERS: "20"
      EULA: "TRUE"
      SERVER_NAME: "xxxxx"
      ICON: "xxxxxx"
      TYPE: "FORGE"
      PVP: "false"
      ALLOW_FLIGHT: "true"
      ALLOW_NETHER: "true"
      GENERATE_STRUCTURES: "true"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      MODE: "survival"
      FORCE_GAMEMODE: "true"
      OVERRIDE_SERVER_PROPERTIES: "true"
      OVERRIDE_OPS: "true"
      OPS: "xxxxxx"
      MOTD: "xxxxxx"

    image: itzg/minecraft-server

    tty: true
    stdin_open: true
    networks:
     - traefik-public
    deploy:
     labels:
  [Trafik Stuff]

 [other service for web redirection]

volumes:
  mcserver:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /root/minecraft

networks:
  traefik-public:
    external: true
```
