### ISSUE TITLE
Some fenv vars are not change configuration

### ISSUE THREAD

**Issue by BarelElbaz** [itzg/docker-minecraft-server#1024]
I am running the image using docker-compose but some environment variables that I provide in the file are not updating the server configuration such as DIFFICULTY=peaceful
or ICON and ICON_OVERRIDE

## NOTE: I added the environment variable after playing in the server for a while so maybe the image takes the variable only in the first boot?

my docker-compose.yaml:
```
version: "3.9"
services: 
    mcpe:
        image: itzg/minecraft-server
        ports:
            - 25565:25565
        environment: 
            - EULA=TRUE
            - VERSION=1.16
            - OPS=YanayDebug,ArielDebug,brepro1
            - ONLINE_MODE=false
            - MEMORY=2G
            - EXEC_DIRECTLY=true
            - DIFFICULTY=peaceful
            - SERVER_NAME='Ariel And Yanay city'
            - ICON='https://e7.pngegg.com/pngimages/166/158/png-clipart-minecraft-music-video-xbox-360-playstation-4-minecraft-server-icon-game-playstation-4-thumbnail.png'
            - OVERRIDE_ICON=TRUE
        tty: true
        stdin_open: true
        restart: unless-stopped
        volumes: 
            - '/home/barel/mc-data:/data'
volumes: 
    mc-volume:
```
