### ISSUE TITLE
Unable to download & run fabric installer

### ISSUE THREAD

**Issue by cadenkriese** [itzg/docker-minecraft-server#1031]
Hey there, I'm having this issue running fabric, when I specify the installer directory it gets to a second error about a sub-process ending.

I'm brand new to all this so I appreciate any tips / help you can provide, thanks!

<details><summary>Logs</summary>
<p>

### Without installer specified

```
[init] Changing ownership of /data to 1000 ...
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 64 Sep  7 00:33 /data'
[init] Resolved version given LATEST into 1.17.1
[init] Resolving type given FABRIC
[init] Checking Fabric version information.
[init] Downloading https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.7.4/fabric-installer-0.7.4.jar ...
/start-deployFabric: line 61:    36 Segmentation fault      curl -o $FABRIC_INSTALLER -fsSL $FABRIC_INSTALLER_URL
[init] Failed to download from given location https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.7.4/fabric-installer-0.7.4.jar
```
### With installer specified

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 4 1000 1000 128 Sep  7 00:52 /data'
[init] Resolved version given LATEST into 1.17.1
[init] Resolving type given FABRIC
[init] Installing Fabric 1.17.1 using fabric-installer-0.7.4.jar
Loading Fabric Installer: 0.7.4
Using latest loader version
Installing Fabric Loader 0.11.6(1.17.1) on the server
Downloading required files
Downloading library net.fabricmc:tiny-mappings-parser:0.2.2.14
Downloading library net.fabricmc:sponge-mixin:0.9.4+mixin.0.8.2
Downloading library net.fabricmc:tiny-remapper:0.4.2
Downloading library net.fabricmc:access-widener:1.0.0
Downloading library net.fabricmc:fabric-loader-sat4j:2.3.5.4
Downloading library com.google.jimfs:jims:1.2-fabric
Downloading library org.ow2.asm:asm:9.1
Downloading library org.ow2.asm:asm-analysis:9.1
Downloading library org.ow2.asm:asm-commons:9.1
Downloading library org.ow2.asm:asm-tree:9.1
Downloading library org.ow2.asm:asm-util:9.1
Downloading library net.fabricmc:intermediary:1.17.1
Downloading library net.fabricmc:fabric-loader:0.11.6
Downloading library com.google.guava:guava:21.0
Generating server launch JAR
Generating server launch JAR: tiny-mappings-parser-0.2.2.14.jar
Generating server launch JAR: sponge-mixin-0.9.4+mixin.0.8.2.jar
Generating server launch JAR: tiny-remapper-0.4.2.jar
Generating server launch JAR: access-widener-1.0.0.jar
Generating server launch JAR: fabric-loader-sat4j-2.3.5.4.jar
Generating server launch JAR: jimfs-1.2-fabric.jar
Generating server launch JAR: asm-9.1.jar
Generating server launch JAR: asm-analysis-9.1.ja
duplicate file: module-info.class
Generating server launch JAR: asm-commons-9.1.jar
duplicate file: module-info.class
Generating server launch JAR: asm-tree-9.1.jar
duplicate file: module-info.class
Generating server launch JAR: asm-util-9.1.jar
duplicate file: module-info.class
Generating server launch JAR: intermediary-1.17.1.jar
Generating server launch JAR: fabric-loader-0.11.6.jar
Generating server launch JAR: guava-21.0.jar
Done, start server by running fabric-server-launch.jar
Downloading Minecraft server
Done
[init] Downloading mod/plugin https://cdn.modrinth.com//data/P7dR8mSH/versions/0.40.0+1.17/fabric-api-0.40.0+1.17.jar ...
[init] Downloading mod/plugin http://github.com/caffeinemc/lithium-fabric/releases/latest/download/lithium-fabric-mc1.17.1-0.7.4.jar ...
[init] Downloading mod/plugin https://cdn.modrinth.com/data/H8CaAYZC/versions/Starlight%201.0.0%201.17.x/starlight-1.0.0+fabric.73f6d37.jar ...
[init] Downloading mod/plugin https://gihub.com/ishlandbukkit/C2ME-fabric/releases/download/0.2.0%2Balpha.4/c2me-fabric-mc1.17.1-0.2.0+alpha.4.0-all.jar ...
[init] Downloading mod/plugin https://cdn.modrinth.com/data/fQEb0iXm/versions/0.1.4/krypton-0.1.4.jar ...
[init] Dwnloading mod/plugin https://cdn.modrinth.com/data/AZomiSrC/versions/mc1.17.1-0.3.1/hydrogen-fabric-mc1.17.1-0.3.jar ...
[init] Downloading mod/plugin https://ci.lucko.me/job/spark/234/artifact/spark-fabric/build/libs/spark-fabric.jar ...
[init] Creating server.properties in /data/server.properties
[init] Disabling whitelist
[init] Setting whitelist to 'false' in /data/server.properties
[init] Setting white-list to 'false' in /data/server.properties
[init] Adding server-name with 'Dedicated Server' in /data/server.properties
[init] Setting server-port to '25565' in /data/server.properties
[init] Setting motd to '§bPeak' in /data/server.properties
[init] Setting max-tick-time to '-1' in /data/server.properties
[init] Setting enable-rcon to 'true' in /data/server.properties
[init] Setting rcon.password to 'minecraft' in /data/server.properties
[init] Setting rcon.port to '25575' in /data/server.properties
[init] Setting max-players to '8' in /data/server.properties
[init] Setting level-name to 'world' in /data/server.properties
[init] Setting online-mode to 'true' in /data/server.properties
[init] Setting difficulty to 'hard' in /data/server.properties
[init] Checking for JSON files.
[init] Setting initial memory to 4G and max to 4G
[init] Using Aikar's flags
[init] Starting the Minecraft server...
2021-09-07T00:58:18.982Z WARN mc-server-runner sub-process failed {"exitCode": -1}
2021-09-07T00:58:19.001Z INFO mc-server-runner Done
```

</p>
</details>
<details><summary>docker-compose.yml</summary>
<p>

```yaml
services:
  mc:
    image: itzg/minecraft-server:java16
    ports:
      - 25565:25565
      - 25575:25575
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      MEMORY: "4G"
      MAX_PLAYERS: 8
      VIEW_DISTANCE: 12
      MOTD: "\u00A7bPeak"
      DIFFICULTY: "hard"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft"
      USE_AIKAR_FLAGS: "TRUE"
      MAX_TICK_TIME: -1
      REMOVE_OLD_MODS: "TRUE"
      MODS: "https://cdn.modrinth.com//data/P7dR8mSH/versions/0.40.0+1.17/fabric-api-0.40.0+1.17.jar,http://github.com/caffeinemc/lithium-fabric/releases/latest/download/lithium-fabric-mc1.17.1-0.7.4.jar,https://cdn.modrinth.com/data/H8CaAYZC/versions/Starlight%201.0.0%201.17.x/starlight-1.0.0+fabric.73f6d37.jar,https://github.com/ishlandbukkit/C2ME-fabric/releases/download/0.2.0%2Balpha.4/c2me-fabric-mc1.17.1-0.2.0+alpha.4.0-all.jar,https://cdn.modrinth.com/data/fQEb0iXm/versions/0.1.4/krypton-0.1.4.jar,https://cdn.modrinth.com/data/AZomiSrC/versions/mc1.17.1-0.3.1/hydrogen-fabric-mc1.17.1-0.3.jar,https://ci.lucko.me/job/spark/234/artifact/spark-fabric/build/libs/spark-fabric.jar"
    volumes:
      - ./minecraft:/data
    tty: true
    stdin_open: true
```
</p>
</details>
