### ISSUE TITLE
 THE METHOD SPECIFIED IN THE REQUEST IS NOT ALLOWED FOR THE RESOURCE IDENTIFIED BY THE REQUEST URI

### ISSUE THREAD

**Issue by mbc99** [itzg/docker-minecraft-server#1050]
Hi,

I have deployed a Minecraft server using Docker compose with the following configuration:
```
version: '3.7'
services:
 minecraft:
   image: itzg/minecraft-server:java8-multiarch
   ports:
     - "25565:25565"
     - "25575:25575"
   volumes:
     - /home/vm102/Minecraft/data:/data
   environment:
     EULA: "TRUE"
     TYPE: "FORGE"
     VERSION: "1.12.2"
     FORGEVERSION: "14.23.5.2855"
     ONLINE_MODE: "FALSE"
```
I'm using the 1.12.2 Forge version.

Everything seems to load fine except when I try to connect to the server. I add the direction and it seems to identify the server:
![image](https://user-images.githubusercontent.com/44815501/133928817-8c49569a-d996-4c6b-9560-9de094f77e58.png)
However when I attempt to conect I get the error 
` THE METHOD SPECIFIED IN THE REQUEST IS NOT ALLOWED FOR THE RESOURCE IDENTIFIED BY THE REQUEST URI`

Looking at the Internet it seems that the problem is that I Online_mode is not set up to false. But it is not the case (checked on the container information page on portainer).

On the server side I get this every time I try to log in:
`[12:34:46] [Server thread/INFO] [minecraft/NetHandlerLoginServer]: com.mojang.authlib.GameProfile@78364bcf[id=<null>,name=my_user,properties={},legacy=false] (/192.168.1.122:49599) lost connection: Disconnected`
