### ISSUE TITLE
Whitelist needs to be reloaded each time the container starts

### ISSUE THREAD

**Issue by djmattyg007** [itzg/docker-minecraft-server#1061]
Every time the container starts, I need to manually run the rcon command `whitelist reload`. If I don't do that, I can't connect, with the server claiming I'm not in the whitelist. I clearly am, because it works without changing anything (other than running `whitelist reload`).

I'm setting a whitelist of player names, and also using `OVERRIDE_WHITELIST=true`. Are there any other relevant settings?

**Comment by itzg** [comment]
Can you provide the full set of variables you're setting? I'm partly wondering if one of the server types is acting differently.

**Comment by itzg** [comment]
I am not able to recreate this issue using a stripped down version of the compose file:

```yaml
version: "3"

services: 
  mc:
    image: itzg/minecraft-server
    environment: 
      EULA: "true"
      TYPE: SPIGOT
      VERSION: 1.16.5
      DEBUG: "true"
      WHITELIST: "user1,user2,user3,user4,user5"
      OVERRIDE_WHITELIST: "true"
    volumes: 
      - ./data:/data
```

I see 
- white-list.txt get recreated
- as spigot is starting up
  - whitelist.json created with resolved uuids
  - original renamed to white-list.txt.converted

https://youtu.be/2OAgRh2S5gY
