### ISSUE TITLE
Ubuntu 18.04.6 unable to start Minecraft server

### ISSUE THREAD

**Issue by justinhough** [itzg/docker-minecraft-server#1062]
Using Docker Compose unable to start a Minecraft server. Server is running `Ubuntu 18.04.6 LTS`. I have run the same docker-compose file locally on Mac OS and it starts up just fine, but when trying to run on the server the Minecraft server just fails to start, but no real error is logged. It just continually reboots and tries again.

Docker Version: `Docker version 20.10.8, build 3967b7d28e`
Docker Compose Version: `docker-compose version 1.29.2, build 5becea4c`

Log output :
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 3 1000 1000 4096 Sep 28 03:22 /data'
[init] Resolved version given LATEST into 1.17.1
[init] Resolving type given VANILLA
[init] server.properties already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 8G and max to 8G
[init] Starting the Minecraft server...
2021/09/28 04:10:17 Stopping with rcon-cli
2021-09-28T04:10:17.795Z	ERROR	mc-server-runner	Failed to stop using rcon-cli	{"error": "exit status 1"}
2021-09-28T04:10:17.817Z	INFO	mc-server-runner	Sending 'stop' to Minecraft server...
2021-09-28T04:10:17.869Z	INFO	mc-server-runner	Waiting for completion...
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 3 1000 1000 4096 Sep 28 03:22 /data'
[init] Resolved version given LATEST into 1.17.1
[init] Resolving type given VANILLA
[init] server.properties already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 8G and max to 8G
[init] Starting the Minecraft server...
```

docker-compose.yml :
```
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      SERVER_NAME: "Hough Minecraft Server"
      MOTD: "First Peaceful World"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "testing"
      UID: "1000"
      GID: "1000"
      DIFFICULTY: "peaceful"
      MEMORY: "8G"
    restart: always
    volumes:
      - "/minecraft/data:/data"

volumes:
  mc:
```

Output of : `docker container inspect [containerName] -f '{{ json .NetworkSettings }}'`

```
{"Bridge":"","SandboxID":"c8375ab0ee549c4d40ec8d7875e385e7c61780af9011721acba265bdc0d13d0b","HairpinMode":false,"LinkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"Ports":{"25565/tcp":[{"HostIp":"0.0.0.0","HostPort":"25565"},{"HostIp":"::","HostPort":"25565"}],"25575/tcp":null},"SandboxKey":"/run/snap.docker/netns/c8375ab0ee54","SecondaryIPAddresses":null,"SecondaryIPv6Addresses":null,"EndpointID":"","Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","MacAddress":"","Networks":{"minecraft_default":{"IPAMConfig":null,"Links":null,"Aliases":["26efb3adac84","mc"],"NetworkID":"ab70f40b2772bd613dd9784323fa2ddd8d08b513a4b36ad8216e3c557e1bd187","EndpointID":"eb8c9de484f600091eb948e11c3f682dbe31d1fda0cceae9fc24ee8a4e466830","Gateway":"172.20.0.1","IPAddress":"172.20.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:14:00:02","DriverOpts":null}}}
```
