### ISSUE TITLE
Can't serialize unregistered packet

### ISSUE THREAD

**Issue by Villwulf** [itzg/docker-minecraft-server#1063]
When some players try to log in to the server they sometimes get this error and cannot access after many attempts...

**That's the error:**

```
[Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: PlayerX lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet
```

**That's my docker-compose.yml:**

```
version: '3'

services:
  mc:
    container_name: bbCraft
    image: itzg/minecraft-server:java8
    ports:
      - "25570:25565/tcp"
      - "25570:25565/udp"
      - "7657:7657/tcp"
      - "7657:7657/udp"
    volumes:
      - "./data:/data"
    environment:
      EULA: "TRUE"
      MAX_MEMORY: "8G"
      TZ: "Europe/Madrid"
      TYPE: "CUSTOM"
      CUSTOM_SERVER: "https://github.com/magmafoundation/Magma/releases/download/vdd991e7-DEV/Magma-dd991e7-DEV-server.jar"
      ONLINE_MODE: "false"
      DIFFICULTY: "hard"
      SERVER_NAME: "BBCRAFT"
      ICON: "https://i.imgur.com/GdhCn3V.png"
      SEED: "4809127797538437541"
    restart: always

volumes:
  mc:
```
