### ISSUE TITLE
AccessDeniedException: ./world/session.lock

### ISSUE THREAD

**Issue by weihao** [itzg/docker-minecraft-server#1080]
docker-compose.yaml
```
  smp:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "2G"
      VERSION: "1.16.5"
      COPY_CONFIG_DEST: "/data"
      USE_AIKAR_FLAGS: "TRUE"
    volumes:
      - ./smp/config:/config # copy
      - ./smp/plugins:/data/plugins # read/write
      - ./smp/worlds/world:/data/world
    command: --noconsole
    restart: unless-stopped
```

If ./smp/worlds/world is empty, it will give this error. Don't get confused by AccessDeniedException as it is **not a permission-related issue** because it can't access due to the empty directory
```
smp_1          | [01:01:43 FATAL]: Failed to start the minecraft server
smp_1          | java.nio.file.AccessDeniedException: ./world/session.lock
smp_1          |        at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
smp_1          |        at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
smp_1          |        at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
smp_1          |        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(Unknown Source) ~[?:?]
smp_1          |        at java.nio.channels.FileChannel.open(Unknown Source) ~[?:?]
smp_1          |        at java.nio.channels.FileChannel.open(Unknown Source) ~[?:?]
smp_1          |        at net.minecraft.server.v1_16_R3.SessionLock.a(SourceFile:37) ~[patched_1.16.5.jar:git-Paper-790]
smp_1          |        at net.minecraft.server.v1_16_R3.Convertable$ConversionSession.<init>(Convertable.java:257) ~[patched_1.16.5.jar:git-Paper-790]
smp_1          |        at net.minecraft.server.v1_16_R3.Convertable.c(Convertable.java:227) ~[patched_1.16.5.jar:git-Paper-790]
smp_1          |        at net.minecraft.server.v1_16_R3.Main.main(Main.java:154) ~[patched_1.16.5.jar:git-Paper-790]
smp_1          |        at org.bukkit.craftbukkit.Main.main(Main.java:289) ~[patched_1.16.5.jar:git-Paper-790]
smp_1          |        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
smp_1          |        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
smp_1          |        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
smp_1          |        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
smp_1          |        at io.papermc.paperclip.Paperclip.main(Paperclip.java:58) ~[paper-1.16.5-790.jar:?]
smp_1          | 2021-10-21T01:01:43.784Z       INFO    mc-server-runner        Done
```

Expected Behavior:
```
Generate a new world
```
