### ISSUE TITLE
Allow arbitrary URLs for CurseForge modpacks

### ISSUE THREAD

**Issue by fjij** [itzg/docker-minecraft-server#1082]
Wasn't able to load CurseForge modpacks from URL since the new download links redirect to a `https://media.forgecdn.net` link instead of using the format here. Perhaps arbitrary URL support is needed? If not, maybe just adding `https://media.forgecdn.net/*` to the list?

https://github.com/itzg/docker-minecraft-server/blob/2eefb12e6b0ab54131c264c5075ec08ccce4b5d6/start-deployCF#L137

**Comment by itzg** [comment]
If you're seeing an error, can you provide the container logs? Any `$srv_modpack` URL that doesn't match those cases just gets used as is. This worked fine for me:

```yaml
version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:java8
    volumes:
    - data:/data
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: https://media.forgecdn.net/files/3012/800/SkyFactory-4_Server_4.2.2.zip
    ports:
      - "25565:25565"

volumes:
  data: {}
```
