### ISSUE TITLE
Forge 14.23.5.2855 "We appear to be missing one or more essential library files."

### ISSUE THREAD

**Issue by brianoflondon** [itzg/docker-minecraft-server#1085]
I'm trying to get a server up with the following `docker-compose.yml` file:

```yml
version: "3"

services:
  mc:
    container_name: mc-pixelmon
    image: itzg/minecraft-server:java8
    ports:
      - 25595:25565
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.12.2"
      FORGEVERSION: "14.23.5.2855"
      MEMORY: 6G
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./mc-data-pixelmon:/data
  ```

This is failing with the following:

```
mc-pixelmon | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    4 1000     1000          4096 Oct 23 10:51 /data'
mc-pixelmon | [init] Resolved version given 1.12.2 into 1.12.2
mc-pixelmon | [init] Resolving type given FORGE
mc-pixelmon | [init] Checking Forge version information.
mc-pixelmon | [init] server.properties already created, skipping
mc-pixelmon | [init] Checking for JSON files.
mc-pixelmon | [init] Setting initial memory to 6G and max to 6G
mc-pixelmon | [init] Starting the Minecraft server...
mc-pixelmon | We appear to be missing one or more essential library files.
mc-pixelmon | You will need to add them to your server before FML and Forge will run successfully.java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
mc-pixelmon |   at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
mc-pixelmon |   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
mc-pixelmon |   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
mc-pixelmon |   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
mc-pixelmon |   at java.lang.Class.forName0(Native Method)
mc-pixelmon |   at java.lang.Class.forName(Class.java:348)
mc-pixelmon |   at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:52)
mc-pixelmon |   at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
mc-pixelmon | 2021-10-23T10:53:00.740Z  WARN    mc-server-runner        sub-process failed      {"exitCode": 1}
mc-pixelmon | 2021-10-23T10:53:00.740Z  INFO    mc-server-runner        Done
```

Any clues? Help greatly appreciated. I have a working Fabric server running already and that was easy to get going with your fantastic docker files.
