### ISSUE TITLE
How do we use forge mods? Mods not reflecting

### ISSUE THREAD

**Issue by ruanbekker** [itzg/docker-minecraft-server#1086]
Hello, first off, great project, its super useful!

Perhaps i'm doing it wrong but how do we use forge mods on the server so that all the players can use the mods? As far as I am aware, the mods are being installed on the server, then the players need to use the forge client in their launcher and they should be able to view the mods? Which is not what im seeing :( 

1. Attempt one:
- TYPE is set to Forge
- Download the mini-map mod under data/mods (https://media.forgecdn.net/files/3491/662/Xaeros_Minimap_21.19.0_Forge_1.17.1.jar)
- Used normal minecraft installation and connect to my server
- Cant see the mod.

2. Attempt two (using forge client):
- TYPE is set to Forge
- Download the mini-map using the MODS_FILE method (https://media.forgecdn.net/files/3491/662/Xaeros_Minimap_21.19.0_Forge_1.17.1.jar)
- Installed the forge client (forge-1.17.1-37.0.103-installer.jar) and set the launcher to forge, connect to the server
- Getting the following error:

![image](https://user-images.githubusercontent.com/567298/138603317-95c39154-709b-4b81-9a1b-6c85568be375.png)

3. Attempt three (using forge client and use the mods locally):
- TYPE is set to Forge
- Download the mini-map mod under data/mods as well as placing them under my local installation .minecraft/mods - using (https://media.forgecdn.net/files/3491/662/Xaeros_Minimap_21.19.0_Forge_1.17.1.jar)
- Installed the forge client (forge-1.17.1-37.0.103-installer.jar) and set the launcher to forge, connect to the server
- Now I can see the mods, but other players can't as the mods is locally, which I feel defeats the purpose of a modded server.

Below is my config:

```
version: "3.8"

services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    #image: itzg/minecraft-server:java16
    container_name: minecraft-server
    ports:
      - 25565:25565
    environment:
      SERVER_NAME: "XX-XX"
      MOTD: "Forge Minecraft Server"
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.17.1"
      MODE: "survival"
      MEMORY: "1G"
      LEVEL_TYPE: "DEFAULT"
      ENABLE_RCON: "true"
      RCON_PASSWORD: password
      RCON_PORT: 28016
      WHITELIST: "${WHITELISTED_PLAYERS}"
      OPS: "${OPS_PLAYERS}"
      MAX_PLAYERS: 20
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      PVP: "true"
      LEVEL: "cold"
      TZ: "Africa/Johannesburg"
      GUI: "FALSE"
      ENABLE_WHITELIST: "true"
      MODS_FILE: /extras/mods.txt
      # REMOVE_OLD_MODS: "true"
    restart: unless-stopped
    user: "1002:1002"
    volumes:
      - ./data:/data
      - ./mods.txt:/extras/mods.txt:ro
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
```

Any help or tips will be much appreciated
