### ISSUE TITLE
Memory environment variable doesn't change the memory

### ISSUE THREAD

**Issue by Botond24** [itzg/docker-minecraft-server#1110]
### Describe the problem

As mentioned in the title the server doent use the memory set to it.

### Container definition

```YAML
minecraft-ComSci-Mods:
    image: itzg/minecraft-server:java8
    ports:
      - "25565:25565"
    volumes:
      - /opt/docker-data/minecraft-ComSci-Mods:/data
    environment:
      TYPE: FORGE
      VERSION: 1.16.5
      FORGEVERSION: 36.2.8
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PORT: 28016
      Memory: 4G
    restart: always
```

### Container logs

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx   16 1000     1000          4096 Nov  5 20:51 /data'
[init] Resolved version given 1.16.5 into 1.16.5
[init] Resolving type given FORGE
[init] Checking Forge version information.
[init] server.properties already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
2021-11-05 21:04:42,491 main WARN Advanced terminal features are not available in this environment

(this should be the important part)
