### ISSUE TITLE
ENABLE_ROLLING_LOGS cause high cpu usage

### ISSUE THREAD

**Issue by GabiBizdoc** [itzg/docker-minecraft-server#1119]
### Describe the problem

I noticed that "ENABLE_ROLLING_LOGS" causes 100% use of a core.
After searching a bit I noticed that  the default config of Dlog4j is a copy of `/tmp/log4j2.xml`.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN" packages="com.mojang.util">
    <Appenders>
        <Console name="SysOut" target="SYSTEM_OUT">
            <PatternLayout pattern="[%d{HH:mm:ss}] [%t/%level]: %msg%n" />
        </Console>
        <Queue name="ServerGuiConsole">
            <PatternLayout pattern="[%d{HH:mm:ss} %level]: %msg%n" />
        </Queue>
    [...]
    </Appenders>

</Configuration>
```
The problem is that this file uses "ServerGuiConsole" as an appender. But, according to [this](https://hub.spigotmc.org/jira/browse/SPIGOT-3388) issues it should use "TerminalConsole" instead.

> md_5 md_5 added a comment - 30/Jun/17 6:05 AM
> You must have an appender named TerminalConsole.
>
>We cannot validate that the custom log4j you supply is compatible with the server. Overriding the log4j configuration should essentially be treated as a modification to the server so if your log4j config is insufficient, then that's probably your issue not ours.
>
> The Vanilla server will also use 100% CPU if you enable the gui

I tested with TerminalConsole and it works
```xml
        <Queue name="TerminalConsole">
            <PatternLayout pattern="[%d{HH:mm:ss} %level]: %msg%n" />
        </Queue>
```

### Container definition

```yml
version: "3.9"
services:
  mc:
    image: itzg/minecraft-server
    container_name: mc
    ports:
      - 25565:25565
    environment:
      TYPE: "SPIGOT"
      EULA: "TRUE"
      VERSION: 1.17.1
      ONLINE_MODE: "TRUE"
      DIFFICULTY: "hard"
      EXEC_DIRECTLY: "TRUE"
      ENABLE_ROLLING_LOGS: "TRUE"
      MEMORY: "3G"
      INIT_MEMORY: "2G"
      MAX_MEMORY: "12G"
    restart: on-failure
    volumes:
      - ./data:/data
```
