### ISSUE TITLE
Better-Minecraft unable to locate installed forge jar

### ISSUE THREAD

**Issue by Fishearl** [itzg/docker-minecraft-server#1121]
### Describe the problem

Hello,

im trying to get a Better-Minecraft server running but it seems impossible :-(

### Container definition

```
version: '3'
# Other docker-compose examples in /examples

services:
  server:
    image: itzg/minecraft-server:java17
    ports:
      - "25555:25565"
    volumes:
      - "better-minecraft-v10:/data"
      - "./modpacks:/modpacks"

    environment:
      MEMORY: "5G"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      OVERRIDE_OPS: "TRUE"
      DIFFICULTY: "normal"
      VIEW_DISTANCE: "15"
      TYPE: "CURSEFORGE"
      CF_SERVER_MOD: "/modpacks/Better+Minecraft+Server+Pack+[FORGE]+v10.zip"
      USE_MODPACK_START_SCRIPT: "FALSE"
      EULA: "TRUE"
    restart: always

volumes:
  better-minecraft-v10: {}

```

### Container logs

```
...
server_1  |   Patching net/minecraft/client/renderer/block/model/ItemTransform$Deserializer 1/1
server_1  |   Patching com/mojang/blaze3d/vertex/BufferBuilder$SortState 1/1
server_1  |   Patching net/minecraft/client/gui/screens/packs/PackSelectionModel$SelectedPackEntry 1/1
server_1  |   Patching net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk$RebuildTask 1/1
server_1  |   Patching net/minecraft/client/renderer/ScreenEffectRenderer 1/1
server_1  |   Patching net/minecraft/client/gui/screens/MenuScreens 1/1
server_1  |   Patching net/minecraft/client/gui/screens/TitleScreen 1/1
server_1  |   Patching net/minecraft/client/main/Main$2 1/1
server_1  |   Patching net/minecraft/client/gui/screens/worldselection/CreateWorldScreen$SelectedGameMode 1/1
server_1  |   Patching net/minecraft/client/main/Main$1 1/1
server_1  |   Patching net/minecraft/client/main/Main$3 1/1
server_1  |   Patching net/minecraft/client/resources/model/SimpleBakedModel 1/1
server_1  |   Patching com/mojang/blaze3d/platform/GlStateManager 1/1
server_1  |   Patching net/minecraft/client/multiplayer/MultiPlayerGameMode 1/1
server_1  |   Patching net/minecraft/client/gui/screens/inventory/CreativeModeInventoryScreen$ItemPickerMenu 1/1
server_1  |   Patching net/minecraft/client/renderer/entity/ItemRenderer 1/1
server_1  |   Patching com/mojang/blaze3d/vertex/VertexFormatElement$Usage$SetupState 1/1
server_1  | The server installed successfully
server_1  | You can delete this installer file now if you wish
server_1  | [init] ERROR unable to locate installed forge server jar
```
