### ISSUE TITLE
BOOLEAN environment variable are always TRUE

### ISSUE THREAD

**Issue by alesmenzel** [itzg/docker-minecraft-server#1137]
### Describe the problem

Any boolean environment variable defined inside docker-compose.yml is treated as TRUE even if set to false, here is a simple demonstration:

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "FALSE"
    tty: true
    stdin_open: true
    restart: unless-stopped
...
```

### Container definition

```
Paste run command or compose file here
```

### Container logs

```
Paste logs here
```
