### ISSUE TITLE
net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime

### ISSUE THREAD

**Issue by lraszewski** [itzg/docker-minecraft-server#1141]
### Describe the problem

net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0

I experienced this issue with the new 1.18 update. Prior to this update, the server was working perfectly. After the update initially didn't work by running `docker-compose down` and `docker-compose up`, I deleted my `minecraft-data` directory and reran `docker-compose up` without any success.

Looks like the java version is too old? I am not sure if this is a local issue or container issue.

### Container definition

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MOTD: "Luc's Minecraft Server. Hell Yeah"
      DIFFICULTY: hard
      MEMORY: 4G
      OVERRIDE_SERVER_PROPERTIES: "true"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data
```

### Container logs

```
luc@luc-server:~/minecraft-server$ sudo docker-compose up
Creating network "minecraft-server_default" with the default driver
Creating minecraft-server_mc_1 ... done
Attaching to minecraft-server_mc_1
mc_1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Nov 30 22:30 /data'
mc_1  | [init] Resolved version given LATEST into 1.18
mc_1  | [init] Resolving type given VANILLA
mc_1  | [init] Disabling whitelist
mc_1  | [init] Setting whitelist to 'false' in /data/server.properties
mc_1  | [init] Setting white-list to 'false' in /data/server.properties
mc_1  | [init] Setting enable-rcon to 'true' in /data/server.properties
mc_1  | [init] Setting rcon.password to 'minecraft' in /data/server.properties
mc_1  | [init] Setting rcon.port to '25575' in /data/server.properties
mc_1  | [init] Setting motd to 'Luc's Minecraft Server. Hell Yeah' in /data/server.properties
mc_1  | [init] Setting difficulty to 'hard' in /data/server.properties
mc_1  | [init] Checking for JSON files.
mc_1  | [init] Setting initial memory to 4G and max to 4G
mc_1  | [init] Starting the Minecraft server...
mc_1  | Error: LinkageError occurred while loading main class net.minecraft.bundler.Main
mc_1  | 	java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
mc_1  | 2021-11-30T22:30:32.274Z	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}
mc_1  | 2021-11-30T22:30:32.275Z	INFO	mc-server-runner	Done
```

**Comment by ClayMav** [comment]
Try using `itzg/minecraft-server:java17` or latest

**Comment by lraszewski** [comment]
> Try using `itzg/minecraft-server:java17` or latest

Tried using:

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MOTD: "Luc's Minecraft Server. Hell Yeah"
      DIFFICULTY: hard
      MEMORY: 4G
      OVERRIDE_SERVER_PROPERTIES: "true"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data
```

And got the same result.

Tried using:

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server:java17
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MOTD: "Luc's Minecraft Server. Hell Yeah"
      DIFFICULTY: hard
      MEMORY: 4G
      OVERRIDE_SERVER_PROPERTIES: "true"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data
```

And it worked!

I'm running a completely vanilla server, so I was hoping to just run latest to keep the server up to date. So I might leave this issue open with the hope a solution is pushed to latest.
