### ISSUE TITLE
Healthcheck is restarting Minecraft during preparing spawn area under 1.18

### ISSUE THREAD

**Issue by Lownin** [itzg/docker-minecraft-server#1144]
### Describe the problem

Since updating to 1.18, the "Preparing spawn area" of server startup is taking much longer.  Before it completes, I see a message:
```
2021-12-01T18:48:12.361Z	ERROR	mc-server-runner	Failed to stop using rcon-cli	{"error": "exit status 1"}
2021-12-01T18:48:12.364Z	INFO	mc-server-runner	Sending 'stop' to Minecraft server...
2021-12-01T18:48:12.365Z	INFO	mc-server-runner	Waiting for completion...
```
... and from there, I enter a boot loop.

I've temporarily worked around the issue by setting `DISABLE_HEALTHCHECK: "true"`

Is there a workaround that would allow me to keep the health check?  Is there a way for me to increase the amount of time before the check imitates a restart?

Thank you.

### Container definition

```
version: "3"

services:
  minecraft-crafting:
    container_name: "minecraft-craft"
    env_file:
      - "minecraft.env"
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
    volumes:
      - /mnt/swarm/data/craft:/data
    environment:
      EULA: "TRUE"
      DISABLE_HEALTHCHECK: "true"
    tty: true
    stdin_open: true
    restart: unless-stopped
```

### Container logs

```
[init] Updating whitelist
[init] Checking for JSON files.
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
Starting net.minecraft.server.Main
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 7 1000 1000 16 Dec  1 18:48 /data'
[init] Resolved version given LATEST into 1.18
[init] Resolving type given VANILLA
[init] server.properties already created, skipping
[init] Updating ops
[init] Updating whitelist
[init] Checking for JSON files.
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
Starting net.minecraft.server.Main
```
