### ISSUE TITLE
Version being reslved as LATEST although it is set as 1.17.1 in docker-compose.yml

### ISSUE THREAD

**Issue by SamYouatt** [itzg/docker-minecraft-server#1158]
### Describe the problem

I have explicitly set the version as an environment varialbe in the compose file and yet the container still resolves to LATEST and tries to download the 1.18 server.

### Container definition

```
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: 1.17.1
      MEMORY: 4G
      EXEC_DIRECTLY: true"
      OVERRIDE_SERVER_PROPERTIES: "true"
      ICON: "/home/pi/minecraft/server-icon.png"
      SPAWN_PROTECTION: 0
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /home/pi/minecraft:/data
```

### Container logs

```
[init] Starting the Minecraft server...
Minecraft 1.18 requires running the server with Java 17 or above. Download Java 17 (or above) from https://adoptium.net/
2021-12-03T20:31:18.284Z	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}
2021-12-03T20:31:18.284Z	INFO	mc-server-runner	Done
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x. 8 1000 1000 4096 Dec  3 20:31 /data'
[init] Resolved version given LATEST into 1.18
[init] Resolving type given PAPER
[init] Removing old PaperMC versions ...
[init] Downloading PaperMC 1.18 (build 25) ...
[init] Disabling whitelist
[init] Setting whitelist to 'false' in /data/server.properties
[init] Setting white-list to 'false' in /data/server.properties
[init] Setting spawn-protection to '0' in /data/server.properties
[init] Setting enable-rcon to 'true' in /data/server.properties
[init] Setting rcon.password to 'minecraft' in /data/server.properties
[init] Setting rcon.port to '25575' in /data/server.properties
[init] Setting motd to 'A Paper Minecraft Server powered by Docker' in /data/server.properties
[init] Checking for JSON files.
[init] Setting initial memory to 4G and max to 4G
```
