### ISSUE TITLE
is -java8-multiarch broken after today's log4j fix?

### ISSUE THREAD

**Issue by therealeldaria** [itzg/docker-minecraft-server#1180]
Hello, 

I have had a FTB-Oceanblock running for a while.

Today I ran a docker-compose pull to update after I saw you updated for the Log4j issue.
But after restarting the server, it now crashes with no indication of why in the logs.

I also tried to change to the tag 2021.23.0-java8-multiarch but it still crash at startup.

This is the configuration I have in my compose file.
And it has worked great until today.

```
version: '3' 

services:
  mcb-ftboceanblock:
    container_name: mcb-ftboceanblock
    image: itzg/minecraft-server:${IMAGE_TAG:-java8-multiarch}
    ports:
      - "25569:25565"
    networks:
      - mc
    volumes:
      - "./mcb-ftboceanblock:/data"
    environment:
      EULA: "TRUE"
      TYPE: FTBA
      FTB_MODPACK_ID: "91"
      FTB_MODPACK_VERSION_ID: "2090"
      LEVEL_TYPE: "default"
      VERSION: "1.16.5"
      SERVER_NAME: "mcb-ftboceanblock"
      OPS: "<redacted>"
      FORCE_GAMEMODE: "true"
      MODE: "survival"
      MAX_MEMORY: "8G"
      MOTD: "<redacted>"
```
