### ISSUE TITLE
MAX_TICK_TIME not taken into account as -1 or "-1" in 2021.26.0

### ISSUE THREAD

**Issue by nodje** [itzg/docker-minecraft-server#1222]
### Describe the problem

MAX_TICK_TIME not taken into account as -1 or "-1" in 2021.26.0

The message in the docker logs is:
```
[init] server.properties already created, skipping
[init] Warning: The server.properties for the server doesn't have the Server Watchdog (effectively) disabled.
[init] Warning (cont): Autopause functionality resuming the process might trigger the Watchdog and restart the server completely.
[init] Warning (cont): Set the max-tick-time property to a high value (or disable the Watchdog with value -1 for versions 1.8.1+).
```
and then checking the server.properties content, the MAX_TICK_TIME is still default 60000.

Not too sure why, but as per the doc it's supposed to work 

### Container definition

```
minecraft:
    image: itzg/minecraft-server:2021.26.0
    restart: always
    container_name: minecraft
    environment:
      - EULA=TRUE
      - SERVER_NAME= Home Server
      - DIFFICULTY=normal
      - WHITELIST=user,user2
      - ENFORCE_WHITELIST=TRUE
      - OPS=ops
      - SERVER_PORT=25565
      - ONLINE_MODE=FALSE
      - MAX_TICK_TIME="-1"
      - RCON_PASSWORD=password
      - ENABLE_AUTOPAUSE=TRUE
      - AUTOPAUSE_TIMEOUT_EST=1800 #describes the time between the last client disconnect and the pausing of the process (read as timeout established)
      - AUTOPAUSE_TIMEOUT_INIT=600 #describes the time between server start and the pausing of the process, when no client connects inbetween (read as timeout initialized)
      - AUTOPAUSE_TIMEOUT_KN=120 #describes the time between knocking of the port (e.g. by the main menu ping) and the pausing of the process, when no client connects inbetween (read as timeout knocked)
      - AUTOPAUSE_PERIOD=10 #describes period of the daemonized state machine, that handles the pausing of the process (resuming is done independently)
      - AUTOPAUSE_KNOCK_INTERFACE=eth0
      - MEMORY=2G
      - UID=2004
      - GID=2004
    volumes:
      - /mnt/data/minecraft/config:/config
      - **/mnt/data/minecraft/data:/data**
```

### Container logs

```
Paste logs here
```
