### ISSUE TITLE
USE_LARGE_PAGES not working on Java 17

### ISSUE THREAD

**Issue by huntears** [itzg/docker-minecraft-server#1239]
### Describe the problem

The USE_LARGE_PAGES environment option is not working when using the 1.18.1 version of PaperMC.
It looks like `UseLargePagesInMetaspace` is past deprecation on Java 17

### Container definition

```
version: '3.9'
services:
  minecraft:
      image: itzg/minecraft-server
      ports:
        - 9000:25565/tcp
      environment:
        - TYPE=PAPER
        - VERSION=1.18.1
        - EULA=TRUE
        - MEMORY=16G
        - USE_AIKAR_FLAGS=true
        - USE_LARGE_PAGES=true
        - ENABLE_RCON=true
        - RCON_PASSWORD=VerySecurePassword
      volumes:
        - mc-data:/data
        - mc-logs:/data/logs
      tty: true
      stdin_open: true
      restart: unless-stopped
volumes:
  mc-data: {}
  mc-logs: {}
```

### Container logs

```
minecraft-minecraft-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 6 1000 1000 4096 Jan  1 18:15 /data'
minecraft-minecraft-1  | [init] Resolved version given 1.18.1 into 1.18.1
minecraft-minecraft-1  | [init] Resolving type given PAPER
minecraft-minecraft-1  | [init] Removing old PaperMC versions ...
minecraft-minecraft-1  | [init] Downloading PaperMC 1.18.1 (build 121) ...
minecraft-minecraft-1  | [init] server.properties already created, skipping
minecraft-minecraft-1  | [init] Checking for JSON files.
minecraft-minecraft-1  | [init] Using Aikar's >12GB flags
minecraft-minecraft-1  | [init] Setting initial memory to 16G and max to 16G
minecraft-minecraft-1  | [init] Starting the Minecraft server...
minecraft-minecraft-1  | Unrecognized VM option 'UseLargePagesInMetaspace'
minecraft-minecraft-1  | Error: Could not create the Java Virtual Machine.
minecraft-minecraft-1  | Error: A fatal exception has occurred. Program will exit.
minecraft-minecraft-1  | 2022-01-01T18:30:30.286Z       WARN    mc-server-runner        sub-process failed      {"exitCode": 1}
minecraft-minecraft-1  | 2022-01-01T18:30:30.286Z       INFO    mc-server-runner        Done
minecraft-minecraft-1 exited with code 1
```
