### ISSUE TITLE
Ability to run two minecraft server instances on the same machine

### ISSUE THREAD

**Issue by davidmoshal** [itzg/docker-minecraft-server#1243]
### Enhancement Type

Not sure

### Describe the enhancement

Not sure if this is already supported.
If so, the request is for documentation on how to do it.

So far I've discovered that just running separate containers doesn't work because the second server kills the first server.
Even with different:
- ports
- data directories
- MOTD

Server 1 docker-compose.yml:
```yml
services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      MOTD: "lunar-one"
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: 28016
      restart: always
    volumes:
    - /minecraft/docker-compose/data:/data
```

Server 2 docker-compose.yml
```yml
services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 27777:25565
    environment:
      MOTD: "ben-one"
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: 28616
      restart: always
    volumes:
    - /ben/minecraft/docker-compose/data:/data
```

Here is the log from the **first** server when the **second** server is started:
```sh
2022-01-02T22:37:15.769Z	ERROR	mc-server-runner	Failed to stop using rcon-cli	{"error": "exit status 1"}
2022-01-02T22:37:15.769Z	INFO	mc-server-runner	Sending 'stop' to Minecraft server...
2022-01-02T22:37:15.769Z	INFO	mc-server-runner	Waiting for completion...
```

So, something in the second server kills the first server.

**Comment by davidmoshal** [comment]
Btw, I'm surprised that one docker container can kill another one with different ports and volumes, never seen that happen in the 6+ years I've been using docker. 

I thought that isolation would prevent the that. 
What an I missing?

**Comment by davidmoshal** [comment]
Note: changing ENABLE_RCON to false doesn't prevent the second server from stopping the first server  
(so presumably RCON isn't the culprit).

**Comment by Megasware128** [comment]
I believe a different folder name where the docker-compose file is stored should also help

**Comment by Marshin386** [comment]
davidmoshal, could you share how you got 2 Minecraft servers running on the same docker (in separate containers). what settings did you end up using to make it work? I'm still getting a port conflict (port wont bind) when I try to start the second minecraft server

**Comment by itzg** [comment]
@Marshin386 just change the host (left-side) part of the port mapping to choose unique host ports such as `25566` on `mc2`:

```yaml
version: "3"

services:
  mc1:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    volumes:
      - ./mc1-data:/data
  mc2:
    image: itzg/minecraft-server
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
    volumes:
      - ./mc2-data:/data
```
