### ISSUE TITLE
can't get Forge server to start

### ISSUE THREAD

**Issue by Marshin386** [itzg/docker-minecraft-server#1260]
### Describe the problem

I'm using a Stack for a vanilla server and that works perfectly (thank you for all your hard work, its much appreciated), but when I add the environment variable TYPE=FORGE it won't start. I have posted the issue to the Forge forum, but they said I needed to bring the issue to you instead.

I've included the stack that I'm using.

I turned on debug but I didn't get a debug log. however here is what the output in docker is giving me when I try to start the server with the Forge variable included

"
+ return 1
+ exec mc-server-runner --stop-duration 60s --named-pipe /tmp/minecraft-console-in java -Xmx8G -Xms8G -jar /data/run.sh
Error: Invalid or corrupt jarfile /data/run.sh
2022-01-08T01:16:57.983Z	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}
2022-01-08T01:16:57.983Z	INFO	mc-server-runner	Done
+ export HOME=/data
+ HOME=/data
++ id -u
++ id -g
++ ls -lnd /data
+ log 'Running as uid=1000 gid=1000 with /data as '\''drwxrwsrwx 7 1000 1000 4096 Jan  8 01:16 /data'\'''
+ echo '[init] Running as uid=1000 gid=1000 with /data as '\''drwxrwsrwx 7 1000 1000 4096 Jan  8 01:16 /data'\'''
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwsrwx 7 1000 1000 4096 Jan  8 01:16 /data'
+ '[' '!' -e /data/eula.txt ']'
+ [[ -n '' ]]
+ [[ -n '' ]]
+ which java
+ export VERSIONS_JSON=https://launchermeta.mojang.com/mc/game/version_manifest.json
+ VERSIONS_JSON=https://launchermeta.mojang.com/mc/game/version_manifest.json
+ case "X$VERSION" in
++ get --json-path '$.latest.release' https://launchermeta.mojang.com/mc/game/version_manifest.json
++ flags=()
++ local flags
++ isTrue false
++ local value=false
++ result=
++ case ${value} in
++ result=1
++ return 1
++ mc-image-helper get --json-path '$.latest.release' https://launchermeta.mojang.com/mc/game/version_manifest.json
+ VANILLA_VERSION=1.18.1
+ export VANILLA_VERSION
[init] Resolved version given LATEST into 1.18.1
+ log 'Resolved version given LATEST into 1.18.1'
+ echo '[init] Resolved version given LATEST into 1.18.1'
+ cd /data
+ export ORIGINAL_TYPE=FORGE
+ ORIGINAL_TYPE=FORGE
+ isTrue false
+ local value=false
=
+ case ${value} in
+ result=1
+ return 1
+ versionLessThan 1.7
+ local activeParts
+ version=1.18.1
+ version=1.18.1
+ IFS=.
+ read -ra activeParts
+ local givenParts
+ IFS=.
+ read -ra givenParts
+ (( 3 < 2 ))
+ (( 3 == 2 ))
+ (( activeParts[0] < givenParts[0] ))
+ (( activeParts[0] == givenParts[0] && activeParts[1] < givenParts[1] ))
+ (( activeParts[0] == givenParts[0] && activeParts[1] == givenParts[1] && activeParts[2] < givenParts[2] ))
+ return 1
+ log 'Resolving type given FORGE'
+ echo '[init] Resolving type given FORGE'
[init] Resolving type given FORGE
+ case "${TYPE^^}" in
+ versionLessThan 1.17
+ local activeParts
+ version=1.18.1
+ version=1.18.1
+ IFS=.
+ read -ra activeParts
+ local givenParts
+ IFS=.
+ read -ra givenParts
+ (( 3 < 2 ))
+ (( 3 == 2 ))
+ (( activeParts[0] < givenParts[0] ))
+ (( activeParts[0] == givenParts[0] && activeParts[1] < givenParts[1] ))
+ (( activeParts[0] == givenParts[0] && activeParts[1] == givenParts[1] && activeParts[2] < givenParts[2] ))
+ return 1
+ exec /start-deployForge
+ resolve_versions
+ [[ -z '' ]]
+ [[ -z '' ]]
+ norm=1.18.1
+ case $VANILLA_VERSION in
+ norm=1.18.1
+ promosUrl=http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
+ log 'Checking Forge version information.'
+ echo '[init] Checking Forge version information.'
+ case $FORGEVERSION in
[init] Checking Forge version information.
++ get -s --json-path '.promos['\''1.18.1-recommended'\'']' http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
++ flags=()
++ local flags
++ isTrue false
++ local value=false
++ result=
++ case ${value} in
++ result=1
++ return 1
++ mc-image-helper get -s --json-path '.promos['\''1.18.1-recommended'\'']' http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
"

### Container definition

```
version: "2"
services:
  minecraft-server:
    image: itzg/minecraft-server:java17
    container_name: MC118
    network_mode: host
    environment:
      - PUID=998
      - PGID=100
      - EULA=TRUE
      - VERSION=LATEST
      - MEMORY=8G
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=true
      - ALLOW_NETHER=true
      - GENERATE_STRUCTURES=true
      - PVP=false
      - TYPE=FORGE
    ports:
      - 25565:25565
    volumes:
      - /srv/dev-disk-by-label-data/MC118:/data
    restart: unless-stopped
```

### Container logs

```
Paste logs here
```
