### ISSUE TITLE
OPS and WHITELIST variables don't work with FTB in java8-multiarch version

### ISSUE THREAD

**Issue by champ8644** [itzg/docker-minecraft-server#1289]
### Describe the problem

the whitelist.json and ops.json is created at /data/whitelist.json and /data/ops.json, but FTB is looking it up at /data/FeedTheBeast/whitelist.json and /data/FeedTheBeast/ops.json
This issue has been resolved on the :latest version by https://github.com/itzg/docker-minecraft-server/issues/584
but I suppose the :java8-multiarch didn't got fixed yet. I would like to play on Forge <1.17 so it is inevitable to use the older image version. I have tried adding the CF_BASE_DIR=/data but this seem like it didn't fixed my problem yet.

Is there anything I could do in the environment variable?

### Container definition

```
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java8-multiarch
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: https://media.forgecdn.net/files/3601/943/Enigmatica6Server-0.5.23.zip
      MOTD: "Enigmatica 6 Server Test on Docker"
      DIFFICULTY: normal
      WHITELIST: user1, user2
      OVERRIDE_WHITELIST: TRUE
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      MEMORY: 5G
      TZ: Asia/Bangkok
      OPS: user1, user2
      CF_BASE_DIR: /data
    ports:
      - "25565:25565"

volumes:
  data: {}
```

### Container logs

![image](https://user-images.githubusercontent.com/37543482/149752846-f09041b7-89c0-4556-b5a1-38a47d3952fb.png)

![image](https://user-images.githubusercontent.com/37543482/149752809-26edac3f-a371-410b-af07-58ab7374bb31.png)
