### ISSUE TITLE
Discord Notification: Notify Channel when Issues are Closed.

### ISSUE THREAD

**Issue by shotah** [itzg/docker-minecraft-server#1353]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Github Workflows add Discord notification when issues are closed for better visibility. 

Acceptance Criteria: Discord receives notifications when users or bot closes issue.

**Comment by shotah** [comment]
@itzg Thoughts on adding Closed, Reopened, and Deleted messages? 

![image](https://user-images.githubusercontent.com/8572809/153486858-ba66358d-7a2b-45eb-bde3-eeeb1d003f9b.png)

```yaml
on:
  issues:
    types: [labeled, reopened, closed, deleted]
```

...

```yaml
      - name: notify closed
        if: > 
          github.event.action == 'closed'
          || github.event.action == 'reopened'
          || github.event.action == 'deleted'
        uses: Ilshidur/action-discord@master
        with:
          args: "[${{ github.event.issue.title }} (#${{ github.event.issue.number }})](<${{ github.event.issue.html_url }}>) has been `${{ github.event.action }}` by `${{ github.event.sender.login }}`"
```
