### ISSUE TITLE
[java8] Autopause causing log spam with `ps: unrecognized option: x`

### ISSUE THREAD

**Issue by Caedis** [itzg/docker-minecraft-server#1360]
### Describe the problem

Container info
![image](https://user-images.githubusercontent.com/18713839/153768913-3ba6b0ac-234b-475c-8fc0-f7ba2200cb31.png)

Its looking like the wrong branch was pushed to the tag since `/autopause/pause.sh` does not match the branch's [pause.sh](https://github.com/itzg/docker-minecraft-server/blob/java8/files/autopause/pause.sh) (which has the correct `ps` flags)

I did try stopping and removing the images and pulled fresh copies, but still it persists.

`/autopause/pause.sh` in container:  
```
#!/bin/bash

. /start-utils

if [[ $( ps -ax -o stat,comm | grep 'java' | awk '{ print $1 }') =~ ^S.*$ ]] ; then
  # save world
  rcon-cli save-all >/dev/null

  # wait until mc-monitor is no longer connected to the server
  while :
  do
    if [[ -z "$(netstat -nt | grep "127.0.0.1:$SERVER_PORT" | grep 'ESTABLISHED')" ]]; then
      break
    fi
    sleep 0.1
  done

  # finally pause the process
  logAutopauseAction "Pausing Java process"
  pkill -STOP java
fi
```

### Container definition

```
  mbm:
    image: itzg/minecraft-server:java8
    container_name: mbm
    restart: unless-stopped
    ports:
      - "25566:25565"
    volumes:
      - "/mnt/docker/minecraft/mbm:/data"
    environment:
      - SETUP_ONLY=false
      - GUI=false
      - UID=1000
      - GID=998
      - TZ=America/Chicago
      - ENABLE_AUTOPAUSE=true
      - AUTOPAUSE_TIMEOUT_EST=300
      - AUTOPAUSE_TIMEOUT_INIT=300

      - TYPE=FORGE
      - FORGEVERSION=14.23.5.2860
      - FORGE_INSTALLER_URL=https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-installer.jar
      - VERSION=1.12.2
      - EULA=true
      - USE_AIKAR_FLAGS=true
      - INIT_MEMORY=4G
      - MAX_MEMORY=8G
      - JVM_DD_OPTS=log4j.configurationFile=log4j2_112-116.xml

      - OVERRIDE_SERVER_PROPERTIES=true
      - MOTD=Multiblock Madness Server
      - WHITELIST=<whitelsited_players>
      - ENFORCE_WHITELIST=true
      - ENABLE_RCON=true
      - RCON_PASSWORD=<rcon_password>
      - VIEW_DISTANCE=15
      - MAX_PLAYERS=5
      - MAX_TICK_TIME=-1
      - ALLOW_FLIGHT=true
      - DIFFICULTY=normal
    healthcheck:
      disable: true
```

### Container logs

[mbm.log](https://github.com/itzg/docker-minecraft-server/files/8056311/mbm.log)
