### ISSUE TITLE
Java Version mismatch?

### ISSUE THREAD

**Issue by IngwiePhoenix** [itzg/docker-minecraft-server#1366]
### Describe the problem

Hello!

I wanted to restart an old server and update it to play with my friends. However, after running it with the rebuild parameters via Docker Compose, I was met with this error:

```
minecraft_1  | Error: A JNI error has occurred, please check your installation and try again
minecraft_1  | Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
minecraft_1  |  at java.lang.ClassLoader.defineClass1(Native Method)
minecraft_1  |  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
minecraft_1  |  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
minecraft_1  |  at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
minecraft_1  |  at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
minecraft_1  |  at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
minecraft_1  |  at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
minecraft_1  |  at java.security.AccessController.doPrivileged(Native Method)
minecraft_1  |  at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
minecraft_1  |  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
minecraft_1  |  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
minecraft_1  |  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
minecraft_1  |  at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
minecraft_1  | 2022/02/15 21:12:54 Done
minecraft_minecraft_1 exited with code 0
```

Since the Java version within the container is preset, I would like to know if there is anything I can do to mitigate this on my end?

Some version infos:
```
root@ingwie-io:/srv/minecraft# lsb_release -ac
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
root@ingwie-io:/srv/minecraft# docker --version
Docker version 20.10.12, build e91ed57
root@ingwie-io:/srv/minecraft# docker-compose --version
docker-compose version 1.18.0, build 8dd22a9
```

Thank you and kind regards,

Ingwie

### Container definition

```
version: "2"
services:
  minecraft:
    image: itzg/minecraft-server
    restart: always
    ports:
      - 25575:25575
      - 25565:25565
    volumes:
      - ./data:/data
      - ./plugins:/plugins
      - ./config:/config
      - ./mods:/mods
    environment:
      - EULA=TRUE
```

### Container logs

```
<See above.>
```
