### ISSUE TITLE
rcon-cli timeout in mc-backup with auto-pause on

### ISSUE THREAD

**Issue by khapin** [itzg/docker-minecraft-server#1400]
### Describe the problem

When doing a backup (e.g. manually triggering it using `docker-compose exec backups backup now`), it fails because of a timeout of rcon-cli:
````
2022-03-05T15:17:08+0000 INFO Repository already initialized
2022-03-05T15:17:09+0000 INFO waiting for rcon readiness...
2022-03-05T15:17:19+0000 ERROR Unable to execute rcon-cli save-on - try 0/5. Retrying in 10s
2022-03-05T15:17:19+0000 ERROR Failure reason: 2022/03/05 15:17:19 Failed to connect to RCON serverread tcp 172.30.0.3:55520->172.30.0.3:25575: i/o timeout
````

if the server is being auto-paused.
But it works correctly if the server is active.

Same if I try to run rcon-cli from the backup container (`docker-compose exec backups rcon-cli`):
`2022/03/05 15:17:37 Failed to connect to RCON serverread tcp 172.30.0.3:55522->172.30.0.3:25575: i/o timeout`

But if I try to rcon-cli from the minecraft container (`docker-compose exec mc_big rcon-cli`) it works correctly, knocks the server back up, and I can run the backup

### Container definition

```
version: "3.7"
services:
  mc_big:
    image: itzg/minecraft-server
    container_name: MC_creative_latest
    environment:
      SERVER_NAME: "redacted"
      MOTD: "Creative mode, big world"
      LEVEL: "Creative-big"
      EULA: "TRUE"
      VERSION: "LATEST"
      MODE: "creative"
      ENABLE_COMMAND_BLOCK: "true"
      DIFFICULTY: "peaceful"
      ENABLE_AUTOPAUSE: "TRUE"
      MAX_TICK_TIME: "-1"
      AUTOPAUSE_TIMEOUT_INIT: "30"
      AUTOPAUSE_TIMEOUT_EST: "10"
      TZ: "Europe/London"
      OVERRIDE_SERVER_PROPERTIES: "true"
      ENABLE_RCON: "true"
      ONLINE_MODE: "false"
      RCON_PASSWORD: 'redacted'
      RCON_PORT: 25575
      restart: unless-stopped
    volumes:
      - mc_creative_big:/data

  router:
    image: itzg/mc-router
    ports:
      - 25565:25565
    command: --mapping=mcbig.example.net=mc_big:25565,mcsurvival.example.net=mc_survival:25565
    environment:
      restart: unless-stopped
 
     
  backups:
    image: itzg/mc-backup
    container_name: MCBackup_creative_big
    environment:
      BACKUP_NAME: Creative-big
      BACKUP_INTERVAL: "12h"
      BACKUP_METHOD: restic
      RESTIC_PASSWORD: "redacted"
      RESTIC_REPOSITORY: "rclone:restic-minecraft"
      RESTIC_ADDITIONAL_TAGS: "creative_big"
      RCON_PORT: 25575
      RCON_PASSWORD: 'redacted'
      RCON_HOST: mc_big
      PAUSE_IF_NO_PLAYERS: "true"
      restart: unless-stopped
    volumes:
      - mc_creative_big:/data:ro
      - backupdir:/backups
      - /home/username/.config/rclone/rclone.conf:/config/rclone/rclone.conf:ro
    network_mode: "service:mc_big"

volumes:
  mc_creative_big:
    driver: local
    driver_opts:
      type: none
      device: /doc/minecraft-docker/Creative-big/
      o: bind
  mc_survival:
    driver: local
    driver_opts:
      type: none
      device: /doc/minecraft-docker/survival/
      o: bind
  backupdir:
    driver: local
    driver_opts:
      type: none
      device: /doc/MCbackups/restic/
      o: bind

```

### Container logs

```
Paste logs here
```
