### ISSUE TITLE
VANILLA_VERSION not working after latest Pufferfish changes

### ISSUE THREAD

**Issue by bram-pkg** [itzg/docker-minecraft-server#1401]
### Describe the problem

I'm running a server with the container shown below, however the `if` statement that checks for a valid version inside `deployPufferfish` is getting triggered.

### Container definition

```
services:
  server:
    # Releases: https://github.com/itzg/docker-minecraft-server/releases
    image: "itzg/minecraft-server:latest"
    ports: # port definitions here
    environment:
      TZ: "Europe/Amsterdam"
      MEMORY: "8G"
      USE_AIKAR_FLAGS: "true"
      EULA: "TRUE"
      # https://github.com/itzg/docker-minecraft-server/blob/master/scripts/start-deployPufferfish
      TYPE: "PUFFERFISH"
      VERSION: "1.18"
      # Builds at: https://ci.pufferfish.host/job/Pufferfish-1.18/
      PUFFERFISH_BUILD: "50"
      # more config here...
    volumes: # definitions here...
    tty: true
    stdin_open: true
    restart: "unless-stopped"
```

### Container logs

```
minecraft_server | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 11 1000 1000 4096 Mar  5 17:29 /data'
minecraft_server | [init] Resolved version given 1.18 into 1.18
minecraft_server | [init] Resolving type given PUFFERFISH
minecraft_server | [init] ERROR: Pufferfish server type only supports versions 1.18 or 1.17, use PUFFERFISH_BUILD to select the the correct build 47 => 1.18.1, 50 => 1.18.2 etc
```
