### ISSUE TITLE
ONLINE_MODE: "FALSE" environment variable ignored in docker-compose

### ISSUE THREAD

**Issue by palkoc** [itzg/docker-minecraft-server#1435]
### Describe the problem

I have added ```ONLINE_MODE: "FALSE"``` to docker-compose.yml, trying to start the container in online_mode off. It seems that the option is ignored and it starts in online_mode=true anyway. 

I have tried to create ```.env``` file:

```bash
ONLINE_MODE=FALSE
```

and started docker-compose as ``` docker-compose --env-file .env up```, the result was the same... Server started in ONLINE_MODE=True. ```docker run -e ONLINE_MODE=FALSE``` works as expected.  Am I doing something wrong?

Thanks and have a nice day.
Pavol

### Container definition

```
version: '3'
# Other docker-compose examples in /examples
services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - ./mc/:/data
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      EXEC_DIRECTLY: "TRUE"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      ALLOW_FLIGHT: "TRUE"
    restart: always
    stdin_open: true
    tty: true
volumes:
  mc: {}
```

### Container logs

```
Paste logs here
```
