### ISSUE TITLE
Move documentation to a docs site for navigability and accessibility

### ISSUE THREAD

**Issue by ChipWolf** [itzg/docker-minecraft-server#1440]
### Enhancement Type

Not sure

### Describe the enhancement

With the size the readme has become, it would benefit from becoming a micro-site using Mkdocs or similar.
This would be more scalable, accessible, and allow for better navigation between key concepts and features.

**Comment by itzg** [comment]
I like the look of this one and use of markdown: https://squidfunk.github.io/mkdocs-material/

**Comment by itzg** [comment]
@camalot thought I'd bring our conversation over here. 

I'm now thinking a Jekyll based site generator would be ideal since that'll plug into GitHub pages without additional build support 

https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#static-site-generators

**Comment by itzg** [comment]
...and taking a few more minutes to read, I see that using custom site generators are fairly simple:

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow

**Comment by camalot** [comment]
Looks like this https://github.com/marketplace/actions/deploy-mkdocs can be used to directly deploy an MkDocs site directly to github pages with the material theme.

**Comment by camalot** [comment]
Quick little test: https://camalot.github.io/mkdocs-test/ in this repo https://github.com/camalot/mkdocs-test

**Comment by itzg** [comment]
That looks great @camalot ! I think we should go with that. The only I'm left pondering is how to transition over. 

A few sections at a time leaving major headers as a link over to new docs?

Do the whole thing at once with each major section as a "page" and then have one big link at the top that says where to find docs?

**Comment by camalot** [comment]
Shouldn't take too long to do in initial convert. I have been taking each "Heading2" and making those into "pages" in this test repo. 

Maybe leave original readme there with a link to the docs indicating the transition, and that the doc site may be incomplete, so refer to the readme.

Can probably better organize the "pages" too, by "edition" or something. then you could technically have bedrock docs there too. 

example, I created `docs/deployment` and that has files for helm, aws, docker-compose and they are then referenced in the nav like this:

```yaml
    - "Deployment Templates and Examples":
      - "Helm Charts": "deployment/helmcharts.md"
      - "Amazon Web Services (AWS)": "deployment/aws.md"
      - "Docker Compose": "deployment/docker-compose.md"
```

which renders as
![image](https://user-images.githubusercontent.com/171452/229221671-f35a1fd2-7819-47e6-a933-6a925604d9b3.png)


I also just figured out that you can do the following in the navigation

```yaml
 - "Related Projects":
    - related-projects.md
    - "itzg/minecraft-bedrock-server": https://github.com/itzg/docker-minecraft-bedrock-server
    - "mc-router": https://github.com/itzg/mc-router
    - "itzg/bungeecord": https://github.com/itzg/docker-bungeecord/
    - "itzg/mc-backup": https://github.com/itzg/docker-mc-backup
    - "rcon-cli": https://github.com/itzg/rcon-cli
    - "mc-monitor": https://github.com/itzg/mc-monitor
    - "mc-image-helper": https://github.com/itzg/mc-image-helper
    - "itzg/rcon": https://github.com/itzg/docker-rcon-web-admin
```
Which renders the following:
![image](https://user-images.githubusercontent.com/171452/229220768-a3da79ef-1d0d-491f-8f3b-10ef9d2b3f3c.png)

There is a "related-projects.md" file which has the descriptions and links, but in the navigation, they are also direct links.
