### ISSUE TITLE
Docker on windows causes world corruption on generation

### ISSUE THREAD

**Issue by Merith-TK** [itzg/docker-minecraft-server#1450]
### Describe the problem

Launch server in docker
causes world corruption

launch server manually on windows, no corruption

Windows Host is windows 11, 21h1, build 22000.556

### Container definition

```yml
  mc-lobby:
    image: itzg/minecraft-server:java17
    container_name: mc-lobby
    #restart: unless-stopped
    networks:
      - server-network
    user: "1000:1000"
    stdin_open: true
    tty: true
    #ports:
    # - "host:container/<udp or tcp>"
    volumes:
      - "./minecraft/lobby:/data"
    environment:
      SYNC_SKIP_NEWER_IN_DESTINATION: "false"
      COPY_CONFIG_DEST: "/data"
      PUID: "1000"
      PGID: "1000"
      TYPE: "fabric"
      VERSION: "1.18.1"
      #PACKWIZ_URL: "https://gitlab.com/Merith-TK/vanillia-modpack/-/raw/server/server/pack.toml"
      EULA: "true"
      MEMORY: "4G"
```

### Container logs

From container (couldnt get complete logs, but enough to show the problem)
https://mclo.gs/i03r23f

from host
https://mclo.gs/klPri14
