### ISSUE TITLE
Forge uses old run script (run.sh) when version is being changed to older

### ISSUE THREAD

**Issue by CDFN** [itzg/docker-minecraft-server#1459]
### Describe the problem

As in title. If we run 1.18.2 server then stop, change VERSION=1.8.8, server starts up with 1.18.2 instead 1.8.8.

### Container definition

Kubernetes values of `env`: 
```yaml
     - env:
        - name: TYPE
          value: FORGE
        - name: EULA
          value: "TRUE"
```
 then
```yaml
     - env:
        - name: TYPE
          value: FORGE
        - name: VERSION
          value: 1.8.8
        - name: EULA
          value: "TRUE"
 ```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 15 1000 1000 4096 Apr  8 12:37 /data'
[init] Resolved version given 1.8.8 into 1.8.8 and major version 1.8
[init] Resolving type given FORGE
[init] **********************************************************************
[init] WARNING: Some mods and modpacks may require Java 8.
[init]          Please use itzg/minecraft-server:java8
[init] **********************************************************************
[init] Checking Forge version information.
Unknown option: '-s'
Possible solutions: --skip-existing, --skip-up-to-date
[init] Downloading 1.8.8-11.15.0.1655-1.8.8
[init] ...trying https://maven.minecraftforge.net/net/minecraftforge/forge/1.8.8-11.15.0.1655/forge-1.8.8-11.15.0.1655-installer.jar
[init] Installing Forge 1.8.8-11.15.0.1655. This might take a minute or two...
[init] Finding installed server jar...
[init] Using server /data/run.sh
[init] server.properties already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 1G and max to 1G
[init] Using Forge supplied run.sh script...
```
