### ISSUE TITLE
Character Sound Issues on 1.18.x

### ISSUE THREAD

**Issue by ruanbekker** [itzg/docker-minecraft-server#1473]
### Audio Issues

Hello, ever since upgrading from 1.17.2 to 1.18.1 and 1.18.2 I am getting a strange audio issue, where the chickens sounds are sounding like trap doors opening and closing.

Anyone experienced these issues before? I am open for any suggestions.

### My upgrade path

the container has persistent data, so I've bumped up the tag, and redeployed. 

### Container definition

```
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    ports:
      - 25565:25565
    environment:
      SERVER_NAME: "$SERVER_NAME"
      MOTD: "Forge Minecraft Server"
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.18.2"
      MODE: "survival"
      MEMORY: "1G"
      LEVEL_TYPE: "DEFAULT"
      ENABLE_RCON: "true"
      RCON_PASSWORD: $PASSWORD
      RCON_PORT: 28016
      WHITELIST: "$USER_LIST"
      OPS: "$USER_LIST"
      MAX_PLAYERS: 20
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      PVP: "true"
      LEVEL: "cold"
      TZ: "Africa/Johannesburg"
      GUI: "FALSE"
      ENABLE_WHITELIST: "true"
      MODS_FILE: /extras/mods.txt
      REMOVE_OLD_MODS: "true"
      ONLINE_MODE: "TRUE"
    restart: unless-stopped
    user: "1002:1002"
    volumes:
      - ./data:/data
      - ./mods.txt:/extras/mods.txt:ro
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
```

### Container logs

No errors:

```
minecraft-server      | [14:52:57] [Server thread/INFO] [ne.mi.co.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@4331cea
minecraft-server      | [14:52:57] [Server thread/INFO] [minecraft/PlayerList]: x[/x.x.x.x:64049] logged in with entity id x at (x.x, -x.0, -x.4527779625238)
minecraft-server      | [14:52:57] [Server thread/INFO] [minecraft/DedicatedServer]: x joined the game
```
