### ISSUE TITLE
mc-image-helper get subcommand causes SELinux quirkiness

### ISSUE THREAD

**Issue by virtualdxs** [itzg/docker-minecraft-server#1485]
Apologies in advance, I am struggling to comprehend how SELinux categories are supposed to work.

I have an Oracle Linux 8 box, on which I'm using podman with docker-compose to bring up a Spigot server with a few spiget plugins. It seems that when I stop the container, make changes to my docker-compose.yml, and start it again, the container gets permission denied on the first plugin version.json file. (I haven't 100% nailed down what reproduces it yet.) I tracked down the issue and determined that all files downloaded from spiget have SELinux categories on them:

```
-rw-rw-r--. 1 20003 root system_u:object_r:container_file_t:s0:c40,c562    17870 Apr 22 05:54 83661.jar
-rw-rw-r--. 1 20003 root system_u:object_r:container_file_t:s0:c40,c562    29256 Apr 22 05:54 86391.jar
-rw-rw-r--. 1 20003 root system_u:object_r:container_file_t:s0:c40,c562    85928 Apr 22 05:54 91537.jar
-rw-rw-r--. 1 20003 root system_u:object_r:container_file_t:s0:c40,c562  2219573 Apr 22 05:54 97320.jar
drwxrwxr-x. 5 20003 root system_u:object_r:container_file_t:s0               199 Apr 22 05:54 BedWars1058
drwxrwxr-x. 2 20003 root system_u:object_r:container_file_t:s0                24 Apr 22 05:54 bStats
drwxrwxr-x. 2 20003 root system_u:object_r:container_file_t:s0                24 Apr 22 05:54 PluginMetrics
-rw-r--r--. 2 root  root unconfined_u:object_r:container_file_t:s0      10464701 Dec  7 05:56 slimeworldmanager-plugin-2.2.1.jar
```

Note the `:c40,c562` on the top 4, and the lack thereof on the 3 folders below (created by the container) and the bottom plugin (created manually). This is confirmed to most likely be the issue by `audit2why`:

```
#       Possible cause is the source level (s0:c30,c433) and target level (s0:c40,c562) are different.
```

Unfortunately, I was not able to determine what causes files to be created with or without categories.

Please let me know if you need more information, or if I should have filed this under itzg/docker-minecraft-server instead.

**Comment by virtualdxs** [comment]
To clarify, the ones owned by user root are like that because I copied them there as root. All files created by the container are owned by uid 20003 (but still group 0).

docker-compose.yml:
```
services:
  minecraft:
    image: itzg/minecraft-server
    user: "20003"
    ports:
      - 32703:25565
    volumes:
      - ./data:/data
    environment:
      EULA: "true"
      TYPE: SPIGOT
      VERSION: 1.8.8-R0.1-SNAPSHOT-latest
      SPIGET_RESOURCES: 97320,83661,86391,91537
      JVM_OPTS: '-javaagent:slimeworldmanager-classmodifier-2.2.1.jar'
    tty: true
    stdin_open: true
```

**Comment by itzg** [comment]
If you're copying files in as root, then you have probably created your own permissions conflict. Look through your `./data` directory and get things consistent to uid 20003.

**Comment by virtualdxs** [comment]
The files that are owned by root are not the problem, it's files owned by 20003 with the SELinux categories set. I'll go ahead and make everything consistent but it's had no issues reading the things owned by root.

**Comment by virtualdxs** [comment]
Reproduced with no root-owned files in the data directory. Procedure:

1. Create docker-compose.yml with the following:
```
services:
  minecraft:
    image: itzg/minecraft-server
    user: "20003"
    volumes:
      - ./data:/data
    environment:
      EULA: "true"
      TYPE: SPIGOT
      VERSION: 1.8.8-R0.1-SNAPSHOT-latest
      SPIGET_RESOURCES: 97320,83661,86391,91537
      FOO: bar
    tty: true
    stdin_open: true
```
2. Run `docker-compose up`
3. Wait until (at least) the spiget resources have downloaded
4. Press Ctrl+C
5. Add an environment variable to docker-compose.yml (I added `FOO: bar`)
6. Wait 5 minutes (minimum duration between checking spiget resources)
7. Run `docker-compose up`

Output:
```
minecraft_1  | [init] Running as uid=20003 gid=0 with /data as 'drwxrwxr-x. 7 20003 0 4096 Apr 22 16:27 /data'
minecraft_1  | [init] Resolved version given 1.8.8-R0.1-SNAPSHOT-latest into 1.8.8-R0.1-SNAPSHOT-latest
minecraft_1  | [init] Resolving type given SPIGOT
minecraft_1  | [init] Downloading Spigot from https://cdn.getbukkit.org/spigot/spigot-1.8.8-R0.1-SNAPSHOT-latest.jar ..
.
minecraft_1  | [init] Getting plugins via Spiget
minecraft_1  | [init] Downloading resource 97320 ...
minecraft_1  | jq: error: Could not open file /data/plugins/.97320-version.json: Permission denied
```
