### ISSUE TITLE
ops.json and whitelist.json not redownloaded on restart

### ISSUE THREAD

**Issue by camalot** [itzg/docker-minecraft-server#1505]
### Describe the problem

If the `/data/ops.json` or `/data/whitelist.json` already exists, and `OPS_FILE` / `WHITELIST_FILE` are URLS, they are not downloaded to replace the existing files. 

instead of a copy from `/data/ops.json` to the server directory, why not just use a symlink?
example: `ln -s /data/whitelist.json /data/FeedTheBeast/ServerFiles/whitelist.json`.

Would also be great if there was a way to have it recheck the remote file periodically, so a server restart isn't required to update the whitelist. (this is probably an additional feature)

### Container definition

```yaml
version: '3.7'
networks:
  internal:
    driver: bridge
services:
  # https://github.com/itzg/docker-minecraft-server/blob/master/README.md
  minecraft-curseforge:
    hostname: minecraft-curseforge
    container_name: minecraft-curseforge
    image: itzg/minecraft-server:java17-alpine
    networks:
    - internal
    ports: 
    - 25565:25565
    restart: unless-stopped
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    deploy:
      resources:
        limits:
          memory: 6g
        reservations:
          memory: 2g
    environment:
      # OPS_FILE: /data/ops.json
      OPS_FILE: 'http://andeddu.local:10070/minecraft/ops.json'
      # WHITELIST_FILE: /data/whitelist.json
      WHITELIST_FILE: 'http://andeddu.local:10070/minecraft/whitelist.json'
      ENFORCE_WHITELIST: 'true'
      MEMORY: 5G
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/all_the_mods_7-0.3.20.zip
      ALLOW_NETHER: 'true'
      ANNOUNCE_PLAYER_ACHIEVEMENTS: 'true'
      MAX_PLAYERS: 20
      SNOOPER_ENABLED: 'false'
      HARDCORE: 'false'
      DIFFICULTY: easy
      GENERATE_STRUCTURES: 'true'
      MAX_BUILD_HEIGHT: 256
      SPAWN_ANIMALS: 'true'
      SPAWN_NPCS: 'true'
      SPAWN_MONSTERS: 'true'
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 10
      MODE: survival
      PVP: 'false'
      LEVEL_TYPE: BIOMESOPLENTY
      ALLOW_FLIGHT: 'false'
      USE_MODPACK_START_SCRIPT: 'true'
      UID: 1000
      GID: 1000
      TZ: 'America/Chicago'
      EULA: 'true'
      tty: 'true'
      stdin_open: 'true'
    volumes:
    - /mnt/container_data/minecraft/curseforge/modpacks:/modpacks
    - /mnt/container_data/minecraft/curseforge/data:/data
```

### Container logs

log output if the files exist:
```
[init] Looking for Feed-The-Beast / CurseForge server modpack.
[init] detected FTB, changing properties path to /data/FeedTheBeast/SIMPLE-SERVER-FILES-0.3.20/server.properties
[init] server.properties already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 5G and max to 5G
[init] Running FTB /data/FeedTheBeast/SIMPLE-SERVER-FILES-0.3.20/startserver.sh in /data/FeedTheBeast/SIMPLE-SERVER-FILES-0.3.2
```

log output if they do not already exist:

```
[init] Resolving type given CURSEFORGE
[init] Looking for Feed-The-Beast / CurseForge server modpack.
[init] detected FTB, changing properties path to /data/FeedTheBeast/SIMPLE-SERVER-FILES-0.3.20/server.properties
[init] server.properties already created, skipping
[init] Downloading ops.json from http://andeddu.local:10070/minecraft/ops.json
[init] Downloading whitelist.json from http://andeddu.local:10070/minecraft/whitelist.json
[init] Checking for JSON files.
[init] Setting initial memory to 5G and max to 5G
[init] Running FTB /data/FeedTheBeast/SIMPLE-SERVER-FILES-0.3.20/startserver.sh in /data/FeedTheBeast/SIMPLE-SERVER-FILES-0.3.20
```
