### ISSUE TITLE
Simple voice chat, double container, port issue

### ISSUE THREAD

**Issue by OlrigSente** [itzg/docker-minecraft-server#1506]
Hello, more of a question than an issue but i encounter a strange behaviour here : 
I Actually run 2 differents container, each one with a minecraft server from ITZG. In both container (one forge, and one fabric if that matter) i have simple voice chat installed. Here is my configuration for it regarding port

Server 1
```yaml
minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: server1
    ports:
      - 25565:25565
      - 24454:24454/udp
```

Server 2
```yaml
minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: server2
    ports:
      - 25566:25565
      - 24455:24454/udp
```

The default port for simple voice chat is 24454 UDP that why. But with this configuration, the mods didn't work on the server2 and to fix it, i had to change the port config to - 24455:24455/udp (and make the change to simple voice chat config file inside /data in order to change the default port to 24455)

In my understanding, docker container should run as an Isolated Resource. So i'm wondering why i encounter a port conflict ? 
Thanks for your answer
