### ISSUE TITLE
Magma server api URL outdated

### ISSUE THREAD

**Issue by Baconing** [itzg/docker-minecraft-server#1517]
### Describe the problem

The api url for magma was updated and you can't download the server. I tried changing it myself but it didn't seem to work and I don't want to go any deeper.

### Container definition
```
version: "3"

services:
  censored:
    image: itzg/minecraft-server:java17
    ports:
      - 25565:21055
    volumes:
      - /home/bacon/.mc/censored:/data
    environment:
      PATH: "/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      LANG: "en_US.UTF-8"
      LANGUAGE: "en_US:en"
      LC_ALL: "en_US.UTF-8"
      JAVA_VERSION: "jdk-17.0.3+7"
      JAVA_HOME: "/opt/java/openjdk"
      TYPE: "CUSTOM"
      VERSION: "1.16.5"
      CUSTOM_SERVER: "server.jar"
      EULA: "TRUE"
      UID: "1000"
      GID: "1000"
      RCON_PASSWORD: "minecraft"
    tty: true
    stdin_open: true
    restart: unless-stopped
```
### Container logs

```
censored | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 1 1000 984 446 May 12 22:23 /data'
censored  | [init] Resolved version given 1.16.5 into 1.16.5 and major version 1.16
censored  | [init] Resolving type given MAGMA
censored | [init] **********************************************************************
censored  | [init] WARNING: Some mods and modpacks may require Java 8.
censored | [init]          Please use itzg/minecraft-server:java8
censored  | [init] **********************************************************************
censored  | curl: (22) The requested URL returned error: 404
censored  | [init] ERROR failed to locate latest Magma info for 1.16.5 in channel stable (error=0)
```
