### ISSUE TITLE
FTB Direwolf20 1.18 cannot find jar

### ISSUE THREAD

**Issue by bitkill** [itzg/docker-minecraft-server#1523]
### Describe the problem

I cannot launch FTB's Direwolf20 1.18
v 1.2.0
https://www.feed-the-beast.com/modpack/95_ftb_presents_direwolf20_1_18/versions

It seems that it cannot find the jar in the /data folder
error source:
https://github.com/itzg/docker-minecraft-server/blob/master/scripts/start-deployFTBA#L79

Looking at the folder, I cannot see the jar like I would with Direwolf20 1.16
folder listing:
```
root@4d0f153ea549:/# ls /data/ 
config  defaultconfigs  eula.txt  ftb-installer  kubejs  libraries  log4jfix  minecraft_server.1.18.2.jar  mods  resourcepacks  run.bat  run.sh  user_jvm_args.txt  version.json
```

### Container definition

```yaml
version: '3.7'

volumes:
  mc-ftb: 

services:

  minecraft:
    image: itzg/minecraft-server:java11-jdk
    environment:
      EULA: TRUE
      TYPE: FTBA
      FTB_MODPACK_ID: 95
      FTB_MODPACK_VERSION_ID: 2127
      MEMORY: 12G
      MOTD: "Have a nice day"
      MAX_PLAYERS: 20
    ports:
      - 25565:25565
    volumes:
      - mc-ftb:/data
```

### Container logs

```
minecraft-docker-minecraft-1  |   Patching com/mojang/blaze3d/vertex/VertexFormatElement$Usage$SetupState 1/1
minecraft-docker-minecraft-1  | The server installed successfully
minecraft-docker-minecraft-1  | You can delete this installer file now if you wish
minecraft-docker-minecraft-1  | 2022/05/19 21:37:47 Installed!
minecraft-docker-minecraft-1  | [init] ERROR unable to locate the installed FTB server jar
```
