### ISSUE TITLE
GENERIC_PACKS not finding correct base_dir

### ISSUE THREAD

**Issue by brandan-schmitz** [itzg/docker-minecraft-server#1524]
### Describe the problem

It seems that when specifying a GENERIC_PACK such as the latest [RLCraft server pack](https://media.forgecdn.net/files/3655/676/RLCraft+Server+Pack+1.12.2+-+Release+v2.9.1c.zip) the find command located at https://github.com/itzg/docker-minecraft-server/blob/master/scripts/start-setupModpack#L227 is not locating the correct base_dir location.

With the included example of the RLCraft the value of that base_dir variable gets set to `/tmp/generic_pack_base/resources/customloadingscreen/sample` when it should stay at `/tmp/generic_pack_base` for this modpack:

```
+ unzip -o -q -d /tmp/generic_pack_base /data/packs/RLCraft+Server+Pack+1.12.2+-+Release+v2.9.1c.zip
++ find /tmp/generic_pack_base -type d '(' -name mods -o -name plugins -o -name config ')' -printf %h -quit
+ base_dir=/tmp/generic_pack_base/resources/customloadingscreen/sample
```

RLCraft: https://www.curseforge.com/minecraft/modpacks/rlcraft

### Container definition

Deployed in Kubernetes with the following file saved as `rlcraft.yaml`

```shell
kubectl apply -f rlcraft.yaml
```

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rlcraft
  namespace: dillon-minecraft-servers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: rlcraft
  name: rlcraft
  namespace: dillon-minecraft-servers
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rlcraft
  template:
    metadata:
      labels:
        run: rlcraft
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - image: itzg/minecraft-server:java8
        tty: true
        stdin: true
        name: rlcraft
        env:
        - name: EULA
          value: "TRUE"
        - name: "TYPE"
          value: "FORGE"
        - name: "VERSION"
          value: "1.12.2"
        - name: "FORGE_INSTALLER_URL"
          value: "https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-installer.jar"
        - name: "GENERIC_PACK"
          value: "https://media.forgecdn.net/files/3655/676/RLCraft+Server+Pack+1.12.2+-+Release+v2.9.1c.zip"
        - name: "MEMORY"
          value: "5G"
        - name: "DEBUG"
          value: "true"
        ports:
        - name: minecraft
          containerPort: 25565
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: 5Gi
            cpu: 4000m
          limits:
            memory: 8Gi
            cpu: 8000m
        livenessProbe:
          tcpSocket:
            port: 25565
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rlcraft
---
apiVersion: v1
kind: Service
metadata:
  name: rlcraft
  namespace: dillon-minecraft-servers
  annotations:
    "mc-router.itzg.me/externalServerName": "private-server-address-here"
spec:
  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
  selector:
    run: rlcraft
  type: ClusterIP
```

### Container logs

Logs without DEBUG=true
```
chmod: changing permissions of '/data': Operation not permitted
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwsr-x 3 0 1000 4096 May 20 01:08 /data'
[init] Resolved version given 1.12.2 into 1.12.2 and major version 1.12
[init] Resolving type given FORGE
[init] Downloading https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-installer.jar ...
[init] Installing Forge . This might take a minute or two...
[init] Finding installed server jar...
[init] Using server forge-1.12.2-14.23.5.2860.jar
[init] Downloading generic pack from https://media.forgecdn.net/files/3655/676/RLCraft+Server+Pack+1.12.2+-+Release+v2.9.1c.zip
[init] Checking if generic packs are up to date
[init] Generic pack(s) are out of date. Re-applying...
[init] Writing generic pack manifest ... 
[init] Applying generic pack ...
[init] Saving generic pack(s) checksum
[init] Creating server.properties in /data/server.properties
[init] Disabling whitelist functionality
[init] Setting white-list to 'false' in /data/server.properties
[init] WARNING: whitelist enabled but not enforced. Set ENFORCE_WHITELIST=TRUE or update 'enforce-whitelist' in server.properties to enforce the whitelist.
[init] Setting enable-rcon to 'true' in /data/server.properties
[init] Setting rcon.password to 'minecraft' in /data/server.properties
[init] Setting rcon.port to '25575' in /data/server.properties
[init] Setting motd to 'A Forge Minecraft Server powered by Docker' in /data/server.properties
[init] Checking for JSON files.
[init] Setting initial memory to 5G and max to 5G
[init] Starting the Minecraft server...
```

Relevant part of the debug logs showing the variable values:
```
+ unzip -o -q -d /tmp/generic_pack_base /data/packs/RLCraft+Server+Pack+1.12.2+-+Release+v2.9.1c.zip
++ find /tmp/generic_pack_base -type d '(' -name mods -o -name plugins -o -name config ')' -printf %h -quit
+ base_dir=/tmp/generic_pack_base/resources/customloadingscreen/sample
```

Content of the manifest.txt file:
```
imagemeta/rotating_cake_top_left.json
imagemeta/rotating_cake_bottom_left.json
imagemeta/rotating_cake_bottom_right.json
imagemeta/rotating_cake_top_right.json
function/item_rotation.json
function/interpolate.json
action/sound_at_end.json
instruction/item_rotate_anti_clockwise.json
instruction/item_rotate_clockwise.json
image/block_cake_inner_4_wide.json
image/block_cake_side_4_wide.json
image/loading_bar_boss_percentage.json
image/text_status.json
image/dirt_background.json
image/text_status_white.json
image/cake_top_right.json
image/cake_bottom_right.json
image/panorama.json
image/bottom_bar.json
image/text_percentage_scrolling.json
image/text_sub_status_white.json
image/loading_bar_bevel_percentage.json
image/loading_bar_boss.json
image/text_generic_error.json
image/loading_bar_bevel.json
image/block_4_wide_percentage.json
image/cake.json
image/mojang_splash.json
image/text_percentage_white.json
image/cake_top_left.json
image/text_percentage.json
image/loading_bar_standard_percentage.json
image/cake_bottom_left.json
image/text_sub_status.json
image/item.json
image/block_4_wide.json
image/loading_bar_standard.json
image/horizontal_stripe.json
config/white.json
config/generic_error.json
config/forge_duplicate.json
config/rotating_cakes.json
config/default.json
config/worldload.json
config/custom.json
config/scrolling.json
config/scrolling_detailed.json
```
