### ISSUE TITLE
Cannot find Forge 1.18.2

### ISSUE THREAD

**Issue by Pilchh** [itzg/docker-minecraft-server#1525]
### Describe the problem

When attempting to start the server for the first time it attempts to download the forge version but it fails to download it from the webpage as it gets a 404 page not found error.

### Container definition

```
version: '3.2'

services:
  forge-server:
    container_name: forge
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      - "TYPE=FORGE"
      - "FORGEVERSION=1.18.2"
      - "VERSION=1.18.2"
      - "EULA=true"
      - "OPS=Pilchh"
      - "MEMORY=6G"
    volumes:
      - /srv/forge:/data
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 May 20 15:47 /data',
[init] Resolved version given 1.18.2 into 1.18.2 and major version 1.18,
[init] Resolving type given FORGE,
[init] Checking Forge version information.,
[init] Downloading 1.18.2-1.18.2-1.18.2,
[init] ...trying https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.2-1.18.2/forge-1.18.2-1.18.2-installer.jar,
[mc-image-helper] 15:51:14.175 ERROR : 'get' command failed: Failed to download https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.2-1.18.2/forge-1.18.2-1.18.2-installer.jar: status code: 404, reason phrase: Not Found,
[init] ...trying https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.2-1.18.2-1.18.2/forge-1.18.2-1.18.2-1.18.2-installer.jar,
[mc-image-helper] 15:51:15.411 ERROR : 'get' command failed: Failed to download https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.2-1.18.2-1.18.2/forge-1.18.2-1.18.2-1.18.2-installer.jar: status code: 404, reason phrase: Not Found,
[init] Unable to locate usable URL for 1.18.2-1.18.2-1.18.2
```
