### ISSUE TITLE
CurseForge server no longer starting.

### ISSUE THREAD

**Issue by scottmando2000** [itzg/docker-minecraft-server#1535]
### Describe the problem

Since the update 2 days ago,  my All The Mods 7 CurseForge server will no longer start properly.

### Container definition

```
version: "3"

services:
  atm7:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "FALSE"
      TYPE: "CURSEFORGE"
      PAPERBUILD: 318
      MEMORY: 16G
      SPAWN_PROTECTION: 0
      UID: 1234
      GID: 1234
      CF_SERVER_MOD: "/modpacks/SIMPLE-SERVER-FILES-0.3.20.zip"
    tty: true
    stdin_open: true
    restart: unless-stopped
    user: 1234:1234
    volumes:
      - ./atm7:/data
      - ./modpacks:/modpacks
```

### Container logs

```
minecraft-atm7-1  | [init] Looking for Feed-The-Beast / CurseForge server modpack.
minecraft-atm7-1  | [init] Conflicting FTB/CurseForge packages have been installed. Please cleanup /data/FeedTheBeast
minecraft-atm7-1  | [init] Running as uid=1234 gid=1234 with /data as 'drwxrwxr-x 3 1234 1234 4096 May  6 00:38 /data'
minecraft-atm7-1  | [init] Resolved version given LATEST into 1.18.2 and major version 1.18
```
