### ISSUE TITLE
Synology Docker - Setting MOTD environmental variable does not work.

### ISSUE THREAD

**Issue by nate-krichbaum** [itzg/docker-minecraft-server#1552]
### Describe the problem

Setting environmental variable of MOTD does not seem to propagate to the actual MOTD. The default MOTD overwrites it.

On Synology Docker.

### Container definition

{
   "CapAdd" : null,
   "CapDrop" : null,
   "cmd" : "",
   "cpu_priority" : 50,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : false,
   "enabled" : true,
   "entrypoint_default" : "/start",
   "env_variables" : [
      {
         "key" : "MOTD",
         "value" : "What up! We're cool guys looking for other cool guys who want to hang out . Nothing Sexual."
      },
      {
         "key" : "PATH",
         "value" : "/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "LANG",
         "value" : "en_US.UTF-8"
      },
      {
         "key" : "LANGUAGE",
         "value" : "en_US:en"
      },
      {
         "key" : "LC_ALL",
         "value" : "en_US.UTF-8"
      },
      {
         "key" : "JAVA_VERSION",
         "value" : "jdk-17.0.1+12"
      },
      {
         "key" : "JAVA_HOME",
         "value" : "/opt/java/openjdk"
      },
      {
         "key" : "UID",
         "value" : "1000"
      },
      {
         "key" : "GID",
         "value" : "1000"
      },
      {
         "key" : "MEMORY",
         "value" : ""
      },
      {
         "key" : "TYPE",
         "value" : "VANILLA"
      },
      {
         "key" : "VERSION",
         "value" : "LATEST"
      },
      {
         "key" : "ENABLE_RCON",
         "value" : "true"
      },
      {
         "key" : "RCON_PORT",
         "value" : "25575"
      },
      {
         "key" : "RCON_PASSWORD",
         "value" : "104190"
      },
      {
         "key" : "ENABLE_AUTOPAUSE",
         "value" : "false"
      },
      {
         "key" : "AUTOPAUSE_TIMEOUT_EST",
         "value" : "3600"
      },
      {
         "key" : "AUTOPAUSE_TIMEOUT_KN",
         "value" : "120"
      },
      {
         "key" : "AUTOPAUSE_TIMEOUT_INIT",
         "value" : "600"
      },
      {
         "key" : "AUTOPAUSE_PERIOD",
         "value" : "10"
      },
      {
         "key" : "AUTOPAUSE_KNOCK_INTERFACE",
         "value" : "eth0"
      },
      {
         "key" : "ENABLE_AUTOSTOP",
         "value" : "false"
      },
      {
         "key" : "AUTOSTOP_TIMEOUT_EST",
         "value" : "3600"
      },
      {
         "key" : "AUTOSTOP_TIMEOUT_INIT",
         "value" : "1800"
      },
      {
         "key" : "AUTOSTOP_PERIOD",
         "value" : "10"
      },
      {
         "key" : "SERVER_NAME",
         "value" : "Party Mansion"
      },
      {
         "key" : "ANNOUNCE_PLAYER_ACHIEVEMENTS",
         "value" : "true"
      },
      {
         "key" : "OPS",
         "value" : "Null"
      },
      {
         "key" : "EULA",
         "value" : "TRUE"
      },
      {
         "key" : "PUID",
         "value" : "1026"
      },
      {
         "key" : "PGID",
         "value" : "101"
      }
   ],
   "exporting" : false,
   "id" : "e587417dad883a86c48ec5842da64d55dfbeb2e3754b02a0739e134a1d43be20",
   "image" : "itzg/minecraft-server:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "itzg-slacker-minecraft",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 25565,
         "host_port" : 25560,
         "type" : "tcp"
      },
      {
         "container_port" : 25575,
         "host_port" : 25570,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false,
      "enable_status_page" : false,
      "enable_web_page" : false,
      "web_page_url" : ""
   },
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/docker/minecraft",
         "mount_point" : "/data",
         "type" : "rw"
      }
   ]
}

**Comment by itzg** [comment]
I'm not able to recreate this, but I also don't have experience nor access to Synology.

I created a container with
```
docker run -it --rm -e EULA=TRUE -e MOTD="Testing the MOTD" -p 25565:25565 itzg/minecraft-server
```

and I see the MOTD in the server listing:
![image](https://user-images.githubusercontent.com/988985/172494147-f42924fb-fd36-4541-8868-1ebfa39df8f2.png)

**Comment by nate-krichbaum** [comment]
In that case I switched to a docker compose file and still am having trouble.

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25560:25565
    environment:
      EULA: "TRUE"
      MOTD: "\u00a76What up! We're cool guys looking for other cool guys who want to hang out.\u00a7c Nothing Sexual."
      MEMORY: "4G"
      TYPE: "VANILLA"
      VERSION: "LATEST"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "104190"
      ENABLE_AUTOPAUSE: "false"
      AUTOPAUSE_TIMEOUT_EST: "3600"
      AUTOPAUSE_TIMEOUT_KN: "120"
      AUTOPAUSE_TIMEOUT_INIT: "600"
      AUTOPAUSE_PERIOD: "10"
      AUTOPAUSE_KNOCK_INTERFACE: "eno1"
      ENABLE_AUTOSTOP: "false"
      SERVER_NAME: "Party Mansion"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "True"
      OPS: "null"
      PUID: "1000"
      PGID: "1000"
    volumes:
      - /home/nate/Docker/minecraft:/data
    tty: true
    stdin_open: true
    restart: unless-stopped
```
