### ISSUE TITLE
If Paper server hasn't released a version that matches "latest", run fails

### ISSUE THREAD

**Issue by yourpropertyexpert** [itzg/docker-minecraft-server#1557]
### Describe the problem

The issue came to light with the release of 1.19 yesterday.

docker-minecraft-server build starts by resolving LATEST, which now returns 1.19 (as both the full and major version strings.)

It then tries to download 1.19 from the PAPERMC servers, which give a 404 (because they haven't released yet.)

This forces it into loop (possibly infinite, but I CTRL-Cd before finding out), which would presumably only resolve in days/weeks when PAPERMC release.

PaperMC are, obviously, aware of the issue, but have upstream dependencies on Spigot, which is a bit opaque about release schedules.

A possible workaround for 1.20 would be to, before it looks for LATEST, checked whether LATEST was available, and if not, skip the "Removing old PaperMC versions ..." step.

This wouldn't help with new installations, but would help with server restarts of existing ones.

### Container definition

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server:java17-alpine
    ports:
      - 25565:25565
    environment:
      EULA: "true"
      ENABLE_RCON: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 10
      MEMORY: 3G
      CONSOLE: "true"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
```

### Container logs

```
minecraft-mc-1  | [init] Changing ownership of /data to 1000 ...
minecraft-mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 26 0 0 832 Jun  4 15:27 /data'
minecraft-mc-1  | [init] Resolved version given LATEST into 1.19 and major version 1.19
minecraft-mc-1  | [init] Resolving type given PAPER
minecraft-mc-1  | curl: (22) The requested URL returned error: 404
minecraft-mc-1  | [init] Removing old PaperMC versions ...
minecraft-mc-1  | [init] Downloading PaperMC 1.19 (build null) ...
minecraft-mc-1  | curl: (22) The requested URL returned error: 404
minecraft-mc-1  | ERROR: failed to download PaperMC from version=1.19 build=null download=
minecraft-mc-1 exited with code 1
minecraft-mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 25 0 0 800 Jun  8 17:52 /data'
minecraft-mc-1  | [init] Resolved version given LATEST into 1.19 and major version 1.19
minecraft-mc-1  | [init] Resolving type given PAPER
minecraft-mc-1  | curl: (22) The requested URL returned error: 404
minecraft-mc-1  | [init] Removing old PaperMC versions ...
minecraft-mc-1  | [init] Downloading PaperMC 1.19 (build null) ...
minecraft-mc-1  | curl: (22) The requested URL returned error: 404
minecraft-mc-1  | ERROR: failed to download PaperMC from version=1.19 build=null download=
minecraft-mc-1 exited with code 1
```
