### ISSUE TITLE
Unable to locate installed forge server jar

### ISSUE THREAD

**Issue by Ksccds** [itzg/docker-minecraft-server#1565]
Hi 

Im trying to make a Better-Minecraft server in Docker but its not working for me :(

Container Environment
![image](https://user-images.githubusercontent.com/107549390/173810162-b74243a1-4125-4b77-bf25-faf0f5649a84.png)
![image](https://user-images.githubusercontent.com/107549390/173810236-c1074250-ef97-4c87-9b98-fce4cc1d39ea.png)

Container Logs
[BetterMinecraft-1.18.2.csv](https://github.com/itzg/docker-minecraft-server/files/8908550/BetterMinecraft-1.18.2.csv)

**Comment by lucksma96** [comment]
Did you disable `USE_MODPACK_START_SCRIPT`?

My modpack does not have a start script, so I disabled it and got this same error.

I noticed that the script only looks for the .jar as deep as 2 levels, but the Forge installer installs it 6 levels deep in `/libraries/net/minecraftforge/forge/minecraftversion-forgeversion/`.

**Comment by itzg** [comment]
You can also try using it as a generic pack, such as this example I created recently for ATM7:

```yaml
version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    volumes:
    - ./data:/data
    - ./modpacks:/modpacks:ro
    environment:
      EULA: "true"
      MEMORY: 2G
      TYPE: FORGE
      VERSION: 1.18.2
      FORGEVERSION: 40.1.30
      # Need to download Server-Files-0.4.13.zip and
      # put it in modpacks directory next to this compose file
      GENERIC_PACK: /modpacks/Server-Files-0.4.13.zip
    ports:
      - "25565:25565"
```
