### ISSUE TITLE
Magma API Update

### ISSUE THREAD

**Issue by OutcastChris** [itzg/docker-minecraft-server#1579]
### Describe the problem

The current magma deploy script pulls from the old API version and as such does not work.

The new API (v2) is present;
https://api.magmafoundation.org/api-docs/#/

### Container definition

```
rpguilds-magma:
    restart: always
    image: itzg/minecraft-server:java17
    ports:
      - 25525:25577
    volumes:
      - /docker/minecraft/rpguilds/magma:/data
    networks:
      - rpguilds-dev
      - rpguilds-proxy
    environment:
      USE_AIKAR_FLAGS: "TRUE"
      EULA: "TRUE"
      TYPE: "MAGMA"
      SERVER_NAME: "magma"
      VERSION: "1.18.2"
      MEMORY: "4G"
    stdin_open: true
    tty: true
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Jun 27 11:07 /data'
[init] Resolved version given 1.18.2 into 1.18.2
[init] Resolving type given MAGMA
curl: (22) The requested URL returned error: 404 
[init] ERROR failed to locate latest Magma info for 1.18.2 in channel stable (error=0)
```
