### ISSUE TITLE
ERROR: the given Forge installer doesn't exist : magma-installer-1.16.5-89287b58.jar

### ISSUE THREAD

**Issue by PackmanDude** [itzg/docker-minecraft-server#1598]
### Describe the problem

Using java8 tag with TYPE=MAGMA & VERSION=1.16.5 after pulling gives an error:
```
[init] ERROR: the given Forge installer doesn't exist : magma-installer-1.16.5-89287b58.jar
```
and stops.

### Container definition

```
services:
  server:
    container_name: minecraft
    image: itzg/minecraft-server:java8
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:
      - env.list
    volumes:
      - './data:/data'
    ports:
      - '25565:25565'
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 4 1000 1000 4096 Jul 13 15:43 /data'
[init] Resolved version given 1.16.5 into 1.16.5 and major version 1.16
[init] Resolving type given MAGMA
[init] ERROR: the given Forge installer doesn't exist : magma-installer-1.16.5-89287b58.jar
```
