### ISSUE TITLE
FTB Direwolf18 installation failing (at least with direwolf 1.18.0, not sure about the rest)

### ISSUE THREAD

**Issue by ThatCoffeeGuy** [itzg/docker-minecraft-server#1651]
First of all, thank you for your work on this image - very useful and nicely developed. 

### Describe the problem

The issue I am facing: 

After changing modpack version ID in docker-compose (2142 --> 2234), to update from direwolf18 1.5.1 to 1.8.0, the installer complained of not being able to download all mods, crashed the process and rendered the server unable to start. 

```2022/08/05 21:08:38 Downloaded 491 successful, 266 failed, 0 incomplete.```

Using serverinstall_95_2234 file downloaded from [FTB](https://api.modpacks.ch/public/modpack/95/2234/server/linux), will download all the required mods, but will also break something, because running the docker image will end up like this:

```[22:24:21] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing mandatory dependencies: forge, forge, forge, forge, forge```

After trying a lot of copying and trying to match required dependencies, I somehow ended up with: 
```[init] FTB modpack ID 95, version ID 2234 is ready to go
[init] ERROR unable to locate the installed FTB server jar
minecraft_server.1.18.2.jar 
```
While obviously, the file is present...

Thanks!

### Container definition

```

version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25569:25565
      - 8127:8123
      - 21565:21565
    environment:
      EULA: TRUE
      TYPE: "FTBA"
      FTB_MODPACK_ID: "95"
      FTB_MODPACK_VERSION_ID: "2234" # 1.8.0
      MOTD: "Modded MC FTW! Direwolf 1.18 1.8.0"
      ONLINE_MODE: true
      SERVER_NAME: "FTB Direwolf 1.18 1.8.0"
      ENABLE_RCON: true
      ENABLE_QUERY: true
      QUERY_PORT: 21565
      INIT_MEMORY: "4G"
      MAX_MEMORY: "8G"
      TZ: "Europe/Budapest"
      ENABLE_QUERY: true
      ALLOW_FLIGHT: true
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /mnt/ftb-direwolf18broken:/data


  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dynmap'
      MYSQL_USER: 'dynmap'
      MYSQL_PASSWORD: 'dynmap'
      MYSQL_ROOT_PASSWORD: 'dynmap'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /mnt/ftb-direwolf18-dynmap-mysql:/var/lib/mysql

```

### Container logs

[log.txt](https://github.com/itzg/docker-minecraft-server/files/9271551/log.txt)
