### ISSUE TITLE
Minecraft server process failed {"exitCode": -1}

### ISSUE THREAD

**Issue by k0mar12** [itzg/docker-minecraft-server#1665]
### Describe the problem

Runing on the:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Container definition

```
version: '3'

services:
  mc-server:
    image: itzg/minecraft-server
    user: minecraft
    container_name: '${DOCKER_PREFIX}_mc_server'
    ports:
      - 25565:25565
      - 25575:25575
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      EULA: 'TRUE'
      TYPE: 'PAPER'
      VERSION: '1.19.2'
      UID: 1000
      GID: 998
      ONLINE_MODE: 'FALSE'
      MOTD: '${MC_SERVER_NAME}'
      MEMORY: '${MC_RAM_MEMORY}'
      MAX_PLAYERS: '${MC_MAX_PLAYERS}'
    volumes:
      - ./src/minecraft-server/plugins:/data/plugins
      - ./src/minecraft-server/mods:/data/mods
      - ./src/minecraft-server/config:/data/config

id`s local user is 1000:998
```

### Container logs

```
[18:40:13 INFO]: Running delayed init tasks
[18:40:13 INFO]: Done (30.105s)! For help, type "help"
[18:40:13 INFO]: Timings Reset
2022-08-11T18:40:23.192Z	WARN	mc-server-runner	Minecraft server process failed	{"exitCode": -1}
2022-08-11T18:40:23.196Z	INFO	mc-server-runner	Done
```
