### ISSUE TITLE
[init] ERROR: unsupported archive type: text/html

### ISSUE THREAD

**Issue by Y4rd13** [itzg/docker-minecraft-server#1714]
### Describe the problem

I have a docker-compose with two containers, one server without mods (`mc-no-mods`) and one with mods (`mc-mods`). When running docker-compose, only the server without mods works.

The docker logs don't say much other than that the mods are out of date (of course they are, since the working version is for 1.16.5), and then it says that it supports `archive type text/html`, however there are no files with this extension.

I also find it curious that when defining the CFG prefix as an empty string, it still logs the following: `[init] Replacing env variables in /data that match the prefix CFG`

[Here is the zip file with the mods for v.1.16.5. ](https://drive.google.com/file/d/1zsNcw5YGnrh-_zO1MWfmnhYnyt9vrR4p/view?usp=sharing)

_I have learned a lot lately with your work, keep on keepin' on the awesome job!_ 

### Container definition

```yml
version: "3"

x-server: &server
  env_file:
    - .env
  tty: true
  stdin_open: true

  environment: &env
    LEVEL_TYPE: "minecraft:normal"
    EULA: "true"
    OPS: ${OPS_LIST}
    DIFFICULTY: "normal"
    MAX_PLAYERS: "3"
    VIEW_DISTANCE: "6"
    SIMULATION-DISTANCE: "6"
    SPAWN_PROTECTION: "0"
    PLAYER_IDLE_TIMEOUT: "10"
    ENABLE_COMMAND_BLOCK: "false"
    SNOOPER_ENABLED: "false"

    # Autopause
    ENABLE_AUTOPAUSE: "true"
    AUTOPAUSE_TIMEOUT_INIT: "1800"
    AUTOPAUSE_TIMEOUT_EST: "600"
    AUTOPAUSE_PERIOD: "300"

    # Specs
    MAX_TICK_TIME: -1
    INIT_MEMORY: ${INIT_MEMORY}
    MAX_MEMORY: ${MAX_MEMORY}

    # RCON
    ENABLE_RCON: ${ENABLE_RCON}
    RCON_PASSWORD: ${RCON_PASSWORD}
    RCON_PORT: ${RCON_PORT}

    # Debug
    DEBUG_EXEC: "false"
    DEBUG_AUTOPAUSE: "false"
    DEBUG_MEMORY: "false"

    # ENV settings
    ENV_VARIABLE_PREFIX: ""
    REPLACE_ENV_IN_PLACE: "true"
    REPLACE_ENV_DURING_SYNC: "true"
    OVERRIDE_SERVER_PROPERTIES: "true"

services:
  mc-no-mods:
    <<: *server
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${SV_PORT_1}:${SV_PORT_1}
    volumes:
      - ./minecraft-data:/data
    environment:
      <<: *env
      TYPE: "VANILLA"
      VERSION: "1.19.2"
      SERVER_NAME: "foo 1"
      MODTD: "bar 2"
  mc-mods:
    <<: *server
    image: itzg/minecraft-server:java8-multiarch
    env_file:
      - .env
    ports:
      - ${SV_PORT_2}:${SV_PORT_2}
    volumes:
      - ./minecraft-no-mods-data:/data
      - ./modpacks:/modpacks
    environment:
      <<: *env
      restart: on-failure
      VERSION: "1.16.5"
      SERVER_NAME: "foo 2"
      MODTD: "bar 2"
      TYPE: "FORGE"
      FORGE_VERSION: "36.2.35"
      GENERIC_PACK: "/modpacks/my_generic_modpack_v1.zip"
      USE_MODPACK_START_SCRIPT: "false"
      REMOVE_OLD_MODS: "false"
      SKIP_GENERIC_PACK_UPDATE_CHECK: "true"
volumes:
  minecraft-data:
  minecraft-no-mods-data:
  modpacks:
```

### Container logs

```bash
sudo docker-compose up --build

mc-no-mods_1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 6 1000 1000 4096 Sep  4 04:28 /data'
mc-no-mods_1  | [init] Resolved version given 1.19.2 into 1.19.2 and major version 1.19
mc-no-mods_1  | [init] Autopause functionality enabled
mc-mods_1     | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 4 1000 1000 4096 Sep  4 04:22 /data'
mc-mods_1     | [init] Resolved version given 1.16.5 into 1.16.5 and major version 1.16
mc-mods_1     | [init] Autopause functionality enabled
mc-no-mods_1  | [init] Resolving type given VANILLA
mc-mods_1     | [init] Resolving type given FORGE
mc-no-mods_1  | [init] Updating server properties in /data/server.properties
mc-no-mods_1  | [init] Disabling whitelist functionality
mc-no-mods_1  | [init] Replacing env variables in /data that match the prefix CFG_ ...
mc-mods_1     | [mc-image-helper] 00:57:12.686 INFO  : Forge version 36.2.34 for minecraft version 1.16.5 is already installed
mc-mods_1     | [init] Checking if generic packs are up to date
mc-mods_1     | [init] Generic pack(s) are out of date. Re-applying...
mc-mods_1     | [init] ERROR: unsupported archive type: text/html
mc-server_mc-mods_1 exited with code 1
```
