### ISSUE TITLE
Icons fail on latest version

### ISSUE THREAD

**Issue by cecilia-sanare** [itzg/docker-minecraft-server#1738]
### Describe the problem

Upon starting up the container it fails to launch after attempting to retrieve the icon.

Seems to be likely related to these commits.

a57d678fdd867e64d3c1bc6537c4fd8c7b132bee
https://github.com/itzg/mc-image-helper/commit/d1a08666008e7bc590974c97a163db542dab1613

### Container definition

```
version: "3"

x-minecraft: &mc
  image: itzg/minecraft-server:java17-alpine
  expose:
    - "25565"
  tty: true
  stdin_open: true
  restart: unless-stopped
  networks:
    - minecraft

x-minecraft-environment: &mc-env
  EULA: "TRUE"
  OVERRIDE_SERVER_PROPERTIES: "TRUE"
  SYNC_CHUNK_WRITES: "false"
  USE_AIKAR_FLAGS: "TRUE"
  OPS: 33ceed63-2539-4725-ad93-8c869aaf551e,fa8032ed-8b1f-4fad-a09c-0fe685332a46,d288f246-4197-4bc5-8d5e-a439a171b945
  OVERRIDE_OPS: "TRUE"
  REMOVE_OLD_MODS: "TRUE"
  REMOVE_OLD_MODS_INCLUDE: "*.jar"
  REMOVE_OLD_MODS_DEPTH: 1
  REMOVE_OLD_MODS_EXCLUDE: ""
  SPAWN_PROTECTION: "0"
  GH_TOKEN: ${RUNTIME_GH_TOKEN}
  MAX_TICK_TIME: 120000

x-minecraft-whitelist: &mc-env-wl
  WHITELIST: "33ceed63-2539-4725-ad93-8c869aaf551e,fa8032ed-8b1f-4fad-a09c-0fe685332a46,d288f246-4197-4bc5-8d5e-a439a171b945"
  ENFORCE_WHITELIST: "TRUE"
  OVERRIDE_WHITELIST: "TRUE"

services:
  infrared:
    container_name: infrared
    image: haveachin/infrared:latest
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
    expose:
      - "25565"
    networks:
      - minecraft
    volumes:
      - ${INFRARED_DIR}:/configs
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
  
  minecraft-smp:
    <<: *mc
    container_name: minecraft-smp
    environment:
      <<: *mc-env
      VERSION: 1.19.2
      TYPE: PAPER
      SPIGET_RESOURCES: 64346,91722
      ICON: https://raw.githubusercontent.com/cecilia-sanare/SelfHosted/main/assets/icons/smp.png
      OVERRIDE_ICON: "TRUE"
      MOTD: Polycule SMP Server
    volumes:
      - /etc/minecraft/latest/smp:/data
  
  minecraft-atm:
    <<: *mc
    container_name: minecraft-atm
    environment:
      <<: *mc-env
      MEMORY: 16G
      TYPE: FORGE
      VERSION: 1.18.2
      FORGEVERSION: 40.1.68
      GENERIC_PACK: /modpacks/ATM_7_Server_0.4.29.zip
      MOTD: Polycule ATM7 Server
    volumes:
      - /etc/minecraft/latest/atm:/data
      - /etc/minecraft/modpacks:/modpacks:ro

  minecraft-origins:
    <<: *mc
    container_name: minecraft-origins
    environment:
      <<: *mc-env
      ENABLE_COMMAND_BLOCK: "TRUE"
      MEMORY: 16G
      TYPE: FABRIC
      VERSION: 1.19.2
      PACKWIZ_URL: https://raw.githubusercontent.com/temmies-origins/temmies-origins-modpack/v0.1.14/pack.toml
      MODRINTH_PROJECTS: dcintegration,passive-endermen
      MOTD: Polycule Origins Server
      ICON: https://raw.githubusercontent.com/cecilia-sanare/SelfHosted/main/assets/icons/origins.png
      OVERRIDE_ICON: "TRUE"
      SEED: "2830351026098010116"
    volumes:
      - /etc/minecraft/latest/origins:/data
      - /etc/minecraft/modpacks:/modpacks:ro

networks:
  minecraft: {}
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 12 1000 1000 4096 Sep 19 02:34 /data'
[init] Resolved version given 1.19.2 into 1.19.2 and major version 1.19
[init] Resolving type given PAPER
[init] Removing old PaperMC versions ...
[init] Downloading PaperMC 1.19.2 (build 153) ...
[init] Removing old mods including:*.jar excluding:
[init] Getting plugins via Spiget
[init] Downloading resource 64346 ...
[init] resource '64346' not downloaded because installed version '1.20.1' already up to date ('1.20.1')
[init] Downloading resource 91722 ...
[init] resource '91722' not downloaded because installed version '1.3.1' already up to date ('1.3.1')
[init] Updating server properties in /data/server.properties
[init] Disabling whitelist functionality
[init] Recreating ops.json file at server startup
[init] Updating ops
[init] Using server icon from https://raw.githubusercontent.com/cecilia-sanare/SelfHosted/main/Icons/smp.png...
[mc-image-helper] 02:42:29.774 ERROR : 'get' command failed: status code: 404, reason phrase: Not Found
[init] ERROR: failed to download icon from https://raw.githubusercontent.com/cecilia-sanare/SelfHosted/main/Icons/smp.png
```
