### ISSUE TITLE
failed to ping localhost:25565 : All attempts fail: #1: failed to connect: dial tcp 127.0.0.1:25565: connect: connection refuse

### ISSUE THREAD

**Issue by mindphaseproductions** [itzg/docker-minecraft-server#1758]
### Describe the problem

In the 'Container health' section within the minecraft_server container in my Portainer, I am receiving an error: "failed to ping localhost:25565 : All attempts fail: #1: failed to connect: dial tcp 127.0.0.1:25565: connect: connection refused". This seems to have not been a problem, as I have had this image running for over a month and have not touched anything. I never even configured a Container health check for any of my containers. Maybe it's due to a recent update?

### Container logs

```
services:
  minecraft_server:
    container_name: minecraft_server
    environment:
      EULA: "TRUE"
      GID: "1000"
      TYPE: VANILLA
      TZ: America/Toronto
      UID: "1000"
      VERSION: LATEST
    hostname: XXXXX
    image: itzg/minecraft-server
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 200k
    networks:
      default: null
    ports:
    - mode: ingress
      target: 25565
      published: "25565"
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: /home/XXXXX/.config/appdata/minecraft_server
      target: /data
      bind:
        create_host_path: true
    - type: bind
      source: /media/storage/XXXXX/storage
      target: /storage
      bind:
        create_host_path: true
  portainer:
    command:
    - -H
    - unix:///var/run/docker.sock
    container_name: portainer
    environment:
      TZ: America/Toronto
    hostname: XXXXX
    image: portainer/portainer-ce
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 200k
    networks:
      default: null
    ports:
    - mode: ingress
      target: 9000
      published: "9000"
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      bind:
        create_host_path: true
    - type: bind
      source: /home/XXXXX/.config/appdata/portainer
      target: /data
      bind:
        create_host_path: true
    - type: bind
      source: /media/storage/XXXXX/storage
      target: /storage
      bind:
        create_host_path: true

```
