### ISSUE TITLE
Run plugins on Server with Curseforge type

### ISSUE THREAD

**Issue by BastianLo** [itzg/docker-minecraft-server#1805]
### Describe the problem

I am running a container with a Curseforge-Modpack. Is it possible to install plugins on the server, like on Spigot?
I tried using the SPIGET_RESOURCES variable. But it doesn't seem to be compatible with TYPE=CURSEFORGE.

### Container definition

```
version: '3.3'
services:
    minecraft-server:
        volumes:
            - './data:/data'
            - './plugins:/plugins'
            - './modpacks:/modpacks'
        environment:
            - TYPE=CURSEFORGE
            - CF_SERVER_MOD=/modpacks/ddss.zip
            - EULA=TRUE
            - USE_MODPACK_START_SCRIPT=false
            - FTB_LEGACYJAVAFIXER=true
            - MEMORY=12G
            - SPIGET_RESOURCES=9089,34315
        ports:
            - '25565:25565'
        container_name: mc
        image: itzg/minecraft-server:java8
```

### Container logs

```
Paste logs here
```
