### ISSUE TITLE
geyser plugin loads but does not work

### ISSUE THREAD

**Issue by asdfzxcvbn** [itzg/docker-minecraft-server#1834]
### Describe the problem

i'm trying to use geyser in the container, but attempting to connect fails. the output supplies:
```
[22:18:11 INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v2.1.0-SNAPSHOT
[22:18:11 INFO]: [Geyser-Spigot] ******************************************
[22:18:11 INFO]: [Geyser-Spigot] 
[22:18:11 INFO]: [Geyser-Spigot] Loading Geyser version 2.1.0-SNAPSHOT (git-master-7171ade)
[22:18:11 INFO]: [Geyser-Spigot] 
[22:18:11 INFO]: [Geyser-Spigot] ******************************************
[22:18:16 INFO]: [Geyser-Spigot] Started Geyser on 0.0.0.0:36281
```
but connecting on that port does not work. i have already allocated the port in my `docker-compose.yml`, but when port scanning, the geyser port is **closed**:
![image](https://user-images.githubusercontent.com/109937991/202881380-caaa14d0-d0a2-4821-95de-72c3a26118f0.png)

### Container definition

```
version: "3"

services:
  server:
    image: itzg/minecraft-server:java17-alpine
    container_name: minecraft
    hostname: minecraft
    ports:
      - 36280:36280   # port for minecraft server
      - 36281:36281   # port for geyser
    volumes:
      - ./server-data:/data
      - ./server-plugins:/plugins
    environment:
      EULA: TRUE
      TYPE: PAPER
      MOTD: [redacted]
      DIFFICULTY: normal
      #WHITELIST: [redacted]
      WHITELIST_FILE: /data/whitelist.json
      ENFORCE_WHITELIST: TRUE
      OPS: [redacted]
      ENABLE_RCON: false
      ENABLE_QUERY: false
      MAX_PLAYERS: 3
      GENERATE_STRUCTURES: true
      SNOOPER_ENABLED: false
      SPAWN_ANIMALS: true
      SPAWN_MONSTERS: true
      SPAWN_NPCS: true
      MODE: survival
      ONLINE_MODE: true
      MEMORY: 2G
      TZ: America/New_York
      ICON: [redacted]
      OVERWRITE_ICON: TRUE
    tty: true
    stdin_open: true
    restart: unless-stopped
```

### Container logs

```
[init] 2022-11-19 22:34:19-05:00 Enabling whitelist functionality
[init] 2022-11-19 22:34:20-05:00 DEBUG: Setting white-list to 'true' in /data/server.properties
[init] 2022-11-19 22:34:20-05:00 DEBUG: Setting enforce-whitelist to 'true' in /data/server.properties
[init] 2022-11-19 22:34:20-05:00 DEBUG: Setting spawn-animals to 'true' in /data/server.properties
[init] 2022-11-19 22:34:20-05:00 DEBUG: Setting spawn-monsters to 'true' in /data/server.properties
[init] 2022-11-19 22:34:20-05:00 DEBUG: Setting spawn-npcs to 'true' in /data/server.properties
[init] 2022-11-19 22:34:20-05:00 DEBUG: Setting generate-structures to 'true' in /data/server.properties
[init] 2022-11-19 22:34:20-05:00 DEBUG: Setting snooper-enabled to 'false' in /data/server.properties
[init] 2022-11-19 22:34:20-05:00 DEBUG: Setting enable-query to 'false' in /data/server.properties
[init] 2022-11-19 22:34:20-05:00 DEBUG: Setting enable-rcon to 'false' in /data/server.properties
[init] 2022-11-19 22:34:20-05:00 DEBUG: Setting rcon.password to '*****' in /data/server.properties
[init] 2022-11-19 22:34:20-05:00 DEBUG: Setting rcon.port to '25575' in /data/server.properties
[init] 2022-11-19 22:34:20-05:00 DEBUG: Setting max-players to '3' in /data/server.properties
[init] 2022-11-19 22:34:20-05:00 DEBUG: Setting online-mode to 'true' in /data/server.properties
[init] 2022-11-19 22:34:21-05:00 DEBUG: Setting motd to [redacted] in /data/server.properties
[init] 2022-11-19 22:34:22-05:00 DEBUG: Setting difficulty to 'normal' in /data/server.properties
[init] 2022-11-19 22:34:22-05:00 Setting mode
[init] 2022-11-19 22:34:22-05:00 DEBUG: Setting gamemode to 'survival' in /data/server.properties
+ versionLessThan 1.7.6
+ mc-image-helper compare-versions 1.19.2 lt 1.7.6
+ return 1
+ opsFile=ops.json
+ whitelistFile=whitelist.json
+ isTrue ''
+ case "${1,,}" in
+ return 1
+ '[' -n '' ']'
+ '[' -n [redacted] ']'
+ process_user_csv ops.json [redacted]
+ local output=ops.json
+ local list=[redacted]
+ local playerDataList
+ [[ ops.json == *\o\p\s* ]]
+ userData='{"uuid": .id, "name": .username, "level": 4}'
+ log 'Updating ops'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2022-11-19 22:34:23-05:00 Updating ops
+ for i in ${list//,/ }
+ '[' -e ops.json ']'
+ grep -q [redacted] ops.json
+ log '[redacted] already present in ops.json, skipping'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2022-11-19 22:34:23-05:00 [redacted] already present in ops.json, skipping
+ continue
++ jq -s .
++ echo ''
+ local 'newUsers=[]'
+ [[ ops.json =~ .*\.txt ]]
+ '[' -e /data/ops.json ']'
++ cat /data/ops.json
+ local 'currentUsers=[
  {
    "uuid": "7ea55aba-eb3f-432a-a8fe-2d142ad36b6d",
    "name": "[redacted]",
    "level": 4,
    "bypassesPlayerLimit": false
  }
]'
+ jq --argjson current '[
  {
    "uuid": "7ea55aba-eb3f-432a-a8fe-2d142ad36b6d",
    "name": "[redacted]",
    "level": 4,
    "bypassesPlayerLimit": false
  }
]' --argjson new '[]' -n '$new + $current | unique_by(.uuid)'
+ isTrue ''
+ case "${1,,}" in
+ return 1
+ '[' -n /data/whitelist.json ']'
+ '[' '!' -e /data/whitelist.json ']'
+ '[' -n '' ']'
+ exec /start-finalExec
+ '[' -n '[icon-url]' ']'
+ '[' '!' -e server-icon.png ']'
+ isTrue ''
+ case "${1,,}" in
+ return 1
+ canUseRollingLogs=true
+ useFallbackJvmFlag=false
+ versionLessThan 1.7
+ mc-image-helper compare-versions 1.19.2 lt 1.7
+ return 1
+ isFamily VANILLA
+ for f in "${@}"
+ [[ SPIGOT == \V\A\N\I\L\L\A ]]
+ return 1
+ isFamily VANILLA
+ for f in "${@}"
+ [[ SPIGOT == \V\A\N\I\L\L\A ]]
+ return 1
+ isType PURPUR
+ for t in "${@}"
+ [[ PAPER == \P\U\R\P\U\R ]]
+ return 1
+ isType PURPUR
+ for t in "${@}"
+ [[ PAPER == \P\U\R\P\U\R ]]
+ return 1
+ versionLessThan 1.18.1
+ mc-image-helper compare-versions 1.19.2 lt 1.18.1
+ return 1
+ false
+ isTrue false
+ case "${1,,}" in
+ return 1
+ versionLessThan 1.14
+ mc-image-helper compare-versions 1.19.2 lt 1.14
+ return 1
+ [[ '' = false ]]
+ expandedDOpts=
+ '[' -n '' ']'
+ isTrue ''
+ case "${1,,}" in
+ return 1
+ isTrue ''
+ case "${1,,}" in
+ return 1
+ isTrue ''
+ case "${1,,}" in
+ return 1
+ isTrue ''
+ case "${1,,}" in
+ return 1
+ isTrue ''
+ case "${1,,}" in
+ return 1
+ [[ -n 2G ]]
+ log 'Setting initial memory to 2G and max to 2G'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2022-11-19 22:34:25-05:00 Setting initial memory to 2G and max to 2G
+ [[ -n 2G ]]
+ JVM_OPTS='-Xms2G '
+ [[ -n 2G ]]
+ JVM_OPTS='-Xmx2G -Xms2G '
+ mcServerRunnerArgs=(--stop-duration "${STOP_DURATION:-60}s" --named-pipe "${CONSOLE_IN_NAMED_PIPE:-/tmp/minecraft-console-in}")
+ [[ -n '' ]]
+ [[ PAPER == \C\U\R\S\E\F\O\R\G\E ]]
+ [[ PAPER == \C\U\R\S\E\F\O\R\G\E ]]
+ [[ paper-1.19.2-278.jar =~ run.sh ]]
+ '[' -f /data/bootstrap.txt ']'
+ log 'Starting the Minecraft server...'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2022-11-19 22:34:25-05:00 Starting the Minecraft server...
+ finalArgs=($JVM_XX_OPTS $JVM_OPTS $expandedDOpts -jar "$SERVER" "$@" $EXTRA_ARGS)
+ isTrue false
+ case "${1,,}" in
+ return 1
+ isTrue false
+ case "${1,,}" in
+ return 1
+ isTrue false
+ case "${1,,}" in
+ return 1
+ exec mc-server-runner --stop-duration 60s --named-pipe /tmp/minecraft-console-in java -Xmx2G -Xms2G -jar paper-1.19.2-278.jar
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.5+8) Host: Linux 5.2.0 (amd64)
Loading libraries, please wait...
2022-11-19 22:34:32,065 ServerMain WARN Advanced terminal features are not available in this environment
[22:34:35 INFO]: Building unoptimized datafixer
[22:34:37 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:34:40 INFO]: Loaded 7 recipes
[22:34:42 INFO]: Starting minecraft server version 1.19.2
[22:34:42 INFO]: Loading properties
[22:34:42 INFO]: This server is running Paper version git-Paper-278 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: b95d4b2)
[22:34:42 INFO]: Server Ping Player Sample Count: 12
[22:34:42 INFO]: Using 4 threads for Netty based IO
[22:34:43 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[22:34:43 INFO]: Default game type: SURVIVAL
[22:34:43 INFO]: Generating keypair
[22:34:43 INFO]: Starting Minecraft server on *:36280
[22:34:43 INFO]: Using epoll channel type
[22:34:43 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[22:34:43 INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[22:34:44 INFO]: [floodgate] Loading floodgate v2.2.0-SNAPSHOT (b73-4f36112)
[22:34:44 INFO]: [floodgate] Took 446ms to boot Floodgate
[22:34:44 INFO]: [Geyser-Spigot] Loading Geyser-Spigot v2.1.0-SNAPSHOT
[22:34:45 INFO]: [Geyser-Spigot] Loading extensions...
[22:34:45 INFO]: [Geyser-Spigot] Loaded 0 extension(s)
[22:34:45 INFO]: Server permissions file permissions.yml is empty, ignoring it
[22:34:45 INFO]: Preparing level "world"
[22:34:46 INFO]: Preparing start region for dimension minecraft:overworld
[22:34:46 INFO]: Time elapsed: 209 ms
[22:34:46 INFO]: Preparing start region for dimension minecraft:the_nether
[22:34:46 INFO]: Time elapsed: 87 ms
[22:34:46 INFO]: Preparing start region for dimension minecraft:the_end
[22:34:46 INFO]: Time elapsed: 77 ms
[22:34:46 INFO]: [floodgate] Enabling floodgate v2.2.0-SNAPSHOT (b73-4f36112)
[22:34:48 INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v2.1.0-SNAPSHOT
[22:34:48 INFO]: [Geyser-Spigot] ******************************************
[22:34:48 INFO]: [Geyser-Spigot] 
[22:34:48 INFO]: [Geyser-Spigot] Loading Geyser version 2.1.0-SNAPSHOT (git-master-7171ade)
[22:34:48 INFO]: [Geyser-Spigot] 
[22:34:48 INFO]: [Geyser-Spigot] ******************************************
[22:34:53 INFO]: [Geyser-Spigot] Started Geyser on 0.0.0.0:36281
[22:34:53 INFO]: [Geyser-Spigot] Done (5.482s)! Run /geyser help for help!
[22:34:53 INFO]: Running delayed init tasks
[22:34:53 INFO]: Done (11.584s)! For help, type "help"
[22:34:53 INFO]: Timings Reset
```

**Comment by itzg** [comment]
I don't have any experience with Geyser but if it's for bridging Bedrock then it needs to be a UDP port mapping and not TCP.

**Comment by asdfzxcvbn** [comment]
huh, that worked. i thought port mappings opened both the tcp and udp port. for anyone who faces this problem in the future, you can base your `docker-compose.yml` off mine (change according to your geyser's `config.yml`):

```
version: "3"

services:
  server:
    image: itzg/minecraft-server:java17-alpine
    container_name: minecraft
    hostname: minecraft
    ports:
      - 36280:36280/tcp
      - 36280:36280/udp
      - 36281:36281/tcp
      - 36281:36281/udp
    volumes:
      - ./server-data:/data
      - ./server-plugins:/plugins
    environment:
      EULA: TRUE
      TYPE: PAPER
      MOTD: example motd
      DIFFICULTY: normal
      WHITELIST_FILE: /data/whitelist.json
      ENFORCE_WHITELIST: TRUE
      OPS: [redacted]
      ENABLE_RCON: false
      ENABLE_QUERY: false
      MAX_PLAYERS: 3
      GENERATE_STRUCTURES: true
      SNOOPER_ENABLED: false
      SPAWN_ANIMALS: true
      SPAWN_MONSTERS: true
      SPAWN_NPCS: true
      MODE: survival
      ONLINE_MODE: true
      MEMORY: 6G
      USE_AIKAR_FLAGS: true
      TZ: America/New_York
      ICON: [redacted]
      OVERWRITE_ICON: TRUE
    tty: true
    stdin_open: true
    restart: unless-stopped
```
