### ISSUE TITLE
Downloading modpack error (Unexpected content type 'application/x-amz-json-1.0') 

### ISSUE THREAD

**Issue by Alexandros-Aristovoulos** [itzg/docker-minecraft-server#1849]
Docker compose yaml used to start a minecraft container with the [Medieval MC Modpack](https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric) :
```
  minecraft:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: https://mediafilez.forgecdn.net/files/4111/179/Medieval+MC+Server+Pack+FABRIC+1.19.2+v12.5.zip
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /home/NAS/Minecraft:/data
```

results in the following error:
```
minecraft_1  | [init] Resolved version given LATEST into 1.19.2 and major version 1.19
minecraft_1  | [init] Resolving type given CURSEFORGE
minecraft_1  | [init] Looking for Feed-The-Beast / CurseForge server modpack.
minecraft_1  | [init] Downloading modpack from https://mediafilez.forgecdn.net/files/4111/179/Medieval+MC+Server+Pack+FABRIC+1.19.2+v12.5.zip...
minecraft_1  | [mc-image-helper] 13:10:20.695 ERROR : 'get' command failed: Unexpected content type 'application/x-amz-json-1.0', expected any of [application/zip]
minecraft_1  | [init] ERROR: failed to download modpack
```

Tested with a couple of different modpacks and they all have the same issue
