### ISSUE TITLE
Having trouble starting a CurseForge server: Vault Hunters

### ISSUE THREAD

**Issue by efunneko** [itzg/docker-minecraft-server#1864]
I have been using this great docker image for a couple of years now with both modded and vanilla servers. It really is a wonderful tool to simplify running a server. Unfortunately, I am having a problem with a new server from CurseForge. 

The server file I am trying to use is Vault+Hunters+3rd+Edition-alpha-0.0.3_Server.zip, which is available at the curseforge site.

I first tried the normal way of launching a CurseForge pack with the type set to CURSEFORGE and the CF_SERVER_MOD env variable pointing to the pack. This decompressed the pack, but came back with:

    vaulthuntersS3_1  | [init] Please make sure you are using the server version of the FTB modpack!

I searched around and found some suggestions to switching to a GENERIC pack. I then used TYPE=FORGE, GENERIC_PACK pointing to the pack and VERSION=1.18.2 (which is the MC version for the pack).

This got way further, but at the end it returned:

    vaulthuntersS3_1  | [init] Finding installed server jar...
    vaulthuntersS3_1  | [init] Unable to derive server jar for Forge

I also saw a suggestion to not run the pack's script. So I tried setting USE_MODPACK_STARTUP_SCRIPT to false. This gave me:

    vaulthuntersS3_1  | [init] ERROR Unable to find forge installer in modpack.
    vaulthuntersS3_1  | [init]       Make sure you downloaded the server files.

I am happy to keep debugging this, but I would love some direction if possible.

Here is my compose file:

    version: "3"

    services:
      vaulthuntersS3:
        image: itzg/minecraft-server:latest
        ports:
          - 33335:25569
        environment:
          EULA: "TRUE"
          SERVER_NAME: "Vault Hunters S3 Server"
          DIFFICULTY: "hard"
          SPAWN_PROTECTION: "0"
          SEED: ""
          MODE: "survival"
          MEMORY: "8G"
          TYPE: "CURSEFORGE"
    #      TYPE: "FORGE"
          VERSION: 1.18.2
    #      USE_MODPACK_START_SCRIPT: "false"
          CF_SERVER_MOD: "Vault+Hunters+3rd+Edition-alpha-0.0.3_Server.zip"
    #      GENERIC_PACK: "/data/Vault+Hunters+3rd+Edition-alpha-0.0.3_Server.zip" 
          ENABLE_ROLLING_LOGS: "true"
        volumes:
          # attach a directory relative to the directory containing this compose file
          - /minecraft/vault-hunters-s3:/data

**Comment by itzg** [comment]
Great troubleshooting! You have tried all the easy things I would have suggested. The last idea I have (other than the CurseForge support overhaul I am very slowly working towards) is to run the modpack server install manually with their instructions and the grab the populated mods directory.

**Comment by efunneko** [comment]
On the Vault Hunters discord, I found a link to this very detailed document about getting the server running on Linux: https://docs.google.com/document/d/1VQVkaUqeUzWRVh1GbOWTLkY8Nu2X1FWcpAS6zO1Lqtk/edit?usp=sharing

It is specific to running in Oracle Cloud, but one of the sections applies to any Linux. Using that guide, I got the server running pretty easily with these few steps:

1. Download the forge installer (https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.2-40.1.61/forge-1.18.2-40.1.61-installer.jar)
2. Run it in the directory where you want the server
3. Download the server pack
4. Unzip it on top of the forge install
5. Run it (./run.sh)

I believe the docker image does #1 and #2, but #4 and #5 must differ.

Anyway, I am good for the moment. I would prefer to run all this in a container, but no rush on a fix just for me.

**Comment by itzg** [comment]
Steps 1-5 is exactly what the GENERIC_PACK does. I'm now guessing they have some files in the server pack that step on the files the container manages. I'll investigate a little bit from your compose file.

**Comment by itzg** [comment]
Ugh, will have to try later

![image](https://user-images.githubusercontent.com/988985/208467364-0d75a7ce-afd6-4d1d-abf5-22c83bc37517.png)

**Comment by itzg** [comment]
This worked for me. Mainly found that forge version needed to be configured to latest since some mods were not happy with the older, recommended version.

```yaml
version: "3"

services:
  vaulthuntersS3:
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: 1.18.2
      # The default, recommended, is too old for some of the mods
      FORGE_VERSION: LATEST
      GENERIC_PACK: "/modpacks/Vault+Hunters+3rd+Edition-update-4_Server.zip"
      # ...following left as before
      SERVER_NAME: "Vault Hunters S3 Server"
      DIFFICULTY: "hard"
      SPAWN_PROTECTION: "0"
      SEED: ""
      MODE: "survival"
      MEMORY: "8G"
      ENABLE_ROLLING_LOGS: "true"
    volumes:
      # set this as needed, just using a managed volume for ease of testing
      - data:/data
      # ...BUT maintain modpacks separately, such as relative to compose file
      - ./modpacks:/modpacks

volumes:
  data: {}
```
