### ISSUE TITLE
Modrinth integration seems to only pick up plugins, but not mods

### ISSUE THREAD

**Issue by terafin** [itzg/docker-minecraft-server#1910]
The modrinth integration seems to only pick up plugins, but not mods.

Here's an docker-compose (ish):

``` yaml
    image: itzg/minecraft-server:latest
    tty: true
    environment:
      EULA: 'TRUE'
      TYPE: PAPER
      MODRINTH_PROJECTS: "easiervillagertrading"
      MODRINTH_ALLOWED_VERSION_TYPE: "release"
```

Given this is a mod, but not a plugin, it seems to no-op and skip downloading/installing it.

_Originally posted by @terafin in https://github.com/itzg/docker-minecraft-server/issues/1884#issuecomment-1383363968_
