### ISSUE TITLE
Unable to update container to :latest via watchtower

### ISSUE THREAD

**Issue by nitobuendia** [itzg/docker-minecraft-server#1921]
### Describe the problem

When running watchtower to update cointainers, I get the following error:

```
Could not do a head request for "itzg/minecraft-server:latest", falling back to regular pull.
Reason: registry responded to head request with "404 Not Found", auth: "not present"
```

This did not happen before. The first occurence started on Jan 21st. It seems related to [this issue](https://github.com/containrrr/watchtower/discussions/1529#discussioncomment-4748053). For example, pihole had the same error but they fixed it. The issue also contains links to instructions on how to solve it.

### Container definition

This is my docker-compose.yaml file:

```yaml
version: "3.3"

services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-server
    restart: "no"
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      - TZ=Asia/Singapore
      - EULA=TRUE
      - VERSION=LATEST
      - MEMORY=4G
      # Change this to select the world you want to run.
      - LEVEL=world
    volumes:
      - "./data:/data"

```

### Container logs

The container is running fine. This is not relevant for this issue.
