### ISSUE TITLE
Java8 image can't reach forge

### ISSUE THREAD

**Issue by sfxworks** [itzg/docker-minecraft-server#1944]
### Describe the problem

For some reason, the java 8 image is staling when trying to download the forge installer, which already exists with force download equal to false. Though I'm unsure if this is the core issue or something else is happening behind the scenes that is the true error. 

Running a server. Did tests on our network and even exec'd into see if I could curl the forge installer manually. That works all fine. Though the installer on this server appears to want to try to install forge, and stalls on this. 

```
-rw-rw-r--  1 1001 minecraft   30 Dec 10  2021  .forge-installed-1.12.2-14.23.5.2857
-rw-rw-r--  1 1001 minecraft 3.4K Dec 10  2021  forge-1.12.2-14.23.5.2857-installer.jar.log
-rw-r--r--  1 1001 minecraft 4.3M Feb  2 09:23  forge-1.12.2-14.23.5.2857-universal.jar
-rw-rw-r--  1 1001 minecraft 4.3M Dec 10  2021  forge-1.12.2-14.23.5.2857.jar
```
We also have it set that it doesn't try to redownload it again in an env var.
`  FORCE_REDOWNLOAD: "false"` 

### Container definition

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: unitedfederationofafkplayers
  namespace: jungle-apple
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: unitedfederationofafkplayers
  serviceName: unitedfederationofafkplayers
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: unitedfederationofafkplayers
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: unitedfederationofafkplayers
        image: docker.io/itzg/minecraft-server:java8
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 1
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: minecraft-tcp
          timeoutSeconds: 1
        name: unitedfederationofafkplayers
        ports:
        - containerPort: 25565
          name: minecraft-udp
          protocol: UDP
        - containerPort: 25565
          name: minecraft-tcp
          protocol: TCP
        - containerPort: 8123
          name: dynmap
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: minecraft-tcp
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "4"
            memory: 15750Mi
          requests:
            cpu: 500m
            memory: 5Gi
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 1000
          runAsUser: 1001
        startupProbe:
          failureThreshold: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: minecraft-tcp
          timeoutSeconds: 1
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        tty: true
        volumeMounts:
        - mountPath: /data
          name: minecraft-volume
          subPath: servers/unitedfederationofafkplayers
        - mountPath: /web
          name: minecraft-volume
          subPath: web
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - chown -R 1001:1000 /data
        image: busybox
        imagePullPolicy: IfNotPresent
        name: permissions
        resources:
          limits:
            cpu: 500m
            memory: 100Mi
          requests:
            cpu: 500m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: minecraft-volume
          subPath: servers/unitedfederationofafkplayers
      nodeSelector:
        node-role.kubernetes.io/game: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: minecraft-volume
        persistentVolumeClaim:
          claimName: ns-pvc
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
---
apiVersion: v1
data:
  ALLOW_NETHER: "false"
  ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
  CONSOLE: <nil>
  DIFFICULTY: easy
  ENABLE_COMMAND_BLOCK: "true"
  ENABLE_QUERY: "true"
  EULA: "true"
  FORCE_GAMEMODE: "false"
  FORCE_REDOWNLOAD: "false"
  FORGEVERSION: 14.23.5.2857
  GENERATE_STRUCTURES: "false"
  GUI: "false"
  HARDCORE: "false"
  ICON: https://mcserverhosting.net/favicon.ico
  INIT_MEMORY: 3500M
  JVM_DD_OPTS: fml.doNotBackup=true fml.queryResult:confirm
  JVM_XX_OPTS: -XX:+UseLargePagesInMetaspace -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions
    -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50
    -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AlwaysPreTouch
    -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
  LEVEL: world
  LEVEL_TYPE: DEFAULT
  MAX_BUILD_HEIGHT: "256"
  MAX_MEMORY: 14250M
  MAX_PLAYERS: "20"
  MAX_TICK_TIME: "20000"
  MAX_WORLD_SIZE: "1000"
  MODE: Survival
  MOTD: Welcome to the place where people join and immediately go AFK.
  ONLINE_MODE: "false"
  OPS: MCRailRoader
  OVERRIDE_SERVER_PROPERTIES: "false"
  PVP: "false"
  REMOVE_OLD_MODS: "false"
  SERVER_NAME: unitedfederationofafkplayers
  SNOOPER_ENABLED: "true"
  SPAWN_ANIMALS: "false"
  SPAWN_NPCS: "false"
  SPAWN_PROTECTION: "0"
  TYPE: FORGE
  USE_LARGE_PAGES: "true"
  VERSION: 1.12.2
  VIEW_DISTANCE: "10"
kind: ConfigMap
metadata:
  name: unitedfederationofafkplayers
  namespace: jungle-apple
```

### Container logs

```
Defaulted container "unitedfederationofafkplayers" out of: unitedfederationofafkplayers, permissions (init)
[init] Running as uid=1001 gid=1000 with /data as 'drwxrwxr-x 20 1001 1000 41 Feb  2 09:23 /data'
[init] Resolved version given 1.12.2 into 1.12.2 and major version 1.12
[init] Resolving type given FORGE
[mc-image-helper] 09:49:59.545 INFO  : Downloading Forge installer 14.23.5.2857 for Minecraft 1.12.2
...
Eventually fails readiness probe
```
