### ISSUE TITLE
Duplicate CF Slugs

### ISSUE THREAD

**Issue by FuzzyFur** [itzg/docker-minecraft-server#1946]
### Describe the problem

When attempting to install this pack (https://www.curseforge.com/minecraft/modpacks/hyperion) from CF, the following error is thrown in docker-compose:

```
hyperion-mc-1  | [mc-image-helper] 04:27:23.387 ERROR : 'install-curseforge' command failed. Version is 1.24.21
hyperion-mc-1  | me.itzg.helpers.errors.GenericException: More than one mod found with slug={}hyperion
```

It seems that even when CF_SLUG is omitted and CF_PAGE_URL is provided, CF_PAGE_URL is reduced to a slug when processed and ignores the explicit destination which one would expect would resolve duplicate slugs.

### Container definition

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8-multiarch
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: AUTO_CURSEFORGE
      #CF_SLUG: hyperion
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/hyperion
      CF_FILE_ID: 3104821
      CF_FILENAME_MATCHER: 1.0.4
      VERSION: 1.12.2
      MEMORY: 4G
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
    networks:
    - intweb
networks:
    intweb:
        external: true
```

### Container logs

```
hyperion-mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 1 1000 1000 4096 Feb  3 04:20 /data'
hyperion-mc-1  | [init] Resolved version given 1.12.2 into 1.12.2 and major version 1.12
hyperion-mc-1  | [init] Resolving type given AUTO_CURSEFORGE
```
