### ISSUE TITLE
Declaring 2 Server Instances in the same `docker-compose.yml` breaks one of the servers

### ISSUE THREAD

**Issue by ApricotFarmer11** [itzg/docker-minecraft-server#1956]
### Describe the problem

When I attempt to run two servers at once in the same docker-compose file, one of the servers' processes gets killed when another starts.

### Container definition

```
version: "3"

services:
  mc1:
    image: itzg/minecraft-server:java17-graalvm-ce
    environment:
      EULA: "TRUE"
      TYPE: "PUFFERFISH"
      VERSION: "1.18.2"
      USE_AIKAR_FLAGS: true
      MEMORY: "1536M"
      SPIGET_RESOURCES: "28140,34315,67788,2237"
    tty: true
    stdin_open: true
    volumes:
      - ./mc1:/data
  proxy:
    image: itzg/bungeecord
    ports:
      - 25565:25577
    volumes:
      - ./proxy:/server
    environment:
      TYPE: "VELOCITY"

  mc2:
    image: itzg/minecraft-server:java17-graalvm-ce
    environment:
      EULA: "TRUE"
      TYPE: "PUFFERFISH"
      VERSION: "1.19.3"
      USE_AIKAR_FLAGS: true
      MEMORY: "1536M"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
     - ./mc2:/data
```

### Container logs

```
server-mc1 | [init] Starting the Minecraft Server...
server-mc2 | 2023-02-06T18:42:02.622Z    WARN    mc-server-runner        Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.      {"exitCode": -1}
server-mc2  | 2023-02-06T18:42:02.632Z    INFO    mc-server-runner        Done
server-mc2 exited with code 255
```
