### ISSUE TITLE
When overriding max memory for Java options original options are still there

### ISSUE THREAD

**Issue by psolomon-services** [itzg/docker-minecraft-server#1962]
### Describe the problem

I am using docker-compose to start up the mincraft server.  I added some Java options to increase max memory.  When I look at htop, the process looks like this:

> java -Xmx1G -Xms1G -Xmx6G -Xms6G -jar minecraft_server.1.19.3.jar

My env settings in my docker-compose file are:

>     environment:
>       JVM_OPTS:  "-Xmx6G -Xms6G"
>       EULA: "TRUE"
>       TZ:   "America/Chicago"

It appears it is using the proper amount of memory (guessing it just takes the last values on the command line).  This is not a bug, per-se, but a request to clean up the command line args.

### Container definition

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    mem_limit: 6G
    mem_reservation: 6G
    cpus: 2
    ports:
      - 25565:25565
    environment:
      JVM_OPTS:  "-Xmx6G -Xms6G"
      EULA: "TRUE"
      TZ:   "America/Chicago"
      #SERVER_PORT=25565
      #RCON_PORT=
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - /opt/minecraft-data:/data
```

### Container logs

```
Paste logs here
```
