### ISSUE TITLE
Latest does not run on Raspberry pi 4 (at the moment)

### ISSUE THREAD

**Issue by jphellemons** [itzg/docker-minecraft-server#1978]
### Describe the problem

> minecraft | exec /usr/local/bin/entrypoint-demoter: exec format error

when using this docker compose file (maybe I messed up)

```
version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server:latest
    container_name: minecraft
    environment:
      EULA: "TRUE"
      GAMEMODE: creative
      DIFFICULTY: easy
      SERVERNAME: "HellCraft"
    ports:
      - 19132:19132/udp
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
```

### Container definition

```
docker-compose up -d
```

### Container logs

```
minecraft | exec /usr/local/bin/entrypoint-demoter: exec format error
```

found this with `docker-compose logs -f bds`
