### ISSUE TITLE
Memory not respected using Aikar flags

### ISSUE THREAD

**Issue by skupfer** [itzg/docker-minecraft-server#1981]
### Describe the problem

It looks like the memory variable is not being respected while using `USE_AIKAR_FLAGS: "true"`. I resorted to this variable since depending on the modpack your scripts are sometimes not able to properly set the variable in the files used by a given modpack. Nothing bad since there is an alternative solution as per above.

Now this is the generated `user_jvm_args.txt` content::

```
# Xmx and Xms set the maximum and minimum RAM usage, respectively.
# They can take any number, followed by an M or a G.
# M means Megabyte, G means Gigabyte.
# For example, to set the maximum to 3GB: -Xmx3G
# To set the minimum to 2.5GB: -Xms2500M

# A good default for a modded server is 4GB.
# Uncomment the next line to set it.
# -Xmx4G
-Xms8G -Xmx8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true
```

Set to 8GB instead of 16. While 8GB might be enough it is not what I thought to have configured. Using a different modpack, i.e. `      CF_SERVER_MOD: "/modpacks/Cryptopolis_server_pack_4.0.zip"` using the same config, the user_jvm_args gets generated but is empty!

```
# Xmx and Xms set the maximum and minimum RAM usage, respectively.
# They can take any number, followed by an M or a G.
# M means Megabyte, G means Gigabyte.
# For example, to set the maximum to 3GB: -Xmx3G
# To set the minimum to 2.5GB: -Xms2500M
# A good default for a modded server is 4GB.
# Uncomment the next line to set it.
# -Xmx4G
``` 

### Container definition

```
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java17
    environment:
      EULA: "true"
      MEMORY: "16G"
      MOTD: "ATM7:Sky server"
      RCON_PASSWORD: "pass"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      TZ: "Europe/Berlin"
      ENABLE_AUTOPAUSE: "true"
      AUTOPAUSE_TIMEOUT_EST: "600"
      MAX_TICK_TIME: "-1"
      OVERRIDE_SERVER_PROPERTIES: "true"
      SNOOPER_ENABLED: "false"
      OVERRIDE_OPS: "true"
      OPS: "1,2"
      TYPE: "CURSEFORGE"
      CF_SERVER_MOD: "/modpacks/server-1.2.2.zip"
      CF_BASE_DIR: "/data"
      VERSION: "1.18.2"
      ENABLE_ROLLING_LOGS: "true"
      USE_AIKAR_FLAGS: "true"
      MAX_PLAYERS: "5"
      GUI: "FALSE"
      LOG_TIMESTAMP: "true"
      LEVEL_TYPE: "skyblockbuilder:skyblock"
      ALLOW_FLIGHT: "true"
    ports:
      - "25568:25565"
    volumes:
      - ./server-data:/data
      - ./modpacks:/modpacks:ro
    stdin_open: true
    tty: true
    restart: unless-stopped
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "1h"
      INITIAL_DELAY: "10m"
      RCON_HOST: mc
      PRE_BACKUP_SCRIPT: |
        echo "Backup from $$RCON_HOST to $$DEST_DIR starting"
      POST_BACKUP_SCRIPT: |
        echo "Backup from $$RCON_HOST to $$DEST_DIR finished"
      PAUSE_IF_NO_PLAYERS: "true"
      PLAYERS_ONLINE_CHECK_INTERVAL: "5m"
      PRUNE_BACKUPS_DAYS: "2"
      RCON_PASSWORD: "pass"
      TZ: "Europe/Berlin"
    volumes:
      # mount the same volume used by server, but read-only
      - ./server-data:/data:ro
      # use a host attached directory so that it in turn can be backed up
      # to external/cloud storage
      - ./mc-backups:/backups
```

### Container logs

```
Paste logs here
```
