### ISSUE TITLE
Modrinth environment variable ignored

### ISSUE THREAD

**Issue by YesterKo** [itzg/docker-minecraft-server#2023]
### Describe the problem

Hi,

I'm currently updating my old minecraft server and found, that CoreProtect is now moved over to Modrinth and can't be downloaded by Spiget anymore. I added coreprotect using `MODRINTH_PROJECTS` variable, but after restarting the container using `docker-compose restart` or `docker-compose up -d`, it seemed to be not loaded, as running `/plugins` didn't return CoreProtect.

I also tried creating a new container with both example Modrinth docker-compose files, but neither downloaded any mods from Modrinth. Interesting to note is that there's no mention of Modrinth in the logs, either. Is the Modrinth script even being run? At first I thought it was because I was using Purpur instead of a modded server, like Fabric. I've tested this all on Ubuntu server 20.04 after running `sudo apt update && sudo apt upgrade && reboot`.

### Container definition

<details>
<summary>
Personal config
</summary>

```yaml
version: "3.8"

services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: "2023-02-23"
    ports:
      - 25565:25565
    environment:
      SERVER_NAME: "Õmmikad"
      MOTD: "Jalad maas 4 life"
      EULA: "TRUE"
      TYPE: "PURPUR"
      VERSION: "1.19.3"
      MODE: "survival"
      MEMORY: "20G"
      LEVEL_TYPE: "DEFAULT"
      ENABLE_RCON: "true"
      RCON_PASSWORD: password
      RCON_PORT: 28016
      SERVER_PORT: 25565
      ENABLE_WHITELIST: "false"
      WHITELIST: "${WHITELISTED_PLAYERS}"
      OPS: "${OPS_PLAYERS}"
      MAX_PLAYERS: 20
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      DIFFICUTLY: "hard"
      PVP: "true"
      LEVEL: "cold"
      TZ: "Europe/Tallinn"
      GUI: "FALSE"
      SPIGET_RESOURCES: "85811"
      # Disabled Harbour: 60088
      MODRINTH_PROJECTS: "coreprotect"
      MODRINTH_ALLOWED_VERSION_TYPE: "release"
      PATCH_DEFINITIONS: "/lapp"
      #MODS_FILE: "/mods.txt"
      REMOVE_OLD_MODS: "true"
      DEBUG: "true"
    restart: unless-stopped
    #user: "${UID}:${GID}"
    volumes:
      - ./data:/data
      - ./lapp:/lapp:ro
      - ./mods.txt:/mods.txt:ro
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
```

</details>

<details>
<summary>
Paper config log
</summary>

```yaml
version: "3"

services:
  mc:
    image: ${IMAGE_TO_TEST:-itzg/minecraft-server}
    environment:
      EULA: "true"
      TYPE: PAPER
      VERSION: 1.19.3
      MODRINTH_PROJECTS: "coreprotect"
      MODRINTH_ALLOWED_VERSION_TYPE: "release"
      DEBUG: "true"
    volumes:
      - ./data:/data
```

</details>

<details>
<summary>
Fabric config
</summary>

```yaml
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      MODRINTH_PROJECTS: fallingtree
      DEBUG: "true"
    volumes:
      - data:/data

volumes:
  data: {}
```

</details>

### Container logs

[Personal config log](https://pastebin.com/36yAmDaE)
[Paper config log](https://pastebin.com/VmEsDran)
[Fabric config log](https://pastebin.com/81zc6d4f)
