### ISSUE TITLE
Cannot find forge version in older FORGE_INSTALLER

### ISSUE THREAD

**Issue by kevinkjt2000** [itzg/docker-minecraft-server#2031]
### Describe the problem

Relates to https://github.com/itzg/mc-image-helper/issues/174

I also tried specifying FORGE_VERSION=10.13.4.1614 and FORGEVERSION=10.13.4.1614, but it seems the helper utility is invoked regardless.

### Container definition

```
  gtnh:
    container_name: gtnh
    image: itzg/minecraft-server:java19@sha256:3f4abaf7e50ae695943b0dda962ce244fe76f7e5954415d12ef1eabb10e71046
    environment:
      ALLOW_FLIGHT: "TRUE"
      CF_BASE_DIR: "/data"
      COPY_CONFIG_DEST: "/data"
      ENFORCE_WHITELIST: "TRUE"
      EULA: "TRUE"
      EXTRA_ARGS: "@/modpacks/java9args.txt"
      FORGE_INSTALLER: "/modpacks/forge-1.7.10-10.13.4.1614-1.7.10-installer.jar"
      FORGE_VERSION: "10.13.4.1614"
      FORGEVERSION: "10.13.4.1614"
      GENERIC_PACK: "/modpacks/GT_New_Horizons_2.3.1_Server_Java_17-19.zip"
      JVM_XX_OPTS: "@/modpacks/brucethemoose-args.txt"
      LEVEL_TYPE: "rwg"
      LEVEL: "world"
      MEMORY: "6G"
      MOTD: "2.3.1 has landed"
      OVERRIDE_SERVER_PROPERTIES: "true"
      REMOVE_OLD_MODS_INCLUDE: "lwjgl3ify-1.3.0.jar"
      REMOVE_OLD_MODS: "true"
      SERVER_NAME: "Crazy Minecrafters"
      SPAWN_PROTECTION: "0"
      SYNC_SKIP_NEWER_IN_DESTINATION: "false"
      TYPE: "FORGE"
      USE_AIKAR_FLAGS: "false"
      USE_MODPACK_START_SCRIPT: "false"
      VIEW_DISTANCE: "16"
    ports:
      - "25565:25565"
      - "55164:25565"
    volumes:
      - "./data:/data"
      - "./modpacks:/modpacks"
      - "./mods:/mods"
      - "./root-overlay:/config"
    tty: true
    stdin_open: true
    restart: "unless-stopped"
```

I can provide some of the other files if necessary, but I believe they are unrelated since this forge version parsing happens relatively early in the startup.

### Container logs

```
gtnh  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 1 1000 1002 1354 Mar 25 14:56 /data'
gtnh  | [init] Resolved version given LATEST into 1.19.4 and major version 1.19
gtnh  | [init] Resolving type given FORGE
gtnh  | [mc-image-helper] 15:03:24.262 ERROR : 'install-forge' command failed. Version is 1.25.16
gtnh  | me.itzg.helpers.errors.GenericException: Failed to locate version from provided installer file
gtnh  |         at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:88)
gtnh  |         at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:84)
gtnh  |         at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:16)
gtnh  |         at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
gtnh  |         at picocli.CommandLine.access$1500(CommandLine.java:148)
gtnh  |         at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
gtnh  |         at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
gtnh  |         at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
gtnh  |         at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
gtnh  |         at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
gtnh  |         at picocli.CommandLine.execute(CommandLine.java:2170)
gtnh  |         at me.itzg.helpers.McImageHelper.main(McImageHelper.java:132)
gtnh  | [init] ERROR failed to install Forge given installer /modpacks/forge-1.7.10-10.13.4.1614-1.7.10-installer.jar
gtnh exited with code 0
```
