### ISSUE TITLE
Can't find jar file on StoneBlock3

### ISSUE THREAD

**Issue by RussiaPlayer** [itzg/docker-minecraft-server#2033]
### Describe the problem

The minecraft-data folder:
```
config
defaultconfigs
eula.txt
ftb-installer
jre
kubejs
libraries
log4jfix
minecraft_server.1.18.2.jar
mods
resourcepacks
run.bat
run.sh
user_jvm_args.txt
version.json
```

### Container definition

```
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25566:25566
    environment:
      EULA: "TRUE"
      TYPE: "FTBA"
      FTB_MODPACK_ID: "100"
      MEMORY: 4G
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
```

### Container logs

```
[init] ERROR unable to locate the installed FTB server jar
```
