### ISSUE TITLE
[SpigotLibraryLoader] failing cause it can't access repo.maven.apache.org:443

### ISSUE THREAD

**Issue by Audition-CSBlock** [itzg/docker-minecraft-server#2038]
[Paper/issues/9055](https://github.com/PaperMC/Paper/issues/9055) 

I've opened an issue on the paper github but they say it has to do with docker, which i already thought, but the issue template here said "after the [init] prefixed logs" to not report here. This does happen after the [init] but, it still has to do with the container.

Basically, [SpigotLibraryLoader] tries to access repo.maven.apache.org:443. The host has access to it via curl, but inside the container it won't work. I've tried https://www.google.com/ to see if port 443 is blocked, but google does work. I have no clue anymore.

I'll share my docker-compose.yml here:

```yaml
services:
  main:
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "TRUE"
      USE_AIKAR_FLAGS: "TRUE"
      MAX_MEMORY: "2G"
      EXEC_DIRECTLY: "TRUE"
      TYPE: "PAPER"
    ports:
      - 25565:25565
    volumes:
      - /...:/data
      - /etc/localtime:/etc/localtime:ro

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.60.0/24
          gateway: 172.21.60.1
```

**Comment by itzg** [comment]
I'm sorry but this is not caused by my image. As they mentioned, this is a docker issue with your network setup.

**Comment by Audition-CSBlock** [comment]
I'll try changing some network settings and i'll update what works.

**Comment by camalot** [comment]
@Audition-CSBlock 

why are you configuring the ipam? where did you get the values from for that section? by default docker will handle this. you can override it, but I am going to say that if you don't know what it is doing, you should use the default in that case.

You could probably get away with just removing the entire 

``` yaml
ipam:
  driver: default
  config: 
  - subnet: 172.21.60.0/24
  - gateway: 172.21.60.1
```

**Comment by Audition-CSBlock** [comment]
Thank you for the help but that section needs to stay. I've tried without to see if that caused the problem, but it gave the same result.

**Comment by camalot** [comment]
I guess I am unsure of your network config for the host that you are running it on. that would really determine how you configure that.

**Comment by Audition-CSBlock** [comment]
Hi, I just wanted to share what I found as this issue has been active for a long time and I finally fixed it:
I'm behind wireguard which sets its MTU to 1420, Docker defaults to 1500, so the SSL packets get broken. I always thought it was dns, but I tried a lot of dns fixes and the problem still persisted only on SSL traffic. So if anyone else has this problem, here's how to fix it:

Add the following to /etc/docker/daemon.json
```yaml
{
    "mtu": 1360
}
```

If you have my configuration, it's a little different because /etc/docker/daemon.json only accounts for the docker networks host,bridge (afaik), so if you have this section:
```yaml
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
          gateway: 172.0.0.1
```

Do it like this:
```yaml
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1360
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
          gateway: 172.0.0.1
```

of course you don't have to use 1360, i've tried 1420 and it works so far. but at least try and stay below your wireguard mtu.
