### ISSUE TITLE
TYPE=AUTO_CURSEFORGE not working in latest docker image

### ISSUE THREAD

**Issue by lnieuwenhuis** [itzg/docker-minecraft-server#2068]
### Describe the problem

When I issue the following command:

docker run -e EULA=TRUE -e VERSION=1.16.5 -e TYPE=AUTO_CURSEFORGE -e CF_PAGE_URL=https://www.curseforge.com/minecraft/modpacks/the-pixelmon-modpack -e CF_API_KEY='**************************************************************************' -e MEMORY=4G -e MAX_MEMORY=12G -p 25567:25565 --name Pixelmon itzg/minecraft-server:java8-multiarch

I get the following response, even though I have the latest docker image.

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Sep  2  2022 /data'
[init] Resolved version given 1.16.5 into 1.16.5 and major version 1.16
[init] Resolving type given AUTO_CURSEFORGE
[init] Invalid type: 'AUTO_CURSEFORGE'
[init] Must be: VANILLA, FORGE, BUKKIT, SPIGOT, PAPER, FTBA (multiarch-only),
[init]          CURSEFORGE, SPONGEVANILLA, PURPUR, CUSTOM,
[init]          MAGMA, MOHIST, CATSERVER, LOLISERVER, AIRPLANE, PUFFERFISH, CANYON, LIMBO, CRUCIBLE

Any idea what's causing AUTO_CURSEFORGE to not work?

### Container definition

```
docker run -e EULA=TRUE -e VERSION=1.16.5 -e TYPE=AUTO_CURSEFORGE -e CF_PAGE_URL=https://www.curseforge.com/minecraft/modpacks/the-pixelmon-modpack -e CF_API_KEY='**************************************************************************' -e MEMORY=4G -e MAX_MEMORY=12G -p 25567:25565 --name Pixelmon itzg/minecraft-server:java8-multiarch
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Sep  2  2022 /data'
[init] Resolved version given 1.16.5 into 1.16.5 and major version 1.16
[init] Resolving type given AUTO_CURSEFORGE
[init] Invalid type: 'AUTO_CURSEFORGE'
[init] Must be: VANILLA, FORGE, BUKKIT, SPIGOT, PAPER, FTBA (multiarch-only),
[init]          CURSEFORGE, SPONGEVANILLA, PURPUR, CUSTOM,
[init]          MAGMA, MOHIST, CATSERVER, LOLISERVER, AIRPLANE, PUFFERFISH, CANYON, LIMBO, CRUCIBLE
```

**Comment by itzg** [comment]
I'm not seeing the same behavior. I know you said you have the latest, but can you pull again with

```
docker pull itzg/minecraft-server:java8-multiarch
```

You can always confirm what image you're using with

```
docker image inspect -f '{{.Config.Labels}}' itzg/minecraft-server:java8-multiarch
```

**Comment by drakosoldier298** [comment]
similiar issue with a 1.18.2 pack vault hunters 3rd edition. The problem is that v1 of the api for curseforge has been shutdown

**Comment by itzg** [comment]
@drakosoldier298 I am unable to recreate a problem with vault hunters 3rd edition. This started up fine:

```yaml
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/vault-hunters-1-18-2/files/4516811
      MEMORY: 4G
    volumes:
      - mc-data:/data

volumes:
  mc-data: {}
```

What do you mean about "v1 of the api for curseforge has been shutdown"?
