### ISSUE TITLE
Cannot start Modpack with AUTO_CURSEFORGE

### ISSUE THREAD

**Issue by PrivatePasta** [itzg/docker-minecraft-server#2085]
### Describe the problem

I'm trying to run the [Fantasy Minecraft](https://www.curseforge.com/minecraft/modpacks/fantasy-minecraft-fabric) Modpack with AUTO_CURSEFORGE, getting a lot of errors, not being able to start the server. For reference, I've tried to run the server directly without docker and it works fine. Also, I tried it with GENERIC_PACK and it doesn't work either.

The image I used in docker was first latest, then tried with java19 just to make sure that wasn't the issue. Same problem.

### Container definition

```
  minecraft:
    image: itzg/minecraft-server:java19
    container_name: minecraft
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.19.2"
      OVERRIDE_SERVER_PROPERTIES: "true"
      ENABLE_AUTOPAUSE: "true"
      RCON_PASSWORD: "[password]"
      TYPE: "AUTO_CURSEFORGE"
      CF_API_KEY: '[apkey]'
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/fantasy-minecraft-fabric"
      CF_BASE_DIR: "/mods"
    volumes:
      - /home/ubuntu/docker/config/minecraft/data:/data
      - /home/ubuntu/docker/config/minecraft/mods:/mods
    tty: true
    stdin_open: true
    restart: unless-stopped
```

### Container logs

[fantasyMC.log](https://github.com/itzg/docker-minecraft-server/files/11242578/fantasyMC.log)
