### ISSUE TITLE
MODRINTH_PROJECTS option skips fabric-api 

### ISSUE THREAD

**Issue by anaxios** [itzg/docker-minecraft-server#2091]
### Describe the problem

The container is skipping downloading some of the mods from modrinth, for example: fabric-api. 

I tried starting a new container with empty volume and have the same problem.
I tried appending a specific version but same problem.

I checked here: `https://api.modrinth.com/v2/project/P7dR8mSH/version?loaders=["fabric"]&game_versions=["1.19.4"]` and the proper versions appear, thinking the mod dev miscategorized something.

### Container definition

```
    environment:
      TYPE: "FABRIC"
      FABRIC_LOADER_VERSION: 0.14.19
      FABRIC_LAUNCHER_VERSION: 0.11.2
      VERSION: "1.19.4"
      OVERRIDE_SERVER_PROPERTIES: "true"
      MODRINTH_PROJECTS: "fabricproxy-lite,geyser,fabric-api,carpet,lithium,sodium,krypton,starlight,ledger,fabric-language-kotlin,ferrite-core,memoryleakfix,luckperms,leukocyte"
      MODRINTH_DOWNLOAD_OPTIONAL_DEPENDENCIES: "true"
      MODRINTH_ALLOWED_VERSION_TYPE: "release"
```

### Container logs

```
[init] Resolved version given 1.19.4 into 1.19.4 and major version 1.19
[init] Resolving type given FABRIC
[mc-image-helper] 07:58:25.167 INFO  : Downloading FabricProxy-Lite-2.5.0.jar
[mc-image-helper] 07:58:25.677 INFO  : Downloading fabric-carpet-1.19.4-1.4.101+v230319.jar
[mc-image-helper] 07:58:25.810 INFO  : Downloading lithium-fabric-mc1.19.4-0.11.1.jar
[mc-image-helper] 07:58:26.046 INFO  : Downloading sodium-fabric-mc1.19.4-0.4.10+build.24.jar
[mc-image-helper] 07:58:26.146 INFO  : Downloading krypton-0.2.2.jar
[mc-image-helper] 07:58:26.300 INFO  : Downloading starlight-1.1.1+fabric.ae22326.jar
[mc-image-helper] 07:58:26.565 INFO  : Downloading ledger-1.2.7.jar
[mc-image-helper] 07:58:26.651 INFO  : Downloading fabric-language-kotlin-1.9.3+kotlin.1.8.20.jar
[mc-image-helper] 07:58:26.851 INFO  : Downloading ferritecore-5.2.0-fabric.jar
[mc-image-helper] 07:58:26.978 INFO  : Downloading memoryleakfix-fabric-1.17+-1.0.0.jar
[mc-image-helper] 07:58:27.109 INFO  : Downloading LuckPerms-Fabric-5.4.66.jar
[mc-image-helper] 07:58:27.252 INFO  : Downloading leukocyte-0.3.5+1.19.4-rc2.jar
```
