### ISSUE TITLE
MODRINTH_PROJECTS doesn't work without MODRINTH_PROJECT being present

### ISSUE THREAD

**Issue by douglasparker** [itzg/docker-minecraft-server#2139]
### Describe the problem

I am not currently using a modpack, and `MODRINTH_PROJECTS` will not work without `MODRINTH_PROJECT` being present.

Using a fake slug does not fix this issue.

### Container definition

```yaml
services:
    minecraft:
      image: itzg/minecraft-server:java17
      container_name: minecraft
      environment:
        EULA: "TRUE"
        VERSION: "1.19.4"
        TYPE: "MODRINTH"
        MODRINTH_LOADER: "fabric"
        MODRINTH_DEFAULT_VERSION_TYPE: "release"
        # litematica was manually added due to need. Will be added to Modrinth in the near future.
        MODRINTH_PROJECT: "fake-slug"
        MODRINTH_PROJECTS: "-bedrock-plus,advancementinfo,adventurez,amecs,anti-xray,antighost,appleskin,areas,artifacts,auth-me,axolotl-buckets,bad-wither-no-cookie,bedrockify,bedrockwaters,better-enchanted-books,better-stats,betterend:beta,betterf3,betternether:beta,boat-item-view,borderless-mining,bosses-of-mass-destruction:beta,capes,carpet,carry-on,cem,cherished-worlds,chunk-loaders,cit-resewn,client-tweaks,comforts,continuity:beta,cosmetic-armor,crafting-tweaks,ctrl-q,cyberanner-ironchest,dark-waters,dcwa,dismount-entity,double-doors,dripsounds-fabric:beta,dynamic-fps,dynamiccrosshair,dynamiccrosshaircompat,edf-remastered,enchanting-infuser,entityculling,entitytexturefeatures,every-compat,fabric-api,fabric-seasons,fabricskyboxes,fabricskyboxes-interop,fabrishot,fallingleaves,fantasy-furniture,farmers-delight-fabric,fastanim,fastload,ferrite-core,feytweaks,fwaystones,gildedarmor,goated,grass-seeds,highlight,htm,immediatelyfast,indium,inventory-profiles-next,invmove:beta,iris,item-highlighter,jei:beta,just-enough-resources-jer:beta,krypton,lambdynamiclights,language-reload,lithium,log-cleaner,lostfeatures:beta,macos-input-fixes,make_bubbles_pop,mavm,memoryleakfix,midnightcontrols,mine-treasure,minecraftcapes,mixintrace,mob-captains,modmenu,mooshroom-tweaks,more-babies,morechathistory,moreculling,mouse-tweaks,move-boats,move-minecarts,netherportalfix,no-chat-reports,no-resource-pack-warnings,not-enough-animations,noxesium,optigui:beta,paladins-furniture,patchouli,presence-footsteps,random-village-names,reeses-sodium-options,skeleton-horse-spawn,smoothboot-fabric,sodium,sodium-extra,sodium-shadowy-path-blocks,sound-physics-remastered:beta,starlight,stendhal,superflat-world-no-slimes,supplementaries,terralith,tooltipfix,towns-and-towers,travelersbackpack,tree-harvester,universal-enchants,useless-reptile:beta,village-spawn-point,villager-names-serilum,visual-overhaul,visuality:beta,wavey-capes,weaker-spiderwebs,windchimes,yigd,yosbr,yungs-better-desert-temples,yungs-better-dungeons,yungs-better-mineshafts,yungs-better-nether-fortresses,yungs-better-ocean-monuments,yungs-better-strongholds,yungs-better-witch-huts,yungs-bridges,yungs-extras,zombie-horse-spawn,zoomify"
        MODRINTH_DOWNLOAD_OPTIONAL_DEPENDENCIES: true
        MEMORY: "12G"
      volumes:
        - ./minecraft:/data
      ports:
        - 0.0.0.0:25565:25565
      stdin_open: true # docker run -i
      tty: true # docker run -t
      restart: unless-stopped
```

### Container logs

**MODRINTH_PROJECT: missing**
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 May 20 22:43 /data'
[init] Resolved version given 1.19.4 into 1.19.4 and major version 1.19
[init] Resolving type given MODRINTH
[init] ERROR: MODRINTH_PROJECT is required to be set
```

**MODRINTH_PROJECT: Fake slug**
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 May 20 22:43 /data'
[init] Resolved version given 1.19.4 into 1.19.4 and major version 1.19
[init] Resolving type given MODRINTH
[mc-image-helper] 22:45:14.921 ERROR : Invalid parameter provided for 'install-modrinth-modpack' command: Unable to locate requested project given ProjectRef(idOrSlug=fake-slug, versionType=null, versionId=null, versionName=null)
[init] ERROR failed to install Modrinth modpack
```
