### ISSUE TITLE
Pufferfish Modrinth Downloader

### ISSUE THREAD

**Issue by Rattlyy** [itzg/docker-minecraft-server#2187]
### Describe the problem

If you try to download plugins from Modrinth while using Pufferfish you will get an error.

### Container definition

```
creative:
    container_name: "creative"
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: "unless-stopped"

    volumes:
      - "./creative:/data"

    environment:
      EULA: "TRUE"
      TYPE: "PUFFERFISH"
      FORCE_REDOWNLOAD: true
      USE_FLARE_FLAGS: true
      USE_AIKAR_FLAGS: true
      SERVER_NAME: "creative"
      VERSION: "1.19.4"
      MEMORY: "10G"
      MODRINTH_PROJECTS: "luckperms,chunky"
      SPIGET_RESOURCES: "13449,390"

```

### Container logs

```
experimental  | Invalid value for option '--loader': expected one of [fabric, quilt, forge, bukkit, spigot, paper, purpur] (case-insensitive) but was 'pufferfish'
experimental  | Usage: mc-image-helper modrinth [--download-optional-dependencies]
experimental  |                                 [--allowed-version-type=<defaultVersionType>]
experimental  |                                 --game-version=<gameVersion> --loader=<loader>
experimental  |                                 [--output-directory=DIR] [--projects=id|slug
experimental  |                                 [\s*,\s*id|slug...]]...
experimental  | Automates downloading of modrinth resources
experimental  |       --allowed-version-type=<defaultVersionType>
experimental  |                           Valid values: release, beta, alpha
experimental  |       --download-optional-dependencies
experimental  |
experimental  |       --game-version=<gameVersion>
experimental  |                           Applicable Minecraft version
experimental  |       --loader=<loader>   Valid values: fabric, quilt, forge, bukkit, spigot,
experimental  |                             paper, purpur
experimental  |       --output-directory=DIR
experimental  |
experimental  |       --projects=id|slug[\s*,\s*id|slug...]
experimental  |                           Project ID or Slug
experimental exited with code 0
```
