### ISSUE TITLE
Unable to access ./fabric-server-mc.1.20-loader.0.14.21-launcher.0.11.2.jar

### ISSUE THREAD

**Issue by trbntwo** [itzg/docker-minecraft-server#2221]
### Describe the problem

The jarfile isnt downloaded or is downloaded but not saved into the `/data` directory, so the server can't start because it is unable to use the missing jarfile

### Container definition

```
version: "3"

services:

  Minecraft:
    image: itzg/minecraft-server:latest
    container_name: MC-TT
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "10002:25565"
    # BlueMap benötigt weiteren Port
    volumes:
      - ./Server:/data
    environment:
    # Generelles
      TZ: "Europe/Berlin"
      EULA: "TRUE"
    # Version
      VERSION: "1.20"
      TYPE: "FABRIC"
    # JVM-Einstellungen
      INIT_MEMORY: "1G"
      MAX_MEMORY: "4G"
      USE_AIKAR_FLAGS: "TRUE"
      GUI: "FALSE"
    # Spieleinstellungen
      MODE: "survival"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "25"
      NETWORK_COMPRESSION_THRESHOLD: "256"
      SIMULATION_DISTANCE: "8"
      VIEW_DISTANCE: "16"
      SPAWN_PROTECTION: "0"
      SNOOPER_ENABLED: "false"
      SEED: "-1964302197403176142"
    # Management
      ENABLE_RCON: "true"
      RCON_PORT: "10102"
      RCON_PASSWORD: REDACTED
    # Branding
      SERVER_NAME: "JP: Trails & Tales"
      ICON: "/data/branding/Favicon-512x.png"
      OVERRIDE_ICON: "TRUE"
      MOTD: "Trails & Tales Server der Janos Pizzeria"
    # Spieler & Berechtigungen
      ENABLE_WHITELIST: "true"
      ENFORCE_WHITELIST: "true"
      WHITELIST: "trbntwo"
      OPS: "trbntwo"
    # Commands bei Serverstart
      RCON_CMDS_STARTUP: |- 
          gamerule playersSleepingPercentage 1
          gamerule doFireTick false
    # Zusaetzliche Inhalte
      MODRINTH_PROJECTS: "fabric-api,cloth-config,yacl,lithium,ferrite-core,starlight,krypton,memoryleakfix,smoothboot-fabric,log-cleaner,invview,convenient-mobgriefing,owo-lib,deathlog,debugify"
      MODRINTH_DOWNLOAD_OPTIONAL_DEPENDENCIES: "true"
      MODRINTH_ALLOWED_VERSION_TYPE: "release"
      VANILLATWEAKS_FILE: "/data/vanilla-tweaks/vt-datapacks.json,/data/vanilla-tweaks/vt-craftingtweaks.json"
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x. 1 1000 1000 420 Jun 15 14:11 /data'
[init] Starting RCON commands
[init] Rcon cmds functionality enabled
[init] Resolved version given 1.20 into 1.20 and major version 1.20
[init] Resolving type given FABRIC
[mc-image-helper] 14:12:06.366 INFO  : Downloading Vanilla Tweaks datapacks for definition file /data/vanilla-tweaks/vt-datapacks.json
[mc-image-helper] 14:12:06.413 INFO  : Downloading Vanilla Tweaks craftingtweaks for definition file /data/vanilla-tweaks/vt-craftingtweaks.json
[mc-image-helper] 14:12:08.169 INFO  : Downloading fabric-api-0.83.0+1.20.jar
[mc-image-helper] 14:12:08.598 INFO  : Downloading cloth-config-11.0.99-fabric.jar
[mc-image-helper] 14:12:09.011 INFO  : Downloading yet-another-config-lib-fabric-3.0.1+1.20.jar
[mc-image-helper] 14:12:09.467 INFO  : Downloading lithium-fabric-mc1.20-0.11.2.jar
[mc-image-helper] 14:12:09.919 INFO  : Downloading ferritecore-6.0.0-fabric.jar
[mc-image-helper] 14:12:10.345 INFO  : Downloading starlight-1.1.2+fabric.dbc156f.jar
[mc-image-helper] 14:12:10.786 INFO  : Downloading krypton-0.2.3.jar
[mc-image-helper] 14:12:11.187 INFO  : Downloading memoryleakfix-fabric-1.17+-1.1.1.jar
[mc-image-helper] 14:12:12.028 INFO  : Downloading logcleaner-1.0.0.jar
[mc-image-helper] 14:12:12.487 INFO  : Downloading InvView-1.4.11-1.20+.jar
[mc-image-helper] 14:12:12.934 INFO  : Downloading convenient-mobgriefing-2.1.0.jar
[mc-image-helper] 14:12:13.187 INFO  : Downloading fabric-api-0.83.0+1.19.4.jar
[mc-image-helper] 14:12:13.983 INFO  : Downloading deathlog-0.3.2+1.20.jar
[mc-image-helper] 14:12:14.923 INFO  : Downloading Debugify-1.20+1.1.jar
[init] Enabling whitelist functionality
[init] Setting mode
[init] Updating ops
[init] trbntwo already present in ops.json, skipping
[init] Updating whitelist
[init] trbntwo already present in whitelist.json, skipping
[init] Using server icon from /data/branding/Favicon-512x.png...
[init] Converting image to 64x64 PNG...
[init] Using Aikar's flags
[init] Setting initial memory to 1G and max to 4G
[init] Starting the Minecraft server...
Error: Unable to access jarfile ./fabric-server-mc.1.20-loader.0.14.21-launcher.0.11.2.jar
2023-06-15T14:12:18.992+0200	WARN	mc-server-runner	Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.	{"exitCode": 1}
2023-06-15T14:12:18.992+0200	INFO	mc-server-runner	Done
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x. 1 1000 1000 420 Jun 15 14:12 /data'
```
