### ISSUE TITLE
1.20 Spigot health check is stuck at “starting”

### ISSUE THREAD

**Issue by Aragur** [itzg/docker-minecraft-server#2224]
### Describe the problem

Using the 1.20 Spigot server, the health check is stuck at “starting” but the server is in a playable state.
This prevents, for example, Traefik to adding a router for this server as Traefik waits until the container is healthy.

### Container definition

```yaml
version: '3.7'

networks:
  proxy:
    external: true

services:
  minecraft-vanilla:
    image: itzg/minecraft-server
    container_name: minecraft-vanilla
    restart: always
    networks:
      - proxy
    ports:
      - 25565:25565
    expose:
      - 8100
    environment:
        TZ: 'Europe/Berlin'
        MEMORY: 6G
        EULA: "true"
        TYPE: SPIGOT
        VERSION: "1.20"
    volumes:
      - ./data:/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.minecraft-map.rule=Host(`map.example.com`)
      - traefik.http.routers.minecraft-map.entrypoints=https
      - traefik.http.routers.minecraft-map.tls.certresolver=default
      - traefik.http.routers.minecraft-map.service=minecraft-map
      - traefik.http.services.minecraft-map.loadbalancer.server.port=8100
```

### Container logs

Not required as it starts successfully
