### ISSUE TITLE
Healthcheck fails because of `--use-server-list-ping`

### ISSUE THREAD

**Issue by kevoh1516** [itzg/docker-minecraft-server#2236]
### Describe the problem

I was trying to debug why the healthcheck was failing and I fixed it by removing `"${MC_HEALTH_EXTRA_ARGS[@]}"` from the `mc-health` script. I printed the args out and it only contained `--use-server-list-ping`. No idea what that is or why it was causing it to fail.

### Container definition

```
services:
  nomi:
    image: 'itzg/minecraft-server:java8-multiarch'
    volumes:
      - ./data:/data
    environment:
      - CF_SERVER_MOD=nomi-ceu-1.6.1-rc-server.zip
      - TYPE=CURSEFORGE
      - EULA=TRUE
    ports:
      - 25565:25565
```
