### ISSUE TITLE
Problems with running the new all-the-mods8 version

### ISSUE THREAD

**Issue by Aventix** [itzg/docker-minecraft-server#2255]
### Describe the problem

Hey, first i wanna thank you for this amazing docker project!

I have following problems, if i install the normal all-the-mods-8 server everything seems fine, but when i try to join, it gives me following errors with the "Hexerei-0.3.2" mod. 

<img width="940" alt="image" src="https://github.com/itzg/docker-minecraft-server/assets/46361039/2a6d32f0-bc4c-4bd1-84ab-e7d475c54d3e">

It seems to be a bug, but maybe im just stupid.

### Container definition

```
version: "3"

services:
  allthemods:
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: "13G"
      TYPE: "AUTO_CURSEFORGE"
      CF_API_KEY: "API_KEY"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-8"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./server-data:/data
```
