### ISSUE TITLE
Server crashes after latest update

### ISSUE THREAD

**Issue by SteffoSpieler** [itzg/docker-minecraft-server#2265]
### Describe the problem

Watchtower just updated the image to the latest version and now the server doesnt start anymore. I've attached the logs.

### Container definition

```
version: "3.8"

services:
  mc:
    container_name: mc-<censored>
    image: itzg/minecraft-server
    ports:
      - 30072:25565
      - 30074:30074/udp
      - 9160:9160/tcp
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: 1.18.2
      FORGE_VERSION: 40.1.84
      MEMORY: 4G
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data

volumes:
  data:
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 9 1000 1000 4096 Jul  1 10:43 /data'
[init] Resolving type given FORGE
[mc-image-helper] 21:20:48.476 WARN  : [903ddb3b-1, L:/192.168.160.2:37512 - R:files.minecraftforge.net/51.79.83.165:443] The connection observed an error
io.netty.handler.timeout.ReadTimeoutException: null
[mc-image-helper] 21:20:48.482 ERROR : 'install-forge' command failed. Version is 1.32.5
io.netty.handler.timeout.ReadTimeoutException: null
[init] ERROR failed to install Forge
```
