### ISSUE TITLE
Server fails to start, but container continues to run

### ISSUE THREAD

**Issue by camalot** [itzg/docker-minecraft-server#2287]
### Describe the problem

Startup fails, but container does not exit. HealthCheck is not reporting `Healthy` or `Unhealthy`, container just reports as running.

![image](https://github.com/itzg/docker-minecraft-server/assets/171452/9120f790-cf64-44f9-8c45-4c9a403a2e37)

I would think that because the server failed to start that the container would report unhealthy, and exit.

### Container definition

```
version: '3.7'
networks:
  internal:
    driver: bridge
services:
  minecraft-curseforge:
    hostname: minecraft-curseforge
    container_name: minecraft-curseforge
    image: itzg/minecraft-server:java17-alpine
    networks:
    - internal
    ports: 
    - 25565:25565
    - 25575:25575
    restart: unless-stopped
    dns:
    - 192.168.2.7
    - 192.168.2.4
    - 192.168.2.1
    - 192.168.2.8
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    dns_search: bit13.local

    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 16g
        reservations:
          memory: 12g
    environment:
    
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      CF_SLUG: all-the-mods-8
      VERSION: 1.19.2
      FORGEVERSION: 43.2.14

      ICON: "https://i.imgur.com/RV1PBPD.png"
      OVERRIDE_ICON: 'TRUE'

      OPS_FILE: 'http://andeddu.bit13.local:10070/tacobot/minecraft/ops.json'
      WHITELIST_FILE: 'http://andeddu.bit13.local:10070/tacobot/minecraft/whitelist.json'
      ENFORCE_WHITELIST: 'true'
      OVERRIDE_WHITELIST: 'true'

      REMOVE_OLD_MODS: 'false'

      MEMORY: 12G
      
      ENABLE_RCON: 'true'
      RCON_PASSWORD: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      BROADCAST_RCON_TO_OPS: 'true'

      ALLOW_NETHER: 'true'
      ANNOUNCE_PLAYER_ACHIEVEMENTS: 'true'
      STOP_SERVER_ANNOUNCE_DELAY: 60
      STOP_DURATION: 60
      
      MOTD: The §l§6TACO§r §cMinecraft§r Server
      MAX_PLAYERS: 20
      SNOOPER_ENABLED: 'false'
      HARDCORE: 'false'
      DIFFICULTY: easy
      GENERATE_STRUCTURES: 'true'
      MAX_BUILD_HEIGHT: 256
      SPAWN_ANIMALS: 'true'
      SPAWN_NPCS: 'true'
      SPAWN_MONSTERS: 'true'
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 10
      MODE: survival
      PVP: 'false'
      LEVEL_TYPE: BIOMESOPLENTY
      ALLOW_FLIGHT: 'true'
      USE_MODPACK_START_SCRIPT: 'true'
      ENABLE_ROLLING_LOGS: 'true'
      GUI: 'FALSE'
      UID: 1000
      GID: 1000
      TZ: 'America/Chicago'
      EULA: 'true'
      tty: 'true'
      stdin_open: 'true'
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - /mnt/container_data/minecraft/curseforge/modpacks:/modpacks
    - /mnt/container_data/minecraft/curseforge/data:/data

```

### Container logs

```
2023-07-13T00:38:58.793986769Z 
2023-07-13T00:38:58.794000527Z Missing mods need to be manually downloaded into repo or excluded:
2023-07-13T00:38:58.794002929Z (Also written to ./MODS_NEED_DOWNLOAD.txt
2023-07-13T00:38:58.794005335Z 
2023-07-13T00:38:58.794272507Z Mod                                                      Slug                Filename                            Download page                                                  
2023-07-13T00:38:58.794279448Z =======================================================  ==================  ==================================  ===============================================================
2023-07-13T00:38:58.794281666Z Fix Experience Bug (now with FABRIC and FORGE versions)  fix-experience-bug  ExperienceBugFix-1.19-1.41.2.3.jar  https://www.curseforge.com/minecraft/mc-mods/fix-experience-bug
2023-07-13T00:38:58.794283477Z Hexerei                                                  hexerei             hexerei-0.3.2.2.jar                 https://www.curseforge.com/minecraft/mc-mods/hexerei           
2023-07-13T00:38:59.121650663Z [init] ERROR failed to auto-install CurseForge modpack
```

**Comment by camalot** [comment]
Also seeing this message. But I have a valid key set.

```
2023-07-13T00:50:49.146417909Z [mc-image-helper] 19:50:49.144 ERROR : Invalid parameter provided for 'install-curseforge' command: Access to https://api.curseforge.com/v1 is forbidden. Make sure to set CF_API_KEY to a valid API key from https://console.curseforge.com/
```

**Comment by itzg** [comment]
I'm not sure what's going on with your API key since apparently it worked for you enough to get to the first problem you described.

With the following compose file, I can't recreate the problem:

```yaml
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java17-alpine
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      MOD_PLATFORM: AUTO_CURSEFORGE
      # allocate from https://console.curseforge.com/ and set in .env file
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-8
      MEMORY: 4G
    volumes:
      - mc-data:/data
volumes:
  mc-data: {}
```

The container just simply exits with exit code 1:

```
> docker compose ps -a
NAME                IMAGE                                 COMMAND             SERVICE             CREATED             STATUS                          PORTS
issue2287-mc-1      itzg/minecraft-server:java17-alpine   "/start"            mc                  2 minutes ago       Exited (1) About a minute ago
```

Logs with download bits snipped:

```
issue2287-mc-1  | [init] Changing ownership of /data to 1000 ...
issue2287-mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Jul 12 13:56 /data'
issue2287-mc-1  | [mc-image-helper] 01:51:18.839 INFO  : Processing modpack 'All the Mods 8-1.0.22.zip' (all-the-mods-8) @ 520914:4633481
issue2287-mc-1  | [mc-image-helper] 01:51:19.158 INFO  : Excluding mod file 'Entity Culling Fabric/Forge' (entityculling) due to configuration
issue2287-mc-1  | [mc-image-helper] 01:51:19.298 INFO  : Downloaded mod file mods/elevatorid-1.19.2-1.8.9.jar
issue2287-mc-1  | [mc-image-helper] 01:51:19.301 INFO  : Excluding mod file 'Just Enough Resources (JER)' (just-enough-resources-jer) due to configuration
issue2287-mc-1  | [mc-image-helper] 01:51:19.362 INFO  : Downloaded mod file mods/getittogetherdrops-forge-1.19.2-1.3.jar
issue2287-mc-1  | [mc-image-helper] 01:51:19.376 INFO  : Excluding mod file 'Extreme sound muffler (Forge)' (extreme-sound-muffler) due to configuration
issue2287-mc-1  | [mc-image-helper] 01:51:19.382 INFO  : Downloaded mod file mods/ftb-essentials-1902.1.10-build.47.jar
.
.
.
issue2287-mc-1  | [mc-image-helper] 01:51:43.404 INFO  : Downloaded mod file mods/twilightforest-1.19.2-4.2.1518-universal.jar
issue2287-mc-1  | [mc-image-helper] 01:51:43.982 INFO  : Downloaded mod file mods/blue_skies-1.19.2-1.3.20.jar
issue2287-mc-1  | [mc-image-helper] 01:51:45.233 INFO  : Downloaded mod file mods/minecolonies-1.19.2-1.0.1489-BETA.jar
issue2287-mc-1  | [mc-image-helper] 01:51:45.982 INFO  : Downloading Forge installer 43.2.14 for Minecraft 1.19.2
issue2287-mc-1  | [mc-image-helper] 01:51:46.716 INFO  : Running Forge installer. This might take a while...
issue2287-mc-1  | 
issue2287-mc-1  | 
issue2287-mc-1  | Missing mods need to be manually downloaded into repo or excluded:
issue2287-mc-1  | (Also written to ./MODS_NEED_DOWNLOAD.txt
issue2287-mc-1  | 
issue2287-mc-1  | 
issue2287-mc-1  | Mod                                                      Slug                Filename                            Download page                                                  
issue2287-mc-1  | =======================================================  ==================  ==================================  ===============================================================
issue2287-mc-1  | Fix Experience Bug (now with FABRIC and FORGE versions)  fix-experience-bug  ExperienceBugFix-1.19-1.41.2.3.jar  https://www.curseforge.com/minecraft/mc-mods/fix-experience-bug
issue2287-mc-1  | Hexerei                                                  hexerei             hexerei-0.3.2.2.jar                 https://www.curseforge.com/minecraft/mc-mods/hexerei           
issue2287-mc-1  | [init] ERROR failed to auto-install CurseForge modpack
```
