### ISSUE TITLE
Conflicting versions of Modrinth mods and dependencies 

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#2297]
https://discord.com/channels/660567679458869252/660567682751528981/1130548169021857895

It ends up downloading both fabric API versions 0.83 and 0.85

Given

```

```docker
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
      - 24454:24454/udp
    environment:
      EULA: "TRUE"
      VERSION: "1.20.1"
      TYPE: FABRIC
      MEMORY: "5G"
      REMOVE_OLD_MODS: TRUE
      MODRINTH_PROJECTS: fabric-api,appleskin,plasmo-voice,terralith,lithium,randomium-ore,jade,krypton,tectonic,ferrite-core,extended-drawers,fallingtree,supplementaries,carry-on,vanilla-refresh
      MODRINTH_DOWNLOAD_OPTIONAL_DEPENDENCIES: false
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./data:/data
      - ./mods:/mods
```

```
