### ISSUE TITLE
Old Minecraft Forge Versions not working

### ISSUE THREAD

**Issue by denizkoekden** [itzg/docker-minecraft-server#2303]
### Describe the problem

Minecraft 1.4.7 with Forge Version 6.6.1.529 is not working. I get `itzg.helpers.errors.GenericException: Failed to locate forge installer ` Error.

### Container definition

```
Image:  itzg/minecraft-server:java8-multiarch

    environment:
      TYPE: "FORGE"
      OVERRIDE_SERVER_PROPERTIES: "false"
      EULA: "TRUE"
      VERSION: "1.4.7"
      FORGE_VERSION: 6.6.1.529
      GUI: "FALSE"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "12G"
      USE_AIKAR_FLAGS: "true"
      JVM_XX_OPTS: "-XX:+UseG1GC"```


### Container logs

```
[36m mc  | [0m[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Jul 24 10:51 /data'

[36m mc  | [0m[init] Resolved version given 1.4.7 into 1.4.7 and major version 1.4

[36m mc  | [0m[init] Resolving type given FORGE

[36m mc  | [0m[ mc-image-helper] 10:51:14.594 INFO  : Downloading Forge installer 6.6.1.529 for Minecraft 1.4.7

[36m mc  | [0m[ mc-image-helper] 10:51:15.922 ERROR : 'install-forge' command failed. Version is 1.29.0

[36m mc  | [0mme.itzg.helpers.errors.GenericException: Failed to locate forge installer

[36m mc  | [0m   at me.itzg.helpers.forge.ForgeInstaller.downloadInstaller(ForgeInstaller.java:398)

[36m mc  | [0m   at me.itzg.helpers.forge.ForgeInstaller.downloadAndInstall(ForgeInstaller.java:258)

[36m mc  | [0m   at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:134)

[36m mc  | [0m   at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:84)

[36m mc  | [0m   at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:16)

[36m mc  | [0m   at picocli.CommandLine.executeUserObject(CommandLine.java:2041)

[36m mc  | [0m   at picocli.CommandLine.access$1500(CommandLine.java:148)

[36m mc  | [0m   at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)

[36m mc  | [0m   at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)

[36m mc  | [0m   at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)

[36m mc  | [0m   at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)

[36m mc  | [0m   at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)

[36m mc  | [0m   at picocli.CommandLine.execute(CommandLine.java:2170)

[36m mc  | [0m   at me.itzg.helpers. mcImageHelper.main( mcImageHelper.java:139)

[36m mc  | [0m[init] ERROR failed to install Forge

[36m mc exited with code 1
[0m```
