### ISSUE TITLE
Issue Auto-CF Installing All the Mods 8

### ISSUE THREAD

**Issue by jamstruth** [itzg/docker-minecraft-server#2310]
### Describe the problem

Attempting to install All the Mods 8 results in the following error

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `me.itzg.helpers.curseforge.model.ModLoaderType` from String "6": not one of the values accepted for Enum class: [0, 1, 2, 3, 4, 5]
 at [Source: (reactor.netty.ByteBufMono$ReleasingInputStream); line: 1, column: 6699] (through reference chain: me.itzg.helpers.curseforge.model.GetModResponse["data"]->me.itzg.helpers.curseforge.model.CurseForgeMod["latestFilesIndexes"]->java.util.ArrayList[1]->me.itzg.helpers.curseforge.model.FileIndex["modLoader"])
```

### Container definition

```
version: "3.7"

services:
  minecraft:
    image: itzg/minecraft-server:java17-alpine
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: ${SERVER_TYPE}
      INIT_MEMORY: 512M
      MAX_MEMORY: ${MAX_MEMORY}
      SPIGET_RESOURCES: ${SPIGOT_PLUGIN_IDS}
      WHITELIST: ${WHITELIST}
      OPS: ${OPS}
      MAX_PLAYERS: ${MAX_PLAYERS}
      USE_SIMD_FLAGS: true
      USE_AIKAR_FLAGS: true
      TUNE_VIRTUALIZED: FALSE
      TUNE_NURSERY_SIZES: FALSE
      ENABLE_ROLLING_LOGS: true
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-8
      CF_API_KEY: ${CF_API_KEY}
      MOTD: Jams and Em Mod it Up
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - minecraft:/data
      - ${MINECRAFT_BACKUP_FOLDER}:/backups
      - extra_mods:/downloads
volumes:
  minecraft:
  extra_mods:
```

### Container logs

```
		at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:24)
		at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
		at picocli.CommandLine.access$1500(CommandLine.java:148)
		at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
		at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
		at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
		at picocli.CommandLine.execute(CommandLine.java:2170)
		at me.itzg.helpers.McImageHelper.main(McImageHelper.java:139)
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `me.itzg.helpers.curseforge.model.ModLoaderType` from String "6": not one of the values accepted for Enum class: [0, 1, 2, 3, 4, 5]
 at [Source: (reactor.netty.ByteBufMono$ReleasingInputStream); line: 1, column: 6699] (through reference chain: me.itzg.helpers.curseforge.model.GetModResponse["data"]->me.itzg.helpers.curseforge.model.CurseForgeMod["latestFilesIndexes"]->java.util.ArrayList[1]->me.itzg.helpers.curseforge.model.FileIndex["modLoader"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:2002)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1230)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:415)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._fromString(EnumDeserializer.java:279)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481)
	at me.itzg.helpers.http.ObjectFetchBuilder.lambda$handleResponse$1(ObjectFetchBuilder.java:85)
	... 9 common frames omitted
[init] ERROR failed to auto-install CurseForge modpack```
