### ISSUE TITLE
image tries to download fabric from nonexisting website

### ISSUE THREAD

**Issue by LazyGamer1111** [itzg/docker-minecraft-server#2331]
### Describe the problem

When i try to download fabric using the image, it tries to download it from meta.fabricmc.net/172.67.151.177:443 with the last ip always being different. But the request always times out.

### Container definition

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.19.2"
      FABRIC_LOADER_VERSION: "0.14.22"
      FABRIC_LAUNCHER_VERSION: "0.11.2"
      MEMORY: "6G"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
 ```

### Container logs

```
origins-mc-1  | [init] Resolving type given FABRIC
origins-mc-1  | [mc-image-helper] 08:21:44.033 INFO  : Installing Fabric Versions(game=1.19.2, loader=0.14.22, installer=0.11.2)
origins-mc-1  | [mc-image-helper] 08:22:44.420 ERROR : 'install-fabric-loader' command failed. Version is 1.25.3
origins-mc-1  | reactor.core.Exceptions$ReactiveException: io.netty.channel.ConnectTimeoutException: connection timed out: meta.fabricmc.net/172.67.151.177:443
origins-mc-1  |         at reactor.core.Exceptions.propagate(Exceptions.java:408)
origins-mc-1  |         at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
origins-mc-1  |         at reactor.core.publisher.Mono.block(Mono.java:1710)
origins-mc-1  |         at me.itzg.helpers.fabric.FabricLauncherInstaller.processInstallUsingVersions(FabricLauncherInstaller.java:118)
origins-mc-1  |         at me.itzg.helpers.fabric.FabricLauncherInstaller.installUsingVersions(FabricLauncherInstaller.java:77)
origins-mc-1  |         at me.itzg.helpers.fabric.InstallFabricLoaderCommand.call(InstallFabricLoaderCommand.java:86)
origins-mc-1  |         at me.itzg.helpers.fabric.InstallFabricLoaderCommand.call(InstallFabricLoaderCommand.java:15)
origins-mc-1  |         at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
origins-mc-1  |         at picocli.CommandLine.access$1500(CommandLine.java:148)
origins-mc-1  |         at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
origins-mc-1  |         at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
origins-mc-1  |         at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
origins-mc-1  |         at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
origins-mc-1  |         at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
origins-mc-1  |         at picocli.CommandLine.execute(CommandLine.java:2170)
origins-mc-1  |         at me.itzg.helpers.McImageHelper.main(McImageHelper.java:123)
origins-mc-1  |         Suppressed: java.lang.Exception: #block terminated with an error
origins-mc-1  |                 at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
origins-mc-1  |                 ... 14 common frames omitted
origins-mc-1  | Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: meta.fabricmc.net/172.67.151.177:443
origins-mc-1  |         at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:613)
origins-mc-1  |         at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
origins-mc-1  |         at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
origins-mc-1  |         at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
origins-mc-1  |         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
origins-mc-1  |         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
origins-mc-1  |         at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
origins-mc-1  |         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
origins-mc-1  |         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
origins-mc-1  |         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
origins-mc-1  |         at java.base/java.lang.Thread.run(Unknown Source)
origins-mc-1  | [init] ERROR failed to install Fabric launcher from 1.19.2, 0.11.2, 0.14.22
```
