### ISSUE TITLE
Containers keep restarting (Invalid parameter provided for 'manage-users' command?)

### ISSUE THREAD

**Issue by freekvh** [itzg/docker-minecraft-server#2351]
### Describe the problem

Since the latest update all my containers keep restarting, I can't enter the worlds.

### Container definition

```
  minecraft-server-paper-survival-SenM-mobs:
    image: itzg/minecraft-server
    container_name: minecraft-server-paper-survival-SenM-mobs
    ports:
     - 25575:25565
    #  - 4711:4711
    #  - 19132:19132/udp
    networks:
      - minecraft
    volumes:
     - ./mc-paper-SenM-mobs/data:/data
     - ./mc-paper-SenM-mobs/plugins:/plugins
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      # VERSION: LATEST
      # BUILD_FROM_SOURCE: "TRUE"
      MEMORY: "2G"
      TZ: Europe/Amsterdam
      MODE: survival
      DIFFICULTY: easy
      MOTD: Stijn en Papa survival
      OPS: Freekvh
    tty: true
    stdin_open: true
    restart: always
```

### Container logs

```
[mc-image-helper] 21:18:01.220 ERROR : Invalid parameter provided for 'manage-users' command: Could not resolve username from Mojang:  FreekvH
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 1 1000 100 700 Aug 19 21:17 /data'
[init] Resolving type given PAPER
[mc-image-helper] 21:18:07.353 INFO  : Resolved paper to version 1.20.1 build 132
[mc-image-helper] 21:18:07.501 INFO  : The file /data/paper-1.20.1-132.jar is already up to date
[init] Copying any plugins from /plugins to /data/plugins
[init] Setting mode
[mc-image-helper] 21:18:22.229 ERROR : Invalid parameter provided for 'manage-users' command: Could not resolve username from Mojang:  FreekvH
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 1 1000 100 700 Aug 19 21:18 /data'
[init] Resolving type given PAPER
[mc-image-helper] 21:18:28.630 INFO  : Resolved paper to version 1.20.1 build 132
[mc-image-helper] 21:18:28.754 INFO  : The file /data/paper-1.20.1-132.jar is already up to date
[init] Copying any plugins from /plugins to /data/plugins
[init] Setting mode
[mc-image-helper] 21:18:44.455 ERROR : Invalid parameter provided for 'manage-users' command: Could not resolve username from Mojang:  FreekvH
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 1 1000 100 700 Aug 19 21:18 /data'
[init] Resolving type given PAPER
[mc-image-helper] 21:18:50.770 INFO  : Resolved paper to version 1.20.1 build 132
[mc-image-helper] 21:18:50.916 INFO  : The file /data/paper-1.20.1-132.jar is already up to date
[init] Copying any plugins from /plugins to /data/plugins
[init] Setting mode

```
