### ISSUE TITLE
Minecraft Server Crash due to X11 DISPLAY with curseforge modpack

### ISSUE THREAD

**Issue by Calkstein** [itzg/docker-minecraft-server#2355]
### Describe the problem

When attempting to run the Minecraft server with curseforge modpack using the `itzg/minecraft-server:java8-multiarch` image, the server crashes with an error indicating that the X11 DISPLAY variable was not set.

### Container definition

```
version: "3.3"

services:
  mod:
      image: itzg/minecraft-server:java8-multiarch  #ftb
      container_name: mc-mod
      ports:
        - 25565:25565
      command: --installServer
      environment:
        TIMEZONE: ${TimeZone}
        GUI: 'FALSE'
        MEMORY: 12G
        MAX_PLAYERS: 6
        EULA: "TRUE"
        CONSOLE: "TRUE"
        tty: "TRUE"
        stdin_open: "TRUE"
        DIFFICULTY: normal
        VERSION: 1.7.10
        ALLOW_FLIGHT: "TRUE"
        # enforce-secure-profiles: "false"
        ##Curseforge
        TYPE: AUTO_CURSEFORGE 
        # TYPE: FORGE
        CF_SLUG: gt-new-horizons
        CF_API_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      volumes:
        - ./mod:/data
      restart: unless-stopped
      networks:
        - minecraft
```

### Container logs

```
mc-mod  | No X11 DISPLAY variable was set, but this program performed an operation which requires it.
mc-mod  |       at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204) ~[?:1.8.0_312]
mc-mod  |       at java.awt.Window.<init>(Window.java:536) ~[?:1.8.0_312]
mc-mod  |       at java.awt.Frame.<init>(Frame.java:420) ~[?:1.8.0_312]
mc-mod  |       at java.awt.Frame.<init>(Frame.java:385) ~[?:1.8.0_312]
mc-mod  |       at javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1763) ~[?:1.8.0_312]
mc-mod  |       at javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1838) ~[?:1.8.0_312]
mc-mod  |       at javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1696) ~[?:1.8.0_312]
mc-mod  |       at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:863) ~[?:1.8.0_312]
mc-mod  |       at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666) ~[?:1.8.0_312]
mc-mod  |       at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637) ~[?:1.8.0_312]
mc-mod  |       at com.dreammaster.coremod.DepLoader.call(DepLoader.java:181) ~[DepLoader.class:?]
mc-mod  |       at com.dreammaster.coremod.DepLoader.call(DepLoader.java:29) ~[DepLoader.class:?]
mc-mod  |       at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:133) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
mc-mod  |       ... 8 more
mc-mod  | A problem occurred running the Server launcher.
```
