### ISSUE TITLE
Whitelist is Reset after restarting the server.

### ISSUE THREAD

**Issue by dgarvis** [itzg/docker-minecraft-server#2357]
### Describe the problem

After pulling the newest docker image and then restarting my minecraft servers, the whitelist got reset on each server to the default that I had in my docker compose file.  Updating the whitelist and then restarting the server would also cause it to get reset again.

In each log file I see this line:
[init] Enabling whitelist functionality

### Container definition

```
minecraft:
    image: itzg/minecraft-server
    restart: always
    ports:
      # Main Game
      - "25566:25565"
    volumes:
      - "server:/data"
    environment:
      EULA: "TRUE"
      
      TYPE: "SPIGOT"
      VERSION: "1.20.1"

     [omitted]
     
      WHITELIST: "me"
      OPS: "me"

      [omitted]
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 13 1000 1000 4096 Aug 16 20:26 /data'
[init] Resolving type given SPIGOT
[init] Downloading Spigot from https://download.getbukkit.org/spigot/spigot-1.20.1.jar ...
 [init] Enabling whitelist functionality
 [init] Setting initial memory to 15G and max to 15G
 [init] Starting the Minecraft server...
Unbundling libraries to /data/bundler
 Expected file /data/bundler/versions/spigot-1.20.1-R0.1-SNAPSHOT.jar to have hash 37cbe1da24cb7a66e90648519ebb70895b8c9bfa5d734cb84061b7d3bd45af19, but got 2223cfff7d6c1ad5027509e8c3983b8b336f1d37baaad710756a3f35159c04a5
 Unpacking spigot-1.20.1-R0.1-SNAPSHOT.jar (versions:spigot-1.20.1-R0.1-SNAPSHOT.jar) to /data/bundler/versions/spigot-1.20.1-R0.1-SNAPSHOT.jar
 Expected file /data/bundler/libraries/spigot-api-1.20.1-R0.1-SNAPSHOT.jar to have hash 6c4a0d22f308bf8cde4d919f06e6a2c836649776904bfa7405e88cda2995d358, but got 55da66e6f174351ab82fa0e767363d66704f1c2a231c068a8135cef2216902cd
 Unpacking spigot-api-1.20.1-R0.1-SNAPSHOT.jar (libraries:spigot-api-1.20.1-R0.1-SNAPSHOT.jar) to /data/bundler/libraries/spigot-api-1.20.1-R0.1-SNAPSHOT.jar
 Starting server
 Loading libraries, please wait...
```
