### ISSUE TITLE
modrinth pull - java won't start

### ISSUE THREAD

**Issue by SirBastol** [itzg/docker-minecraft-server#2386]
### Describe the problem

fresh docker  install - using portioner to push it as a stack ( it just launches the yml with a web editor)
sometimes fails because modrinth kills downloads on repeated fast try (causing missing modpacks)
but the issue is java is broken 

changed PID AND GID. to 0.  or the docker container user..  made no diffrence

added JAVA VERSION env and it dint fix it. 

and im stumped.. google the error didn't give me anything useful. ( mostly reddit users trolling noobs with rm-rf stuff)

trying to migrate the container and world to a new machine... 
fresh install and  just copy the world folder. 

### Container definition

```
version: "3.8"

networks:
  default:

services:
  Minecraft4a:
    image: itzg/minecraft-server
    hostname: mcround4
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "8123:8100"
      - "8100:8100"
    environment:
      MOD_PLATFORM: MODRINTH
      MODRINTH_MODPACK: https://modrinth.com/modpack/hermitcreateflavors
      OVERRIDE_SERVER_PROPERTIES: TRUE
      MOTD: Respectful - do not steal ask first - friendly play
      SPAWN_PROTECTION: 0
      RCON_PORT: 25575
      TZ: America/Vancouver
      DIFFICULTY: HARD
      ALLOW_FLIGHT: TRUE
      RCON_PASSWORD: rconrodney
      PVP: TRUE
      MAX_PLAYERS: 6
      OPS: 37a79502-60ce-4115-b8d3-ddec19516c46
      MAX_TICK_TIME: 0
      EULA: TRUE
      SERVER_NAME: Hermit Create Flavors - Round4A
      JVM_OPTS: "-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval: 600000 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:G1NewSizePercent: 20 -XX:G1ReservePercent: 20 -XX:MaxGCPauseMillis: 50 -XX:G1HeapRegionSize: 32"
      MEMORY: 4G
      REMOVE_FILES_SPEC: ._*
      LOG_LEVEL: info
    volumes:
      - /Volume1/public1/DockerStuff/Minecraft/backups:/backups:rw
      - /Volume1/public1/DockerStuff/Minecraft/mcround6:/data:rw
    restart: unless-stopped    
```

### Container logs

```
[mc-image-helper] 20:39:02.981 INFO  : Modpack hermitcreateflavors version 4.1 is already installed
[mc-image-helper] 20:39:07.760 INFO  : The file ./ops.json already exists, so no changes will be made
[init] Setting initial memory to 4G and max to 4G
[init] Using Forge supplied run.sh script...
Error: Could not find or load main class 600000
Caused by: java.lang.ClassNotFoundException: 600000
2023-09-17T20:39:14.156-0700    WARN    mc-server-runner    Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.    {"exitCode": 1}
```
