### ISSUE TITLE
vanillatweaks share code yields invalid file

### ISSUE THREAD

**Issue by Airblader** [itzg/docker-minecraft-server#2395]
### Describe the problem

I have created a vanillatweaks resource pack, copied the share code, and added it to my server using

```
VANILLATWEAKS_SHARECODE: "5g3AhS,8wgBco"
REMOVE_OLD_VANILLATWEAKS: "TRUE"
```

The share code in question is the first one, the latter works fine. However, when the server starts up, it produces a broken zip file. Reuploading this zip file on vanillatweaks yields an error that it's a crafting tweak instead.

### Container definition

```
version: "3.8"
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    user: "${UID}:${GID}"
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      UID: 1026
      GID: 65536
      SERVER_NAME: redacted
      ICON: "/assets/icon.jpg"
      TYPE: FABRIC
      VERSION: "1.20.1"
      DIFFICULTY: hard
      VIEW_DISTANCE: 20
      SIMULATION_DISTANCE: 10
      MAX_MEMORY: 12G
      VANILLATWEAKS_SHARECODE: "5g3AhS,8wgBco"
      REMOVE_OLD_VANILLATWEAKS: "TRUE"
      SPAWN_PROTECTION: 0
      ENABLE_AUTOPAUSE: "TRUE"
      AUTOPAUSE_TIMEOUT_INIT: 600
      AUTOPAUSE_TIMEOUT_EST: 600
      # Needed for autopause
      # https://docker-minecraft-server.readthedocs.io/en/latest/misc/autopause-autostop/autopause/
      MAX_TICK_TIME: -1
      EULA: "TRUE"
    volumes:
      - /volume2/docker/redacted/assets:/assets:r
      - /volume2/docker/redacted/data:/data:rw
    network_mode: host
    restart: always
```

### Container logs

```
2023/09/19 10:53:57 | stdout | [mc-image-helper] 08:53:57.815 INFO  : Downloading Vanilla Tweaks resourcepacks for share code 5g3AhS
-- | -- | --
2023/09/19 10:53:56 | stdout | [mc-image-helper] 08:53:56.263 INFO  : Downloading Vanilla Tweaks datapacks for share code 8wgBco
```
