### ISSUE TITLE
Getting ERROR: failed to download Purpur on container start.

### ISSUE THREAD

**Issue by DoTheEvo** [itzg/docker-minecraft-server#2401]
### Describe the problem

Container is failing to start.
Started to test with clean fresh setup.
It fails too, seems its failing during startup because some purpur url is not giving what it should maybe.

`ERROR: failed to download Purpur`

### Container definition

`docker-compose.yml`
```yml
services:
  minecraft:
    image: itzg/minecraft-server:2023.9.1-java17
    container_name: minecraft2
    hostname: minecraft2
    restart: unless-stopped
    env_file: .env
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"     # minecraft server players connect
      - "8100:8100"       # bluemap
      - "8123:8123"       # dynmap
      - "9225:9225"       # prometheus exporter
      - "9940:9940"       # prometheus exporter
      - "24454:24454"     # microphone
      - "24454:24454/udp" # microphone
    volumes:
      - ./minecraft_data:/data
    logging:
      driver: "json-file"


networks:
  default:
    name: $DOCKER_MY_NETWORK
    external: true

```

`.env`

```
# GENERAL
MY_DOMAIN=example.com
DOCKER_MY_NETWORK=caddy_net
TZ=Europe/Bratislava

# ITZG MINECRAFT SPECIFIC
TYPE=PURPUR
EULA=TRUE
ONLINE_MODE=FALSE
SNOOPER_ENABLED=FALSE
SERVER_NAME=Blablabla
ALLOW_CHEATS=TRUE
MAX_MEMORY=3G
MAX_PLAYERS=50
ENABLE_COMMAND_BLOCK=TRUE
ALLOW_NETHER=TRUE
```

### Container logs

Of note is 

`ERROR : 'install-purpur' command failed. Version is 1.34.7`
`me.itzg.helpers.http.FailedRequestException: HTTP request of https://api.purpurmc.org/v2/purpur/1.20.2 failed with 404 Not Found`
`ERROR: failed to download Purpur`

Full log is here [pastebin.com/Ykh6FmvH](https://pastebin.com/Ykh6FmvH)
