### ISSUE TITLE
Unicode support in docker attach

### ISSUE THREAD

**Issue by realwoopee** [itzg/docker-minecraft-server#2423]
### Describe the problem

When attached to the server console using `docker attach` multiple backspace key presses are required to delete non-ascii character.

Example: 
1. Enter `тест` into the console, then press backspace 8 times, then enter 'version' and press enter
2. Do exactly the same thing, but press backspace only 4 times, not 8
3. Enter `say` into the console, then enter `тест` and press backspace 4 times, then press enter
![image](https://github.com/itzg/docker-minecraft-server/assets/14233054/9cc9aa9e-f6c7-4d6c-9090-c77613a87e60)
![image](https://github.com/itzg/docker-minecraft-server/assets/14233054/a23b9238-f71b-4ac0-9957-887304f8a5f8)

Note the misaligned 'vers' happening because of the cursor moving back 8 times.
I am using Putty and Debian for the host, but everywhere else (including `docker exec <container> bash`) cyrillic characters are handled correctly. 

### Container definition

```
Paste run command or compose file here
```
tty and stdin_open are both set to `true`

### Container logs

```
Paste logs here
```

**Comment by itzg** [comment]
Since you did not provide your container config I cannot confirm how you have TTY or stdin setup. In any case, `docker attach` is a docker leave mechanism that connects directly to the Minecraft server process. It is beyond the control of the image to further influence that.

**Comment by itzg** [comment]
...one thing you could try it setting the env variable `EXEC_DIRECTLY` to "true". The server may no longer stop gracefully, but that'll eliminate any possible interference in the console attachment.

**Comment by realwoopee** [comment]
`EXEC_DIRECTLY: 'true'` does fix the issue. I even got syntax highlighting during the command input :)

I mentioned tty and stdin in the original message, but here is the full container config:
```
version: "3"

services:
  server0:
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
      - 25575:25575
    environment:
      EULA: "TRUE"
      TYPE: 'PAPER'
      ICON: <redacted>
      OVERRIDE_ICON: 'TRUE'
      VERSION: '1.20.1'
      DIFFICULTY: 'hard'
      USE_AIKAR_FLAGS: 'true'
      MEMORY: '6G'
      SNOOPER_ENABLED: 'false'
      SERVER_NAME: <redacted>
      RCON_PASSWORD: <redacted>
      MODRINTH_DOWNLOAD_OPTIONAL_DEPENDENCIES: 'false'
      MODRINTH_ALLOWED_VERSION_TYPE: 'beta'
      DATAPACKS: 'https://static.planetminecraft.com/files/resource_media/datapack/global-trades-e2450.zip'
      EXEC_DIRECTLY: 'true'
    tty: true
    stdin_open: true
    volumes:
      - /home/fxserver/minecraft-server/server0/data:/data
      - /home/fxserver/minecraft-server/server0/plugins:/plugins
      - /home/fxserver/minecraft-server/server0/mods:/mods
      - /home/fxserver/minecraft-server/server0/config:/config
```
