### ISSUE TITLE
Modrinth Mod for Quilt failing

### ISSUE THREAD

**Issue by ajamesmichaels** [itzg/docker-minecraft-server#2426]
### Describe the problem

It seems like modrinth / quilt has updated the way they are logging the types of different projects. This configuration worked in the past, but is now failing with this error.

Quilt uses a quilt standard library in addition to the quilt loader.
It seems like in the past, modrinth categorized quilt mods as fabric mods type, so requesting https://modrinth.com/mod/qsl thequilt standard library project with fabric loader worked (project id qvIfYCYJ).

Recently, it seems like qsl was updated to have mod versions only be listed as 'Quilt' (see versions tab, supports column of qsl modrinth page), so the mc-image-helper code is failing with this error from getVersionsforProject in ModrinthApiClient.java
https://github.com/itzg/mc-image-helper/blob/58f1ee2b85dcb4e97386a246372b20f71c532ccb/src/main/java/me/itzg/helpers/modrinth/ModrinthApiClient.java#L185

`[mc-image-helper] 11:58:25.710 ERROR : Invalid parameter provided for 'modrinth' command: No files are available for the project qvIfYCYJ for loader fabric and Minecraft version 1.19.4
`

It's likely that the expandCompatibleLoaders for Quilt loaders will need an additional string 'Quilt' for quilt projects on modrinth, https://github.com/itzg/mc-image-helper/blob/58f1ee2b85dcb4e97386a246372b20f71c532ccb/src/main/java/me/itzg/helpers/modrinth/Loader.java#L8

Sample docker options:
`
      VERSION: 1.19.4
      TYPE: QUILT
      MODRINTH_PROJECTS: qsl
`

### Container definition

```
version: "3"
services:
  mc:
    container_name: craft
    image: itzg/minecraft-server:java17
    environment:
      EULA: "true"
      VERSION: 1.19.4
      TYPE: QUILT
      MODRINTH_PROJECTS: qsl
      TZ: America/New_York
    volumes:
      - craft-data:/data
volumes:
  craft-data:
    external: true
```

### Container logs

```
[init] 2023-10-09 11:57:46-04:00 Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 12 1000 1000 4096 Oct  9 11:28 /data'

[init] 2023-10-09 11:57:46-04:00 Resolving type given QUILT

[mc-image-helper] 11:57:56.393 INFO  : Quilt 1.19.4 loader 0.21.0 is already installed

[mc-image-helper] 11:58:02.355 INFO  : Downloading Vanilla Tweaks datapacks for share code rROFuY

[init] 2023-10-09 11:58:02-04:00 Removing old mods including:*.jar,*-version.json excluding:

[mc-image-helper] 11:58:08.725 INFO  : Downloading lithium-fabric-mc1.19.4-0.11.1.jar

[mc-image-helper] 11:58:17.233 INFO  : Downloading phosphor-fabric-mc1.19.x-0.8.1.jar

[mc-image-helper] 11:58:25.710 ERROR : Invalid parameter provided for 'modrinth' command: No files are available for the project qvIfYCYJ for loader fabric and Minecraft version 1.19.4

```
