### ISSUE TITLE
Resolve users online while having server offline stopped working

### ISSUE THREAD

**Issue by oldium** [itzg/docker-minecraft-server#2481]
### Describe the problem

In past it was possible to resolve users to UUID while having server set to offline (env `ONLINE_MODE: "FALSE"` in `docker-compose.yml`). This worked fine. Now the startup shows the following error:

```
ERROR : Invalid parameter provided for 'manage-users' command: Unable to resolve username while offline: SomeUserName
```

I use proxy, which is online, and the user UUID is still being passed to the server. Having the server offline does not always mean that the users should not be resolved online.

### Container definition

```
    ...
    environment:
      ONLINE_MODE: "FALSE"
      WHITELIST: oldium
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      ...
```

### Container logs

```
2023-11-11T20:57:14.914459934Z [init] Enabling whitelist functionality
2023-11-11T20:57:17.258297896Z [mc-image-helper] 21:57:17.255 ERROR : Invalid parameter provided for 'manage-users' command: Unable to resolve username while offline: oldium
```
