### ISSUE TITLE
Additionally escaped unicode escape sequence in MOTD and LEVEL_NAME in server.properties

### ISSUE THREAD

**Issue by oldium** [itzg/docker-minecraft-server#2482]
### Describe the problem

I am using diacritics inside both motd and level name, but this stopped working (cannot tell when). I tried the following:

```yaml
    ...
    environment:
      MOTD: Tajemnej sv\u011Bt
      LEVEL: Tajemnej sv\u011Bt
      ...
```

which worked before (used it long time ago), but now in `server.properties` there is one more backslash added:

```
level-name=Tajemnej sv\\u011Bt
motd=Tajemnej sv\\u011Bt
```

The environment property value as printed by `printenv` looks correct:

```
MOTD=Tajemnej sv\u011Bt
LEVEL=Tajemnej sv\u011Bt
```

I also tried to use diacritics:

```yaml
    ...
    environment:
      MOTD: Tajemnej svět
      LEVEL: Tajemnej svět
      ...
```

This succeeds with latest PAPER server, but fails with 1.18.2, where it initially looks good (the first small version of `server.properties` looks good with UTF-8 diacritics), but after the server starts up, the `server.properties` gets populated and now contains:

```
level-name=Tajemnej sv\u00C4\u009Bt
motd=Tajemnej sv\u00C4\u009Bt
```

Please make the `\u` sequence working again, so that it is written as:

```
level-name=Tajemnej sv\u011Bt
motd=Tajemnej sv\u011Bt
```

into `server.properties`. I tried to modify the `server.properties` file during clean startup (it takes some time until the JARs are downloaded) and the server correctly creates world `Tajemnej svět` when there is just a single backslash.

**Comment by itzg** [comment]
I just fixed a related issue, so please re-pull the latest image. However, I do want to point out that pre-escaping unicode does not work at this time. 

Using
```yaml
      TYPE: PAPER
      VERSION: "1.18.2"
      MOTD: Tajemnej svět
      DUMP_SERVER_PROPERTIES: true
```

the property is
```
motd=Tajemnej sv\u011Bt
```

with VERSION changed to "1.20.2" the property is
```
motd=Tajemnej svět
```
