### ISSUE TITLE
Modpack with memory variables crashing

### ISSUE THREAD

**Issue by jpcarpanezi** [itzg/docker-minecraft-server#2496]
### Describe the problem

I'm trying to create a Minecraft server with the modpack "Create and Guns" from Curseforge. But, when creating the server i'm struggling with memory usage, because obviously with the default memory, server is having memory heap problems.

But when i use the variables `INIT_MEMORY` and `MAX_MEMORY` to define a higher usage, the server is crashing on final steps and i don't know why.

### Container definition

```
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java17-jdk
    ports:
      - "25565:25565"
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "6G"
      TYPE: "AUTO_CURSEFORGE"
      CF_MODPACK_ZIP: "/opt/create-and-guns.zip"
      CF_API_KEY: "MY-API-KEY"
      CF_SLUG: "create-and-guns"
    restart: unless-stopped
    volumes:
      - ./create-and-guns.zip:/opt/create-and-guns.zip
      - ./Structory_1.20.2_v1.3.3.jar:/downloads/Structory_1.20.2_v1.3.3.jar
      - ./data:/data
    container_name: curseforge
```

### Container logs

```
/data/./run.sh: line 6:   434 Killed                  java @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.20.1-47.2.1/unix_args.txt "$@"
```
