### ISSUE TITLE
Start up file permission denied

### ISSUE THREAD

**Issue by TheAceMan** [itzg/docker-minecraft-server#2510]
### Describe the problem

I have a few minecraft servers running in Docker for a while but recently ran into a startup issue. This is the error I receive:

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x. 2 1000 1000 0 Nov 25 19:31 /data'
/start-configuration: line 87: /data/.rcon-cli.env: Permission denied
```
I recently updated the the docker server packages and restarted the server when I think the issues begin. Not sure if it pulled a newer image as part of that or not.

A new server with this same docker compose will start fine using an empty directly and can write files but if I restart the new server it fails with the above error. Appears it can not modify the existing file for some reason at start up. I assume it is something to do with using a volume mount but it had been working until recently. Any direction would be helpful as I have tried multiple changes to the file share and the container security/user values.

Also I moved a new minecraft server to Kubernetes and see the same issue, a new instance of minecraft starts correctly but if I delete the pod it will have the same error when creating the new pod using the existing files on the fileshare. This is using the same file share. So think it is either the file share or container having an issue but can't put my finger on what is going on.

### Container definition

```
version: "3.9"
services:
  mc-survival:
    container_name: mc-survival
    image: itzg/minecraft-server
    restart: unless-stopped
    networks:
      - minecraft
    security_opt:
      - no-new-privileges:true
    volumes:
      - minecraft_data_survival:/data
    environment:
      - MOTD="survival world"
      - EULA=TRUE
      - DIFFICULTY=easy
      - MODE=survival
      - LEVEL_TYPE=default
      - MAX_TICK_TIME="-1"
      - MEMORY=3G

volumes:
  minecraft_data_survival:
    driver_opts:
      o: "username=user,password=pass,uid=1000,gid=1000"
      type: "cifs"
      device: \\192.168.1.22\minecraft\data\survival
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x. 2 1000 1000 0 Nov 25 19:31 /data'
/start-configuration: line 87: /data/.rcon-cli.env: Permission denied
```
