### ISSUE TITLE
Updated Bukkit download URL https://getbukkit.org/get/

### ISSUE THREAD

**Issue by bradpoulton** [itzg/docker-minecraft-server#2521]
### Describe the problem

My docker container is not starting due to not being able to download the jar file from download.getbukkit.org. It looks like they have migrated to https://getbukkit.org/get/. Here are the applicable logs.

### Container logs
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x. 9 1000 1000 4096 Jul 31  2022 /data'

[init] Resolved version given 1.19 into 1.19

[init] Resolving type given SPIGOT

[init] Downloading Spigot from https://download.getbukkit.org/spigot/spigot-1.19.jar ...

curl: (22) The requested URL returned error: 523
```

Workaround

I was able to get round this issue by switching from TYPE=SPIGOT to TYPE=CUSTOM and using CUSTOM_SERVER=/data/spigot_server-1.19.jar

https://github.com/itzg/docker-minecraft-server/blob/2507028193d10806e751a99bea016e3be3e64264/scripts/start-deployBukkitSpigot#L71

**Comment by itzg** [comment]
Thanks for investigating. That would be great if you could PR that change.

**Comment by itzg** [comment]
No problem at all. I can investigate also, but yes my initial suspicion is that they have been down lately. Some users have been getting 523 error pages lately, which means their backend is down. 

I would suggest switching to PaperMC which is plugin compatible and has much better support.

**Comment by kmdkuk** [comment]
I had a similar problem and report it just in case.
Consider using PaperMC.
````yaml
      - env:
        - name: TYPE
          value: SPIGOT
        - name: VERSION
          value: "1.19.4"
        - name: EULA
          value: "true"
        image: itzg/minecraft-server:java8
````

log
```sh
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwsrwx 2 1000 1000 90 Dec  8 10:58 /data'
[init] Resolving type given SPIGOT
[init] Downloading Spigot from https://download.getbukkit.org/spigot/spigot-1.19.4.jar ...
curl: (22) The requested URL returned error: 522
```
