### ISSUE TITLE
Health check does not working anymore with TYPE=PURPUR/PAPER/SIGOT

### ISSUE THREAD

**Issue by cn-ml** [itzg/docker-minecraft-server#2545]
### Describe the problem

I just pulled the latest itzg/minecraft-server:java17 for my server, but my web services in that container (through plugins) are no longer routed through my reverse proxy due to the health check failing. I will disable the healthcheck for now, because the server seems to be running fine, but I don't know what happened since the last restart.

The output of `mc-health` is:
```
failed to ping localhost:25565 : json: cannot unmarshal string into Go struct field ServerInfo.description of type mcpinger.RegularChatComponent
```

### Container definition

```yml
...
  minecraft:
    restart: always
    image: itzg/minecraft-server:java17
    depends_on:
      - db
    env_file: stack.env
    environment:
      UID: 1001
      GID: 1001
      TYPE: PURPUR
      PURPUR_BUILD: LATEST
      REMOVE_OLD_MODS: true
      MEMORY: 18G
      USE_AIKAR_FLAGS: true

      MOTD: my modt
      DIFFICULTY: normal
      SPAWN_PROTECTION: 0
      MODE: survival
      ENABLE_QUERY: true
      QUERY_PORT: 25565
      MAX_PLAYERS: 20
      OPS: |-
        <player>
      EXISTING_OPS_FILE: SYNCHRONIZE
      WHITELIST: |-
        <players>
      EXISTING_WHITELIST_FILE: SYNCHRONIZE
      ENFORCE_WHITELIST: true
      ICON: https://static.content.de/iconurl.png
      OVERRIDE_ICON: true # get command failed
      RCON_PASSWORD: <redacted>
      TZ: Europe/Berlin
      STOP_SERVER_ANNOUNCE_DELAY: 30 # remember to set the stop grace period for the container
      ENABLE_ROLLING_LOGS: true
      USE_SIMD_FLAGS: true # Only for pufferfish (safe with java <= 19)
      EULA: true
    stop_grace_period: 2m # must be at least the stop server announce delay + stop delay
    ports:
      - 25560:25565/tcp # Server Port
      - 25560:25565/udp # Query Port
    volumes:
      - /data/minecraft/data:/data
      - /data/minecraft/plugins:/plugins:ro
    networks:
      - default
...
```

### Container logs

*log is normal, no errors, no warnings, container starts normally and minecraft server works fine*
