### ISSUE TITLE
forge fails to process entities

### ISSUE THREAD

**Issue by slyfox1186** [itzg/docker-minecraft-server#2554]
### Describe the problem

The files load, then they disappear and reload, and repeat, then it just gives up eventually.

### Container definition

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      TYPE: "FORGE"
      EULA: "TRUE"
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
```

### Container logs

```
Adding input to inheritance map
Processing entries
Can't Find Class: it/unimi/dsi/fastutil/ints/IntIterator
Can't Find Class: com/mojang/serialization/codecs/RecordCodecBuilder$Instance
Can't Find Class: javax/annotation/ParametersAreNonnullByDefault
Can't Find Class: com/google/common/collect/ImmutableMap$Builder
Can't Find Class: com/mojang/serialization/codecs/RecordCodecBuilder
Can't Find Class: javax/annotation/Nonnull
Can't Find Class: com/google/common/collect/ImmutableMap
Can't Find Class: com/mojang/datafixers/Products$P4
Can't Find Class: com/mojang/datafixers/Products$P8
Can't Find Class: com/mojang/datafixers/Products
Can't Find Class: io/netty/buffer/ByteBuf
Can't Find Class: com/mojang/serialization/Codec
Can't Find Class: javax/annotation/meta/TypeQualifierDefault
Can't Find Class: com/google/common/collect/Immuta
```

**Comment by itzg** [comment]
Please try the following:

1. Temporarily mount a new, empty data directory

```
    volumes:
      - ./minecraft-data-2:/data
```

2. Remove the `restart` policy setting until the configuration is stable
3. Apply the changes with `docker compose up -d`

Please provide the **full** container logs if the problem persists.

**Comment by slyfox1186** [comment]
im having a hard time giving you the entire logs.... they disappear and re-appear and repeat. they eventually just do not come back and so I am struggling to "catch" it before it disappears.... when I do catch it and open it they are incomplete..

but the ultimate result was the same as before. I made the parent directory `chmod 777`

**Comment by itzg** [comment]
I don't understand how the logs disappear and re-appear? It sounds like you haven't correctly applied the changes I requested and I can't help further until you do. Before making those changes perhaps make sure to run `docker compose down` and stop any other related containers you have left over.

**Comment by slyfox1186** [comment]
Yeah they appear and dissapear. So they are there once second and then they are gone the next.

Here is docker-compose logs

```
mc_1  | [init] Changing ownership of /data to 1000 ...
mc_1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 2 1000 1000 4096 Dec 21 18:58 /data'
mc_1  | [init] Resolving type given FORGE
mc_1  | [mc-image-helper] 18:58:19.798 INFO  : Downloading Forge installer 49.0.10 for Minecraft 1.20.4
mc_1  | [mc-image-helper] 18:58:20.297 INFO  : Running Forge installer. This might take a while...
mc_1  | [mc-image-helper] 18:58:41.787 ERROR : 'install-forge' command failed. Version is 1.37.3
mc_1  | me.itzg.helpers.errors.GenericException: Unable to locate forge server jar
mc_1  | 	at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:215)
mc_1  | 	at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:88)
mc_1  | 	at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:103)
mc_1  | 	at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:19)
mc_1  | 	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
mc_1  | 	at picocli.CommandLine.access$1500(CommandLine.java:148)
mc_1  | 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
mc_1  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
mc_1  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
mc_1  | 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
mc_1  | 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
mc_1  | 	at picocli.CommandLine.execute(CommandLine.java:2170)
mc_1  | 	at me.itzg.helpers.McImageHelper.main(McImageHelper.java:157)
mc_1  | [init] ERROR failed to install Forge
```

here is the docker-compose.yml file

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      TYPE: "FORGE"
      EULA: "TRUE"
    volumes:
      - ./minecraft-data-2:/data
```
