### ISSUE TITLE
Modrinth version selection reliably choses the oldest available version

### ISSUE THREAD

**Issue by campbellcole** [itzg/docker-minecraft-server#2579]
### Describe the problem

When downloading mods from Modrinth using `MODRINTH_PROJECTS`, the chosen version is always the oldest available version. This constantly causes version conflicts.

For example, create a new image that only requires Modrinth project `ae2`:
```yaml
services:
  example:
    image: itzg/minecraft-server:latest
    volumes:
       - ./example:/data
    ports:
       - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.20.1"
      MEMORY: "6G"
      MODRINTH_PROJECTS: "ae2"
```

When running this server for the first time, the following version is downloaded:
```
[mc-image-helper] 02:27:15.121 INFO  : Downloading appliedenergistics2-fabric-15.0.10.jar
```

We can see the version list on Modrinth shows this version as the oldest `release` version:
![image](https://github.com/itzg/docker-minecraft-server/assets/10430178/67e86d3f-0ac5-403b-87f3-aba118bda219)

Similarly, if we change the `MODRINTH_ALLOWED_VERSION_TYPE` setting to `beta`, the chosen version changes once again to the oldest beta version, which is even older than the latest release version:
```
[mc-image-helper] 02:31:42.934 INFO  : Downloading appliedenergistics2-fabric-15.0.4-beta.jar
```

I don't know whether or not this is intended. My assumption is that, even when set to `beta`, the latest version should be used. It seemed as though `beta` would enable using even newer versions if they were marked as beta, but would still use the latest available release.

### Container definition

This is my entire compose definition in case there's some dependency management causing this error.
```
services:
  mc-custom:
    image: itzg/minecraft-server:latest
    restart: no
    volumes:
      - ./mc-custom:/data
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.20.1"
      MODRINTH_PROJECTS: "fabric-api:YblXfKtI,cobblemon,bewitchment,botania,sodium,iris,lithium,modmenu,ferrite-core,indium,memoryleakfix,continuity,immediatelyfast,appleskin,rei,create-fabric:beta,create-steam-n-rails,createaddition:beta,cc-tweaked:Scean3uO,create-ore-excavation,bits-and-chisels,rechiseled:9RrwNTgN,rechiseled-create,create-utilities:beta,bellsandwhistles,trash-cans,cccbridge,journeymap,simple-pipes,trinkets,enchantment-descriptions,waystones,item-alchemy,tesseract,expanded-storage,ae2,applied-energistics-2-wireless-terminals,ae2cc,mega,travelersbackpack,crafting-tweaks,inventory-essentials,roughly-enough-professions-rep,myloot"
      #MODRINTH_DOWNLOAD_DEPENDENCIES: "none"
      #MODRINTH_ALLOWED_VERSION_TYPE: "beta"
      #REMOVE_OLD_MODS: "TRUE"
      MODS: |
        https://mediafilez.forgecdn.net/files/4721/545/rer-2.9.0.jar
      MEMORY: "10G"
```

### Container logs

Relevant log lines are in the problem description, there are no other errors to show.
