### ISSUE TITLE
Provide example with CF_MODPACK_MANIFEST

### ISSUE THREAD

**Issue by jagprog5** [itzg/docker-minecraft-server#2581]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

I can't get `CF_MODPACK_MANIFEST` to work, and there are no examples that use this configuration.

[Related issue](https://github.com/itzg/docker-minecraft-server/issues/2136).

Right now in my compose yml I have:

```yml
TYPE: FORGE
CF_MODPACK_MANIFEST: /manifest.json
CF_SLUG: "placeholder_there_is_no_cf_slug"

# read only volume placing manifest.json in container root
```
