### ISSUE TITLE
REMOVE_OLD_MODS overzealous

### ISSUE THREAD

**Issue by jagprog5** [itzg/docker-minecraft-server#2583]
### Describe the problem

Starting with a directory containing three files:

`.env` includes the CF_API_KEY as usual
`compose.yml` (below), and
`manifest.json` (below)

### Container definition

```yaml
services:
  mc:
    image: itzg/minecraft-server:java8-multiarch
    environment:
      EULA: true
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY}
      FORGE_VERSION: "14.23.5.2860"
      VERSION: 1.12.2

      REMOVE_OLD_MODS: "true"

      CF_MODPACK_MANIFEST: /manifest.json
      CF_SLUG: "custom"
      MEMORY: 2G
    volumes:
      - ./data:/data
      - ./manifest.json:/manifest.json:ro
    ports:
      - "25565:25565"

```

```json
{
    "minecraft": {
        "version": "1.12.2",
        "modLoaders": [
            {
                "id": "forge-14.23.5.2860",
                "primary": true
            }
        ]
    },
    "manifestType": "minecraftModpack",
    "manifestVersion": 1,
    "name": "just biomes o plenty",
    "author": "",
    "files": [
        {
            "projectID": 220318,
            "fileID": 3558882,
            "required": true
        }
    ]
}


```

### Container logs

If `REMOVE_OLD_MODS: "true"` then the mod is added to the mods folder, but then it is deleted before the server starts. I don't think this deletion is correct, as the mod isn't "old"; it doesn't make sense to add then immediately remove that same mod. Perhaps I'm misunderstanding something.

Specific process to prove / reproduce:

In one terminal, run a command to see the changes in the files in the directory, filtered by biomes o plenty.

```bash
# changes.log
watchmedo log --patterns="BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar" --ignore-directories --recursive . > changes.log
```

Then in the other, start it up:

```bash
docker-compose up
```

Wait for the server to finish booting, then ctrl-c on the docker compose, then ctrl-c on the watchmedo.

`changes.log` looks like this (shows the creation and deletion):

```txt
on_created(self=<watchdog.tricks.LoggerTrick object at 0x7fcfed45b460>, event=<FileCreatedEvent: event_type=created, src_path='./data/mods/BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar', is_directory=False>)
on_modified(self=<watchdog.tricks.LoggerTrick object at 0x7fcfed45b460>, event=<FileModifiedEvent: event_type=modified, src_path='./data/mods/BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar', is_directory=False>)
...
on_deleted(self=<watchdog.tricks.LoggerTrick object at 0x7fcfed45b460>, event=<FileDeletedEvent: event_type=deleted, src_path='./data/mods/BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar', is_directory=False>)
```
