### ISSUE TITLE
Missing unix_args.txt

### ISSUE THREAD

**Issue by Gyrohammer** [itzg/docker-minecraft-server#2585]
### Describe the problem

Hello!

I'm resurrecting a server via docker_compose thru portainer and got an error upon launch. Something about missing unix argument file. I navigated to the directory (libraries/net/minecraftforge/forge/1.19.2-43.2.14/) and saw that the only file in said directory was:

forge-1.19.2-43.2.14-universal.jar

Unsure as to why this has happened, the server was running fine for a few months, taken offline for another few months, and now is throwing the aformentioned error. About 5 months between hibernation and resurrection.

Things I've tried:

- Re-pulling/re-creating the image
- Ensuring permissions are correct (it runs as root so this shouldnt be an issue. Yes I know I need to change that.) 
- Switching java versions (>17)

The server is running Ubuntu and a bunch of other docker containers, managed via portainer. Nothing really remarkable about the setup. 

Let me know if more information is required! 

### Container definition

```
version: '3.7'

services:
  mc:
    image: itzg/minecraft-server:java17
    ports:
      - "30553:25565"
    environment:
     EULA: "TRUE"
     TYPE: FTBA
     FTB_MODPACK_ID: "101"
     FTBA_MODPACK_VERSION: "6503"
     MEMORY: 12G
     PUID: 0
     PGID: 0
    restart: unless-stopped
    volumes:
      - /dockmedia/minecraft/ftb_plexi:/data
      
  backups:
    image: itzg/mc-backup
    environment:
     BACKUP_INTERVAL: "12h"
     INITIAL_DELAY: "2m"
     PRUNE_BACKUPS_DAYS: 7
     PLAYERS_ONLINE_CHECK_INTERVAL: 10m
     PAUSE_IF_NO_PLAYERS: "false"
     TAR_COMPRESS_METHOD": zstd
     ZSTD_PARAMETERS: --long=25 --auto-threads=logical
     TZ: America/New_York
      # instead of network_mode below, could declare RCON_HOST
      # RCON_HOST: mc
    restart: unless-stopped
    volumes:
      # mount the same volume used by server, but read-only
     - /dockmedia/minecraft/ftb_plexi:/data:ro
      # use a host attached directory so that it in turn can be backed up
      # to external/cloud storage
     - /thinkpool/backups/minecraft/plexiglass:/backups
    # share network namespace with server to simplify rcon access
    network_mode: "service:mc"

volumes:
  mc: {}
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 16 1000 1000 4096 Jan 10 21:36 /data'
[init] FTB modpack ID 101, version ID 6503 is ready to go
[mc-image-helper] 21:40:30.074 INFO  : Created/updated 1 property in /data/server.properties
[init] Setting initial memory to 12G and max to 12G
[init] Using Forge supplied run.sh script...
Error: could not open `libraries/net/minecraftforge/forge/1.19.2-43.2.14/unix_args.txt'
2024-01-10T21:40:33.876Z	WARN	mc-server-runner	Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.	{"exitCode": 1}
2024-01-10T21:40:33.876Z	INFO	mc-server-runner	Done
```
