### ISSUE TITLE
CF_MODPACK_MANIFEST not using overrides

### ISSUE THREAD

**Issue by jagprog5** [itzg/docker-minecraft-server#2586]
### Describe the problem

CF_MODPACK_MANIFEST is not adding the override files into the data config folder.

### Container definition

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8-multiarch

    # needed with autostop
    restart: no
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY}
      FORGE_VERSION: "14.23.5.2860"
      VERSION: 1.12.2

      # wait for https://github.com/itzg/docker-minecraft-server/issues/2530
      # REMOVE_OLD_MODS: "true"
      ENABLE_ROLLING_LOGS:  "true"

      ENABLE_AUTOSTOP: "true"
      OVERRIDE_SERVER_PROPERTIES: "true"

      # resource constraints
      MAX_PLAYERS: "10"
      MAX_MEMORY: "8G"
      VIEW_DISTANCE: "8"

      # game preference
      CF_MODPACK_MANIFEST: /manifest.json
      CF_SLUG: "custom"
      DIFFICULTY: "hard"
      LEVEL: "word-data"
      ENABLE_WHITELIST: "true"

    volumes:
      - ./data:/data
      - ./modpack-client/manifest.json:/manifest.json:ro

    env_file:
      - .env
```
