### ISSUE TITLE
how to use docker compose bukkit server ?

### ISSUE THREAD

**Issue by Pristar4** [itzg/docker-minecraft-server#266]

**Comment by itzg** [comment]
One example is to save the following as the file `docker-compose.yml` and run `docker-compose up -d` to start the container detached.

```yaml
version: '3.4'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: BUKKIT
    ports:
      - 25565:25565
    volumes:
      - ./bukkit-data:/data
```
