### ISSUE TITLE
Server not starting with fantasy-minecraft-fabric

### ISSUE THREAD

**Issue by vablings** [itzg/docker-minecraft-server#2685]
### Describe the problem

For some reason the server seems to hang after starting and refuses all connections 

### Container definition

```
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: true
      TYPE: AUTO_CURSEFORGE
      CF_SLUG: fantasy-minecraft-fabric
      MEMORY: 16G
      VERSION: 1.20.1
      DISABLE_HEALTHCHECK: TRUE
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
      - ./downloads:/downloads
      - ./modpacks:/modpacks:ro
    ports:
      - "7777:7777"
```

### Container logs

https://hastebin.com/share/raseqivigu.ruby
