### ISSUE TITLE
Invalid parameter provided for 'manage-users' command: UUID cannot be provided

### ISSUE THREAD

**Issue by mariuszste** [itzg/docker-minecraft-server#2697]
### Describe the problem

Crash when trying to add `WHITELIST` on a `1.5.2 vanilla` `online mode` server via UUID

Adding via username works but I would prefer to use UUID since they are guaranteed to not change. The doc says `A list of usernames and/or UUIDs separated by comma` so I assume the crash on UUID is a bug

### Container definition

```yaml
version: '3.9'
services:
  minecraft152:
    image: itzg/minecraft-server:java8
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 25152:25152
    volumes:
      - /home/redacted/minecraft/1.5.2:/data
    environment:
      - VERSION=1.5.2
      - TYPE=VANILLA
      - EULA=TRUE
      - SERVER_PORT=25152
      - INIT_MEMORY=1G
      - MAX_MEMORY=2G
      - MOTD=nezu test server
      - DIFFICULTY=hard
      - OVERRIDE_WHITELIST=true
      - WHITELIST=ec71604f-dac9-4f30-9bdf-227cd6b6843c
      - OPS=ec71604f-dac9-4f30-9bdf-227cd6b6843c
      - ENABLE_COMMAND_BLOCK=false
      - SPAWN_PROTECTION=0
      - VIEW_DISTANCE=10
      - SEED=915375531
      - MODE=survival
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 2 1000 1000 4096 Mar  5 13:19 /data'
[init] Resolving type given VANILLA
[init] Resolved version given 1.5.2 into 1.5.2
[init] Enabling whitelist functionality
[init] Setting mode
[mc-image-helper] 13:29:08.865 INFO  : Created/updated 1 property in /data/server.properties
[mc-image-helper] 13:29:10.095 ERROR : Invalid parameter provided for 'manage-users' command: UUID cannot be provided: ec71604f-dac9-4f30-9bdf-227cd6b6843c
```
