### ISSUE TITLE
Multiple Ports

### ISSUE THREAD

**Issue by the-gray-ghost** [itzg/docker-minecraft-server#2725]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

The mod "Simple Voice Chat" requires opening up a second port 24454/udp on the server.  However, I have not found a way to do that with this image as it only allows a single port to be assigned.

**Comment by itzg** [comment]
You can bind any number of ports you want in your container. The image doesn't dictate the port mappings, it just advertises 25565 as possible port to map.

**Comment by the-gray-ghost** [comment]
Understood.  But I need two separate ports both mapped to the same container.

25565:25565
24454:24454

As far as I can tell, this has to be done at creation.  It appears the only way to do it currently is with Compose.  I my suggestion would be to have the ability to add additional ports in the same way that we add additional "Environment Variables" under the "Optional Settings" when we create the container with your image.

**Comment by itzg** [comment]
Yes at creation time in the compose file you would do:

```yaml
services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
      - "24454:24454"
    environment:
      EULA: true
      # ...etc
```
