### ISSUE TITLE
Add tailscale example docker compose

### ISSUE THREAD

**Issue by Nilon123456789** [itzg/docker-minecraft-server#2744]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

It could be nice if you add this docker compose example file to allow quick tailscale minecraft server
```yaml
version: "3"
services:
  tailscale-client:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: tailscale-minecraft # This name will be the one on the tailscale network
    environment:
      TS_AUTHKEY: "tskey-auth-PLACE-YOUR-KEY-HERE"
      TS_STATE_DIR: "/var/lib/tailscale"
      TS_USERSPACE: "FALSE" # Only needed if using AUTOPAUSE
    volumes:
      - ${PWD}/ts-minecraft/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  minecraft-server:
    image: itzg/minecraft-server
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      # ENABLE_AUTOPAUSE: "TRUE"
      # AUTOPAUSE_KNOCK_INTERFACE: "tailscale0"
      # MAX_TICK_TIME: "-1"
    volumes:
      - minecraftserver:/data
    tty: true
    network_mode: container:tailscale
    
volumes:
  minecraftserver:
```
