### ISSUE TITLE
AUTO_CURSEFORGE gives 503 Service Unavailable

### ISSUE THREAD

**Issue by jagprog7** [itzg/docker-minecraft-server#2745]
### Describe the problem

Please see the logs below - fails to pull modpack and start.

Note that this container definition hasn't changed and worked previously - might be a curseforge api change...

Also note that the image is up to date:

```bash
$ docker pull itzg/minecraft-server:java8-multiarch
java8-multiarch: Pulling from itzg/minecraft-server
Digest: sha256:cdac1b2041a19e9446990ae9b91cac5470f16067a40a70c30daab40f0a355a2f
Status: Image is up to date for itzg/minecraft-server:java8-multiarch
docker.io/itzg/minecraft-server:java8-multiarch
```

See repo [here](https://github.com/jagprog5/modpack-server/tree/71bb7612d0d22e72759fe4ca4aa657dae6bf685f).

### Container definition

```yaml
version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8-multiarch

    # needed with autostop
    restart: no
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY}
      FORGE_VERSION: "14.23.5.2860"
      VERSION: 1.12.2

      ENABLE_ROLLING_LOGS:  "true"

      ENABLE_AUTOSTOP: "true"
      # shouldn't be too small or else a backup could be created per startup
      # 8 hours in seconds
      AUTOSTOP_TIMEOUT_EST: 28800
      AUTOSTOP_TIMEOUT_INIT: 28800
      OVERRIDE_SERVER_PROPERTIES: "true"

      # resource constraints
      MAX_PLAYERS: "10"
      MAX_MEMORY: "10G"
      VIEW_DISTANCE: "14"
      USE_AIKAR_FLAGS: "true"

      # game preference
      CF_MODPACK_ZIP: /profile.zip
      CF_SLUG: "custom"
      # needed since incorrectly declared as server side when it's only client side
      CF_EXCLUDE_MODS: "244447"
      DIFFICULTY: "hard"
      LEVEL: "world-data"
      ENABLE_COMMAND_BLOCK: "true"
      ENABLE_WHITELIST: "true"
      RCON_CMDS_STARTUP:  |-
        # gamerule mobGriefing false DISABLED BY MOD
        gamerule commandBlockOutput false
        gamerule logAdminCommands false
    
    depends_on:
      restore-backup:
        condition: service_completed_successfully

    volumes:
      - ./data:/data
      - ./modpack-client/profile.zip:/profile.zip:ro

    env_file:
      - .env
  
  restore-backup:
    image: itzg/mc-backup
    restart: no
    entrypoint: restore-tar-backup
    volumes:
      - ./data:/data
      - ./data_backup:/backups:ro
  
  backups:
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      RCON_HOST: mc
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
      BACKUP_INTERVAL: "1d"
      PRUNE_BACKUPS_DAYS: 7

      TAR_COMPRESS_METHOD: "zstd"
      ZSTD_PARAMETERS: "-10 --long=25 --single-thread"
    volumes:
      - ./data:/data:ro
      - ./data_backup:/backups

```

### Container logs

```
modpack-server-mc-1  | [init] Changing ownership of /data to 1000 ...
modpack-server-mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 2 1000 1000 4096 Mar 29 04:40 /data'
modpack-server-mc-1  | [init] Autostop functionality enabled
modpack-server-mc-1  | [init] Starting RCON commands
modpack-server-mc-1  | [init] Rcon cmds functionality enabled
modpack-server-mc-1  | [mc-image-helper] 04:40:13.427 INFO  : Installing modpack 'John's 1.12.2' version null from provided modpack zip
modpack-server-mc-1  | [mc-image-helper] 04:40:13.565 ERROR : 'install-curseforge' command failed. Version is 1.38.7
modpack-server-mc-1  | me.itzg.helpers.http.FailedRequestException: HTTP request of https://api.curseforge.com/v1/mods/search?gameId=432&slug=dynamiclights-reforged failed with 503 Service Unavailable: Fetching object content
modpack-server-mc-1  |  at me.itzg.helpers.http.FetchBuilderBase.lambda$failedRequestMono$2(FetchBuilderBase.java:195)
modpack-server-mc-1  |  at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
modpack-server-mc-1  |  at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:122)
modpack-server-mc-1  |  at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:129)
modpack-server-mc-1  |  at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
modpack-server-mc-1  |  at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)
modpack-server-mc-1  |  at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:194)
modpack-server-mc-1  |  at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
modpack-server-mc-1  |  at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071)
modpack-server-mc-1  |  at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118)
modpack-server-mc-1  |  at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
modpack-server-mc-1  |  at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
modpack-server-mc-1  |  at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415)
modpack-server-mc-1  |  at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:446)
modpack-server-mc-1  |  at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:500)
modpack-server-mc-1  |  at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:782)
modpack-server-mc-1  |  at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114)
modpack-server-mc-1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
modpack-server-mc-1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
modpack-server-mc-1  |  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
modpack-server-mc-1  |  at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
modpack-server-mc-1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
modpack-server-mc-1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
modpack-server-mc-1  |  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
modpack-server-mc-1  |  at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
modpack-server-mc-1  |  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
modpack-server-mc-1  |  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
modpack-server-mc-1  |  at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
modpack-server-mc-1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
modpack-server-mc-1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
modpack-server-mc-1  |  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
modpack-server-mc-1  |  at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
modpack-server-mc-1  |  at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1338)
modpack-server-mc-1  |  at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1387)
modpack-server-mc-1  |  at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
modpack-server-mc-1  |  at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
modpack-server-mc-1  |  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
modpack-server-mc-1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
modpack-server-mc-1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
modpack-server-mc-1  |  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
modpack-server-mc-1  |  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
modpack-server-mc-1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
modpack-server-mc-1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
modpack-server-mc-1  |  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
modpack-server-mc-1  |  at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
modpack-server-mc-1  |  at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
modpack-server-mc-1  |  at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
modpack-server-mc-1  |  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
modpack-server-mc-1  |  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
modpack-server-mc-1  |  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
modpack-server-mc-1  |  at java.lang.Thread.run(Thread.java:748)
modpack-server-mc-1  |  Suppressed: java.lang.Exception: #block terminated with an error
modpack-server-mc-1  |          at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
modpack-server-mc-1  |          at reactor.core.publisher.Mono.block(Mono.java:1712)
modpack-server-mc-1  |          at me.itzg.helpers.curseforge.CurseForgeInstaller.resolveExcludeIncludes(CurseForgeInstaller.java:658)
modpack-server-mc-1  |          at me.itzg.helpers.curseforge.CurseForgeInstaller.processModpack(CurseForgeInstaller.java:543)
modpack-server-mc-1  |          at me.itzg.helpers.curseforge.CurseForgeInstaller.processModpackManifest(CurseForgeInstaller.java:295)
modpack-server-mc-1  |          at me.itzg.helpers.curseforge.CurseForgeInstaller.lambda$installFromModpackZip$0(CurseForgeInstaller.java:132)
modpack-server-mc-1  |          at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:213)
modpack-server-mc-1  |          at me.itzg.helpers.curseforge.CurseForgeInstaller.installFromModpackZip(CurseForgeInstaller.java:129)
modpack-server-mc-1  |          at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:222)
modpack-server-mc-1  |          at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:30)
modpack-server-mc-1  |          at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
modpack-server-mc-1  |          at picocli.CommandLine.access$1500(CommandLine.java:148)
modpack-server-mc-1  |          at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
modpack-server-mc-1  |          at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
modpack-server-mc-1  |          at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
modpack-server-mc-1  |          at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
modpack-server-mc-1  |          at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
modpack-server-mc-1  |          at picocli.CommandLine.execute(CommandLine.java:2170)
modpack-server-mc-1  |          at me.itzg.helpers.McImageHelper.main(McImageHelper.java:159)
modpack-server-mc-1  | [init] ERROR failed to auto-install CurseForge modpack
```
