### ISSUE TITLE
Constant timeouts and download resilience issues, specially with slower hosts such as fabricmc

### ISSUE THREAD

**Issue by icanhasjonas** [itzg/docker-minecraft-server#2752]
### Describe the problem

Downloading mods, from anywhere but north america, seems tough because of the tight read timeouts and retry policy in the mc-image-helper tool?

```
[mc-image-helper] 03:47:48.799 WARN  : [8478f765-1, L:/192.168.228.2:37918 - R:meta.fabricmc.net/172.67.151.177:443] The connection observed an error
```

We're getting constant timeouts here :-) And it would seem the timeouts are set quite low as default, and no retry. 

### Container definition

```
services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: xxxxxx
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/prominence-2-rpg
      MEMORY: 4G
      CF_OVERRIDES_SKIP_EXISTING: true
    volumes:
      - ./mc-data:/data
      - ./downloads:/downloads
```

### Container logs

```
[mc-image-helper] 03:47:48.799 WARN  : [8478f765-1, L:/192.168.228.2:37918 - R:meta.fabricmc.net/172.67.151.177:443] The connection observed an error
```
