### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by maxens-git** [itzg/docker-minecraft-server#2772]
### Describe the problem

I have this error when i want to start my docker container

### Container definition

```
version: '3.3'
services:
     minecraft-serve:
        volumes:
            - '/docker/minecraft-spigot/:/data'
        restart: unless-stopped
        environment:
            - TYPE=SPIGOT
            - EULA=TRUE
            - VERSION=1.20
            #- MODE=survival
            - EXEC_DIRECTLY=true
            - MEMORY=5G
            - MAX_PLAYERS=50
            - ONLINE_MODE=false
        ports:
            - '25565:25565'
        container_name: minecraft-spigot
        network_mode: nginx-proxy-manager_default
        image: itzg/minecraft-server

```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 11 1000 1000 4096 Dec  2 17:40 /data'

[init] Resolving type given SPIGOT

[init] Downloading Spigot from https://download.getbukkit.org/spigot/spigot-1.20.jar ...

[mc-image-helper] 08:42:35.024 INFO  : Created/updated 1 property in /data/server.properties

[init] Setting initial memory to 5G and max to 5G

[init] Starting the Minecraft server...

Unbundling libraries to /data/bundler

Starting server

Unsupported Java detected (65.0). Only up to Java 20 is supported.
```
