### ISSUE TITLE
Add git and Git-lfs package for FastBack mod

### ISSUE THREAD

**Issue by BlownIntoSpace** [itzg/docker-minecraft-server#2780]
### Enhancement Type

A completely new feature

### Describe the enhancement

The [FastBack](https://pcal43.github.io/fastback/native-git.html) mod uses git to manage world versions. I believe it used to use jgit in the past, but now requires git and git-lfs to be natively installed.

I have tested it by installing the git binaries using 
```
FROM itzg/minecraft-server:latest
RUN apt-get update && apt-get install -y git git-lfs
```
and it seems to run well when it works, but the fastback mod does seem to be unable to find the git executables half the time if i dont manually rebuild the image every time i launch the server, but that could just be an issue on my end.

Git would also require a .gitconfig file in the containers /etc/gitconfig directory, which i just set to something like this:
```
[user]
	name = Minecraft Server
	email = server@example.com
	username = minecraft-server
[init]
	defaultBranch = main
```
which could be easily overridden using volumes if anyone wanted to have their own info in there.

**Comment by itzg** [comment]
git is already installed, but git-lfs would indeed need to be added here (and same for other distros)

https://github.com/itzg/docker-minecraft-server/blob/c666cf28f4b557ba3dba4075d9a5c5bec8a1fd8e/build/ubuntu/install-packages.sh#L18

Good point about the default gitconfig file. I would have completely missed that. 

If you want to PR those changes, then that would work for me.

**Comment by cn-ml** [comment]
Thanks a lot, previously i always built my own images with

```yaml
build:
  dockerfile_inline: |-
    FROM itzg/minecraft-server:java17
    RUN apt-get update \
      && apt-get install -y git-lfs \
      && rm -rf /var/lib/apt/lists/*
  tags:
    - itzg/minecraft-server:java17-gitlfs
```

This makes it a lot easier to update my images.
