### ISSUE TITLE
RLCraft LootTweaker failed custom NetworkCheckHandler

### ISSUE THREAD

**Issue by bennyyy999** [itzg/docker-minecraft-server#2790]
### Describe the problem

I used the [example docker-compose file](https://github.com/itzg/docker-minecraft-server/blob/master/examples/docker-compose-rlcraft.yml) and adapted it to the new curseforge stuff, the server is also online, but when I wanna join it gives me this error: 

> Server Mod rejections: LootTweaker: Failed mod's custom NetworkCheckHandler FMLMod:loottweaker{0.3.1}

In the server mods folder I see `LootTweaker-0.3.1+MC1.12.2.jar` and my local instance also has 0.3.1 installed.
What is the problem here?

### Container definition

```
version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:java8
    volumes:
      - data:/data
      - ./modpacks:/modpacks:ro
    environment:
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/rlcraft/files/4612979"
      EULA: "true"
      TYPE: "FORGE"
      VERSION: "1.12.2"
      FORGE_VERSION: "14.23.5.2860"
      OVERRIDE_SERVER_PROPERTIES: "true"
      DIFFICULTY: "hard"
      MAX_TICK_TIME: "-1"
      ALLOW_FLIGHT: "true"
      ENABLE_COMMAND_BLOCK: "true"
      VIEW_DISTANCE: "10"
      MAX_MEMORY: "12G"
    ports:
      - 25565:25565

volumes:
  data:

```

### Container logs

```
Paste logs here
```
