### ISSUE TITLE
Restarted container, now it wont boot

### ISSUE THREAD

**Issue by TsunayoshiSawada** [itzg/docker-minecraft-server#2808]
### Describe the problem

Just restarted the container and now it wont boot, was working fine until 1.20.4

### Container definition

```
version: "3.9"
# make sure you edit the server-name with your server name
services:
  voxel:
    image: itzg/minecraft-server
    container_name: minecraft-kaizoku
    user: "1001:1001"
    # restart: unless-stopped
    environment:
      - EULA=TRUE
      - MEMORY=6G
      - TYPE=PAPER
    # This is most important - make sure your volume path is unique and exists - this is where your config will exist
    volumes:
      - /home/ubuntu/containers/minecraft-servers/kaizoku:/data
    networks:
      - minecraft-kaizoku
    # Make sure you use a unique port, check with Sawada for existing dns records if you are using this on a server with multiple minecrafts
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true

networks:
  minecraft-kaizoku:
    name: minecraft-kaizoku
    driver: bridge```


### Container logs

```
[init] Downloading PaperMC 1.20.5 (build 22) ...
[init] Setting initial memory to 6G and max to 6G
[init] Starting the Minecraft server...
Applying patches
Starting org.bukkit.craftbukkit.Main
Exception in thread "ServerMain" java.lang.UnsupportedClassVersionError: org/bukkit/craftbukkit/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

```
