### ISSUE TITLE
rcon commands in helm config file not working

### ISSUE THREAD

**Issue by Lite5h4dow** [itzg/docker-minecraft-server#2817]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

rcon commands on startup, first connect, and last disconnect don't seem to apply.

would appreciate it if this compatibility was extended to the helm config unless there is another way to apply these, for example environment variables

```yaml
rcon:
    # If you enable this, make SURE to change your password below.
    enabled: true
    # By default, the container will generate a random password at startup
    # to ensure internal RCON tooling, including a backup container,
    # can be used, but the password is secure.
    withGeneratedPassword: false
    port: 25575
    rconCmdsStartup: |-
      /gamerule doFireTick false
      /pregen start 1000
    rconCmdsFirstConnect: |-
      /pregen stop
    rconCmdsLastDisconnect: |-
      /pregen start 1000
```
