### ISSUE TITLE
Possible Fabric issue? (With a tinge of user error)

### ISSUE THREAD

**Issue by DeamonDrakX** [itzg/docker-minecraft-server#2830]
### Describe the problem

Currently trying to get the Prominence 2 (v2.8.0hf) from Curseforge to run in a tasty continer via this awesome image. However, after the world spins up I get this extremely ominious error

mc-1  | io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
mc-1  | [13:44:32] [Netty Epoll Server IO #35/ERROR]: Exception occurred in netty pipeline

Which happens literally every 5 seconds. This doesn't occur when running the modpack on (bare metal/host?). 
While users can connect to the server and do things just fine, I'm not sure where/when this error will actually impact experience. 

I was thinking of just running the modpack outside of the curseforge type context and with type=FABRIC but the example docker-compose yaml doesn't shine a good light on how to get all the mod contents into the volume (though I might just point the volume at the baremetal directory for funsies)

Any insight would be appreciated.

### Container definition

```

version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:${IMAGE_TAG:-java17}
    volumes:
    - ./modpacks:/modpacks:ro
    - data:/data
    environment:
      EULA: "true"
      MEMORY: 16G
      ENABLE_RCON: "false"
      VERSION: "1.20.1"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/Prominence_2.8.0.zip

    ports:
      - "47779:25565"
    restart: unless-stopped

volumes:
  data: {}

```

### Container logs

```
mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 4 1000 1000 4096 May 18 13:40 /data'
mc-1  | [init] Resolved version given 1.20.1 into 1.20.1
mc-1  | [init] Looking for Feed-The-Beast / CurseForge server modpack.
mc-1  | [init] detected FTB, changing properties path to /data/FeedTheBeast/server.properties
mc-1  | [init] Setting initial memory to 16G and max to 16G
mc-1  | [init] Running FTB /data/FeedTheBeast/start.sh in /data/FeedTheBeast ...

```
