### ISSUE TITLE
Unable to create new containers with 1.20.5 and 1.20.6

### ISSUE THREAD

**Issue by danabrey** [itzg/docker-minecraft-server#2840]
### Describe the problem

I'm having an issue creating new containers for version 1.20.5 and 1.20.6 on Ubuntu 22.04.

I've pulled the latest versions of both of the java17 and java21 tagged images. I may be doing something silly!

### Container definition

With java21:

```
version: "3"
services:
  server:
    image: itzg/minecraft-server:java21
    volumes:
      - /data/minecraft-challenge-2024:/data
    ports:
      - "25565:25565"
    environment:
      - "EULA=TRUE"
      - "VERSION=1.20.6"
      - "MEMORY=4G"
```

With java17:

```
version: "3"
services:
  server:
    image: itzg/minecraft-server:java17
    volumes:
      - /data/minecraft-challenge-2024:/data
    ports:
      - "25565:25565"
    environment:
      - "EULA=TRUE"
      - "VERSION=1.20.6"
      - "MEMORY=4G"
```

### Container logs

With java21: 

```
server_1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 May 22 12:36 /data'
server_1  | [init] ERROR: your Docker provider has an annoying flaw where it
server_1  | [init]        tries to set PATH even though the container establishes
server_1  | [init]        a very specific value.
server_1  | [init] ERROR: could not locate path that contains java
minecraftchallenge2024_server_1 exited with code 1
```

With java17:

```
server_1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 May 22 12:37 /data'
server_1  | [init] Resolving type given VANILLA
server_1  | [init] Resolved version given 1.20.6 into 1.20.6
server_1  | [init] Downloading 1.20.6 server...
server_1  | [init] Creating server properties in /data/server.properties
server_1  | [init] Disabling whitelist functionality
server_1  | [mc-image-helper] 12:40:44.537 INFO  : Created/updated 4 properties in /data/server.properties
server_1  | [init] Setting initial memory to 4G and max to 4G
server_1  | [init] Starting the Minecraft server...
server_1  | Error: LinkageError occurred while loading main class net.minecraft.bundler.Main
server_1  | 	java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
server_1  | 2024-05-22T12:40:51.822Z	WARN	mc-server-runner	Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.	{"exitCode": 1}
server_1  | 2024-05-22T12:40:51.822Z	INFO	mc-server-runner	Done
minecraftchallenge2024_server_1 exited with code 1
```

**Comment by itzg** [comment]
You definitely need to be using the java21 image but note the error 

```
server_1  | [init] ERROR: your Docker provider has an annoying flaw where it
server_1  | [init]        tries to set PATH even though the container establishes
server_1  | [init]        a very specific value.
```

Are you using Portainer? It's usually the one that breaks the PATH variable like that.

A `docker compose down` and then `docker compose up -d` might fix it since it would give a fresh container (but existing volume mapping) to be created.

**Comment by danabrey** [comment]
Hmm, no, I'm just using regular `docker` and `docker compose` via the CLI.

I'll make sure I'm not using super old versions, it could be that.

**Comment by JohnyRicio** [comment]
I have same issue on my server and also on the local machine. 

`Error: LinkageError occurred while loading main class net.minecraft.bundler.Main
        java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0`

I am traiing to start server on my qnap ts431 server and there I need to run from image java17, because of arm32. On my local windows machine it does not work as well with same error. Looks like that old version of java is inside of the container.

**Comment by darkweasel77** [comment]
Same issue - regular` docker` and `docker-compose`

**Comment by itzg** [comment]
@darkweasel77 , run the following and provide the output of those

```
docker image inspect -f '{{json .Config.Labels}}' itzg/minecraft-server
docker run --rm --entrypoint bash itzg/minecraft-server -c 'echo $PATH; ls -l /opt/java/openjdk/bin/java'
```

**Comment by darkweasel77** [comment]
If I specify something other than latest (say java11 or java17): 
```
  mcworld:
    container_name: mcworld
    image: itzg/minecraft-server:java11
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    volumes:
      - ./_minecraft:/data
    restart: unless-stopped
```

I get: 
```
mcworld                 | [init] Resolved version given LATEST into 1.20.6
mcworld                 | [init] Downloading 1.20.6 server...
mcworld                 | [mc-image-helper] 03:27:59.322 INFO  : Created/updated 1 property in /data/server.properties
mcworld                 | [init] Setting initial memory to 1G and max to 1G
mcworld                 | [init] Starting the Minecraft server...
mcworld                 | Error: LinkageError occurred while loading main class net.minecraft.bundler.Main
mcworld                 |       java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 55.0
mcworld                 | 2024-06-08T03:28:09.938Z      WARN    mc-server-runner        Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.        {"exitCode": 1}
mcworld                 | 2024-06-08T03:28:09.938Z      INFO    mc-server-runner        Done

```

**Comment by darkweasel77** [comment]
@itzg I just installed jdk21 to see if that made a difference.

```
> docker image inspect -f '{{json .Config.Labels}}' itzg/minecraft-server
{"org.opencontainers.image.authors":"Geoff Bourne <itzgeoff@gmail.com>","org.opencontainers.image.created":"2024-06-05T23:48:47.659Z","org.opencontainers.image.description":"Docker image that provides a Minecraft Server that will automatically download selected version at startup","org.opencontainers.image.licenses":"Apache-2.0","org.opencontainers.image.ref.name":"ubuntu","org.opencontainers.image.revision":"c828985ebe36c44ef57d5af133e1bf38f534ea31","org.opencontainers.image.source":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.title":"docker-minecraft-server","org.opencontainers.image.url":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.version":"java21"}
```

and 
```
 docker run --rm --entrypoint bash itzg/minecraft-server -c 'echo $PATH; ls -l /opt/java/openjdk/bin/java'
/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-rwxr-xr-x 1 root root 12920 Apr 17 07:05 /opt/java/openjdk/bin/java
```

**Comment by itzg** [comment]
@darkweasel77 I really wanted to see what image you had pulled previously, which I why I requested the output of the specific command I provided. In any case, It'll probably work now.

**Comment by darkweasel77** [comment]
@itzg I'll set it back; w/ jdk21 I'm back to getting what I posted above.

**Comment by darkweasel77** [comment]
```
  mcworld:
    container_name: mcworld
    image: itzg/minecraft-server:java17
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    volumes:
      - ./_minecraft:/data
    restart: unless-stopped
```

```
> which java
/usr/bin/java
```

```
> java --version
openjdk 17.0.11 2024-04-16
OpenJDK Runtime Environment (build 17.0.11+9-Ubuntu-122.04.1)
OpenJDK 64-Bit Server VM (build 17.0.11+9-Ubuntu-122.04.1, mixed mode, sharing)
```


```
mcworld                 | [init] Resolved version given LATEST into 1.20.6
mcworld                 | [mc-image-helper] 03:37:23.077 INFO  : Created/updated 1 property in /data/server.properties
mcworld                 | [init] Setting initial memory to 1G and max to 1G
mcworld                 | [init] Starting the Minecraft server...
mcworld                 | Error: LinkageError occurred while loading main class net.minecraft.bundler.Main
mcworld                 |       java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
mcworld                 | 2024-06-08T03:37:32.329Z      WARN    mc-server-runner        Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.        {"exitCode": 1}
mcworld                 | 2024-06-08T03:37:32.329Z      INFO    mc-server-runner        Done
```

```
> docker image inspect -f '{{json .Config.Labels}}' itzg/minecraft-server
{"org.opencontainers.image.authors":"Geoff Bourne <itzgeoff@gmail.com>","org.opencontainers.image.created":"2024-06-05T23:48:47.659Z","org.opencontainers.image.description":"Docker image that provides a Minecraft Server that will automatically download selected version at startup","org.opencontainers.image.licenses":"Apache-2.0","org.opencontainers.image.ref.name":"ubuntu","org.opencontainers.image.revision":"c828985ebe36c44ef57d5af133e1bf38f534ea31","org.opencontainers.image.source":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.title":"docker-minecraft-server","org.opencontainers.image.url":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.version":"java21"}
```

```
> docker run --rm --entrypoint bash itzg/minecraft-server -c 'echo $PATH; ls -l /opt/java/openjdk/bin/java'
/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-rwxr-xr-x 1 root root 12920 Apr 17 07:05 /opt/java/openjdk/bin/java
```

**Comment by darkweasel77** [comment]
If i use:
```
  mcworld:
    container_name: mcworld
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    volumes:
      - ./_minecraft:/data
    restart: unless-stopped
```

I get: 
```
mcworld                 | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 13 1000 1000 4096 Jun  8 03:27 /data'
mcworld                 | [init] ERROR: your Docker provider has an annoying flaw where it
mcworld                 | [init]        tries to set PATH even though the container establishes
mcworld                 | [init]        a very specific value.
mcworld                 | [init] ERROR: could not locate path that contains java
mcworld exited with code 1
```
