### ISSUE TITLE
Connection refused: getsockopt

### ISSUE THREAD

**Issue by cssinate** [itzg/docker-minecraft-server#2863]
### Describe the problem

I'm really sorry - I'm a bit of a noob with all things server management. Ever since the update where they required Java 21 (1.20.4?) we haven't been able to connect to our server. I just get "Connection refused: getsockopt". There are no logs since that update happened.

### Container definition

```
minecraft:
    container_name: minecraft
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    # version: "1.20.4"
    image: itzg/minecraft-server
    restart: unless-stopped
    volumes:
      - ./minecraft:/data
    environment:
      - EULA=TRUE
```

### Container logs

```
Paste logs here
```
