### ISSUE TITLE
Getting a java.lang.UnsupportedClassVersionError running PAPER

### ISSUE THREAD

**Issue by joejulian** [itzg/docker-minecraft-server#2905]
### Describe the problem

When attempting to run using PAPER, the jar was built with 65.0 - newer than the 61.0 that's in this image.

### Container definition

Using the helm chart, I'm installing with these values:
```
minecraftServer:
  difficulty: easy
  enforceSecureProfile: false
  eula: true
  maxBuildHeight: 2048
  maxTickTime: -1
  memory: 3072M
  onlineMode: false
  serviceType: LoadBalancer
  type: PAPER
  whitelist: XXX,YYY
  ops: XXX
persistence:
  dataDir:
    enabled: true
```

### Container logs

```
[init] Running as uid=1000 gid=3000 with /data as 'drwxrwxrwx 13 1000 3000 4096 Jun 15 21:46 /data'
[init] Resolving type given PAPER
[mc-image-helper] 21:52:59.765 INFO  : Resolved paper to version 1.20.6 build 145
[mc-image-helper] 21:53:00.016 INFO  : The file /data/paper-1.20.6-145.jar is already up to date
[init] server.properties already created and managed manually
[init] Updating ops
[init] XXX already present in ops.json, skipping
[init] Updating whitelist
[init] XXX already present in whitelist.json, skipping
[init] YYY already present in whitelist.json, skipping
[init] Setting initial memory to 3072M and max to 3072M
[init] Starting the Minecraft server...
Starting org.bukkit.craftbukkit.Main
Exception in thread "ServerMain" java.lang.UnsupportedClassVersionError: org/bukkit/craftbukkit/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:38)
	at java.base/java.lang.Thread.run(Unknown Source)
2024-06-15T21:53:07.156Z	INFO	mc-server-runner	Done

```
