### ISSUE TITLE
Error with minecraft 1.21 Fabric

### ISSUE THREAD

**Issue by MohamedAliRashad** [itzg/docker-minecraft-server#2907]
### Describe the problem

Server Craches

### Container definition

```
version: "3.8"

services:
  minecraft-server2:
    image: itzg/minecraft-server
    container_name: minecraft-server2
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      EULA: "true"
      ONLINE_MODE: "false"
      DIFFICULTY: "normal"
      PVP: "false"
      SERVER_NAME: "Secrets of Life"
      MOTD: "Welcome to Secrets of Life!"
      SEED: "-5048147120987527884"
      TYPE: FABRIC
      VERSION: "1.21"
      MODRINTH_PROJECTS: |
        fabric-api
        cloth-config
      REMOVE_OLD_MODS: TRUE
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./new_data:/data
```

### Container logs

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000785c108eca51, pid=751, tid=812
#
# JRE version: OpenJDK Runtime Environment Temurin-21.0.3+9 (21.0.3+9) (build 21.0.3+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (21.0.3+9-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x7cfa51]  G1ConcurrentMark::mark_in_bitmap(unsigned int, oopDesc*) [clone .constprop.0]+0x41
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /data/core.751)
#
# An error report file with more information is saved as:
# /data/hs_err_pid751.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
2024-06-16T04:47:34.589Z	WARN	mc-server-runner	Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.	{"exitCode": -1}
2024-06-16T04:47:34.589Z	INFO	mc-server-runner	Done
```
