### ISSUE TITLE
NeoForge in Curse Forge modpacks

### ISSUE THREAD

**Issue by kevinvdburgt** [itzg/docker-minecraft-server#2933]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Some modpacks at Curse Forge are using NeoForge as their mod loader (for example [ATM10](https://www.curseforge.com/minecraft/modpacks/all-the-mods-10)).

Currently starting the modpack requires to start it with CF, after the mod has been downloaded, the type can be switched to NEOFORGE. However, it would be nice if CF had support for NeoForge as well :-)

**Comment by itzg** [comment]
Thanks for pointing this out. I had added NeoForge support for Modrinth modpacks, but apparently I didn't circle around and add it for CurseForge ones.

**Comment by kevinvdburgt** [comment]
Do you have an example how to use it with CF/NEOFORGE :-)?

**Comment by itzg** [comment]
Referencing ATM10, as you found, would be the example. Making sure you've re-pulled the image it will be specified using https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/

**Comment by Molier** [comment]
working docker compose for reference.
```yaml
atm10:
    container_name: atm10
    image: itzg/minecraft-server
    environment:
      MEMORY: 8G
      EULA: true
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: all-the-mods-10
      CF_FORCE_SYNCHRONIZE: "true"
      CF_EXCLUDE_MODS: | # remove problematic client side mods
        lighty
        986380
      TYPE: NEOFORGE
      VERSION: 1.21
      NEOFORGE_VERSION: 21.0.167
    tty: true
    stdin_open: true
    restart: no
    volumes:
      - dataatm:/data
volumes:
  dataatm:
```
