### ISSUE TITLE
Modrinth Local Pack Error

### ISSUE THREAD

**Issue by addreeh** [itzg/docker-minecraft-server#2980]
### Describe the problem

Trying to start a server using a local file, I tried with mrpack and json, and both give me the same error

### Container definition

```
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MOD_PLATFORM: "MODRINTH"
      MODRINTH_MODPACK: "/modpacks/modrinth.index.json"
    volumes:
      - mc-data:/data
      - ./modpacks:/modpacks:ro

volumes:
  mc-data: {}
```

### Container logs

```
ubuntu@oci:~$ ls
docker  docker-compose.yml  minecraft  modpacks  wirehole  wirehole2
ubuntu@oci:~$ ls modpacks/
Peleland.mrpack  modrinth.index.json
ubuntu@oci:~$ cat docker-compose.yml
version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MOD_PLATFORM: "MODRINTH"
      MODRINTH_MODPACK: "/modpacks/modrinth.index.json"
    volumes:
      - mc-data:/data
      - ./modpacks:/modpacks:ro

volumes:
  mc-data: {}
```
```
ubuntu@oci:~$ docker-compose up
Starting ubuntu_mc_1 ... done
Attaching to ubuntu_mc_1
mc_1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-x--- 2 1000 1000 4096 Jul 10 08:08 /data'
mc_1  | [mc-image-helper] 08:09:07.661 ERROR : Invalid parameter provided for 'install-modrinth-modpack' command: Unable to locate requested project given /modpacks/modrinth.index.json
mc_1  | [init] ERROR failed to install Modrinth modpack
ubuntu_mc_1 exited with code 1
```
