### ISSUE TITLE
docker-compose data not storing on local maching

### ISSUE THREAD

**Issue by mr05je** [itzg/docker-minecraft-server#2987]
### Describe the problem

using docker-compose files not storing on local machine, tried all:
- used `./:/data`
- used `/games/mc/ftb-nt.1:/data`
- used volume

anything of this not working, mb my problem, but other dockers on my pc works (like this config)

### Container definition

```yml
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    container_name: mc-ftb-nt.1
    restart: always
    ports:
      - 25565:25565
    environment:
      - MEMORY=8G
      - EULA=TRUE
      - ONLINE_MODE=FALSE
      - TYPE=FTBA
      - FTB_MODPACK_ID=123
      - FTB_MODPACK_VERSION_ID=12255
    volumes:
      - ftb-nt.1:/data

volumes:
  ftb-nt.1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /games/mc/ftb-nt.1
```

### docker inspect -f "{{json .Mounts}}" mc-ftb-nt.1 RESULT:
```
[{"Type":"volume","Name":"mc_ftb-nt.1","Source":"/var/snap/docker/common/var-lib-docker/volumes/mc_ftb-nt.1/_data","Destination":"/data","Driver":"local","Mode":"rw","RW":true,"Propagation":""}]
```
