### ISSUE TITLE
`mc-image-helper` fails when both `WHITELIST` and `EXISTING_WHITELIST_FILE: SYNCHRONIZE` is set

### ISSUE THREAD

**Issue by madebylydia** [itzg/docker-minecraft-server#2994]
### Describe the problem

If you use the following content I am handing you out in this issue, you will obtain the respective issue.
However, undefining the `EXISTING_WHITELIST_FILE`, the container will successfully launch with no issue.

This is contradictory to the documentation, which does say that both may be used:
![image](https://github.com/user-attachments/assets/0576d68d-dedb-4381-bc64-1437c1120502)
See https://docker-minecraft-server.readthedocs.io/en/latest/configuration/server-properties/#whitelist-players.

### Dockerfile
```dockerfile
FROM itzg/minecraft-server:latest

COPY assets/ /assets
```

### Docker Compose
```yaml
services:
  mc:
    build:
      context: .
      dockerfile: mc.Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"

    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: 1.20.6
      USE_AIKAR_FLAGS: true
      SNOOPER_ENABLED: false
      ONLINE_MODE: false

	  [...]

      # Whitelist + Server operator
      ENABLE_WHITELIST: true
      ENFORCE_WHITELIST: true
      WHITELIST: |
        843919ddeebc4932a39c7ee372c88dc7
      EXISTING_WHITELIST_FILE: SYNCHRONIZE

    volumes:
      - mc_data:/data

volumes:
  mc_data:
```

### Container logs

```log
mc-1  | [mc-image-helper] 20:34:17.308 INFO  : Fabric launcher for minecraft 1.20.6 loader 0.15.11 is already available
[...]
mc-1  | [init] Enabling whitelist functionality
mc-1  | [mc-image-helper] 20:34:24.074 ERROR : 'manage-users' command failed. Version is 1.39.3
mc-1  | com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
mc-1  |  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1]
mc-1  | 	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
mc-1  | 	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4996)
mc-1  | 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4898)
mc-1  | 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3733)
mc-1  | 	at me.itzg.helpers.users.ManageUsersCommand.loadExistingJavaJson(ManageUsersCommand.java:269)
mc-1  | 	at me.itzg.helpers.users.ManageUsersCommand.processJavaUserIdList(ManageUsersCommand.java:139)
mc-1  | 	at me.itzg.helpers.users.ManageUsersCommand.call(ManageUsersCommand.java:101)
mc-1  | 	at me.itzg.helpers.users.ManageUsersCommand.call(ManageUsersCommand.java:35)
mc-1  | 	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
mc-1  | 	at picocli.CommandLine.access$1500(CommandLine.java:148)
mc-1  | 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
mc-1  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
mc-1  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
mc-1  | 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
mc-1  | 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
mc-1  | 	at picocli.CommandLine.execute(CommandLine.java:2174)
mc-1  | 	at me.itzg.helpers.McImageHelper.main(McImageHelper.java:159)```
