### ISSUE TITLE
Plugin not recognizing Fabric

### ISSUE THREAD

**Issue by dominik-warch** [itzg/docker-minecraft-server#2998]
### Describe the problem

I'm trying to install the Chunky Plugin for Fabric but the plugin does not recognize fabic being installed and so the mod resolution and the following server startup fails.

### Container definition

```
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      PLUGINS: |
        https://modrinth.com/mod/fabric-api
        https://modrinth.com/plugin/chunky
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
```

### Container logs

```
mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 12 1000 1000 4096 Jul 17 14:05 /data'
mc-1  | [init] Resolving type given FABRIC
mc-1  | [mc-image-helper] 14:07:41.194 INFO  : Fabric launcher for minecraft 1.21 loader 0.15.11 is already available
mc-1  | [mc-image-helper] 14:07:43.249 INFO  : Downloading /data/mods/chunky from https://modrinth.com/plugin/chunky
mc-1  | [mc-image-helper] 14:07:43.523 INFO  : The file /data/mods/fabric-api is already up to date
mc-1  | [mc-image-helper] 14:07:44.978 INFO  : Created/updated 1 property in /data/server.properties
mc-1  | [init] Setting initial memory to 1G and max to 1G
mc-1  | [init] Starting the Minecraft server...
mc-1  | Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
mc-1  | [14:07:45] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.15.11
mc-1  | [14:07:45] [main/WARN]: Mod resolution failed
mc-1  | [14:07:45] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE chunky 1.4.16 {depends fabric @ [*]}, ROOT_FORCELOAD_SINGLE chunky 1.4.16]
mc-1  | [14:07:45] [main/INFO]: Reason: [HARD_DEP chunky 1.4.16 {depends fabric @ [*]}]
mc-1  | [14:07:45] [main/INFO]: Fix: add [add:fabric 1 ([(-∞,∞)])], remove [], replace []
mc-1  | [14:07:45] [main/ERROR]: Incompatible mods found!
mc-1  | net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
mc-1  | A potential solution has been determined, this may resolve your problem:
mc-1  |          - Install fabric, any version.
mc-1  | More details:
mc-1  |          - Mod 'Chunky' (chunky) 1.4.16 requires any version of fabric, which is missing!
mc-1  |         at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
mc-1  |         at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
mc-1  |         at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
mc-1  |         at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
mc-1  |         at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
mc-1  |         at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
mc-1  |         at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21-loader.0.15.11-launcher.1.0.1.jar:1.0.1]
mc-1  | 2024-07-17T14:07:45.760Z        WARN    mc-server-runner        Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.        {"exitCode": 1}
mc-1  | 2024-07-17T14:07:45.760Z        INFO    mc-server-runner        Done
```

**Comment by itzg** [comment]
You seem to be mixing up features. Use this to grab from Modrinth

https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/modrinth/

**Comment by dominik-warch** [comment]
Ah indeed! Thank you for your fast response. For refence, with this compose.yml everything works:

```
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_PROJECTS: | 
        fabric-api
        chunky
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
 ```
