### ISSUE TITLE
CF_EXCLUDE_MODS Still Being Downloaded

### ISSUE THREAD

**Issue by mr-swz** [itzg/docker-minecraft-server#3047]
### Describe the problem

My ATM10 server is trying to load the mod "lighty" which it shouldn't, hence causing a crash.

I have put "lighty" in CF_EXCLUDE_MODS environmental variable, however it is still being downloaded and loaded.

### Container definition

```
podman create --restart always \
    -p 25565:25565 \
    -e EULA=TRUE \
    -e TYPE="AUTO_CURSEFORGE" \
    -e CF_API_KEY='MY_API_KEY' \
    -e MEMORY="64G" \
    -e CF_SLUG="all-the-mods-10" \
    -e ENABLE_ROLLING_LOGS=TRUE \
    -e ENABLE_COMMAND_BLOCK=TRUE \
    -e MAX_BUILD_HEIGHT=384 \
    -e PVP=FALSE \
    -e MAX_PLAYERS="2147483647" \
    -e ALLOW_FLIGHT=TRUE \
    -e ENABLE_WHITELIST=TRUE \
    -e CF_EXCLUDE_MODS="lighty fix-experience-bug default-options effective-forge flickerfix fps-reducer toast-control betterf3 dark-mode-everywhere model-gap-fix packmenu simple-backups textrues-embeddium-options yeetusexperimentus" \
    --volume /mnt/minecraft/atm10:/data:Z \
    --name minecraft itzg/minecraft-server:latest
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x. 15 1000 1000 4096 Aug 20 15:17 /data'

[mc-image-helper] 15:46:39.110 WARN  : Re-installing due to missing files from modpack: [mods/lighty-neoforge-3.0.0-beta.4+1.21.jar]

[mc-image-helper] 15:46:40.931 INFO  : Processing modpack 'All the Mods 10-0.35' (all-the-mods-10) @ 925200:5643841

[mc-image-helper] 15:46:42.397 INFO  : Excluding mod file 'Yeetus Experimentus' (yeetusexperimentus) due to configuration

[mc-image-helper] 15:46:42.644 INFO  : Mod file ./mods/lithostitched-neoforge-1.21-1.2.5a.jar already exists

...

        Crash Report UUID: 8b0ffb61-99c9-4c94-8345-6e10270ef813

        FML: 4.0.24

        NeoForge: 21.1.21[15:47:07] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server

net.neoforged.fml.ModLoadingException: Loading errors encountered:

        - Lighty (lighty) has failed to load correctly

          java.lang.NoClassDefFoundError: net/minecraft/client/OptionInstance$ValueSet
```

Note the second line of container log. It still tries to download excluded mod.

**Comment by EmilyxFox** [comment]
I was playing around with this a little bit and I could get it to exclude by using the project ID instead:
![image](https://github.com/user-attachments/assets/7763920c-a2f1-43b7-931c-82117d8bffda)
```yaml
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      VERBOSE: TRUE
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      CF_API_KEY: apikey
      MEMORY: 10G
      CF_SLUG: "all-the-mods-10"
      CF_FORCE_SYNCHRONIZE: TRUE
      CF_EXCLUDE_MODS: |
        986380
        fix-experience-bug
        default-options
        effective-forge
        flickerfix
        fps-reducer
        toast-control
        betterf3
        dark-mode-everywhere
        model-gap-fix
        packmenu
        simple-backups
        textrues-embeddium-options
        yeetusexperimentus
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
      ```
