### ISSUE TITLE
Rare Ice being skipped. incorrectly being classified as client mod

### ISSUE THREAD

**Issue by Linguardium** [itzg/docker-minecraft-server#3062]
### Describe the problem

> Skipping rare-ice-0.6.0.jar since it is a client mod

when using https://www.curseforge.com/minecraft/modpacks/faehaven/files/5687725 
Rare Ice mod is skipped and incorrectly marked as clientside only.

https://www.curseforge.com/minecraft/mc-mods/rare-ice

### Container definition

```
name: Faehaven
services:
  Faehaven:
    container_name: Faehaven
    hostname: Faehaven
    image: itzg/minecraft-server:latest
    environment:
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/faehaven
      MEMORY: 8G
```

### Container logs

```
Faehaven  | [mc-image-helper] 02:53:49.106 DEBUG : FILE FETCH: uri=https://edge.forgecdn.net/files/5374/432/CreateNumismatics-1.0.6%2bforge-mc1.20.1.jar headers=[user-agent: itzg/mc-image-helper/1.39.11 (cmd=install-curseforge), x-fetch-session: 00d3717c-63ef-49ab-8824-1bf4293864aa, x-api-key: [redacted], host: edge.forgecdn.net, accept: */*]
Faehaven  | [mc-image-helper] 02:53:49.107 DEBUG : JSON FETCH: uri=https://api.curseforge.com/v1/mods/938667 headers=[user-agent: itzg/mc-image-helper/1.39.11 (cmd=install-curseforge), x-fetch-session: 00d3717c-63ef-49ab-8824-1bf4293864aa, x-api-key: [redacted], accept: application/json, host: api.curseforge.com]
Faehaven  | [mc-image-helper] 02:53:49.107 DEBUG : Skipping rare-ice-0.6.0.jar since it is a client mod
Faehaven  | [mc-image-helper] 02:53:49.107 DEBUG : JSON FETCH: uri=https://api.curseforge.com/v1/mods/551520 headers=[user-agent: itzg/mc-image-helper/1.39.11 (cmd=install-curseforge), x-fetch-session: 00d3717c-63ef-49ab-8824-1bf4293864aa, x-api-key: [redacted], accept: application/json, host: api.curseforge.com]
```
