### ISSUE TITLE
ATM-10 failing to start

### ISSUE THREAD

**Issue by Ovaru** [itzg/docker-minecraft-server#3117]
### Describe the problem

I had trouble initially getting my ATM10 server up and running but eventually it started. It was up for about 2 days before I accidentally took it down and it tried to update itself to the latest version of ATM10 1.3 (I'm running 1.1) the server was unable to start and I realized it tried to update.

Getting a similar error as to when I had tried to start the server a few days ago but I'm not sure what fixed it then so I'm not sure how to fix it now.

I've tried adding
``` 
      CF_EXCLUDE_MODS: 986380 520110 394468 447673
      CF_FORCE_REINSTALL_MODLOADER: true
      CF_OVERRIDES_SKIP_EXISTING: true
```
but the result is the same

### Container definition

```
services:
  mc:
    image: itzg/minecraft-server:java21
    tty: true
    stdin_open: true
    ports:
      - "25562:25562"
    environment:
      ICON: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fgamepedia.cursecdn.com%2Fftb_gamepedia%2Fthumb%2Fd%2Fd9%2FAll_the_Mods.png%2F260px-All_the_Mods.png%3Fversion%3Dd4fd8e6214102a9220b1129bdf0acd78&f=1&nofb=1&ipt=e472cfc78ff189d25ce4a34f9a43c670c08acad53e8c9f77292816797bbe9161&ipo=images
      VERSION: 1.21.1
      SPAWN_PROTECTION: 0
      TYPE: AUTO_CURSEFORGE
      EULA: "TRUE"
      MEMORY: 32G
      SERVER_NAME: 'All The Mods'
      UID: 1000
      GID: 1000
      SERVER_PORT: 25562
      MOTD: "§k§5T§bAll §eThe §cMods§k§5T"
      CF_API_KEY: 'MY API KEY'
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-10/download/5815632
      CF_EXCLUDE_MODS: 986380 520110 394468 447673
      CF_FORCE_REINSTALL_MODLOADER: true
      CF_OVERRIDES_SKIP_EXISTING: true
    restart: unless-stopped
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /home/ethan/ModdedMC:/data:/data```
```

### Container logs

```
moddedmc-mc-1  | [17:34:22.045] [main/ERROR] [loading.moddiscovery.ModFile/LOADING]: Access transformer file META-INF/accesstransformer.cfg provided by mod allthewizardgear does not exist!
moddedmc-mc-1  | [17:34:22.606] [main/INFO] [loading.FMLServiceProvider/CORE]: Loading coremod script-engine for [apothic_enchanting]
moddedmc-mc-1  | [17:34:28.020] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
moddedmc-mc-1  | [17:34:28.022] [main/INFO] [mixin/]: Compatibility level set to JAVA_21
moddedmc-mc-1  | [17:34:28.244] [main/INFO] [LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
moddedmc-mc-1  | [17:34:28.261] [main/WARN] [mixin/]: Reference map 'betterdungeons.refmap.json' for betterdungeons.mixins.json could not be read. If this is a development environment you can ignore this message
moddedmc-mc-1  | Exception in thread "main" java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/caffeinemc/mods/sodium/client/services/PlatformRuntimeInformation
moddedmc-mc-1  |        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
moddedmc-mc-1  |        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
moddedmc-mc-1  |        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
moddedmc-mc-1  |        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103)
moddedmc-mc-1  |        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
moddedmc-mc-1  |        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
moddedmc-mc-1  |        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
moddedmc-mc-1  |        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
moddedmc-mc-1  |        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
moddedmc-mc-1  | Caused by: java.lang.NoClassDefFoundError: net/caffeinemc/mods/sodium/client/services/PlatformRuntimeInformation
moddedmc-mc-1  |        at TRANSFORMER/sodium_extra@0.6.0-beta.3+mc1.21.1/me.flashyreese.mods.sodiumextra.client.SodiumExtraClientMod.mixinConfig(SodiumExtraClientMod.java:79)
moddedmc-mc-1  |        at TRANSFORMER/sodium_extra@0.6.0-beta.3+mc1.21.1/me.flashyreese.mods.sodiumextra.mixin.SodiumExtraMixinConfigPlugin.createConfig(SodiumExtraMixinConfigPlugin.java:13)
moddedmc-mc-1  |        at TRANSFORMER/sodium_extra@0.6.0-beta.3+mc1.21.1/net.caffeinemc.caffeineconfig.AbstractCaffeineConfigMixinPlugin.onLoad(AbstractCaffeineConfigMixinPlugin.java:16)
moddedmc-mc-1  |        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119)
moddedmc-mc-1  |        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:790)
moddedmc-mc-1  |        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)
moddedmc-mc-1  |        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)
moddedmc-mc-1  |        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
moddedmc-mc-1  |        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
moddedmc-mc-1  |        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
moddedmc-mc-1  |        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
moddedmc-mc-1  |        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
moddedmc-mc-1  |        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
moddedmc-mc-1  |        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:94)
moddedmc-mc-1  |        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
moddedmc-mc-1  |        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:57)
moddedmc-mc-1  |        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:190)
moddedmc-mc-1  |        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298)
moddedmc-mc-1  |        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311)
moddedmc-mc-1  |        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298)
moddedmc-mc-1  |        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
moddedmc-mc-1  |        at java.base/java.lang.Class.forName(Unknown Source)
moddedmc-mc-1  |        at java.base/java.lang.Class.forName(Unknown Source)
moddedmc-mc-1  |        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.ImmediateWindowHandler$DummyProvider.lambda$updateModuleReads$1(ImmediateWindowHandler.java:173)
moddedmc-mc-1  |        at java.base/java.util.Optional.map(Unknown Source)
moddedmc-mc-1  |        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.ImmediateWindowHandler$DummyProvider.updateModuleReads(ImmediateWindowHandler.java:173)
moddedmc-mc-1  |        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:94)
moddedmc-mc-1  |        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.FMLLoader.beforeStart(FMLLoader.java:160)
moddedmc-mc-1  |        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:115)
moddedmc-mc-1  |        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
moddedmc-mc-1  |        ... 8 more
moddedmc-mc-1  | Caused by: java.lang.ClassNotFoundException: net.caffeinemc.mods.sodium.client.services.PlatformRuntimeInformation
moddedmc-mc-1  |        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
moddedmc-mc-1  |        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
moddedmc-mc-1  |        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:216)
moddedmc-mc-1  |        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
moddedmc-mc-1  |        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:216)
moddedmc-mc-1  |        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
moddedmc-mc-1  |        ... 38 more

```
