### ISSUE TITLE
Cannot update FTB Evolution Modpack

### ISSUE THREAD

**Issue by hofq** [itzg/docker-minecraft-server#3179]
### Describe the problem

![grafik](https://github.com/user-attachments/assets/54b1199c-5343-4a45-a76a-24eb044df3be)

Values set:
          ftbModpackId: 125
          ftbModpackVersionId: 100005

### Container definition

```yaml
    targetRevision: "*.*.*"
    helm:
      values: |
        replicaCount: 1
        persistence:
          dataDir:
            enabled: true
            Size: 50Gi
        # extraVolumes:
        #   - volumeMounts:
        #       - name: kubejs-cm
        #         mountPath: /mnt/volume
        #         readOnly: true
        #     volumes:
        #       - name: nfs
        #         nfs:
        #           server: some.nfs.server.com
        #           path: /
        #           mountOptions:
        #             - port=2049
        #             - hard
        #             - vers=4
        minecraftServer:
          serviceType: LoadBalancer
          icon: https://cdns-images.dzcdn.net/images/cover/a2b508c6ee9de484750115903ecaed4b/0x1900-000000-80-0-0.jpg
          ops: "Kippenhof"
          eula: "TRUE"
          type: "FTBA"
          ftbModpackId: 125
          ftbModpackVersionId: "100005"
          difficulty: easy
          maxPlayers: 20
          maxWorldSize: 29999984
          maxTickTime: 60000
          memory: 6144M
          motd: "\u00a7x\u00a7f\u00a7f\u00a76\u00a76\u00a70\u00a70\u00a7oM\u00a7x\u00a7f\u00a7f\u00a76\u00a71\u00a70\u00a7d\u00a7oe\u00a7x\u00a7f\u00a7f\u00a75\u00a7c\u00a71\u00a7a\u00a7oi\u00a7x\u00a7f\u00a7f\u00a75\u00a77\u00a72\u00a76\u00a7on\u00a7x\u00a7f\u00a7f\u00a75\u00a72\u00a73\u00a73\u00a7oe\u00a7x\u00a7f\u00a7f\u00a74\u00a7d\u00a74\u00a70\u00a7o \u00a7x\u00a7f\u00a7f\u00a74\u00a77\u00a74\u00a7d\u00a7oE\u00a7x\u00a7f\u00a7f\u00a74\u00a72\u00a75\u00a79\u00a7oi\u00a7x\u00a7f\u00a7f\u00a73\u00a7d\u00a76\u00a76\u00a7oe\u00a7x\u00a7f\u00a7f\u00a73\u00a78\u00a77\u00a73\u00a7or\u00a7x\u00a7f\u00a7f\u00a73\u00a73\u00a78\u00a70\u00a7o \u00a7x\u00a7f\u00a7f\u00a72\u00a7e\u00a78\u00a7c\u00a7oS\u00a7x\u00a7f\u00a7f\u00a72\u00a79\u00a79\u00a79\u00a7oc\u00a7x\u00a7f\u00a7f\u00a72\u00a74\u00a7a\u00a76\u00a7oh\u00a7x\u00a7f\u00a7f\u00a71\u00a7f\u00a7b\u00a73\u00a7ow\u00a7x\u00a7f\u00a7f\u00a71\u00a7a\u00a7b\u00a7f\u00a7oi\u00a7x\u00a7f\u00a7f\u00a71\u00a74\u00a7c\u00a7c\u00a7ot\u00a7x\u00a7f\u00a7f\u00a70\u00a7f\u00a7d\u00a79\u00a7oz\u00a7x\u00a7f\u00a7f\u00a70\u00a7a\u00a7e\u00a76\u00a7oe\u00a7x\u00a7f\u00a7f\u00a70\u00a75\u00a7f\u00a72\u00a7on"

```

### Container logs

```
+ export HOME=/data
+ HOME=/data
++ id -u
++ id -g
++ ls -lnd /data
+ log 'Running as uid=1000 gid=3000 with /data as '\''drwxrwsrwx 5 0 2000 12 Dec  6 16:48 /data'\'''
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2024-12-06 16:52:32+00:00 Running as uid=1000 gid=3000 with /data as 'drwxrwsrwx 5 0 2000 12 Dec  6 16:48 /data'
+ '[' '!' -e /data/eula.txt ']'
+ isTrue false
+ case "${1,,}" in
+ return 1
+ isTrue false
+ case "${1,,}" in
+ return 1
+ rm -f /data/.rcon-cli.env /data/.rcon-cli.yaml
+ isTrue false
+ case "${1,,}" in
+ return 1
+ isTrue false
+ case "${1,,}" in
+ return 1
+ [[ -n '' ]]
+ fixJavaPath
+ which java
+ cd /data
+ export DECLARED_TYPE=FTBA
+ DECLARED_TYPE=FTBA
+ export DECLARED_VERSION=LATEST
+ DECLARED_VERSION=LATEST
+ isTrue false
+ case "${1,,}" in
+ return 1
+ isTrue false
+ case "${1,,}" in
+ return 1
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ : ''
+ [[ -n '' ]]
+ case "${TYPE^^}" in
+ MODPACK_PLATFORM=FTBA
+ [[ -n FTBA ]]
+ case "${MODPACK_PLATFORM^^}" in
+ exec /start-deployFTBA
+ set -e
++ getDistro
++ grep -E '^ID=' /etc/os-release
++ cut -d= -f2
++ sed -e 's/"//g'
+ [[ ubuntu = alpine ]]
+ [[ -v FTB_MODPACK_ID ]]
+ [[ 125 =~ [0-9]+ ]]
+ [[ ! -n 100005 ]]
+ [[ 100005 =~ [0-9]+ ]]
+ isTrue false
+ case "${1,,}" in
+ return 1
+ '[' -f .ftb-installed ']'
+ ftbInstaller=/data/ftb-installer
+ arm=
+ [[ -f /data/ftb-installer ]]
+ log 'Installing modpack ID 125, version ID 100005'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2024-12-06 16:52:33+00:00 Installing modpack ID 125, version ID 100005
+ log 'This could take a while...'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2024-12-06 16:52:33+00:00 This could take a while...
+ /data/ftb-installer 125 100005 --noscript --auto
```
