### ISSUE TITLE
Wrong url generation for Canyon (b1.7.3)

### ISSUE THREAD

**Issue by MMorokk** [itzg/docker-minecraft-server#3224]
### Describe the problem

When i run  docker compose up its telling me that url returning 404, page not found. Quick look at the logs tells me that url is concatenated with " characters around part of the url. Url itself is valid if we remove quotes. 
Should be an easy fix, i think.

### Container definition

```yml
services:
  mc:
    container_name: mc
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MAX_MEMORY: 8G
      TZ: Europe/Warsaw
      VERSION: b1.7.3
      TYPE: CANYON
      ONLINE_MODE: false
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
```

### Container logs

```
$ docker compose up
[+] Running 1/0
 ✔ Container mc  Created                                                                                           0.0s 
Attaching to mc
mc  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 2 1000 1000 4096 Jan  3 20:52 /data'
mc  | [init] Resolving type given CANYON
mc  | [init] Downloading Canyon build 18 from https://canyonmodded.p0rtal.gay/job/Canyonmodded/lastSuccessfulBuild/artifact/"canyon/Canyon-Server/target/canyon-server.jar" ...
mc  | curl: (22) The requested URL returned error: 404
mc exited with code 22
```
