### ISSUE TITLE
ketting server startup is broken

### ISSUE THREAD

**Issue by XIshArkIX** [itzg/docker-minecraft-server#3243]
### Describe the problem

Ketting server is not installed/started due to misconfiguration (arguments passed to the kettinglauncher). Attached screenshot so you can better see the issue.
![image](https://github.com/user-attachments/assets/b515ea21-ca38-450e-9b42-5a4de8008743)


### Container definition

```yaml
services:                                                                                                                                                                                                                                                                                  
  mc:                                                                                                                                                                                                                                                                                      
    image: "itzg/minecraft-server:java21-alpine"                                                                                                                                                                                                                                           
    tty: true                                                                                                                                                                                                                                                                              
    stdin_open: true                                                                                                                                                                                                                                                                       
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      ONLINE_MODE: "FALSE"
      GUI: "FALSE"
      USE_SIMD_FLAGS: "TRUE"
      PLAYER_IDLE_TIMEOUT: 600
      SERVER_NAME: "tea-party"
      ALLOW_FLIGHT: "TRUE"
      MOTD: "Welcome to tea-party"
      ENABLE_ROLLING_LOGS: "TRUE"
      TZ: "MSK"
      INIT_MEMORY: "4G"
      MEMORY: "10G"
      EULA: "TRUE"
      TYPE: "KETTING"
      VERSION: "1.20.1"
      FORGE_VERSION: "47.3.22"
      KETTING_VERSION: "0.3.33"
      CF_OVERRIDES_EXCLUSIONS: |
        shaderpacks/**
    volumes:
      - minecraft-data:/data
      - minecraft-plugins:/plugins

volumes:
  minecraft-data:
    external: true
  minecraft-plugins:
    external: true
```

### Container logs

```
mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 16 1000 1000 4096 Jan 10 01:48 /data'
mc-1  | [init] Resolving type given KETTING
mc-1  | [init] Resolved version given 1.20.1 into 1.20.1
mc-1  | [init] Copying any plugins from /plugins to /data/plugins
mc-1  | [mc-image-helper] 02:22:12.344 INFO  : Created/updated 1 property in /data/server.properties
mc-1  | [init] log4j2.xml already created, skipping
mc-1  | [init] Setting initial memory to 4G and max to 10G
mc-1  | [init] Starting the Minecraft server...
mc-1  | WARNING: Using incubator modules: jdk.incubator.vector
mc-1  | Loaded 60 translations
mc-1  | 2025-01-10 02:22:15,538 main ERROR Error processing element Queue ([Appenders: null]): CLASS_NOT_FOUND
mc-1  | 2025-01-10 02:22:15,778 main ERROR Unable to locate appender "TerminalConsole" for logger config "root"
Loading libs... 100% [======================] 25/25 (0:00:00) 
Exception in thread "main" java.lang.NumberFormatException: For input string: "1-kettingVersion"
mc-1  |         at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
mc-1  |         at java.base/java.lang.Integer.parseInt(Unknown Source)
mc-1  |         at java.base/java.lang.Integer.parseInt(Unknown Source)
mc-1  |         at org.kettingpowered.launcher.KettingLauncher.ensureOneServerAndUpdate(KettingLauncher.java:235)
mc-1  |         at org.kettingpowered.launcher.KettingLauncher.init(KettingLauncher.java:123)
mc-1  |         at org.kettingpowered.launcher.Main.main(Main.java:190)
mc-1  | 2025-01-10T02:22:16.800Z        WARN    mc-server-runner        Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.        {"exitCode": 1}
mc-1  | 2025-01-10T02:22:16.800Z        INFO    mc-server-runner        Done
mc-1 exited with code 0
```
