### ISSUE TITLE
Escape space from slug part of filename

### ISSUE THREAD

**Issue by maxencevm** [itzg/docker-minecraft-server#3245]
### Describe the problem

Tanks for creating and maintaining this project.

My part of filename of architectury need a space but I don't find a way to espace space

Sorry for my bad English 

### Container definition

```
services:
  minecraft_skyfactory5:
    container_name: minecraft_skyfactory5
    image: itzg/minecraft-server:java17-graalvm
    tty: true
    stdin_open: true
    user: 1007:1007
    restart: always
    ports:
      - "25565:25565"
    #env_file: env.conf
    environment:
      EULA: "TRUE"
      MEMORY: "6G"
      TYPE: "AUTO_CURSEFORGE"
      CF_API_KEY: "$$2a$$10$$buD5xLKRUvDYPpc8fEaBzOmjXC/21k0YpJ2QvIKptNlWaDqEKcloC"
      CF_SLUG: "skyfactory-5"
      MAX_PLAYERS: 5
      ONLINE_MODE: true
      SERVER_PORT: 25565
      RCON_PASSWORD: "NOVAGDAB4585"
      CURSEFORGE_FILES: |
        ftb-chunks-forge@2001
        architectury-api@[Forge 1.20(.1)]
        ftb-library-forge@2001
        ftb-teams-forge@2001
    volumes:
      - ./data:/data
```

### Container logs

```
minecraft_skyfactory5  | [mc-image-helper] 01:48:22.888 ERROR : Invalid parameter provided for 'curseforge-files' command: Mod file reference is not valid: 1.20(.1)]
```
