### ISSUE TITLE
Mohist support is down

### ISSUE THREAD

**Issue by WaveringAna** [itzg/docker-minecraft-server#3246]
### Describe the problem

It seems Mohist doesnt use codemc for their circleci anymore. The image helper tries to auto update and then crashes upon the 404 that occurs.

https://ci.codemc.io/job/MohistMC/job/Mohist-1.20.1/

### Container definition

```
services:
  mc:
    image: itzg/minecraft-server:stable
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      #MOD_PLATFORM: CURSEFORGE
      # allocate from https://console.curseforge.com/ and set in .env file
      #CF_API_KEY: ""
      # Optional: select a specific version/file
      #CF_FILENAME_MATCHER: "0.2.34"
      TYPE: MOHIST
      GENERIC_PACK: /modpacks/modpack.zip
      MEMORY: 8G
#      FORGE_VERSION: ${FORGE_VERSION:-47.3.11}
      VERSION: 1.20.1
      MOHIST_BUILD: 923
      OPS: "QuixoticLove"
    volumes:
      - ./data:/data
      - ./modpacks:/modpacks:ro
      - ./mods:/mods:ro
      - ./plugins:/plugins:ro
    restart: unless-stopped
```

### Container logs

```
$ docker compose up
[+] Running 1/0
 ✔ Container minecraft-mc-1  Recreated                                                                                                                                                                                    0.1s
Attaching to mc-1
mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 20 1000 1000 4096 Dec 30 18:30 /data'
mc-1  | [init] Resolving type given MOHIST
mc-1  | [init] Resolved version given 1.20.1 into 1.20.1
mc-1  | [mc-image-helper] 03:10:54.800 WARN  : https://ci.codemc.io/job/MohistMC/job/Mohist-1.20.1/ cannot be retrieved: status=404
mc-1  | [init] ERROR: mohist builds do not exist for 1.20.1
mc-1  | [init]        check https://ci.codemc.io/job/MohistMC/ for available versions
mc-1  | [init]        and set VERSION accordingly
mc-1 exited with code 0
```
