### ISSUE TITLE
Invalid parameter provided for 'install-curseforge' command:

### ISSUE THREAD

**Issue by LamaFahrrad** [itzg/docker-minecraft-server#3251]
### Describe the problem

When i try to docker compose up my .yml file i always get this error. I doubled the $ signs in my API Key.

[mc-image-helper] 20:29:41.458 ERROR : Invalid parameter provided for 'install-curseforge' command: Access to https://api.curseforge.com is forbidden or rate-limit has been exceeded. Ensure CF_API_KEY is set to a valid API key from https://console.curseforge.com/ or allow rate-limit to reset.
mc-1  | [init] [ERROR] Failed to auto-install CurseForge modpack

### Container definition

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      CF_API_KEY: '$$2a$$10$$....'
      TYPE: AUTO_CURSEFORGE
      MEMORY: 10G
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-10

    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data

### Container logs

```
Paste logs here
```

**Comment by itzg** [comment]
If you're sure the API key is valid (thanks for confirming the escaped dollar signs) then it must be the rate-limit, as mentioned in the error:

ERROR : Invalid parameter provided for 'install-curseforge' command: Access to https://api.curseforge.com/ is forbidden **or rate-limit has been exceeded**. Ensure CF_API_KEY is set to a valid API key from https://console.curseforge.com/ **or allow rate-limit to reset**.

**Comment by Ingraved** [comment]
I see the same. It appears to be hitting a rate limit. I think i can 'trick' it into downloading more when I restart the container.
```
[mc-image-helper] 00:39:26.532 WARN  : Retrying to download BrandonsCore-1.20.1-3.2.1.302-universal.jar @ Brandon's Core:Brandons Core 1.20.1-3.2.1.302
[mc-image-helper] 00:39:26.537 WARN  : Retrying to download L_Enders_Cataclysm-2.31- 1.20.1.jar @ L_Ender 's Cataclysm:L_Enders_Cataclysm-2.31- 1.20.1.jar
[mc-image-helper] 00:39:26.545 INFO  : Downloaded mod file mods/Draconic-Evolution-1.20.1-3.1.2.598-universal.jar
[mc-image-helper] 00:39:26.574 INFO  : Excluding mod file 'Just Enough Mekanism Multiblocks' (just-enough-mekanism-multiblocks) due to configuration
[mc-image-helper] 00:39:26.574 WARN  : Retrying to download blue_skies-1.20.1-1.3.31.jar @ Blue Skies:Blue Skies: Population 1.20.1-v1.3.31
[mc-image-helper] 00:39:26.660 INFO  : Downloaded mod file mods/Croptopia-1.20.1-FORGE-3.0.4.jar
[mc-image-helper] 00:39:26.689 ERROR : Invalid parameter provided for 'install-curseforge' command: Access to https://api.curseforge.com is forbidden or rate-limit has been exceeded. Ensure CF_API_KEY is set to a valid API key from https://console.curseforge.com/ or allow rate-limit to reset.

[init] [ERROR] Failed to auto-install CurseForge modpack
```

This is for docker compose running in portainer.
```
services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      # allocate from https://console.curseforge.com/ and set in .env file
      CF_API_KEY: ${CF_API_KEY} # $$2a$$10$$...
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9
      # Optional: select a specific version/file
      #CF_FILENAME_MATCHER: "0.2.34"
      MEMORY: 8G
    volumes:
      - mc-data:/data
```
