### ISSUE TITLE
"konkrete" maybe shouldn't be excluded

### ISSUE THREAD

**Issue by EmilyxFox** [itzg/docker-minecraft-server#3299]
### Describe the problem

It looks like `konkrete` which is [currently on the default exclude list](https://github.com/itzg/docker-minecraft-server/blob/b74de64009f8dfbca1c6d8b9989b933ffd756b9f/files/cf-exclude-include.json#L75) probably shouldn't be. It seems to prevent the [Cottage Witch](https://www.curseforge.com/minecraft/modpacks/cottage-witch) modpack from starting. I haven't looked too much into it. There was [a conversation on the Discord server about it](https://canary.discord.com/channels/660567679458869252/660569641550217327/1338164667817660417).

### Container definition

```yaml
services:
  mc:
    image: itzg/minecraft-server:java17
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: AUTO_CURSEFORGE
      VERSION: 1.17.0
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/cottage-witch
      CF_API_KEY: REDACTED
      MEMORY: 6G
      USE_AIKAR_FLAGS: "true"
      DIFFICULTY: "2"
      ENABLE_COMMAND_BLOCK: "true"
      ALLOW_FLIGHT: "true"
    volumes:
      - ./data:/data:z
```

### Container logs

```
[15:15:55] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
2025-02-09T15:15:55.966178834Z net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
2025-02-09T15:15:55.966180293Z     Mod §ebiomesinjars§r requires §6konkrete§r §o1.5.0 or above§r
2025-02-09T15:15:55.966181834Z §7Currently, §6konkrete§r§7 is §o§nnot installed
2025-02-09T15:15:55.966182834Z ]
```
