### ISSUE TITLE
Error: Unable to access jafile

### ISSUE THREAD

**Issue by bau-steinchen** [itzg/docker-minecraft-server#3310]
### Describe the problem

I had a running atm9 server for quite some time and wanted to have a look into atm10.
I used the template from the [examples ](https://github.com/itzg/docker-minecraft-server/blob/master/examples/atm10/docker-compose.yml)but i keep getting this Error

minecraft_atm10-mc-1  | Error: Unable to access jarfile

Do atm10 need some prerequisites? Do i miss something? Atm9 runs with the same docker-compose.yml file super smooth so there is something missing on my side.

Where do the docker container expect the minecraft jarfile? Do i need to install something additionally for atm10?

### Container definition

```
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "8123:8123"
    environment:
      EULA: "true"
      EXISTING_OPS_FILE: MERGE
      MOD_PLATFORM: AUTO_CURSEFORGE
      # allocate from https://console.curseforge.com/ and set in .env file
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: all-the-mods-10
      # CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-10
      CF_FILENAME_MATCHER: "2.34"
      MEMORY: 12G
      CF_OVERRIDES_EXCLUSIONS: |
        shaderpacks/**
    restart: always
    volumes:
      - ~/storage/data/minecraft_atm10:/data

```

### Container logs

```
 docker compose up
[+] Building 0.0s (0/0)
[+] Running 2/2
 ✔ Network minecraft_atm10_default  Created                                                                                                                                                               0.1s
 ✔ Container minecraft_atm10-mc-1   Created                                                                                                                                                               0.0s
Attaching to minecraft_atm10-mc-1
minecraft_atm10-mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 3 1000 1000 4096 Feb 14 09:47 /data'
minecraft_atm10-mc-1  | [mc-image-helper] 09:50:14.992 INFO  : Processing modpack 'All the Mods 10-2.34' (all-the-mods-10) @ 925200:6169683
minecraft_atm10-mc-1  | [mc-image-helper] 09:50:16.594 INFO  : Excluding mod file 'Searchables' (searchables) due to configuration
minecraft_atm10-mc-1  | [mc-image-helper] 09:50:16.732 INFO  : Mod file mods/ftb-teams-neoforge-2101.1.2.jar already exists
minecraft_atm10-mc-1  | [mc-image-helper] 09:50:16.733 INFO  : Mod file mods/crafting_on_a_stick-1.21.0.1.jar already exists
minecraft_atm10-mc-1  | [mc-image-helper] 09:50:16.734 INFO  : Excluding mod file 'AppleSkin' (appleskin) due to configuration
minecraft_atm10-mc-1  | [mc-image-helper] 09:50:16.856 INFO  : Mod file mods/cupboard-1.21-2.9.jar already exists
minecraft_atm10-mc-1  | [mc-image-helper] 09:50:16.857 INFO  : Mod file mods/connectedglass-1.1.12-neoforge-mc1.21.jar already exists
minecraft_atm10-mc-1  | [mc-image-helper] 09:50:16.859 INFO  : Mod file mods/torchmaster-neoforge-1.21.1-21.1.5-beta.jar already exists

........
minecraft_atm10-mc-1  | [mc-image-helper] 09:50:23.986 INFO  : Mod file mods/pamhc2foodcore-NEOFORGE-1.21.1-1.0.0.jar already exists
minecraft_atm10-mc-1  | [mc-image-helper] 09:50:23.989 INFO  : Mod file mods/jearchaeology-1.21.0-1.1.5.jar already exists
minecraft_atm10-mc-1  | [mc-image-helper] 09:50:23.994 INFO  : Mod file mods/mcw-bridges-3.0.0-mc1.21.1neoforge.jar already exists
minecraft_atm10-mc-1  | [init] Creating server properties in /data/server.properties
minecraft_atm10-mc-1  | [init] Disabling whitelist functionality
minecraft_atm10-mc-1  | [init] Setting initial memory to 12G and max to 12G
minecraft_atm10-mc-1  | [init] Starting the Minecraft server...
minecraft_atm10-mc-1  | Error: Unable to access jarfile
minecraft_atm10-mc-1  | 2025-02-14T09:50:31.580Z        WARN    mc-server-runner        Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.      {"exitCode": 1}
minecraft_atm10-mc-1  | 2025-02-14T09:50:31.581Z        INFO    mc-server-runner        Done

```
