### ISSUE TITLE
[New jar name] Unable to locate the installed FTB server jar

### ISSUE THREAD

**Issue by nilskiefer** [itzg/docker-minecraft-server#3311]
### Describe the problem

Hello, trying to setup a server for FTB cotton. By default it seems that a file with name `fabric-server-launch.jar` generates, changing its name to for ex. `fabric-1.16.5-0.11.3-universal.jar` makes the server launch successfully. 

Likewise changing `start.sh`to `run.sh` results in the following:

```bash
mc_ftb_cotton  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x. 1 1000 1000 392 Feb 15 19:01 /data'
mc_ftb_cotton  | [init] FTB modpack ID 86, version ID 2057 is ready to go
mc_ftb_cotton  | grep: run.s: No such file or directory
mc_ftb_cotton  | [init] [ERROR] Unrecognized loader type in run.sh 
mc_ftb_cotton  | #!/usr/bin/env sh
mc_ftb_cotton  | "jre/8.0.312+7/bin/java" -jar -Dlog4j.configurationFile=.patches/log4j2_112-116.xml -Xmx4096M fabric-server-launch.jar nogui
mc_ftb_cotton exited with code 1
```

inside `./data`

```bash
config    fabric-server-launch.jar  ftb-installer-v2          jre     libraries  server.jar
eula.txt  ftb-installer.log         ftb-server-installer.log  kubejs  mods       start.sh
```
Ive seen this issue being taken up before like in [#1492](https://github.com/itzg/docker-minecraft-server/issues/1492), I think the easiest "solution" would be to add an env variable where one can explicitly override the expected names of files.

### Container definition

```yaml
services:
  mc:
    image: itzg/minecraft-server:java8-multiarch
    container_name: mc_ftb_cotton
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FTBA"
      FTB_MODPACK_ID: "86"
      SERVER_JAR: "fabric-server-launch.jar"
      #FTB_FORCE_REINSTALL: TRUE
    volumes:
      - "${BASE_PATH}/data:/data"
    stdin_open: true
    tty: true
    restart: unless-stopped
```

### Container logs

```bash
mc_ftb_cotton  | [init] Changing ownership of /data to 1000 ...
mc_ftb_cotton  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x. 1 1000 1000 0 Feb 15 18:05 /data'
mc_ftb_cotton  | [init] Downloading FTB installer for ARM
mc_ftb_cotton  | [init] Installing modpack ID 86, version ID 2057
mc_ftb_cotton  | [init] This could take a while...
mc_ftb_cotton  |                            ███████ ████████ ██████  
mc_ftb_cotton  |                            ██         ██    ██   ██ 
mc_ftb_cotton  |                            █████      ██    ██████  
mc_ftb_cotton  |                            ██         ██    ██   ██ 
mc_ftb_cotton  |                            ██         ██    ██████  
mc_ftb_cotton  |                            
mc_ftb_cotton  |                            
mc_ftb_cotton  |                    Server installer version: v1.0.13(dfb068)
mc_ftb_cotton  |                          Sat, 15 Feb 2025 18:05:42 UTC
mc_ftb_cotton  | 
mc_ftb_cotton  |                             Installer Issue tracker
mc_ftb_cotton  |              https://github.com/FTBTeam/FTB-Server-Installer/issues
mc_ftb_cotton  |                                         
mc_ftb_cotton  |  INFO  Fetched modpack:
mc_ftb_cotton  |        Name: FTB Cotton
mc_ftb_cotton  |        Version: 1.1.0
mc_ftb_cotton  |        ModLoader: fabric (0.11.3)
mc_ftb_cotton  |        Is Update: false
mc_ftb_cotton  |        Install Path: /data
mc_ftb_cotton  |  INFO  Starting mod pack download...
Download complete [243/243] ██████████████████████████████████████████ 100% | 5s
mc_ftb_cotton  |  INFO  Modpack files downloaded
mc_ftb_cotton  |  INFO  Running Fabric installer
mc_ftb_cotton  | Loading Fabric Installer: 1.0.1
mc_ftb_cotton  | Installing Fabric Loader 0.11.3(1.16.5) on the server
mc_ftb_cotton  | Downloading required files
mc_ftb_cotton  | Downloading library net.fabricmc:tiny-mappings-parser:0.2.2.14
mc_ftb_cotton  | Downloading library net.fabricmc:sponge-mixin:0.9.2+mixin.0.8.2
mc_ftb_cotton  | Downloading library net.fabricmc:tiny-remapper:0.3.0.70
mc_ftb_cotton  | Downloading library net.fabricmc:access-widener:1.0.0
mc_ftb_cotton  | Downloading library net.fabricmc:fabric-loader-sat4j:2.3.5.4
mc_ftb_cotton  | Downloading library com.google.jimfs:jimfs:1.2-fabric
mc_ftb_cotton  | Downloading library org.ow2.asm:asm:9.1
mc_ftb_cotton  | Downloading library org.ow2.asm:asm-analysis:9.1
mc_ftb_cotton  | Downloading library org.ow2.asm:asm-commons:9.1
mc_ftb_cotton  | Downloading library org.ow2.asm:asm-tree:9.1
mc_ftb_cotton  | Downloading library org.ow2.asm:asm-util:9.1
mc_ftb_cotton  | Downloading library net.fabricmc:intermediary:1.16.5
mc_ftb_cotton  | Downloading library net.fabricmc:fabric-loader:0.11.3
mc_ftb_cotton  | Downloading library com.google.guava:guava:21.0
mc_ftb_cotton  | Generating server launch JAR
mc_ftb_cotton  | Generating server launch JAR: tiny-mappings-parser-0.2.2.14.jar
mc_ftb_cotton  | Generating server launch JAR: sponge-mixin-0.9.2+mixin.0.8.2.jar
mc_ftb_cotton  | Generating server launch JAR: tiny-remapper-0.3.0.70.jar
mc_ftb_cotton  | Generating server launch JAR: access-widener-1.0.0.jar
mc_ftb_cotton  | Generating server launch JAR: fabric-loader-sat4j-2.3.5.4.jar
mc_ftb_cotton  | Generating server launch JAR: jimfs-1.2-fabric.jar
mc_ftb_cotton  | Generating server launch JAR: asm-9.1.jar
mc_ftb_cotton  | Generating server launch JAR: asm-analysis-9.1.jar
mc_ftb_cotton  | duplicate file: module-info.class
mc_ftb_cotton  | Generating server launch JAR: asm-commons-9.1.jar
mc_ftb_cotton  | duplicate file: module-info.class
mc_ftb_cotton  | Generating server launch JAR: asm-tree-9.1.jar
mc_ftb_cotton  | duplicate file: module-info.class
mc_ftb_cotton  | Generating server launch JAR: asm-util-9.1.jar
mc_ftb_cotton  | duplicate file: module-info.class
mc_ftb_cotton  | Generating server launch JAR: intermediary-1.16.5.jar
mc_ftb_cotton  | Generating server launch JAR: fabric-loader-0.11.3.jar
mc_ftb_cotton  | Generating server launch JAR: guava-21.0.jar
mc_ftb_cotton  | Downloading Minecraft server
mc_ftb_cotton  | Done
mc_ftb_cotton  | Done, start server by running fabric-server-launch.jar
mc_ftb_cotton  |  SUCCESS  Fabric installed successfully
mc_ftb_cotton  |  INFO  Downloading log4j fix log4j2_112-116.xml
mc_ftb_cotton  |  SUCCESS  Modpack installed successfully
mc_ftb_cotton  | [init] [ERROR] Unable to locate the installed FTB server jar 
mc_ftb_cotton  | [init] [ERROR]       Tried looking for run.sh fabric-1.16.5-0.11.3-universal.jar fabric-1.16.5-0.11.3-1.16.5-universal.jar fabric-1.16.5-0.11.3-server-launch.jar fabric-1.16.5-0.11.3.jar 
mc_ftb_cotton exited with code 0
```

**Comment by itzg** [comment]
Want to submit a PR to add that to variants?

https://github.com/itzg/docker-minecraft-server/blob/dcf4ae89fb5a81bd28b47f69150017464ffef7d5/scripts/start-deployFTBA#L107

**Comment by nilskiefer** [comment]
Seems to be working, it's worth mentioning that you'll need to build with `eclipse-temurin:8-jdk` as base to test with cotton modpack (ID 86). 

```yaml
services:
  mc:
    image: custom-minecraft
    container_name: mc_ftb_cotton
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FTBA"
      FTB_MODPACK_ID: "86"
      FTB_CUSTOM_VARIANT: "fabric-server-launch.jar"  # User-defined variant
      #FTB_FORCE_REINSTALL: TRUE
    # volumes:
    #  - "${BASE_PATH}/data:/data"
    stdin_open: true
    tty: true
    restart: unless-stopped
```
