### ISSUE TITLE
Stuck on "joining world"

### ISSUE THREAD

**Issue by nexus9111** [itzg/docker-minecraft-server#3316]
#### Description:

I am experiencing an issue where I am unable to join my Minecraft server after the spawn area has finished generating. The launcher gets stuck on "joining world," despite the server logs indicating that the player has successfully joined the game.

#### Server Logs:

```
[10:52:47] [User Authenticator #2/INFO]: UUID of player **** is ************-****-****-****-************
[10:52:47] [Server thread/INFO]: ***** [/***.***.***.***:45826] logged in with entity id 521 at (-452.5, 63.0, 40.5)
[10:52:47] [Server thread/INFO]: ***** joined the game
```

#### Additional Information:

- I have tried launching the server from two different machines, but the issue persists.
- The server logs indicate that the player has successfully joined the game, but the launcher remains stuck on "joining world."

#### Question:

How can I resolve this issue and successfully join the Minecraft server?

### Container definition

```
Paste run command or compose file here
```

#### Docker Compose Configuration:

```yaml
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: true
      VERSION: "1.20.1"
      OVERRIDE_WHITELIST: true
      WHITELIST: |
        *****
        *****
        *****
      MODRINTH_MODPACK: 4BV47HRn
      MODRINTH_VERSION: C3rdirIw
      MAX_MEMORY: "15G"
      MODRINTH_FORCE_SYNCHRONIZE: true
      MODRINTH_EXCLUDE_FILES: |
        oculus
        entity_model_features
        entity_texture_features
        yungsmenutweaks
        notenoughanimations
        RyoamicLights
        EuphoriaPatcher
        skinlayers3d
        3dskinlayers
        betterend
      MODRINTH_OVERRIDES_EXCLUSIONS: |
        mods/NekosEnchantedBooks-*.jar
        mods/citresewn-*.jar
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
```
