### ISSUE TITLE
Newer FTB modpack versions don't seem to be supported.

### ISSUE THREAD

**Issue by plzlearn** [itzg/docker-minecraft-server#3324]
### Describe the problem

Newer versions of FTB modpacks don't seem to want to install. For example, in FTB Evolutions, after modpack version 1.3.0, the version ID format changed from 12629 to 100005 for version 1.4.0. Any version after 1.3.0 fails to install.

### Container definition

```
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: FTBA
      FTB_MODPACK_ID: "125"
      FTB_MODPACK_VERSION_ID: "100029"
      MEMORY: 10G
      PVP: "FALSE"
      ENABLE_ROLLING_LOGS: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
networks: {}
```

### Container logs

```
ftbevolution-mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 19 1000 1000 38 Feb  7 03:28 /data'
ftbevolution-mc-1  | [init] Installing modpack ID 125, version ID 100029
ftbevolution-mc-1  | [init] This could take a while...
ftbevolution-mc-1 exited with code 1
```
