### ISSUE TITLE
set MODRINTH_PROJECTS to an empty string can't removes all previously managed project-files

### ISSUE THREAD

**Issue by uhziel** [itzg/docker-minecraft-server#3339]
### Describe the problem

```
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      VERSION: 1.21.4
      TYPE: "PAPER"
      MODRINTH_PROJECTS: "tabtps"
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
```

When `MODRINTH_PROJECTS` set to `""`, can't remove tabtps.

But `CURSEFORGE_FILES` can do it.

https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/curseforge-files/
> References removed from the declaration are automatically cleaned up and setting CURSEFORGE_FILES to an empty string removes all previously managed project-files.

### Container definition

```
Paste run command or compose file here
```

### Container logs

```
Paste logs here
```
