### ISSUE TITLE
Volume owner assigned to other user

### ISSUE THREAD

**Issue by bolinocroustibat** [itzg/docker-minecraft-server#3352]
### Describe the problem

Using the [basic docker compose template](https://docker-minecraft-server.readthedocs.io/en/latest/#using-docker-compose), when launching with `docker compose up -d` as root user (linux uid 0), the local volume `./data` get created and owned as another linux user (which as uid 1000).
Why?
How to change that?

<img width="558" alt="Image" src="https://github.com/user-attachments/assets/15262940-551f-419b-89d4-d1279eb02f16" />

### Container definition

```
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
```

### Container logs

```
🌀 ❯ docker compose logs -f
minecraft-server  | [init] Changing ownership of /data to 1000 ...
minecraft-server  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 2 1000 1000 4096 Mar  8 06:04 /data'
minecraft-server  | [init] Resolving type given VANILLA
minecraft-server  | [init] Resolved version given LATEST into 1.21.4
minecraft-server  | [init] Downloading 1.21.4 server...
minecraft-server  | [init] Creating server properties in /data/server.properties
minecraft-server  | [init] Disabling whitelist functionality
minecraft-server  | [mc-image-helper] 06:04:27.213 INFO  : Created/updated 5 properties in /data/server.properties
minecraft-server  | [init] Setting initial memory to 1G and max to 1G
minecraft-server  | [init] Starting the Minecraft server...
```
