### ISSUE TITLE
Broke my Minecraft network

### ISSUE THREAD

**Issue by connor33341** [itzg/docker-minecraft-server#3357]
### Describe the problem

Broke all the server.properties files, and alot of the containers started to loop

![Image](https://github.com/user-attachments/assets/bff0ddad-304b-4fc1-bd79-2655491a8a67)

### Container definition

```
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "8100:8100"
      #- "19132:19132/udp"
      - "25575:25575"
    #networks:
      #- minecraft
    environment:
      EULA: "TRUE"
      VERSION: 1.21
      SERVER_NAME: "Server"
      PLAYER_IDLE_TIMEOUT: 15
      TYPE: "PAPER"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      VIEW_DISTANCE: 64
      DIFFICULTY: "hard"
      ICON: "https://djeqr6to3dedg.cloudfront.net/repo-logos/itzg/minecraft-server/live/logo-1704684813344.png"
      HARDCORE: "false"
      SNOOPER_ENABLED: "false"
      SPAWN_PROTECTION: 2
      MAX_BUILD_HEIGHT: 500
      MAX_PLAYERS: 100
      INIT_MEMORY: 4G
      MAX_MEMORY: 16G
      ENABLE_RCON: "TRUE"
      ONLINE_MODE: "FALSE"
      REPLACE_ENV_VARIBLES: "TRUE"
      ENV_VARIBLE_PREFIX: "CFG_"
      #MOTD: PMC03b0e4dd76bff7dc2491fc7db109e1f4
      MOTD: §l§cUpdate Notes§r RAM 8->16, View&SimDistance 32->64. §l§chttps://connor33341.github.io/mc/§r
      MAX_WORLD_SIZE: 1000000
      OPS: |
        Connor_33341
      #  user 2
      #  user 2
      
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
  creative:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    #ports:
      #- "25565:25565"
      #- "8100:8100"
      #- "19132:19132/udp"
      #- "25575:25575"
    #networks:
      #- minecraft
    environment:
      EULA: "TRUE"
      VERSION: 1.21
      SERVER_NAME: "Server"
      PLAYER_IDLE_TIMEOUT: 15
      TYPE: "PAPER"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      VIEW_DISTANCE: 12
      DIFFICULTY: "peaceful"
      ICON: "https://djeqr6to3dedg.cloudfront.net/repo-logos/itzg/minecraft-server/live/logo-1704684813344.png"
      HARDCORE: "false"
      SNOOPER_ENABLED: "false"
      SPAWN_PROTECTION: 0
      MAX_BUILD_HEIGHT: 500
      MAX_PLAYERS: 5
      INIT_MEMORY: 1G
      MAX_MEMORY: 1G
      ENABLE_RCON: "FALSE"
      ONLINE_MODE: "FALSE"
      REPLACE_ENV_VARIBLES: "TRUE"
      ENV_VARIBLE_PREFIX: "CFG_"
      #MOTD: PMC03b0e4dd76bff7dc2491fc7db109e1f4
      MOTD: §l§cUpdate Notes§r RAM 8->16, View&SimDistance 32->64. §l§chttps://connor33341.github.io/mc/§r
      MAX_WORLD_SIZE: 1000
      OPS: |
        Connor_33341
      #  user 2
      #  user 2
  hardcore:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    #ports:
      #- "25565:25565"
      #- "8100:8100"
      #- "19132:19132/udp"
      #- "25575:25575"
    #networks:
      #- minecraft
    environment:
      EULA: "TRUE"
      VERSION: 1.21
      SERVER_NAME: "Server"
      PLAYER_IDLE_TIMEOUT: 15
      TYPE: "PAPER"
      VIEW_DISTANCE: 32
      DIFFICULTY: "hard"
      ICON: "https://djeqr6to3dedg.cloudfront.net/repo-logos/itzg/minecraft-server/live/logo-1704684813344.png"
      HARDCORE: "true"
      SNOOPER_ENABLED: "false"
      SPAWN_PROTECTION: 0
      MAX_BUILD_HEIGHT: 500
      MAX_PLAYERS: 16
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
      ENABLE_RCON: "FALSE"
      ONLINE_MODE: "FALSE"
      REPLACE_ENV_VARIBLES: "TRUE"
      ENV_VARIBLE_PREFIX: "CFG_"
      #MOTD: PMC03b0e4dd76bff7dc2491fc7db109e1f4
      MOTD: §l§cUpdate Notes§r RAM 8->16, View&SimDistance 32->64. §l§chttps://connor33341.github.io/mc/§r
      MAX_WORLD_SIZE: 10000
      OPS: |
        Connor_33341
      #  user 2
      #  user 2
    volumes:
        # attach the relative directory 'data' to the container's /data path
        - ./hardcoredata:/data

  fabric:
      image: itzg/minecraft-server
      tty: true
      stdin_open: true
      ports:
        - "8123:8123"
        #- "25565:25565"
        #- "8100:8100"
        #- "19132:19132/udp"
        #- "25575:25575"
      #networks:
        #- minecraft
      environment:
        EULA: "TRUE"
        VERSION: 1.21.4
        SERVER_NAME: "Server"
        PLAYER_IDLE_TIMEOUT: 5
        TYPE: "FABRIC"
        VIEW_DISTANCE: 32
        DIFFICULTY: "hard"
        ICON: "https://djeqr6to3dedg.cloudfront.net/repo-logos/itzg/minecraft-server/live/logo-1704684813344.png"
        HARDCORE: "false"
        SNOOPER_ENABLED: "false"
        SPAWN_PROTECTION: 0
        MAX_BUILD_HEIGHT: 500
        MAX_PLAYERS: 3
        INIT_MEMORY: 1G
        MAX_MEMORY: 4G
        ENABLE_RCON: "FALSE"
        ONLINE_MODE: "FALSE"
        REPLACE_ENV_VARIBLES: "TRUE"
        ENV_VARIBLE_PREFIX: "CFG_"
        #MOTD: PMC03b0e4dd76bff7dc2491fc7db109e1f4
        MOTD: §l§cUpdate Notes§r RAM 8->16, View&SimDistance 32->64. §l§chttps://connor33341.github.io/mc/§r
        MAX_WORLD_SIZE: 10000
        OPS: |
          Connor_33341
        #  user 2
        #  user 2
      
      volumes:
        # attach the relative directory 'data' to the container's /data path
        - ./fabricdata:/data  
  econ:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    #ports:
      #- "25565:25565"
      #- "8100:8100"
      #- "19132:19132/udp"
      #- "25575:25575"
    #networks:
      #- minecraft
    environment:
      EULA: "TRUE"
      VERSION: 1.21
      SERVER_NAME: "Server"
      PLAYER_IDLE_TIMEOUT: 15
      TYPE: "PAPER"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      VIEW_DISTANCE: 32
      DIFFICULTY: "normal"
      ICON: "https://djeqr6to3dedg.cloudfront.net/repo-logos/itzg/minecraft-server/live/logo-1704684813344.png"
      HARDCORE: "false"
      SNOOPER_ENABLED: "false"
      SPAWN_PROTECTION: 2
      MAX_BUILD_HEIGHT: 500
      MAX_PLAYERS: 100
      INIT_MEMORY: 2G
      MAX_MEMORY: 4G
      ENABLE_RCON: "FALSE"
      ONLINE_MODE: "FALSE"
      REPLACE_ENV_VARIBLES: "TRUE"
      ENV_VARIBLE_PREFIX: "CFG_"
      #MOTD: PMC03b0e4dd76bff7dc2491fc7db109e1f4
      MOTD: §l§cUpdate Notes§r RAM 8->16, View&SimDistance 32->64. §l§chttps://connor33341.github.io/mc/§r
      MAX_WORLD_SIZE: 10000
      OPS: |
        Connor_33341
      #  user 2
      #  user 2
      
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./econdata:/data

  mc-lobby:
    image: itzg/minecraft-server
    tty: true
    restart: unless-stopped
    stdin_open: true
    #ports:
      #- "25565:25565"
      #- "8100:8100"
      #- "19132:19132/udp"
    #networks:
      #- minecraft
    environment:
      EULA: "TRUE"
      VERSION: 1.21.4
      SERVER_NAME: "Lobby"
      PLAYER_IDLE_TIMEOUT: 120
      TYPE: "PAPER"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      VIEW_DISTANCE: 32
      DIFFICULTY: "peaceful"
      ICON: "https://djeqr6to3dedg.cloudfront.net/repo-logos/itzg/minecraft-server/live/logo-1704684813344.png"
      HARDCORE: "false"
      SNOOPER_ENABLED: "false"
      SPAWN_PROTECTION: 1000
      MAX_BUILD_HEIGHT: 500
      MAX_PLAYERS: 120
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
      ENABLE_RCON: "TRUE"
      ONLINE_MODE: "FALSE"
      REPLACE_ENV_VARIBLES: "TRUE"
      ENV_VARIBLE_PREFIX: "CFG_"
      #MOTD: PMC03b0e4dd76bff7dc2491fc7db109e1f4
      MOTD: §l§cUpdate Notes§r RAM 8->16, View&SimDistance 32->64. §l§chttps://connor33341.github.io/mc/§r
      MAX_WORLD_SIZE: 1000
      OPS: |
        Connor_33341
        JasnMC64
      #  user 2
      #  user 2
    
  mc-lobby-dev:
    image: itzg/minecraft-server
    tty: true
    restart: unless-stopped
    stdin_open: true
    #ports:
      #- "25565:25565"
      #- "8100:8100"
      #- "19132:19132/udp"
    #networks:
      #- minecraft
    environment:
      EULA: "TRUE"
      VERSION: 1.21.4
      SERVER_NAME: "Lobby"
      PLAYER_IDLE_TIMEOUT: 30
      TYPE: "PAPER"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      VIEW_DISTANCE: 32
      DIFFICULTY: "peaceful"
      ICON: "https://djeqr6to3dedg.cloudfront.net/repo-logos/itzg/minecraft-server/live/logo-1704684813344.png"
      HARDCORE: "false"
      SNOOPER_ENABLED: "false"
      SPAWN_PROTECTION: 1000
      MAX_BUILD_HEIGHT: 500
      MAX_PLAYERS: 2
      INIT_MEMORY: 1G
      MAX_MEMORY: 2G
      ENABLE_RCON: "TRUE"
      ONLINE_MODE: "FALSE"
      REPLACE_ENV_VARIBLES: "TRUE"
      ENV_VARIBLE_PREFIX: "CFG_"
      #MOTD: PMC03b0e4dd76bff7dc2491fc7db109e1f4
      MOTD: §l§cUpdate Notes§r RAM 8->16, View&SimDistance 32->64. §l§chttps://connor33341.github.io/mc/§r
      MAX_WORLD_SIZE: 1000
      OPS: |
        Connor_33341
        JasnMC64
      #  user 2
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./lobbydev:/data

  mc-auth:
    image: itzg/minecraft-server
    tty: true
    restart: unless-stopped
    stdin_open: true
    #ports:
      #- "25565:25565"
      #- "8100:8100"
      #- "19132:19132/udp"
    #networks:
      #- minecraft
    environment:
      EULA: "TRUE"
      VERSION: 1.21
      SERVER_NAME: "auth"
      PLAYER_IDLE_TIMEOUT: 30
      TYPE: "PAPER"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        https://cdn.modrinth.com/data/sG6SrXta/versions/tLHWDzcE/AuthMeVelocity-Paper-4.1.2.jar
        https://github.com/AuthMe/AuthMeReloaded/releases/download/5.6.0/AuthMe-5.6.0.jar
      VIEW_DISTANCE: 32
      DIFFICULTY: "peaceful"
      ICON: "https://djeqr6to3dedg.cloudfront.net/repo-logos/itzg/minecraft-server/live/logo-1704684813344.png"
      HARDCORE: "false"
      SNOOPER_ENABLED: "false"
      SPAWN_PROTECTION: 100
      MAX_BUILD_HEIGHT: 500
      MAX_PLAYERS: 125
      INIT_MEMORY: 1G
      MAX_MEMORY: 2G
      ENABLE_RCON: "TRUE"
      ONLINE_MODE: "FALSE"
      REPLACE_ENV_VARIBLES: "TRUE"
      ENV_VARIBLE_PREFIX: "CFG_"
      #MOTD: PMC03b0e4dd76bff7dc2491fc7db109e1f4
      MOTD: §l§cUpdate Notes§r RAM 8->16, View&SimDistance 32->64. §l§chttps://connor33341.github.io/mc/§r
      MAX_WORLD_SIZE: 100
      OPS: |
        Connor_33341
      #  user 2
      #  user 2
      
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./authdata:/data

  proxy:
    image: itzg/mc-proxy
    restart: unless-stopped
    environment:
      TYPE: "VELOCITY"
      REPLACE_ENV_VARIBLES: "true"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/velocity
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/velocity
    ports:
      - "25566:25566"
      - "19132:19132/udp"
    #networks:
      #- minecraft
    volumes:
      - ./proxy-data:/server
      - ./config.yml:/config/config.yml

  #GOAL: Sunset w/ Cloudflare Proxy 
  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.15
    network_mode: host
    restart: unless-stopped
    environment:
    - SECRET_KEY=REMOVED
  
  web:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx:/etc/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mc
    networks:
      - webnet

  backups:
    image: itzg/mc-backup
    #networks:
      #- minecraft
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: mc
      PRUNE_BACKUPS_DAYS: 30
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
    volumes:
      - ./data:/data:ro
      - ./data-backups:/backups
      - ./post-backup.sh:/post-backup.sh:ro

  cloudflare:
    image: cloudflare/cloudflared
    network_mode: host
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token REMOVED

  db:
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=REMOVED
      - MYSQL_USER=main
      - MYSQL_PASSWORD=main
      - MYSQL_DATABASE=authme

volumes:
  mc-data:
  proxy-data:

networks:
  webnet:
    driver: bridge

```

---

### Container logs

```
[mc-image-helper] 22:33:01.913 INFO  : The file /data/plugins/Geyser-Spigot.jar is already up to date
[mc-image-helper] 22:33:01.913 INFO  : The file /data/plugins/floodgate-spigot.jar is already up to date
[mc-image-helper] 22:33:04.678 INFO  : Created/updated 1 property in /data/server.properties
[init] Downloading default configs, if needed
[mc-image-helper] 22:33:06.803 INFO  : The file /data/config/paper-world-defaults.yml already exists
[mc-image-helper] 22:33:06.803 INFO  : The file /data/config/paper-global.yml already exists
[init] Downloading default top-level configs, if needed
[mc-image-helper] 22:33:09.214 INFO  : The file /data/bukkit.yml already exists
[mc-image-helper] 22:33:09.214 INFO  : The file /data/spigot.yml already exists
[mc-image-helper] 22:33:10.798 ERROR : 'manage-users' command failed. Version is 1.40.11
com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 2]
at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2584)
at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2610)
at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInvalidSpace(ParserMinimalBase.java:772)
at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2508)
at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:673)
at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:5004)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4910)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3745)
at me.itzg.helpers.users.ManageUsersCommand.loadExistingJavaJson(ManageUsersCommand.java:266)
at me.itzg.helpers.users.ManageUsersCommand.processJavaUserIdList(ManageUsersCommand.java:139)
at me.itzg.helpers.users.ManageUsersCommand.call(ManageUsersCommand.java:101)
at me.itzg.helpers.users.ManageUsersCommand.call(ManageUsersCommand.java:35)
at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
at picocli.CommandLine.access$1500(CommandLine.java:148)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
at picocli.CommandLine.execute(CommandLine.java:2174)
at me.itzg.helpers.McImageHelper.main(McImageHelper.java:169)
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 1 1000 1000 4096 Mar  9 19:20 /data'
[init] Resolving type given PAPER
```

**Comment by connor33341** [comment]
Also, it corrupted ops.json 

![Image](https://github.com/user-attachments/assets/50863b4e-cd2c-41f7-b193-8280a5ab8faa)

**Comment by connor33341** [comment]
After deleting, corrupted files. The server(s) started again, but I encountered the issue again when restarting

**Comment by itzg** [comment]
You have 14 services in your compose file. Which one is giving you troubles?

**Comment by itzg** [comment]
Since I noticed "lobbydev" in the screenshot, I focused on testing just the following and was unable to recreate the problem:

```yaml
services:
  mc-lobby-dev:
    image: itzg/minecraft-server
    tty: true
#################################################################################
# Disable auto-restart since using SETUP_ONLY: true
#    restart: unless-stopped
    stdin_open: true
      #ports:
      #- "25565:25565"
      #- "8100:8100"
      #- "19132:19132/udp"
    #networks:
    #- minecraft
    environment:
#################################################################################
# DEBUG and SETUP_ONLY to confirm file contents separate from server runtime
      DEBUG: true
      SETUP_ONLY: true
#################################################################################
      EULA: "TRUE"
      VERSION: 1.21.4
      SERVER_NAME: "Lobby"
      PLAYER_IDLE_TIMEOUT: 30
      TYPE: "PAPER"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      VIEW_DISTANCE: 32
      DIFFICULTY: "peaceful"
      ICON: "https://djeqr6to3dedg.cloudfront.net/repo-logos/itzg/minecraft-server/live/logo-1704684813344.png"
      HARDCORE: "false"
      SNOOPER_ENABLED: "false"
      SPAWN_PROTECTION: 1000
      MAX_BUILD_HEIGHT: 500
      MAX_PLAYERS: 2
      INIT_MEMORY: 1G
      MAX_MEMORY: 2G
      ENABLE_RCON: "TRUE"
      ONLINE_MODE: "FALSE"
      REPLACE_ENV_VARIBLES: "TRUE"
      ENV_VARIBLE_PREFIX: "CFG_"
      #MOTD: PMC03b0e4dd76bff7dc2491fc7db109e1f4
      MOTD: §l§cUpdate Notes§r RAM 8->16, View&SimDistance 32->64. §l§chttps://connor33341.github.io/mc/§r
      MAX_WORLD_SIZE: 1000
      OPS: |
        Connor_33341
        JasnMC64
      #  user 2
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./lobbydev:/data
```


<img width="1643" alt="Image" src="https://github.com/user-attachments/assets/fbd542cb-7373-407e-a6c2-754a8e4ba937" />
