### ISSUE TITLE
Keep getting not enough space error

### ISSUE THREAD

**Issue by Wordlesschunk** [itzg/docker-minecraft-server#3368]
### Describe the problem

Morning guys 

seem to keep getting this error appearing below 

<img width="1726" alt="Image" src="https://github.com/user-attachments/assets/a366b8d6-5581-47b4-8118-abc23f40eb70" />

this seems to happen no matter what pack i choose can anyone share some light on a possible solution for this please? 

### Container definition

```
  GNU nano 6.2                                                                          docker-compose.yml                                                                                    
services:
  mc:
    image: itzg/minecraft-server:java21
    environment:
      EULA: true
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      CF_SLUG: skyfactory-4
      CF_FILENAME_MATCHER: 4.2.4
      CF_API_KEY: fooBar
      MEMORY: 4G
    ports:
      - "25565:25565"
    volumes:
      - mc-data:/data
volumes:
  mc-data:
```

### Container logs

```
Attaching to mc-1
mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-x--- 14 1000 1000 4096 Mar 16 14:03 /data'
mc-1  | [mc-image-helper] 14:04:02.612 INFO  : Requested CurseForge modpack SkyFactory 4 - 4.2.4 is already installed for SkyFactory 4
mc-1  | [mc-image-helper] 14:04:03.045 INFO  : Forge version 14.23.5.2860 for minecraft version 1.12.2 is already installed
mc-1  | [mc-image-helper] 14:04:06.243 INFO  : Created/updated 1 property in /data/server.properties
mc-1  | [init] Setting initial memory to 4G and max to 4G
mc-1  | [init] Starting the Minecraft server...
mc-1  | #
mc-1  | # There is insufficient memory for the Java Runtime Environment to continue.
mc-1  | # Native memory allocation (mmap) failed to map 4294967296 bytes. Error detail: committing reserved memory.
mc-1  | OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000700000000, 4294967296, 0) failed; error='Not enough space' (errno=12)
mc-1  | # An error report file with more information is saved as:
mc-1  | # /data/hs_err_pid188.log
mc-1  | 2025-03-16T14:04:06.371Z        WARN    mc-server-runner        Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.     {"exitCode": 1}
mc-1  | 2025-03-16T14:04:06.371Z        INFO    mc-server-runner        Done
mc-1 exited with code 1```

**Comment by itzg** [comment]
Set `DEBUG_MEMORY` env var to "true" and provide those logs.

**Comment by itzg** [comment]
You're getting a different error now. You need to adjust your image tag used

https://docker-minecraft-server.readthedocs.io/en/latest/versions/java/#java-8

Preciously, you must have been low on free memory before, which is likely when carving out 4GB from an 8 GB VM. This time you have about 5GB free.

**Comment by Wordlesschunk** [comment]
Thanks for that @itzg 
i made that change to the docker file (see below)
```
version: '3.8'
services:
  game:
    image: itzg/minecraft-server:java8
    tty: true
    stdin_open: true
    ports:
      - '25565:25565'
    environment:
      EULA: true
      CREATE_CONSOLE_IN_PIPE: true
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: fooBar     
      MEMORY: 4G
      CF_SLUG: skyfactory-4
      CF_FILENAME_MATCHER: 4.2.4
    volumes:
      - './data:/data'
```

But i still get the server failing to boot

<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/86c00710-8f7a-479c-8e60-f212a2716d44" />


I thought maybe it was just random and maybe if i tried a different pack that might work instead, so i used:

```
version: '3.8'
services:
  game:
    image: itzg/minecraft-server:java8
    tty: true
    stdin_open: true
    ports:
      - '25565:25565'
    environment:
      EULA: true
      CREATE_CONSOLE_IN_PIPE: true
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: fooBar     
      MEMORY: 4G
      CF_SLUG: beyond-depth
    volumes:
      - './data:/data'
```

but again getting errors when the server is booting

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/5eb4bb8c-cbd4-4245-8143-61647a7620c6" />


is this just due to me not using the correct java version for each pack and if so is there a easy way for me to know or is this something deeper?
feel like whichever pack i try i get similar errors

Many thanks again!

**Comment by itzg** [comment]
You're getting a totally different error each time since you're changing the scenario each time. What modpack do you actually want to be running? Let's focus on getting that one working.

**Comment by Wordlesschunk** [comment]
Okay, lets try and get the skyfactory-4 one working if thats okay.

sorry for changing the scenario, each time i'm just trying to understand if theres a commonality here with this, as before i never had an issue just spinning up any other pack

thanks

**Comment by itzg** [comment]
Server was able to startup with this compose file:

```yaml
services:
  mc:
    # sky-factory-4 uses Forge 1.12.2 where it and its mods tends to be compatible with Java 8
    # See https://docker-minecraft-server.readthedocs.io/en/latest/versions/java/#java-8
    image: itzg/minecraft-server:java8
    tty: true
    stdin_open: true
    environment:
      EULA: true
      MOD_PLATFORM: AUTO_CURSEFORGE
      # Allocate API key from https://console.curseforge.com/
      # and set in .env file making sure to double up dollar signs, such as
      # CF_API_KEY=$$2a$$10$$....
      # Refer to https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#api-key
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: skyfactory-4
      # exclude client mods not yet listed in
      # https://github.com/itzg/docker-minecraft-server/blob/master/files/cf-exclude-include.json
      CF_EXCLUDE_MODS: |
        waila-stages
      CF_FORCE_SYNCHRONIZE: true
      MEMORY: 4G
    ports:
      - "25565:25565"
    volumes:
      # using a managed volume, but could also be a host directory binding like ./data
      - mc-data:/data
volumes:
  mc-data:
```

**Comment by Wordlesschunk** [comment]
Thanks for the support @itzg i do appreciate it
is there anything that can be taken away from this? i assume that if booting another pack and i get similar errors to that its just a case of excluding that mod 

for the beyond-depth error is that more just relating to forge versioning?

thanks

**Comment by itzg** [comment]
Yeah, most of the time with CurseForge modpacks it'll be a client mod that needs to be excluded. More info here:

https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#exclude-client-mods

Otherwise, yes, the remaining issue was Java version compatibility with Forge.

Now the originally out of memory issue was likely just the VM's operating system simply didn't have enough free memory at the time.

**Comment by joeltoth** [comment]
No matter what I do and what I change I keep getting an "papermc exited with code 137"
```
  papermc:
    container_name: papermc
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    network_mode: host
    healthcheck:
      disable: true
    environment:
      EULA: "TRUE"
      SERVER_PORT: 25565
      TYPE: PAPER
      VERSION: "1.21.4"
      MEMORY: "4G"
      DEBUG_MEMORY: "true"
    restart: always
    volumes:
      - /srv/minecraft/data:/data
```

![Image](https://github.com/user-attachments/assets/0f3659c0-b1a2-4e2b-81e8-182fe0c44f66)

![Image](https://github.com/user-attachments/assets/8db45652-46ce-4c02-86a7-5e31c20780eb)
