### ISSUE TITLE
Failed to install NeoForge

### ISSUE THREAD

**Issue by shivangrathore** [itzg/docker-minecraft-server#3390]
### Describe the problem

It was all working fine, but I wanted to restart my server, I did that and suddenly it doesn't launch. I think there is some problem in manifest resolution which is getting the wrong version somehow? 

I am not sure how underlying resolution works, maybe the api or page we are using to resolve version is expired or its response has changed.

### Container definition

```yaml
services:
  mc:
    image: itzg/minecraft-server:latest
    volumes:
      - ./data:/data
      - ./mods:/mods
    environment:
      EULA: "TRUE"
      TYPE: "NEOFORGE"
      VERSION: "1.21.1"
      MEMORY: "2G"
    ports:
      - 25565:25565
    restart:
      unless-stopped
    depends_on:
      restore-backup:
        condition: service_completed_successfully
  restore-backup:
    image: itzg/mc-backup
    restart: "no"
    entrypoint: restore-rsync-backup
    volumes:
      - ./data:/data
      - ./backups:/backups:ro
  backup:
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      RCON_HOST: "mc"
      BACKUP_INTERVAL: "1h"
      BACKUP_NAME: "world"
      BACKUP_METHOD: "rsync"
      INITIAL_DELAY: 0
      PAUSE_IF_NO_PLAYERS: true
      PRUNE_BACKUPS_COUNT: 30

    volumes:
      - ./data:/data:ro
      - ./backups:/backups
```

### Container logs

[mc-image-helper] 15:33:33.773 ERROR : 'install-neoforge' command failed. Version is 1.41.5
mc-1              | me.itzg.helpers.errors.GenericException: Unable to resolve NeoForge metadata
mc-1              |     at me.itzg.helpers.forge.NeoForgeInstallerResolver.resolve(NeoForgeInstallerResolver.java:92)
mc-1              |     at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:54)
mc-1              |     at me.itzg.helpers.forge.InstallNeoForgeCommand.call(InstallNeoForgeCommand.java:87)
mc-1              |     at me.itzg.helpers.forge.InstallNeoForgeCommand.call(InstallNeoForgeCommand.java:19)
mc-1              |     at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
mc-1              |     at picocli.CommandLine.access$1500(CommandLine.java:148)
mc-1              |     at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
mc-1              |     at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
mc-1              |     at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
mc-1              |     at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
mc-1              |     at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
mc-1              |     at picocli.CommandLine.execute(CommandLine.java:2174)
mc-1              |     at me.itzg.helpers.McImageHelper.main(McImageHelper.java:178)
