### ISSUE TITLE
Issue with ATM10

### ISSUE THREAD

**Issue by ArmonicPvP** [itzg/docker-minecraft-server#3445]
### Describe the problem

ATM10 is getting an error when starting:

`SmithingTemplateViewer (smithingtemplateviewer) has failed to load correctly`

Their devs say issue is related to the docker and how it is pulling files: https://github.com/AllTheMods/ATM-10/issues/2722

### Container definition

```
Paste run command or compose file here
```

### Container logs

```
Paste logs here
```

**Comment by itzg** [comment]
That's not what they're saying. They're refusing to be supportive even when it was pointed out that mod is clearly client-only. 

Server pack files can be used with https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/curseforge/ but I no longer answer issues or questions about those. Modpack authors are too inconsistent with server modpack structure.

**Comment by itzg** [comment]
With the latest image this server started up fine for me:

```yaml
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: true
      MOD_PLATFORM: AUTO_CURSEFORGE
      # Allocate API key from https://console.curseforge.com/
      # and set in .env file making sure to double up dollar signs, such as
      # CF_API_KEY=$$2a$$10$$....
      # Refer to https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#api-key
      CF_API_KEY: ${CF_API_KEY}
#      CF_SLUG: all-the-mods-10
      # 2.47
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-10/files/6502777
      # Optional: select a specific version/file
      # CF_FILENAME_MATCHER: "1.17"
      MEMORY: 4G
      CF_OVERRIDES_EXCLUSIONS: |
        shaderpacks/**
    volumes:
      # Use managed volume by default, but can change to a relative path like
      # ./data:/data
      # to use a host directory
      - mc-data:/data
volumes:
  mc-data:
```
