### ISSUE TITLE
memory docker-compose

### ISSUE THREAD

**Issue by overclockedllama** [itzg/docker-minecraft-server#363]
hiya

i was reading about how to change the memory but am a little unsure of what to put in my docker-compose file. Could you let me know if it is possible to increase the max memory with some sort of command in the docker-compose file? Do I have to build the image from source?

thanks in advance

**Comment by itzg** [comment]
Way down at the very bottom of the README is the section that should help you out

https://github.com/itzg/docker-minecraft-server#memory-limit

Basically, you'll typically want to make use of `MEMORY`, so increasing the container to use 2G of memory would look like this in a compose file:

```
services:
  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      MEMORY: 2G
```
