### ISSUE TITLE
Typo in sed command 

### ISSUE THREAD

**Issue by iamtpage** [itzg/docker-minecraft-server#364]
https://github.com/itzg/docker-minecraft-server/blob/539f7ada706724fb38becb7d527ac73ae198ed13/start-minecraftFinalSetup#L108

if `$MAX_MEMORY` is 8G, then
`sed -i "/MAX_RAM=.*/ c MAX_RAM=${MAX_MEMORY};"`
translates to:
`MAX_RAM=8G;` in `settings.cfg`
and when this is strung together in the JVM command, `java -Xmx 8G; ...` results in an invalid heap size error from the JVM.

Removing the `;` seems to resolve this issue.

**Comment by itzg** [comment]
Fixed by #365

**Comment by itzg** [comment]
Re-opening since we found in #366 that some (or most?) CurseForge/FTB startup scripts expect to strip the trailing character.

**Comment by iamtpage** [comment]
I must be confused with how the container runs, let me explain my use case.
First a few assumptions:
- `MEMORY` by default is `1G`
- You can override `Xms` and `Xmx` by setting `INIT_MEMORY` and `MAX_MEMORY` respectively
- The docker container modifies `/data/FeedTheBeast/settings.cfg` and replaces values with sed according to environmental variables specified when the container starts up (including the ones above)

I run a docker-compose setup for this container as such:
```
  minecraft-server:
    image: hub.tpage.io/tyler/minecraft-server:latest
    ports:
      - 25565:25565
    volumes:
      - /opt/docker-local/minecraft-server:/data
    environment:
      EULA: "TRUE"
      TYPE: "CURSEFORGE"
      MANIFEST: "/data/FeedTheBeast/manifest.json"
      VERSION: "1.12.2"
      CF_SERVER_MOD: "https://www.curseforge.com/minecraft/modpacks/dmt-survival/download/2752193"
      ENABLE_QUERY: "true"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "8G"
      SNOOPER_ENABLED: "false"
      MAX_BUILD_HEIGHT: "512"
      GENERATE_STRUCTURES: "true"
      ENABLE_RCON: "false"
```

When I run the container, it modified my `settings.cfg` script according to the variables above, when it gets to `MAX_RAM`, it replaces it with `8G;`. Then when it's finished, it attempts to run the server with the `java` command and it crashes. Taking a look at `settings.cfg` shows this:

```
;SETTINGS FOR SERVERSTART SCRIPTS
;See "serverstart.log" in the LOGS subfolder
;For more details/help see: https://github.com/AllTheMods/Server-Scripts

MAX_RAM=8G;
GAME_ARGS=nogui
JAVA_ARGS=-d64 -server -XX:+AggressiveOpts -XX:ParallelGCThreads=3 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -Dfml.readTimeout=90 -Dfml.queryResult=confirm

CRASH_COUNT=5
CRASH_TIMER=600

JAVA_PATH=DISABLE
RUN_FROM_BAD_FOLDER=0
IGNORE_OFFLINE=0
IGNORE_JAVA_CHECK=0
USE_SPONGE=0
HIGH_CPU_PRIORITY=1

JMX_ENABLE=0
JMX_PORT=9010
JMX_HOST=127.0.0.1

MODPACK_NAME=blah
DEFAULT_WORLD_TYPE=BIOMESOP
MCVER=1.12.2
FORGEVER=14.23.5.2838
FORGEURL=DISABLE
```

As you can see `MAX_RAM` is the only line in there that ends with a `;`, and when the java command runs the server it errors out because it ends up looking like: `java -Xmx 8G; ...`

Removing the `;` and restarting the script via `ServerStart.sh` and it runs fine. I'd also like to note that with #365 merged in, this was no longer an issue. 

The modpack I run is a custom one, I specify:
- `MANIFEST=/data/FeedTheBeast/manifest.json`
- `TYPE=CURSEFORGE`
- `CF_SERVER_MOD=<link to modpack on curseforge>`
- `ServerStart.sh` from https://github.com/AllTheMods/Server-Scripts
- `settings.cfg` from https://github.com/AllTheMods/Server-Scripts
