### ISSUE TITLE
server ignore OPS when spigot is used

### ISSUE THREAD

**Issue by panteparak** [itzg/docker-minecraft-server#372]
The problem is, on initial boot up of the container, the specified `OP Player` is not being `OP` if the server type is `Spigot`. If the type is not specified, hence server is a typical `minecraft`

The OP Player get OP permission on the server.

I have checked `ops.json` and `ops.txt.converted`, both contains information related to my Minecraft user account.

I have made sure that I deleted any volume and container when i switch between `Spigot` and `Minecraft Server`

Below is my docker compose

```
version: "3.5"

services:
  mc:
    image: itzg/minecraft-server
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      - OPS=<USER>
      - ONLINE_MODE=TRUE
      - EULA=TRUE
      - MODE=survival
      - LEVEL_TYPE=LARGEBIOMES
      - SPAWN_NPCS=TRUE
      - SPAWN_ANIMALS=TRUE
      - SPAWN_MONSTERS=TRUE
      - GENERATE_STRUCTURES=TRUE
      - FORCE_GAMEMODE=TRUE
      - ENABLE_COMMAND_BLOCK=TURE
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=TRUE
      - ALLOW_NETHER=true
      - SERVER_PORT=25565
      - VERSION=1.14.4
      - DIFFICULTY=normal
      - FORCE_REDOWNLOAD=TRUE
      - TYPE=SPIGOT
```
