### ISSUE TITLE
I cannot get the `-e WORLD` environment variable to work correctly.

### ISSUE THREAD

**Issue by Dextroz** [itzg/docker-minecraft-server#378]
I have a world file at `http://somehost.com/files/2019-08-16-01-00-01-world.zip`.

The zip file's structure is:
- 2019-08-16-01-00-01-world.zip
  - world
    - level.dat and other files.

I am using `docker-compose up -d` to spin up a new container as the previous one I created doesn't have enough memory allocated. I looked into changing the `-e MEMORY` envrionment var but it looks like I cannot change the previous containers memory allocations without using workarounds.

My docker-compose.yml:
```yml
minecraft-server:
  ports:
    - "25565:25565"

  environment:
    EULA: "TRUE"
    INIT_MEMORY: "2G"
    MAX_MEMORY: "3G"
    MAX_PLAYERS: 20
    MOTD: "My Minecraft Server"
    SERVER_NAME: "My Minecraft Server"
    SNOOPER_ENABLED: "FALSE"
    ENABLE_QUERY: "FALSE"
    ENABLE_RCON: "FALSE"
    DIFFICULTY: "normal"
    ALLOW_NETHER: "TRUE"
    ENABLE_COMMAND_BLOCK: "FALSE"
    SPAWN_ANIMALS: "TRUE"
    SPAWN_MONSTERS: "TRUE"
    MAX_BUILD_HEIGHT: 256
    GENERATE_STRUCTURES: "TRUE"
    OPS: "TestUser"
    WORLD: "http://somehost.com/files/2019-08-16-01-00-01-world.zip"

  image: itzg/minecraft-server

  container_name: mc1

  tty: true
  stdin_open: true
  restart: always
```

The server spins up fine however, the world doesn't seem to be from the .zip.

Any suggestions? Thanks :-)
