### ISSUE TITLE
FTBRevelation 3.1.0 not working - Insufficient memory

### ISSUE THREAD

**Issue by lmagalhaes1337** [itzg/docker-minecraft-server#382]
Hi there,

I'm having trouble launching the FTBRevelation 3.1.0 server and it's complaining about the ammout of memory. Thing is, in the settings-local file the maximum RAM is set to 1G and railcraft crashes because of that. But everytime I change it to 4G or some other value, as soon as I use docker start mc it will reset to 1G and fail again. Why is it always overriding the values on docker start ?

Thanks

**Comment by itzg** [comment]
I wasn't able to recreate the problem. To sanity check things, can you `docker pull` to make sure you have the latest copy of the image?

I used the compose content below with `MEMORY` set to `2G` instead of the default `1G`. The server seems to have started up and I confirmed the memory setting got applied to the FTB settings file:

```
PS C:\> docker exec examples_mc_1 cat /data/FeedTheBeast/settings-local.sh
export MIN_RAM="2G"
export MAX_RAM="2G"
export JAVA_PARAMETERS="-Xms2G "
```

and that the final java invocation included the memory settings:
```
PS C:\> docker exec examples_mc_1 ps -ef
PID   USER     TIME  COMMAND
    1 minecraf  0:00 mc-server-runner --stop-duration 60s /data/FeedTheBeast/ServerStart.sh
   81 minecraf  0:00 bash /data/FeedTheBeast/ServerStart.sh
   86 minecraf  4:10 java -server -Xmx2G -Xms2G -Dfml.queryResult=confirm -jar FTBserver-1.12.2-14.23.5.2836-universal.jar nogui
  118 root      0:00 bash
  226 root      0:00 ps -ef
```

and the compose file I used
```yaml
version: '3.2'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: FTB
      FTB_SERVER_MOD: https://www.feed-the-beast.com/projects/ftb-revelation/files/2746968/download
      MEMORY: 2G
    ports:
      - 25565:25565
    volumes:
      - mc-ftb-revelation:/data

volumes:
  mc-ftb-revelation: {}
```

It would interesting to compare what you used for the `MEMORY` setting and what you see with the same commands I used.
