### ISSUE TITLE
Server hangs waiting on eula

### ISSUE THREAD

**Issue by notmeta** [itzg/docker-minecraft-server#394]
I am using a docker-compose file with the current contents:

```yml
version: '3'

services:
  minecraft:
    build: .
    environment:
      MEMORY: 16G
      EULA: "TRUE"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: ATM3R-1.4.9_Server-Full.zip 
    ports:
      - my_ip:25595:25565
    volumes:
      - ./data:/data
```

Here are the output logs:
https://pastebin.com/MC6wtyL0

My `/data` folder contains these current files:
```
/home/minecraft/modded# ls data/
ATM3R-1.4.9_Server-Full.zip  config  eula.txt  FeedTheBeast  mods  plugins
```

Whenever I `cat` the eula.txt within `/data/FeedTheBeast` it always says `eula=false` which makes me think something is overriding the eula being created based off the env var.

Any guidance would be appreciated, cheers.

**Comment by itzg** [comment]
Very strange. It should copy it from the `data/eula.txt` copy of the file, so can you `cat` that file's content? Speaking of which, what should probably solve it is deleting `data/eula.txt` and letting the next container startup recreate the eula file from the environment variable

...however, I'm now wondering if FTB needs that to be literally `eula=true` or if it will allow `eula=TRUE`.

**Comment by notmeta** [comment]
> ...however, I'm now wondering if FTB needs that to be literally `eula=true` or if it will allow `eula=TRUE`.
fwiw I have tried `true` too and the same occurs.

**Comment by itzg** [comment]
OK, I think a recent change (https://github.com/itzg/docker-minecraft-server/commit/34d4ae0b59cdc50660e4e980b565d3f8d2ad2d8b) may have caused this particular issue since it normalizes the EULA value to uppercase. I'll revert a small part of that or have it normalize to lowercase since that seems to be what both vanilla and forge agree on.

**Comment by itzg** [comment]
The fix to make EULA be lowercase is now on Docker Hub. Along with pulling that latest image you'll need to delete the `eula.txt` one more time to let it write the new value.

**Comment by notmeta** [comment]
> The fix to make EULA be lowercase is now on Docker Hub. Along with pulling that latest image you'll need to delete the `eula.txt` one more time to let it write the new value.

The fix worked! Thanks a lot :)

**Comment by bfulcher94** [comment]
I think I may be experiencing this same issue - I've tried deleting the eula.txt file with no luck.
When I check the eula.txt file it shows that it's being set by Docker and is set to true.

Compose file:
```
services:                                                                                                                      
     mc:
       container_name: atm7             
       image: itzg/minecraft-server:java8                                               
       volumes:                                                                                                                      
         - ./modded-minecraft-data:/data                                                                                              
         - ./modpacks:/modpacks:ro                                                                                                   
      environment:                                                                                                                    
       MEMORY: 8G                                                                                                                    
       EULA: "TRUE"                                                                                                                  
       MOTD: "Welcome to ByrdCraft!"                                                                                                 
       SEED: "seed"                                                                                                                 
       tty: "true"                                                                                                                  
       stdin_open: "true"                                                                                                            
       restart: unless-stopped                                                                                                      
       ENABLE_ROLLING_LOGS: "true"                                                                                                   
       TYPE: CURSEFORGE                                                                                                              
       CF_SERVER_MOD: https://media.forgecdn.net/files/3614/956/SIMPLE-SERVER-FILES-0.2.34.zip                                     
     ports:                                                                                                                        
       - "25565:25565"                                                                                                         
  volumes:  
    minecraft-data: {}
```

```
atm7  | [20:35:20] [INFO] Done installing loader, deleting installer!
atm7  | [20:35:20] [INFO] You have not accepted the eula yet.
atm7  | [20:35:20] [INFO] By typing TRUE you are indicating your agreement to the EULA of Mojang.
atm7  | [20:35:20] [INFO] Read it at https://account.mojang.com/documents/minecraft_eula before accepting it.
```
