### ISSUE TITLE
Docker Unhealthy notification

### ISSUE THREAD

**Issue by alphat5** [itzg/docker-minecraft-server#403]
Hi everyone !

I just set-up my server using docker and I got an unhealthy report from portainer with this information. Is it possible to have some help on this issue please ? 

```

Status | unhealthy
Failure count | 4
Last output | Traceback (most recent call last): File "/usr/bin/mcstatus", line 11, in <module> sys.exit(cli()) File "/usr/lib/python2.7/site-packages/click/core.py", line 764, in __call__ return self.main(*args, **kwargs) File "/usr/lib/python2.7/site-packages/click/core.py", line 717, in main rv = self.invoke(ctx) File "/usr/lib/python2.7/site-packages/click/core.py", line 1137, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/lib/python2.7/site-packages/click/core.py", line 956, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke return callback(*args, **kwargs) File "/usr/lib/python2.7/site-packages/mcstatus/scripts/mcstatus.py", line 49, in ping click.echo("{}ms".format(server.ping())) File "/usr/lib/python2.7/site-packages/mcstatus/server.py", line 36, in ping connection = TCPSocketConnection((self.host, self.port)) File "/usr/lib/python2.7/site-packages/mcstatus/protocol/connection.py", line 129, in __init__ self.socket = socket.create_connection(addr, timeout=timeout) File "/usr/lib/python2.7/socket.py", line 575, in create_connection raise err socket.error: [Errno 99] Address not available
```

My `docker-compose.yml`

```
version: '3'

services:
  mc:
    volumes:
     - mc:/data
    image: itzg/minecraft-server
    ports:
      - 28500:28500
    environment:
      - EULA=TRUE
      - TYPE=SPIGOT
      - VERSION=1.14.4
#      - VIRTUAL_HOST=mc.keoneserver.ovh
#      - VIRTUAL_PORT=25565
#      - VIRTUAL_NETWORK=nginx-proxy
#      - LETSENCRYPT_HOST=mc.keoneserver.ovh
      - MEMORY=1G
      - DIFFICULTY=normal
      - ENABLE_RCON=false
      - SERVER_PORT=28500
volumes:
   mc:

#networks:
#   default:
#     external:
#         name: reverse


```

Thanks in advance,
Best,
