### ISSUE TITLE
Need help for ducker-composer.yml

### ISSUE THREAD

**Issue by giuliotoplad** [itzg/docker-minecraft-server#462]
I need help setting up the ducker-composer.yml file.  The server that I have to set is located in a folder called mc, inside there is a custom server jar modified by me, I called it Bukkit.jar.  Can anyone write me the code to insert into ducker-composer.yml to start the server.
Sorry for my english but it's not my main language.

**Comment by itzg** [comment]
It would be something like this where you would need to adjust the jar in `CUSTOM_SERVER` and the host directory you want to attach in the last line:

```yaml
version: '3.7'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: CUSTOM
      CUSTOM_SERVER: /data/my-custom-server.jar
    ports:
      - 25565:25565
    volumes:
      - ./your-own-directory:/data
```
