### ISSUE TITLE
Entire server crash after few hours

### ISSUE THREAD

**Issue by ricoxor** [itzg/docker-minecraft-server#470]
Hello, I installed the last image on two differents server and after 10-15 hours, the two server crashed not just docker the entire server.
I tried again and I had the same issue next day.
Do you know if there is something wrong on the last release ?

And do you know how can I backup world/user achievements from de SSH of my server ?

OS: ‪Debian 8.11‬
Server Management‎ : Plesk
Deamon.log for dockerd : https://pastebin.com/J19TEN1W

Thank you in advance

**Comment by itzg** [comment]
Can you clarify what you mean by the “server”? Do you mean the Minecraft server container or the entire host running Docker?

I’m not sure if I can help much if you’re having dockerd issues. 

As for backups, I do provide this image as one solution

https://hub.docker.com/r/itzg/mc-backup

**Comment by ricoxor** [comment]
I tried to host the minecraft image on two servers and each time after few hours the entire server crashed. Not just docker.

**Comment by micschwarz** [comment]
I do have the same problem. I'm running a PaperMc 1.15.2 Server. After one day the mc-server starts to lag and after few minutes the entire Docker host does not respond (cannot connect via SSH, other Docker Container stop working, etc..). I did start Papermc with `--noconsole`

This is my docker-compose file:
```
version: '3'

services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - ./data/minecraft:/data
    environment:
      TYPE: "PAPER"
      EULA: "TRUE"
      MEMORY: "4G"
      SERVER_NAME: "Server"
      MOTD: "Super Duper Server"
      ENABLE_RCON: "TRUE"
      RCON_PASSWORD: "passwd"
      RCON_PORT: 28016
    restart: always
    ports:
      - 28016:28016
    command: --noconsole
  router:
    restart: always
    image: itzg/mc-router
    ports:
      - 25565:25565
    command: --mapping=mc.url.example=minecraft:25565
```
