### ISSUE TITLE
Cannot connect to docker container

### ISSUE THREAD

**Issue by Dalewn** [itzg/docker-minecraft-server#477]
Hey,

after setting up a pretty basic container on my locally running docker using
`docker run -d -p 25565:25565 -e EULA=TRUE --name mc itzg/minecraft-server`
I simply cannot connect to it. I can see in the log that the server was set up fine and seems to be running.
Trying to directly connect to it via "localhost:25565" or "127.0.0.1:25565" directly doesn't work either.

I've previously tried running it on a different machine, with the same results.
Does anyone have clues or hints as to why this doesn't work or what I might be doing wrong?

EDIT: Just stumbled accross the OPENJ9 tag, which surprisingly is working well. Maybe sth wrong witht he LATEST tag?

**Comment by stefandesu** [comment]
I'm having the same issue, except that even the openj9 tag or some older tags I've tried do not work for me either. In the logs everything looks fine, but Minecraft can't connect to it and the port doesn't even show up as open if I use a port scanner. 

If I use the "sirplexus/minecraft-server-standalone" image (which I found in the official Minecraft Server docs), everything works fine. But it seems like nobody's actually using that image so I'd prefer to use this one.

Here's my docker-compose file:

```yaml
version: "3"

services:
  minecraft:
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
    volumes:
      - ./data/mc:/data
    environment:
      - EULA=TRUE
      - MEMORY=3G
    restart: always
```

Port 25565 is allowed in ufw (and if it works with the other image, this shouldn't be the issue):
```
$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
25565/udp                  ALLOW       Anywhere
25565/tcp                  ALLOW       Anywhere
```
