### ISSUE TITLE
Spigot server stuck on "Loading libraries, please wait..."

### ISSUE THREAD

**Issue by snooze92** [itzg/docker-minecraft-server#482]
Hi there!

First of all, thanks for the great work. This is extremely configurable and amazingly documented!

I am having an issue which I am guessing is more due to Spigot itself than the Docker container specifically, but hoping that your experience will help me figure out a way forward.

### Context

I am trying to run a Spigot server with plugins, on a small Intel NUC at home I use as a mediabox the rest of the time...

My `docker-compose.yml` file looks like this:
```
version: '3.7'
services:
  minecraft-server:
    container_name: minecraft-server
    build: ./minecraft-server
    restart: unless-stopped
    ports:
      - "25565:25565" # Minecraft
      - "25575:25575" # RCon
      - "8123:8123" # Dynmap web UI
    environment:
      - EULA=true
      - SERVER_NAME=Mediabox
      - SERVER_PORT=25565
      - DIFFICULTY=easy
      - OPS=snooze92
      - ENABLE_RCON=true
      - RCON_PASSWORD=admin
      - RCON_PORT=25575
      - MAX_PLAYERS=5
      - MAX_WORLD_SIZE=100000
      - ALLOW_NETHER=true
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=true
      - ENABLE_COMMAND_BLOCK=true
      - GENERATE_STRUCTURES=true
      - MAX_BUILD_HEIGHT=512
      - SPAWN_ANIMALS=true
      - SPAWN_MONSTERS=true
      - SPAWN_NPCS=true
      - SPAWN_PROTECTION=0
      - VIEW_DISTANCE=20
      - MODE=survival
      - LEVEL=world
      - ALLOW_FLIGHT=true
      - MEMORY=3G
      - CONSOLE=FALSE
      - GUI=FALSE
    volumes:
      - /data/minecraft/server:/data
  rcon:
    container_name: rcon
    image: itzg/rcon
    ports:
      - "4326:4326" # Web UI
      - "4327:4327" # Websocket
    volumes:
      - /data/minecraft/rcon:/opt/rcon-web-admin/db
```

My `minecraft-server/Dockerfile` file looks like this:
```
FROM itzg/minecraft-server

ENV TYPE=SPIGOT
```

And finally, my `minecraft-server/plugins.yml` file looks like this:
```
plugins:
  worldedit:
    file: WorldEdit.jar
    url: https://dev.bukkit.org/projects/worldedit/files/latest
  FastAsyncWorldEdit:
    file: FastAsyncWorldEdit.jar
    url: https://empcraft.com/fawe/latest.php?bukkit
  worldguard:
    file: WorldGuard.jar
    url: https://dev.bukkit.org/projects/worldguard/files/latest
  citizens:
    file: Citizens.jar
    url: https://dev.bukkit.org/projects/citizens/files/latest
  dynmap:
    file: Dynmap.jar
    url: https://dev.bukkit.org/projects/dynmap/files/latest
```

I don't think it makes a difference but for sake of completeness, I run this wrapped inside a `systemctl` service:
```
[Unit]
Description=my Minecraft server running in Docker Compose
Requires=docker.service
After=network.target local-fs.target docker.service
BindsTo=data.mount

[Service]
User=snooze92
Group=snooze92
WorkingDirectory=/home/snooze92/minecraft
Restart=always
ExecStart=/usr/local/bin/docker-compose up
ExecStop=/usr/local/bin/docker-compose down -v

[Install]
WantedBy=multi-user.target
```

## Symptoms

The beginning of the logs look fine, until
```
[init] Starting the Minecraft server...
```

I then get a warning about the build being outdated, which I find surprising: it happens when I'm configured with the LATEST version by default. The warnings goes away when I pick an older version explicitly. Not sure why Spigot would log an outdated warning on the most recent version of their JAR...
```
*** Error, this build is outdated ***
*** Please download a new build as per instructions from https://www.spigotmc.org/go/outdated-spigot ***
*** Server will start in 20 seconds ***
```

Twenty seconds later, the server does start, I can connect to it and have started to play... everything seems fine. It does log this line:
```
Loading libraries, please wait...
```

And nothing after that. I am able to play the basic game, but I am not sure it ever completes loading of the libraries. I have read similar symptoms online, along with Spigot pegging 1 CPU. It is the case for me as well, as `htop` shows a CPU constantly at 100% even while 0 player is connected...
![htop](https://user-images.githubusercontent.com/3275550/78504391-31de1500-776d-11ea-8f5b-6e0f168420f9.png)

I can see the `--noconsole` and `nogui` arguments there, which reportedly solved the issue for people previously, but still no luck for me.

I am not sure if it is related, but I am also unable to configure the RCON port in the RCON Web UI I run thanks to another container of yours. The Web UI displays well and functions as expected, but no combination of host/ip and port seems to work.

One last thing that I am unsure is related... If I `ls /data/minecraft/server/plugins/` I only see `PluginMetrics` and none of the plugins I have listed in my `plugins.yml` file. Dynmap is definitely not working, as its port 8123 does not respond.

## Questions

I am a Software Engineer, pretty familiar with Docker, Docker Compose, Java, etc. but totally unfamiliar with Spigot in particular.

Do you know where I should be looking next to understand my issue(s)?

Do you know what I can try to fix things?
