### ISSUE TITLE
Idle SPIGOT container using Single core of cpu, tried nogui --noconsole

### ISSUE THREAD

**Issue by LarsMudde** [itzg/docker-minecraft-server#484]
Hi,

I'm trying to host a simple Spigot server for home use on my Ubuntu-server 19.04 homeserver.
This docker container looks very good so I tried to add it to my Docker-compose 3.7 stack.

```
  minecraft:
    container_name: minecraft
    restart: always
    image: itzg/minecraft-server
    volumes:
      - ${USERDIR}/docker/minecraft:/data
    ports:
      - "25565:25565"
    environment:
      - EULA=TRUE
      - ENABLE_RCON=false
      - VERSION=1.15.2
      - MAX_PLAYERS=20
      - UID=${PUID}
      - GID=${PGID}
      - TYPE=SPIGOT
      - SNOOPER_ENABLED=false
      - MAX_TICK_TIME=60000
      - MEMORY=1G
      - MAX_MEMORY=4G
      - CONSOLE=FALSE
      - GUI=FALSE
      - OPS=Update94
 #   tty: true #tried both true and false
 #   stdin_open: true #tried both true and false
 #    command: nogui --noconsole #tried this too
    networks:
      - web
```

Unfortunately the server keeps hogging 100% on one full core at any time. I don't think this is normal. The CPU I'm using is an Intel 7700T. 

This issue is very similar to this topic [https://github.com/itzg/docker-minecraft-server/issues/80](https://github.com/itzg/docker-minecraft-server/issues/80) however none of the proposed solutions seems to solve my problem.

Any help/suggestions/ideas are most welcome, Maybe I'm just missing something simple.

Regards,

Lars
