### ISSUE TITLE
Curl can't resolve host: Spigot 1.15.2

### ISSUE THREAD

**Issue by nose26** [itzg/docker-minecraft-server#498]
I'm running docker-compose on a centos machine.  Whenever I attempt to run the container, it fails to download the .jar server file.  I am specifically having this issue with Spigot, but when I tried to use Paper it gave the same error.  When I set the server to custom, and specify a spigot.jar file, it runs, but gets hung up on loading libraries.  Because in this state it does not exit immediantly (as it does when it fails to download in the other two cases), I am able to open a shell and attempt to ping a few addresses, all of which fail.
  
This is my docker-compose file:
```
version: '3.3'
services:
    minecraft-server:
        image: itzg/minecraft-server:latest
        ports:
            - '80:80'
            - '25565:25565'
        volumes:
            - type: bind
              source: ./finServer/minecraft
              target: /data
        container_name: finServer
        environment:
            - EULA="true"
            - VERSION=1.15.2
            - TYPE=SPIGOT
            #- TYPE=CUSTOM
            #- CUSTOM_SERVER=/data/spigot-1.15.2.jar
            - MAX_MEMORY=4G
        command: --noconsole
```  
  
And this is the result:
```
Starting finServer ... done
Attaching to finServer
finServer           | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x   15 1000     1001          4096 Apr 18 21:00 /data'
finServer           | [init] Resolved version given 1.15.2 into 1.15.2
finServer           | [init] Resolving type given SPIGOT
finServer           | [init] Downloading Spigot from https://cdn.getbukkit.org/spigot/spigot-1.15.2.jar ...
finServer           | curl: (6) Could not resolve host: cdn.getbukkit.org
finServer exited with code 6

```
If I navigate to that url on a different machine, it downloads correctly.  
  
Meanwhile, the same issue occurs with Paper as well.  My docker-compose file in that situation:
```
version: '3.3'
services:
    minecraft-server:
        image: itzg/minecraft-server:latest
        ports:
            - '80:80'
            - '25565:25565'
        volumes:
            - type: bind
              source: ./finServer/minecraft
              target: /data
        container_name: finServer
        environment:
            - EULA=TRUE
            - VERSION=1.15.2
            - TYPE=PAPER
            #- TYPE=CUSTOM
            #- CUSTOM_SERVER=/data/spigot-1.15.2.jar
            - MAX_MEMORY=4G
        command: --noconsole

```  
And the output:  
```
Recreating finServer ... done
Attaching to finServer
finServer           | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    2 1000     1001            22 Apr 18 21:14 /data'
finServer           | [init] Resolved version given 1.15.2 into 1.15.2
finServer           | [init] Resolving type given PAPER
finServer           | [init] Downloading Paper 1.15.2 from https://papermc.io/api/v1/paper/1.15.2/latest/download ...
finServer           | curl: (6) Could not resolve host: papermc.io
finServer           | [init] ERROR: failed to download from https://papermc.io/api/v1/paper/1.15.2/latest/download (status=0)
finServer exited with code 3
```  
  
Once again, I can easily go to that url and download successfully.  I thought maybe using an already build spigot.jar file might help, so I tried using a custom server.  You'll note the commented out lines in the dockerfiles above.  This is the result when they are uncommented (and of course 'TYPE=SPIGOT' commented):  
```
Recreating finServer ... done
Attaching to finServer
finServer           | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    2 1000     1001            47 Apr 18 21:20 /data'
finServer           | [init] Resolved version given 1.15.2 into 1.15.2
finServer           | [init] Resolving type given CUSTOM
finServer           | [init] Using custom server jar at /data/spigot-1.15.2.jar ...
finServer           | [init] Creating server.properties in /data/server.properties
finServer           | [init] Setting server-name to 'Dedicated Server' in /data/server.properties
finServer           | [init] Skip setting server-ip
finServer           | [init] Setting server-port to '25565' in /data/server.properties
finServer           | [init] Setting motd to 'A Custom Minecraft Server powered by Docker' in /data/server.properties
finServer           | [init] Skip setting allow-nether
finServer           | [init] Skip setting announce-player-achievements
finServer           | [init] Skip setting enable-command-block
finServer           | [init] Skip setting spawn-animals
finServer           | [init] Skip setting spawn-monsters
finServer           | [init] Skip setting spawn-npcs
finServer           | [init] Skip setting spawn-protection
finServer           | [init] Skip setting generate-structures
finServer           | [init] Skip setting view-distance
finServer           | [init] Skip setting hardcore
finServer           | [init] Skip setting snooper-enabled
finServer           | [init] Skip setting max-build-height
finServer           | [init] Skip setting force-gamemode
finServer           | [init] Skip setting max-tick-time
finServer           | [init] Skip setting enable-query
finServer           | [init] Skip setting query.port
finServer           | [init] Setting enable-rcon to 'true' in /data/server.properties
finServer           | [init] Setting rcon.password to 'minecraft' in /data/server.properties
finServer           | [init] Setting rcon.port to '25575' in /data/server.properties
finServer           | [init] Skip setting max-players
finServer           | [init] Skip setting max-world-size
finServer           | [init] Setting level-name to 'world' in /data/server.properties
finServer           | [init] Skip setting level-seed
finServer           | [init] Setting pvp to 'true' in /data/server.properties
finServer           | [init] Skip setting generator-settings
finServer           | [init] Setting online-mode to 'true' in /data/server.properties
finServer           | [init] Skip setting allow-flight
finServer           | [init] Setting level-type to 'DEFAULT' in /data/server.properties
finServer           | [init] Skip setting resource-pack
finServer           | [init] Skip setting resource-pack-sha1
finServer           | [init] Skip setting player-idle-timeout
finServer           | [init] Setting difficulty to '1' in /data/server.properties
finServer           | [init] Creating log4j2.xml in /data/log4j2.xml
finServer           | [init] Checking for JSON files.
finServer           | [init] Setting initial memory to 1G and max to 4G
finServer           | [init] Starting the Minecraft server...
finServer           | *** Error, this build is outdated ***
finServer           | *** Please download a new build as per instructions from https://www.spigotmc.org/go/outdated-spigot ***
finServer           | *** Server will start in 20 seconds ***
finServer           | Loading libraries, please wait...

```
I guess maybe I just need to wait longer, but I have let various instances run for over 30 minutes, and one notable attempt ran overnight for close to 10 hours.  In any case, when I open a shell in the container, I can't seem to access the addresses listed in either of the other previous attempts.  Not sure what's going on here.
