### ISSUE TITLE
environmental variables not set in server.properties in curseforge server

### ISSUE THREAD

**Issue by crowlKats** [itzg/docker-minecraft-server#506]
This is my docker-compose file:
```yml
version: '3.8'

services:
  mc_curse:
    image: itzg/minecraft-server
    container_name: mc_sevtech
    restart: always
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      VERSION: 1.12.2
      CF_SERVER_MOD: "https://media.forgecdn.net/files/2788/614/SevTech_Ages_Server_3.1.2-hotfix.1.zip"
      MAX_MEMORY: 5G
      ONLINE_MODE: "false"
      FORCE_GAMEMODE: "true"
      MAX_PLAYERS: 10
      SNOOPER_ENABLED: "false"
    command: --noconsole
    ports:
      - 25566:25565
      - 25576:25575
    volumes:
      - ~/servers/minecraft/sevtech:/data
```
none of the environmental variables were set that affect the server.properties file. Also the defaults set by the image (ie RCON) are not used and are just MC's defaults
