### ISSUE TITLE
can't restart server

### ISSUE THREAD

**Issue by xchoice** [itzg/docker-minecraft-server#522]
Modpack: Manufactio
url: https://www.curseforge.com/minecraft/modpacks/manufactio/files/2943928

docker compose:
```
version: "3.7"
services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    volumes:
      - /srv/minecraft/Manufactio:/data
    environment:
      EULA: "TRUE"
      MEMORY: 8G
      TYPE: CURSE_INSTANCE
      VERSION: 1.12.2
      CURSE_INSTANCE_JSON: minecraftinstance.json
```

error:
[init] Setting initial memory to 8G and max to 8G
2020-05-08T17:41:06.794Z        INFO    mc-server-runner.cfsync Preparing Twitch/Curse instance {"name": "Manufactio"}
2020-05-08T17:41:06.795Z        INFO    mc-server-runner.cfsync Preparing forge server
2020-05-08T17:41:06.795Z        INFO    mc-server-runner.cfsync Preparing libraries for forge server
2020-05-08T17:41:06.861Z        INFO    mc-server-runner.cfsync Preparing mods
2020-05-08T17:41:06.862Z        FATAL   mc-server-runner        Failed to prepare instance      {"error": "failed to prepare mods: failed to remove old mod file: remove mods/memory_repo: directory not empty"}

For the setup, I downloaded the pack from twitch app, copied the files to the attached volume, and started the server with docker-compose up -d. The server starts without problem.

My problem is when I stop the server, and try to bring it up again.
Sometimes instead of "mods/memory_repo" it complains about "mods/1.12.2". If I remove both folders, the server starts again without problem.
