### ISSUE TITLE
Magma + SkyFactory4 - crashes at boot

### ISSUE THREAD

**Issue by Fireant456** [itzg/docker-minecraft-server#525]
I have tested Magma with SkyFactory4 on Windows and had no issues getting it to boot and connect to it. I am running the latest docker version, with the following docker-compose options...

```yml
  skyfactory:
    image: itzg/minecraft-server
    container_name: skyfactory.minecraft.net
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - TYPE=MAGMA
      - VERSION=1.12.2
      - EULA=TRUE
      - ONLINE_MODE=FALSE
      - SERVER_PORT=25568
      - INIT_MEMORY=4G
      - MAX_MEMORY=8G
      # - JVM_XX_OPTS:+UseG1GC
      # - JVM_DD_OPTS=sun.rmi.dgc.server.gcInterval:2147483646
      # - JVM_XX_OPTS=+UnlockExperimentalVMOptions
      # - JVM_XX_OPTS=G1NewSizePercent:20
      # - JVM_XX_OPTS=G1ReservePercent:20
      # - JVM_XX_OPTS=MaxGCPauseMillis:50
      # - JVM_XX_OPTS=G1HeapRegionSize:32M
      # - JVM_DD_OPTS=fml.readTimeout:180      
    volumes:
      - ./data-skyfactory:/data
    ports:
      - "25568:25568/tcp"
      - "25568:25568/udp"
```

I am trying to see if the JVM variables are the culprit as these variables were included in the original mod pack startup scripts. I am unsure if I am doing the -XX variables correctly or not. Below is the original startup config line of JVM options.

`-XX:+UseG1GC 
-Dsun.rmi.dgc.server.gcInterval=2147483646 
-XX:+UnlockExperimentalVMOptions 
-XX:G1NewSizePercent=20 
-XX:G1ReservePercent=20 
-XX:MaxGCPauseMillis=50 
-XX:G1HeapRegionSize=32M 
-Dfml.readTimeout=180`

**Comment by Fireant456** [comment]
Switched over to this, it at least launches without the mod installed... Still unsure if it is correct.
```yml
    environment:
      - TYPE=MAGMA
      - VERSION=1.12.2
      - EULA=TRUE
      - ONLINE_MODE=FALSE
      - SERVER_PORT=25568
      - INIT_MEMORY=4G
      - MAX_MEMORY=8G
      - JVM_OPTS=-XX:+UseG1GC
      - JVM_DD_OPTS=sun.rmi.dgc.server.gcInterval=2147483646
      - JVM_OPTS=-XX:+UnlockExperimentalVMOptions
      - JVM_OPTS=-XX:G1NewSizePercent=20
      - JVM_OPTS=-XX:G1ReservePercent=20
      - JVM_OPTS=-XX:MaxGCPauseMillis=50
      - JVM_OPTS=-XX:G1HeapRegionSize=32M
      - JVM_DD_OPTS=fml.readTimeout=180```

**Comment by itzg** [comment]
Can you include a snippet of the logs where the container crashes?

As for setting multiple values within the `JVM_OPTS` you need to do that as one long string. I recommend using the `key: value` style there and then yaml validation would have flagged the repeated variable declarations. Also, with that style you can use [block scalar style](https://yaml.org/spec/1.2/spec.html#id2795688):

```yaml
environment:
  TYPE: MAGMA
  VERSION: 1.12.2
  EULA: TRUE
  ONLINE_MODE: FALSE
  SERVER_PORT: 25568
  INIT_MEMORY: 4G
  MAX_MEMORY: 8G
  JVM_DD_OPTS: >
    sun.rmi.dgc.server.gcInterval=2147483646
    fml.readTimeout=180```
  JVM_OPTS: >
    -XX:+UseG1GC
    -XX:+UnlockExperimentalVMOptions
    -XX:G1NewSizePercent=20
    -XX:G1ReservePercent=20
    -XX:MaxGCPauseMillis=50
    -XX:G1HeapRegionSize=32M
```
