### ISSUE TITLE
Encountering Forge Error regarding missing .toml files

### ISSUE THREAD

**Issue by LewisLarsen** [itzg/docker-minecraft-server#530]
Hi,

I am attempting to get an Enigmatica 2 Expert: Skyblock Server running in Docker but I am encountering errors related to `mods.toml missing metadata for modid null`. The docker-compose file itself is using the `GENERIC_PACK` and `TYPE:FORGE` attributes due to CurseForge/FTB complaining that the server zip wasn't a valid server pack.

Here's my docker-compose file for Enigmatica 2 Skyblock - 

```
version: '3.7'

networks:
  minecraft:

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: modded_minecraft
    environment:
      EULA: "TRUE"
      SERVER_NAME: "Docker Modded Server"
      MOTD: "A Modded Minecraft Server Running in Docker."
      OPS: "UFPInfinity"
      TYPE: "FORGE"
      GENERIC_PACK: "https://media.forgecdn.net/files/2896/717/Enigmatica2ExpertSkyblockServer-1.35.zip"
      #MAX_MEMORY: 4096
    restart: always  
    ports:
      - "25566:25565" # Minecraft Connection Port
    volumes:
      - ./src:/data
    networks:
      - minecraft
```
Here's the crash report - 
```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 5/15/20 4:01 PM
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	mods.toml missing metadata for modid null,
	The Mod File /data/mods/BuildingGadgets-2.7.4.jar has mods that were not found
]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:179) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:611) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 4.19.76-linuxkit
	Java Version: 1.8.0_212, IcedTea
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), IcedTea
	Memory: 706877824 bytes (674 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	CPUs: 2
	JVM Flags: 3 total; -XX:+UseG1GC -Xms1G -Xmx1G
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.0
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.0-server.jar Minecraft {minecraft@1.15.2 NONE}
		BuildingGadgets-2.7.4.jar Building Gadgets {buildinggadgets@3.1.1b NONE}
		forge-1.15.2-31.1.0-universal.jar Forge {forge@31.1.0 NONE}
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
```

Any assistance would be appreciated, I have managed to get an MCEternal server running in this image, however Enigmatica 2 Skyblock is proving problematic.

Thanks :)
