### ISSUE TITLE
start-server.sh vs StartServer.sh in modpack

### ISSUE THREAD

**Issue by tahnok** [itzg/docker-minecraft-server#540]
Hello,

I am trying to get [Enigmatica 4](https://www.curseforge.com/minecraft/modpacks/enigmatica4/files) running, but I was running into an issue where on boot it would error with `Please make sure you are using the server version of the FTB modpack!`

I believe the issue is that this particular modpack has a `start-server.sh` file instead of `StartServer.sh`. By renaming the file and creating a new zip, the modpack successfully boots

I don't have the brain power to dive through the code, but might it be possible to look for either script name to determine if the server modpack is valid?

sample docker-compose file in case I was doing something dumb.

```
---
version: "3"
services:
        minecraft-mod:
                ports:
                        - "25566:25565"
                environment:
                        EULA: "TRUE"
                        TYPE: CURSEFORGE
                        CF_SERVER_MOD: Enigmatica4Server-0.5.4-hack.zip
                        VERSON: '1.14.4'
                image: itzg/minecraft-server
                restart: unless-stopped
                volumes:
                        - /mnt/raid/docker-data/minecraft-mod:/data
```
