### ISSUE TITLE
minecraft beta support

### ISSUE THREAD

**Issue by JuniorJPDJ** [itzg/docker-minecraft-server#590]
Oldschool is still alive ;D

**Comment by itzg** [comment]
Are you asking for beta version support? It might already work by passing those with `VERSION`. I haven't tried yet myself.

**Comment by JuniorJPDJ** [comment]
I tried it.
There's what it does:
`Resolved version given b1.6.6 into 1.16.1`
If I try custom jar with this version - it cries about `Protocol error` when your healthcheck tries to rcon.
Rcon is probably not supported in this version.
Workaround would be needed ;/

**Comment by itzg** [comment]
For the rcon based health check it can be disabled a few ways, but easiest is with `-e DISABLE_HEALTHCHECK=true`

https://github.com/itzg/docker-minecraft-server#healthcheck

**Comment by itzg** [comment]
...and I'll fix that weird override it did there

**Comment by itzg** [comment]
...however, with that it won't work anyway since b1.6.6. doesn't provide a server jar to download:

![image](https://user-images.githubusercontent.com/988985/87880766-eff27b00-c9b9-11ea-95b2-6e6eb902aaed.png)

**Comment by JuniorJPDJ** [comment]
What about console and graceful shutdown in that case when rcon is not working?

**Comment by itzg** [comment]
Using `docker attach` to access console is always an option when adding `-it` to `docker run` command line. Refer to last part of this section

https://github.com/itzg/docker-minecraft-server#interacting-with-the-server

FYI image has been updated to accept `b1.6.6`, and will now correctly report the absence of the server jar download.

**Comment by JuniorJPDJ** [comment]
Ok, thanks, I'll check it tommorow ;)

**Comment by JuniorJPDJ** [comment]
Yes, thank you, every issue with oldschool beta minecraft is now resolved.
For other searching guys I can provide my docker-compose ;)
```
version: "3.5"

services:
  mc:
    environment:
      EULA: "TRUE"
      TYPE: "CUSTOM"
      VERSION: "b1.6.6"
      CUSTOM_SERVER: "craftbukkit_0.0.0-892.jar"
      INIT_MEMORY: 512M
      MAX_MEMORY: 2G
      ENABLE_RCON: "FALSE"
      GUI: "FALSE"
      DISABLE_HEALTHCHECK: "true"
    image: itzg/minecraft-server
    stop_grace_period: 5m
    ports:
      - 25565:25565
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
```
