### ISSUE TITLE
Curseforge server fails to start 

### ISSUE THREAD

**Issue by the0ckid82** [itzg/docker-minecraft-server#601]
Trying to setup a Curseforge server using the [MC Eternal](https://www.curseforge.com/minecraft/modpacks/minecraft-eternal/files/3018935) Modpack 

my docker-compose file is below 
```
version: "3"

services:
  router:
    image: itzg/mc-router
    restart: always
    ports:
      - 25565:25565
    command:
      - --paper.theock.net=paper:25565,eternal.theock.net=eternal:25565

  paper:
    image: itzg/minecraft-server
    restart: always
    environment:
      TYPE: "PAPER"
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: '${RCON_PASS}'
      MEMORY: "4G"
    volumes:
      - "${CONFIG_DIR}/minecraft/paper:/data"

  eternal:
    image: itzg/minecraft-server
    environment:
      TYPE: "CURSEFORGE"
      EULA: "true"
      VERSION: "1.12.2"
      ENABLE_RCON: "true"
      RCON_PASSWORD: '${RCON_PASS}'
      JVM_OPTS: '-Dfml.queryResult=confirm'
      CF_SERVER_MOD: /modpacks/Eternal.zip
      MEMORY: "8G"
    volumes:
      - "${CONFIG_DIR}/minecraft/eternal:/data"
      - "${CONFIG_DIR}/minecraft/modpacks:/modpacks:ro"

  rcon:
    image: itzg/rcon
    restart: always
    environment:
      RWA_USERNAME: OC
      RWA_PASSWORD: '${RCON_PASS}'
      RAW_ADMIN: "TRUE"
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "${CONFIG_DIR}/rcon:/opt/rcon-web-admin/db"
```

When ever i start the container it attempts to build the server but is never successful as it gets stuck in a loop during the build process. I have attached the container logs to show what is happening. i have tried using other modpacks and have the same issue including the skyfactory modpack shown in the example docker-compose file, and have tried both workarounds
 `-e USE_MODPACK_START_SCRIPT=false.`
`-e FTB_LEGACYJAVAFIXER=true`
both with similar results 

[eternal_docker_log.log](https://github.com/itzg/docker-minecraft-server/files/5025336/eternal_docker_log.log)
