### ISSUE TITLE
Intel NUC - CPU usage at 100% - 1.16.2

### ISSUE THREAD

**Issue by MrBLJ** [itzg/docker-minecraft-server#624]
Hello all,

I'm faced with an issue when running this container.

I'm using this [NUC model](https://www.intel.com/content/www/us/en/products/boards-kits/nuc/kits/nuc6cayh.html) for my home server (4Gb ram), and I was hoping to run a vanilla minecraft server with it. It's been running fine for a few days and a few users could connect & enjoy the game simultaneously (only LAN client, this is for the family).

Now, without changing anything, yesterday, I was alerted because the CPU usage was at 100% for a few minutes, and CPU temp was getting out of hand. I have setup a failsafe so that the NUC will shut down in that case, but there's been a light smell of burnt plastic ... anyway, I've unmounted the all thing and so far so good. I'm working in the field of electronics and to me the board doesn't look like it's been fried. It's working as usual for now.

Anyway. I've run tests and for some reason, each time the container is launched now, CPU usage is going like crazy. According to node-exporter, core one usage is maxed out, the others are at their usual level ~33%. not sure if this is relevant, this is definitely not my area of expertise.

Here's my compose file :
```
---
version: "3.7"
services:
  minecraft-server:
    ports:
      - "25565:25565"
    environment:
      CONSOLE: "FALSE"
      EULA: "TRUE"
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "60000"
      ONLINE_MODE: "FALSE"
      DIFFICULTY: normal
      MAX_PLAYERS: 2
    image: itzg/minecraft-server
    container_name: minecraft
    tty: true
    stdin_open: true
    restart: "no"
    volumes:
      - /mnt/NAS/dev/minecraft:/data
```

According to you, is that a hardware issue (Meaning my NUC is not powerful enough) ? Thing is, I used to run a minecraft server on my PI, and it was doing fine for 2 clients. I wasn't using docker though.

Edit:

CPU usage tested this morning:
![image](https://user-images.githubusercontent.com/12542442/92583291-68770900-f292-11ea-8684-1ead284a09c2.png)
High usage corresponds to when the container is launched. Tested with a fresh container, made sure the world was fully generated (with logs, and by connecting to the server), and with 1 player.
