### ISSUE TITLE
Forge Failed to Prepare Libary

### ISSUE THREAD

**Issue by Shiiivu** [itzg/docker-minecraft-server#632]
FATAL	mc-server-runner	Failed to prepare instance	{"error": "failed to prepare forge: failed to prepare libraries: unable to open forge jar: read .: is a directory"}

Get this when trying to run my CURSED_FORGE_INSTANCE
Not too sure what it wants me to do to fix it if i'm gonna be honest, Trying to run the modpack Valhelsia 3 1.16.1 Everything works till i get to that. I Cant find any documentation on how to fix it so posting here

Cheers :D

**Comment by itzg** [comment]
Can you provide the `docker run` or compose file you're using to create the container?

**Comment by Shiiivu** [comment]
Pretty sure this is what I ran mate. I also manually put the server mod data there to fix an other issue I was having but yes this is what I did.

docker run -d -v /opt/Valhelsia/Data -e TYPE=CURSEFORGE \
    -e CF_SERVER_MOD=Valhelsia_SERVER-3.0.16.zip \
    -p 25565:25565 -e EULA=TRUE --name mc itzg/minecraft-server

**Comment by itzg** [comment]
Copying over logs screenshot from Discord:

![image](https://user-images.githubusercontent.com/988985/93344056-d6718200-f7f6-11ea-8475-60a5620a5e4a.png)

From those logs it looks like `-e TYPE=CURSE_INSTANCE` but it should be `-e TYPE=CURSEFORGE`, referring to https://github.com/itzg/docker-minecraft-server#running-a-server-with-a-curseforge-modpack

**Comment by itzg** [comment]
I have tested the modpack by:
1. creating a directory called `valhelsia3` (but the exact name doesn't matter)
2. created the `docker-compose.yml` below in that directory
3. downloaded `Valhelsia_SERVER-3.0.16.zip` into that directory
4. started with `docker-compose up -d`

`docker-compose.yml`:
```yaml
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/Valhelsia_SERVER-3.0.16.zip
    ports:
    - 25565:25565
    volumes:
    - ./data:/data
    - ./Valhelsia_SERVER-3.0.16.zip:/modpacks/Valhelsia_SERVER-3.0.16.zip:ro
```
