### ISSUE TITLE
/start-deployFTBA: line 40: /data/ftb-installer: Permission denied

### ISSUE THREAD

**Issue by workino** [itzg/docker-minecraft-server#645]
Hello,
i'm trying to install FTBA type of server but i'm getting this error with every modpack.

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 6 Aug  9 18:09 /data'
[init] Resolved version given LATEST into 1.16.3
[init] Resolving type given FTBA
[init] Downloading FTB installer
[init] Installing modpack ID 35, version ID 37
/start-deployFTBA: line 40: /data/ftb-installer: Permission denied

Is it a bug or i'm doing something wrong?

**Comment by itzg** [comment]
If you have `/data` attached from a host directory check to make sure the directory's file system does not have the `noexec` option set. If that's set then the kernel will prevent things from being expected, such as the downloaded installer.

**Comment by mmastrocinque** [comment]
Having the same issue, Checking with findmnt the directory has  rw,relatime. Ideas?

**Comment by mmastrocinque** [comment]
Removing -e MEMORY 6G fixed the issue?

**Comment by itzg** [comment]
I am not able to recreate the issues reported. I was able to successfully start a container using this compose file:

```yaml
version: "3"

services:
  mc:
    image: itzg/minecraft-server:multiarch
    environment:
      EULA: "TRUE"
      TYPE: FTBA
      FTB_MODPACK_ID: "35"
      MEMORY: 6G
    volumes:
    - ./data:/data
    ports:
    - 25565:25565
```
