### ISSUE TITLE
Unable to start the server after a system update Debian 10, kernel 5.9 mainline.

### ISSUE THREAD

**Issue by Nirsiel** [itzg/docker-minecraft-server#653]
Hi, today I stumbled upon a problem after restarting the whole server after a kernel upgrade. Every docker container booted up normally but Minecraft was tucked in restart-loop. So I deleted it and recreated it but the server just failed to start with the following error output

```
Recreating mc-test_minecraft_1 ... done
Attaching to mc-test_minecraft_1
minecraft_1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    3 1000     1000             6 Oct 23 00:06 /data'
minecraft_1  | [init] Resolved version given LATEST into 1.16.3
minecraft_1  | [init] Resolving type given PAPER
minecraft_1  | [init] Downloading Paper 1.16.3 (build latest) from https://papermc.io/api/v1/paper/1.16.3/latest/download ...
minecraft_1  | [init] server.properties already created, skipping
minecraft_1  | [init] Checking for JSON files.
minecraft_1  | [init] Setting initial memory to 1G and max to 2G
minecraft_1  | [init] Starting the Minecraft server...
minecraft_1  | Error occurred during initialization of VM
minecraft_1  | The flag -XX:+UseG1GC can not be combined with -XX:ParallelGCThreads=0
minecraft_1  | 2020-10-23T00:07:48.894Z WARN    mc-server-runner        sub-process failed      {"exitCode": 1}
minecraft_1  | 2020-10-23T00:07:48.894Z INFO    mc-server-runner        Done
mc-test_minecraft_1 exited with code 1
```

And I'm using the following docker-compose file

```
version: '3'

services:
  minecraft:
    image: itzg/minecraft-server
    restart: always
    environment:
      EULA: "true"
      MAX_MEMORY: 2G
      MAX_PLAYERS: 10
      TYPE: PAPER
      VERSION: LATEST
    command: --noconsole
    ports:
      - 25565:25565
    volumes:
      - ./data:/data
```
