### ISSUE TITLE
failed to download spigot

### ISSUE THREAD

**Issue by soneji** [itzg/docker-minecraft-server#655]
Hi

I am using the spigot server. My container wont go up after updating. Is there anything I'm doing wrong? I would be so grateful for your help

Here is my docker-compose.yml

```yaml
minecraft-server:
  ports:
    - "25565:25565"

  environment:
    EULA: "TRUE"
    MEMORY: 8G
    TYPE: SPIGOT
    VERSION: latest
    MAX_PLAYERS: 100
    DIFFICULTY: normal
    ENABLE_AUTOPAUSE: "TRUE"

  image: itzg/minecraft-server

  container_name: mc

  tty: true
  stdin_open: true
  restart: always

  volumes:
    - ./data:/data
```

Here are my docker-compose logs
```
mc                  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    8 1000     1000          4096 Oct 29 17:24 /data'
mc                  | [init] Resolved version given latest into 1.16.3
mc                  | [init] Autopause functionality enabled
mc                  | [init] Resolving type given SPIGOT
mc                  | [init] Downloading Spigot from https://cdn.getbukkit.org/spigot/spigot-1.16.3.jar ...
mc                  |
mc                  | ERROR: failed to download from https://cdn.getbukkit.org/spigot/spigot-1.16.3.jar
mc                  |        Visit https://getbukkit.org/download/spigot to lookup the
mc                  |        exact version, such as 1.4.6-R0.4-SNAPSHOT or 1.8-R0.1-SNAPSHOT-LATEST
mc                  |
```
