### ISSUE TITLE
"LEVEL" option just doesn't work at all

### ISSUE THREAD

**Issue by tristanbrown** [itzg/docker-minecraft-server#660]
I'm trying to host a previously-created world on this new server. 
My docker-compose file:
```
version: "3.7"

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - minecraftdata:/data
      - ./Minecraft Saves/worlds/mygame:/worlds/:ro
    environment:
      EULA: "TRUE"
      WORLD: /worlds
      LEVEL: mygame
```
Host directory structure:
```
docker-compose.yml
Minecraft Saves/
  mygame/
    level.dat
```
After I run `docker-compose up -d`, the container has this directory structure:
```
worlds/
  mygame/
    level.dat
  world/
    level.dat
```
That seems correct, except when I check the logs, the startup script says, `Preparing level "world"`. The resulting world is loaded from the default "world" directory, not the "mygame" directory. Nothing I try seems to get the "mygame" save to load.
