### ISSUE TITLE
Unable to connect to a database (timeout)

### ISSUE THREAD

**Issue by fauconjona** [itzg/docker-minecraft-server#663]
Hello,

I pulled the last version of the docker image but I can't connect to a database, I tried on same server, other server and on local. I have no problem to connect to the database with DBeaver, so not a mariadb problem. If I execute mysql client from the container, I have no response, nothing, and with a wrong IP I have "Can't connect to MySQL server on 'IP' (115)". (https://i.imgur.com/VCi1LUb.png)

docker-compose.yml:
```yml
version: '2'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - "/home/minecraft/ethernity-rpg:/data"
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "*********"
      RCON_PORT: 25575
      VERSION: 1.12.2
      TYPE: MOHIST
      FORGEVERSION: 14.23.5.2854
      MEMORY: 16G
      SERVER_PORT: 25565
      JVM_DD_OPTS: fml.queryResult=confirm
      REPLACE_ENV_VARIABLES: "TRUE"
      ENV_VARIABLE_PREFIX: "CFG_"
      CFG_DB_HOST: "*********"
      CFG_DB_PORT: "3306"
      CFG_DB_NAME: "minecraft"
      CFG_DB_USERNAME: "minecraft"
      CFG_DB_PASSWORD: "********"
    restart: always
```

Error in console:
```
09/11/2020 19:23:58[18:23:58 WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
09/11/2020 19:23:58[18:23:58 WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
09/11/2020 19:23:58[18:23:58 WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
09/11/2020 19:23:58[18:23:58 WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
09/11/2020 19:23:58[18:23:58 WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
09/11/2020 19:23:58[18:23:58 WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:159)
09/11/2020 19:23:58[18:23:58 WARN]: 	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:85)
09/11/2020 19:23:58[18:23:58 WARN]: 	at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.pollMessages(AbstractSqlMessenger.java:115)
09/11/2020 19:23:58[18:23:58 WARN]: 	at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:124)
09/11/2020 19:23:58[18:23:58 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
09/11/2020 19:23:58[18:23:58 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
09/11/2020 19:23:58[18:23:58 WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

I have no idea why it's not working, maybe a mysql issue with the image or I missed something.

**Comment by itzg** [comment]
Without knowing where or how you have deployed mariadb relative to the minecraft server container, I can't offer any advice. Even then, the networking outside the realm of this minecraft-server container is beyond the influence of this repository.

You may want to exec into the container with bash and from there troubleshoot the connectivity to your DB. You may also want to double the luckperms config files got swapped out as you expected with the variable substitution.

**Comment by fauconjona** [comment]
I test with 3 differents databases, 2 with the official mariadb image (https://hub.docker.com/_/mariadb) on the same machine and another, for the same machine, I tried with localhost, container IP and machine IP.

docker-compose.yml:
```yml
version: '2'

services:
  mariadb:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ***********
    ports:
     - "3306:3306"
```

I also tried with the db my PC (Windows) and with port redirection, but no success.

For config I tried without variable substition, nothing change.

**Comment by itzg** [comment]
LuckPerms worked fine for me connecting to the mariadb service named in the compose file. I pieced together the snippets you provided, but used Bukkit instead of Mohist. Perhaps Mohist is the problem and you should report an issue with them.

Compose file: https://github.com/itzg/try-luckperms-with-db/blob/master/docker-compose.yml

LuckPerms config, specifically the data storage section: https://github.com/itzg/try-luckperms-with-db/blob/master/plugins/LuckPerms/config.yml#L86-L95

Logs reported successful setup:
```
mc_1       | [18:34:03 INFO]: [LuckPerms] Loading configuration...
mc_1       | [18:34:05 INFO]: [LuckPerms] Loading storage provider... [MARIADB]
mc_1       | [18:34:05 WARN]: [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Starting...
mc_1       | [18:34:05 WARN]: [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Start completed.
mc_1       | [18:34:05 INFO]: [LuckPerms] Loading messaging service... [SQL]
mc_1       | [18:34:05 INFO]: [LuckPerms] Loading internal permission managers...
mc_1       | [18:34:05 INFO]: [LuckPerms] Performing initial data load...
mc_1       | [18:34:05 INFO]: [LuckPerms] Successfully enabled. (took 2896ms)
```

and in `data/plugins/LuckPerms/config.yml` I confirmed that section got variables replaced as expected:
```yaml
storage-method: mariadb

data:

  address: mariadb:3306

  database: minecraft

  username: "root"
  password: "testing"
```

Full test repo is here https://github.com/itzg/try-luckperms-with-db
