### ISSUE TITLE
Cant Change MOTD using Docker-Compose yaml or editing server.properties

### ISSUE THREAD

**Issue by Cytomax55** [itzg/docker-minecraft-server#669]
When using my docker compose file i cant change the MOTD 
When editing server.properties file the MOTD still wont change 

mc2:
    image: itzg/minecraft-server
    container_name: mc2
    environment:
      - EULA=TRUE
      - SERVER_NAME=RandomServerName
      - MOTD=RandomMOTDMessage
    volumes:
      - /media/username/mc2/data:/data
    ports:
      - 25565:25565 
    restart: unless-stopped

**Comment by itzg** [comment]
There are a couple of ways to solve this, but I suspect setting `OVERRIDE_SERVER_PROPERTIES=TRUE` gives the main behavior you were expecting.

I started with a tweak of yours:
```yaml
version: "3"

services:
  mc2:
    image: itzg/minecraft-server
    environment:
      - EULA=TRUE
      - SERVER_NAME=RandomServerName
      - MOTD=RandomMOTDMessage
      - OVERRIDE_SERVER_PROPERTIES=TRUE
    volumes:
      - ./data:/data
    ports:
      - 25565:25565
    restart: unless-stopped
```

and confirmed the MOTD via client:

![image-khvfuo24](https://user-images.githubusercontent.com/988985/100046658-404d6f80-2dd6-11eb-9289-0bda1268cf04.png)

Then, I changed `MOTD` in the following and redeployed the composition:
```yaml
version: "3"

services:
  mc2:
    image: itzg/minecraft-server
    environment:
      - EULA=TRUE
      - SERVER_NAME=RandomServerName
      - MOTD=NewMOTDMessage
      - OVERRIDE_SERVER_PROPERTIES=TRUE
    volumes:
      - ./data:/data
    ports:
      - 25565:25565
    restart: unless-stopped
```

Then in the client I refreshed the server list and confirmed:

![image-khvfzy30](https://user-images.githubusercontent.com/988985/100046731-6541e280-2dd6-11eb-8f0c-6426adccb00e.png)
