### ISSUE TITLE
Unable to access Forge jarfile error

### ISSUE THREAD

**Issue by shoveln** [itzg/docker-minecraft-server#673]
`docker-compose.yaml`
```
version: "3.7"
services:
    minecraft:
        container_name: minecraft-server
        image: itzg/minecraft-server
        restart: unless-stopped
        ports:
            - "25565:25565"
        environment:
            # Version
            VERSION: 1.12.2
            TYPE: FORGE
            FORGEVERSION: 14.23.5.2854
            # Server Properties
            EULA: "TRUE"
            DIFFICULTY: "normal"
            ALLOW_FLIGHT: "TRUE"
            MEMORY: "8G"
            # Player Settings
            ANNOUNCE_PLAYER_ACHIEVEMENTS: "false"
            MAX_PLAYERS: 4
        volumes:
            - ./data:/data
```
Upon trying to start the server, the following error occurs in the log:

```
minecraft-server | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    7 1000     1000          4096 Nov 29 05:58 /data'
minecraft-server | [init] Resolved version given 1.12.2 into 1.12.2
minecraft-server | [init] Resolving type given FORGE
minecraft-server | [init] Checking Forge version information.
minecraft-server | [init] server.properties already created, skipping
minecraft-server | [init] Setting/adding ops
minecraft-server | [init] log4j2.xml already created, skipping
minecraft-server | [init] Checking for JSON files.
minecraft-server | [init] Setting initial memory to 8G and max to 8G
minecraft-server | [init] Starting the Minecraft server...
minecraft-server | Error: Unable to access jarfile forge-1.12.2-14.23.5.2854.jar
minecraft-server | 2020-11-29T05:58:22.710Z	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}
minecraft-server | 2020-11-29T05:58:22.710Z	INFO	mc-server-runner	Done

```

I have tried removing and re-pulling the docker image, and this didn't seem to make any change. Manually adding that jar and the vanilla jar file also don't fix the error.
