### ISSUE TITLE
Unable to set up server using snapshot 20w45a

### ISSUE THREAD

**Issue by LvInSaNevL** [itzg/docker-minecraft-server#677]
Hey guys I am trying to spin up a minecraft server with the newest snapshot 20w45a but it seems to only start in 1.16.4. Below is my `docker-compose.yaml` file, and I was hoping you guys could take a look and see where I messed up.

```
version: "3"

services:
  # The main survival world
  survival:
    container_name: ${CONTAINER_NAME}_survival
    image: itzg/minecraft-server
    ports:
      - ${SURVIVAL_PORT}:25565
    volumes:
      - ${VOLUME}/survivalData:/data
    environment:
      EULA: "TRUE"
      SERVER_NAME: ${SERVER_NAME}
      MOTD: ${MOTD}
      VERSON: ${IMAGE}
      TZ: ${TIME_ZONE}
      DIFFICULTY: ${DIFFICULTY}
      ANNOUNCE_PLAYER_ACHIEVEMENTS: ${ANNOUNCE_PLAYER_ACHIEVEMENTS}
      ENABLE_COMMAND_BLOCK: ${ENABLE_COMMAND_BLOCK}
      FORCE_GAMEMODE: ${FORCE_GAMEMODE}
      MAX_BUILD_HEIGHT: ${MAX_BUILD_HEIGHT}
      SEED: ${SEED}
      ENABLE_AUTOPAUSE: ${ENABLE_AUTOPAUSE}
      MAX_MEMORY: ${MAX_MEMORY}
      # MODE: creative
      ENABLE_RCON: "true"
      RCON_PASSWORD: "testing"
      RCON_PORT: 28016
      # enable env variable replacement
      REPLACE_ENV_VARIABLES: "TRUE"
      # define an optional prefix for your env variables you want to replace
      ENV_VARIABLE_PREFIX: "CFG_"
      # and here are the actual variables
      CFG_DB_HOST: "http://localhost:3306"
      CFG_DB_NAME: "minecraft"
      CFG_DB_PASSWORD_FILE: "/run/secrets/db_password"
    restart: always
```

And I am starting that with a bash script that looks like this;

```
SERVER_NAME="Universe"
MOTD="to first bake a pie you must invent the universe..."
IMAGE="SNAPSHOT"
VOLUME="./serverData"
TIME_ZONE="America/Fort_Wayne"
SURVIVAL_PORT="33333"
CREATIVE_PORT="33335"
ENABLE_AUTOPAUSE="TRUE"
MAX_MEMORY="3G"
DIFFICULTY="normal"
ANNOUNCE_PLAYER_ACHIEVEMENTS="false"
ENABLE_COMMAND_BLOCK="false"
FORCE_GAMEMODE="false"
MAX_BUILD_HEIGHT="256"
SEED="7185855458401771874"

CONTAINER_NAME=${SERVER_NAME} \
MOTD=${MOTD} \
IMAGE=${IMAGE} \
VOLUME=${VOLUME} \
TIME_ZONE=${TIME_ZONE} \
SURVIVAL_PORT=${SURVIVAL_PORT} \
ENABLE_AUTOPAUSE=${ENABLE_AUTOPAUSE} \
MAX_MEMORY=${MAX_MEMORY} \
DIFFICULTY=${DIFFICULTY} \
ANNOUNCE_PLAYER_ACHIEVEMENTS=${ANNOUNCE_PLAYER_ACHIEVEMENTS} \
ENABLE_COMMAND_BLOCK=${ENABLE_COMMAND_BLOCK} \
FORCE_GAMEMODE=${FORCE_GAMEMODE} \
MAX_BUILD_HEIGHT=${MAX_BUILD_HEIGHT} \
EULA=${EULA} \
SEED=${SEED} \
docker-compose up
```

I am using the batch script to set the environment variables instead of a `.env` file because you cannot set things like container name or ports with that, unless you guys know a work around too haha!

But thanks for looking guys I really appreciate it!
