### ISSUE TITLE
PAPER_DOWNLOAD_URL seems being ignored

### ISSUE THREAD

**Issue by k-jiang** [itzg/docker-minecraft-server#687]
Today when restart my server I found out `PAPER_DOWNLOAD_URL` seems not working in the latest image. I'm using kubernetes and my env is as follow:

```
env:
  - name: TZ
    value: Asia/Shanghai
  - name: EULA
    value: 'TRUE'
  - name: VERSION
    value: 1.16.4
  - name: TYPE
    value: PAPER
  - name: FORCE_REDOWNLOAD
    value: 'true'
  - name: PAPER_DOWNLOAD_URL
    value: 'http://mycustom/paper-1.16.4.jar'
  - name: MEMORY
    value: 5120M
```

I'm sure the url is absolutely working by doing curl in the docker. My `imagePullPolicy` is set to `Always`.
