### ISSUE TITLE
Add Yatopia support

### ISSUE THREAD

**Issue by pavel-voronin** [itzg/docker-minecraft-server#704]
It will be nice to have Yatopia support https://github.com/YatopiaMC/Yatopia

**Comment by itzg** [comment]
It would have been fairly easy to support, but their download page dynamically renders the "href" needed to automate the download:

```
restify --id=stable https://yatopiamc.org/download.html

[{"name":"a","class":"download-button","id":"stable","href":"%s","text":"Latest stable build: %s","elements":[{"name":"span","class":"material-icons","text":"get_app"}]}]
```

If you wouldn't mind specifying a build number, such as `YATOPIA_BUILD_ID=28` then looks like I could have the startup process build a URL like `https://api.yatopiamc.org/v2/build/28/download?branch=ver/1.16.4`.

A solution that works already is using the `CUSTOM_SERVER` option, such as this:
```yaml
version: "3"

services: 
  mc:
    image: itzg/minecraft-server:adopt11
    environment: 
      EULA: "TRUE"
      TYPE: CUSTOM
      CUSTOM_SERVER: https://api.yatopiamc.org/v2/build/28/download?branch=ver/1.16.4
    tty: TRUE
    stdin_open: TRUE
    ports: 
      - 25565:25565
```
