### ISSUE TITLE
Replacing variables inside configs is ignoring last occurrence 

### ISSUE THREAD

**Issue by AMTraxTGE** [itzg/docker-minecraft-server#718]
When setting up my containers with custom environment variables, it seems that when going through the supplied variables, the last variable to be replaced within the config gets ignored.

>[init] Replacing env variables in configs that match the prefix TMC_...
[init] Replacing TMC_DATABASE_HOST with 1XXXXXXX ...
[init] Replacing TMC_DATABASE_PORT with XXXX ...
[init] Replacing TMC_DATA_HOST with 1XXXXXXX ...
[init] Checking for JSON files.

I had expected to see my last variable `TMC_DATABASE_PWD` in this output but I do not. ~~Also, I do not have `TMC_DATA_HOST`  within any of my files.~~

Code File: `start-finalSetupEnvVariables`

Edit 01: `TMC_DATA_HOST` was within my ENV.

**Comment by itzg** [comment]
So far I haven't been able to recreate this issue. I used the following compose file:

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    environment: 
      EULA: "TRUE"
      REPLACE_ENV_VARIABLES: "TRUE"
      ENV_VARIABLE_PREFIX: TMC_
      TMC_ONE: "one"
      TMC_TWO: "two"
    volumes: 
      - ./config:/config
      - ./data:/data
```

and observed output for all of the `TMC_` environment variables declared there:

```
mc_1  | [init] Replacing env variables in configs that match the prefix TMC_...
mc_1  | [init] Replacing TMC_ONE with one ...
mc_1  | [init] Replacing TMC_TWO with two ...
```

Can you double check that `TMC_DATABASE_PWD` was declared in your `-e` or `environment` and that you didn't have a typo?

**Comment by AMTraxTGE** [comment]
Sorry for the delay, I created the variables in the file first, then I went ahead and copied them to the environment variables. I am using a manager for handling my docker container(s) and services, but I've had no other issue applying any of the provided environment variables to the image. 

Image: `itzg/minecraft-server:adopt11`

1. Plugin Configuration:

```mysql-host: ${TMC_DATABASE_HOST}
mysql-port: ${TMC_DATABASE_PORT}
mysql-database: ${TMC_DATABASE}
mysql-username: ${TMC_DATABASE_USERNAME}
mysql-password: ${TMC_DATABASE_PWD}
```

 2. Configuration:
 
![image](https://user-images.githubusercontent.com/12130422/108152930-21ded380-70a8-11eb-8609-1164decff7cc.png)
*This includes a bunch of other environment variables as well

3. Console Output:

![image](https://user-images.githubusercontent.com/12130422/108152859-f360f880-70a7-11eb-9fdc-025b0561bf22.png)

**Comment by itzg** [comment]
I think I finally found the issue and a much more robust way of iterating through the prefixed variables. Can you pull the latest image and see if that fixes it for you?

**Comment by AMTraxTGE** [comment]
I replaced actual replace values with ### but here is the log. It did successfully replace all variables, but give me the
 `sed: bad option in substitution expression` 
error of about 30+ some lines between the two config sections.

```[init] Replacing env variables in configs that match the prefix TMC_ ...
[init] Replacing TMC_CoreProtect_Database with ######## ...
[init] Replacing TMC_CoreProtect_Host with ######## ...
[init] Replacing TMC_CoreProtect_Password with ########## ...
sed: bad option in substitution expression
sed: bad option in substitution expression
sed: bad option in substitution expression
sed: bad option in substitution expression
sed: bad option in substitution expression
sed: bad option in substitution expression
sed: bad option in substitution expression
... (30+)
sed: bad option in substitution expression
sed: bad option in substitution expression
sed: bad option in substitution expression
sed: bad option in substitution expression
sed: bad option in substitution expression
sed: bad option in substitution expression
sed: bad option in substitution expression
[init] Replacing TMC_CoreProtect_Port with #### ...
[init] Replacing TMC_CoreProtect_Username with ######## ...
[init] Replacing TMC_InventoryRollback_Database with ######## ...
[init] Replacing TMC_InventoryRollback_Host with ######## ...
[init] Replacing TMC_InventoryRollback_Password with ######### ...
[init] Replacing TMC_InventoryRollback_Port with #### ...
[init] Replacing TMC_InventoryRollback_Username with ######### ...
```

Both CoreProtect and InventoryRollback both have 5 variables `Database`, `Host`, `Password`, `Port`, `Username` with their respective prefixes

**Comment by itzg** [comment]
> Edit: The password does contain special characters

I'm guessing a backslash, specifically? I was actually wondering about some existing escape character escaping that was there...

**Comment by AMTraxTGE** [comment]
Special Characters Include: `#`, `$`, `@`, and the standard uppercase, lowercase, numbers. I do not have a backslash

**Comment by itzg** [comment]
OK, the latest image now includes pre-processing of characters that would throw off the `sed` operation. See if that latest image now works for you.

FYI, here's the updated compose file I used for testing:
```yaml
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    environment: 
      EULA: "TRUE"
      REPLACE_ENV_VARIABLES: "TRUE"
      ENV_VARIABLE_PREFIX: TMC_
      TMC_ONE: "one"
      TMC_TWO: "this/is a\\special#one$and@so#is\\this"
    volumes: 
      - ./config:/config
      - ./data:/data
```
