### ISSUE TITLE
cURL can't load Paper

### ISSUE THREAD

**Issue by youlovesaturn** [itzg/docker-minecraft-server#724]
When I use **multiarch-latest**, I get this error:
`ERROR: unknown error while looking up PaperMC version=1.16.4`
`curl: (28) Timeout was reached`
`[init] Resolving type given Paper`
`[init] Resolved version given 1.16.4 into 1.16.4`

Even if you use `PAPER_DOWNLOAD_URL`, there will still be an error.
But if I use **multiarch** (not latest) then everything works. 

docker-compose.yml
```
version: '2'
services:
  mc:
    image: itzg/minecraft-server:multiarch-latest
    ports:
        - "25565:25565"
    restart: always
    environment:
        TZ: "Europe/Moscow"
        EULA: "True"
        TYPE: "Paper"
        MEMORY: "2G"
        FORCE_REDOWNLOAD: "True"
        VERSION: "1.16.4"
        ONLINE_MODE: "False"
        CONSOLE: "False"
        DISABLE_HEALTHCHECK: "True"
    volumes:
      - mc-paper:/data

volumes:
  mc-paper:
    driver: local
```
