### ISSUE TITLE
All of Fabric 3 launch script issue 

### ISSUE THREAD

**Issue by GPNikol** [itzg/docker-minecraft-server#728]
So I've run into an interesting issue I don't know quite how to address, or if there is a way to address it on the docker end. I'm trying to setup an All of Fabric 3 server however the mod creators use a unique start script that doesn't play nicely with the docker container. I haven't found a configuration that will work yet. 

The following is my current docker-compose that isn't working: 
```
version: 3

services: 
  minecraft:
      image: itzg/minecraft
      container_name: Fabric
      ports: 
          - "25565:25565"
          - "25575"25755"
      volumes:
         - ./fabric_data:/data
         - ./modpacks:/modpacks:ro
      environment:
         - TYPE: CURSEFORGE
         - CF_SERVER_MOD: "/modpacks/AllofFabric3Server-2.5.9.zip"
         - EULA: "TRUE"
         - INIT_MEMORY: 4G
         - MEMORY: 6G
         - MAX_MEMORY: 8G
```    

I've tried switching to type FORGE and using the generic_pack label, and I've tried disabling the startup script. 

The modpack's server files only contain a start script and a yml to download all of the server files it needs which seems to be the problem, is there any docker config I could use that would make this setup work?

**Comment by itzg** [comment]
I used a slight modification of your compose file:

```yaml
version: "3"

services: 
  minecraft:
      image: itzg/minecraft-server
      tty: true
      stdin_open: true
      ports: 
          - "25565:25565"
      volumes:
         - ./data:/data
         - ./modpacks:/modpacks:ro
      environment:
         TYPE: CURSEFORGE
         CF_SERVER_MOD: "/modpacks/AllofFabric3Server-2.5.9.zip"
         EULA: "TRUE"
         MEMORY: 6G
```

The first time I did `docker-compose up` it stopped at

```
minecraft_1  | [03:20:22] [INFO] Done installing loader, deleting installer!
minecraft_1  | [03:20:22] [INFO] You have not accepted the eula yet.
minecraft_1  | [03:20:22] [INFO] By typing TRUE you are indicating your agreement to the EULA of Mojang.
minecraft_1  | [03:20:22] [INFO] Read it at https://account.mojang.com/documents/minecraft_eula before accepting it.
```

which is odd, because the `eula.txt` was already created by the container's startup script. I restarted the container and it seems to be starting up normally so far.
