### ISSUE TITLE
error: Please make sure you are using the server version of the FTB modpack!

### ISSUE THREAD

**Issue by ibootstrapper** [itzg/docker-minecraft-server#743]
I'm using the below docker-compose.yml file to run the server with RLCRaft though it exits with an error: "Please make sure you are using the server version of the FTB modpack!" any ideas what i'm doing wrong?
```
version: '3'
services:
  minecraft:
    ports:
      - "25565:25565"
    volumes:
            - "./data:/data"
    environment:
      MAX_MEMORY: 4G
      DIFFICULTY: hard
      VERSION: 1.12.2
      TYPE: CURSEFORGE
      CF_SERVER_MOD: modpacks/RLCraft+1.12.2+-+Beta+v2.8.2.zip
    image: itzg/minecraft-server
    restart: always
  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
            - "./db:/opt/rcon-web-admin/db"
  ```

**Comment by itzg** [comment]
From the file name it looks like you may not be using the server version of the modpack. Try instead:

https://www.curseforge.com/minecraft/modpacks/rlcraft/files/2935323

**Comment by isamuelson** [comment]
I ended up changing to the following and it works though there are many time lags
```
version: '3'

services:
  rlcraft:
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MAX_MEMORY: 4G
      MAX_BUILD_HEIGHT: 200
      VIEW_DISTANCE: 10
      LEVEL_TYPE: LARGEBIOMES
      MAX_PLAYERS: 100
      CONSOLE: "false"
      DIFFICULTY: hard
      VERSION: 1.12.2
      TYPE: FORGE
      FORGEVERSION: 14.23.5.2838
      GENERIC_PACK: modpacks/RLCraft+Server+Pack+1.12.2+-+Beta+v2.8.2.zip
      GENERIC_PACK_STRIP_DIRS: "1"
      DISABLE_HEALTHCHECK: "true"
    image: itzg/minecraft-server
    restart: always
    volumes:
      - ./data:/data
      - ./modpacks:/modpacks

  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "./db:/opt/rcon-web-admin/db" #

```
