### ISSUE TITLE
Syntax of GENERATOR_SETTINGS in docker-compose.yml

### ISSUE THREAD

**Issue by naxmefy** [itzg/docker-minecraft-server#768]
trying

```yaml
version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25588:25565"
    volumes:
      - "mc:/data"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      LEVEL_NAME: mc4_void
      LEVEL_TYPE: flat
      GENERATOR_SETTINGS: minecraft:air;minecraft:the_void;decoration

volumes:
  mc:
```

but just failing

```
minecraft4   | Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
minecraft4   |  at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[minecraft_server.1.16.5.jar:?]
minecraft4   |  at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[minecraft_server.1.16.5.jar:?]
minecraft4   |  at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:593) ~[minecraft_server.1.16.5.jar:?]
minecraft4   |  at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[minecraft_server.1.16.5.jar:?]
minecraft4   |  at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:716) ~[minecraft_server.1.16.5.jar:?]
minecraft4   |  at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[minecraft_server.1.16.5.jar:?]
minecraft4   |  at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[minecraft_server.1.16.5.jar:?]
minecraft4   |  at afd.a(SourceFile:493) ~[minecraft_server.1.16.5.jar:?]
```

Can you help with correct syntax?
