### ISSUE TITLE
FTBA - Could not open file version.json: Permission denied

### ISSUE THREAD

**Issue by crafty615** [itzg/docker-minecraft-server#784]
Trying to run a FTB Revelation server and I keep running into this permission denied issue. I can run vanilla servers perfectly fine but I get this issue for both FTB and curse forge mod servers.

Here is my docker compose:
```
version: "3"

services:
  test:
    image: itzg/minecraft-server:multiarch
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FTBA"
      DIFFICULTY: "hard"
      FTB_MODPACK_ID: "35"
      MOTD: "FTB Revelation Server"
      LEVEL: "ftb_revelation_map"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
```
      
Here is the top and bottom of the logs:
```
[init] Changing ownership of /data to 1000 ...
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 1 1000 1000 4096 Feb 26 2021 /data'
[init] Resolved version given LATEST into 1.16.5
[init] Resolving type given FTBA
[init] Downloading FTB installer
[init] Installing modpack ID 35, version ID 174
2021/02/26 11:25:43 Performing installation...
2021/02/26 11:25:43 Getting downloads for Forge Universal
Finished mods/AutoRegLib-1.3-32.jar
...
Finished libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
Finished libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
Finished libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
Finished minecraft_server.1.12.2.jar
Finished 898 successful, 0 failed, 0 incomplete.
2021/02/26 11:26:18 Installed!
jq: error: Could not open file version.json: Permission denied
```
