### ISSUE TITLE
Infinite Restart Loop

### ISSUE THREAD

**Issue by JiahuiChen99** [itzg/docker-minecraft-server#789]
After executing `docker-compose up -d` the minecraft server keeps restarting.
```

CONTAINER ID   IMAGE                   COMMAND    CREATED         STATUS                              PORTS     NAMES
d3fa37bbf579   itzg/minecraft-server   "/start"   5 minutes ago   Restarting (1) About a minute ago             mc_server-mc_1
```

This is my `docker-compose.yml` file
```
version: "3"

services:
  mc-server:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      SERVER_NAME: "mc-server"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
    tty: true
    stdin_open: true
    restart: always
```
This is the log: `standard_init_linux.go:219: exec user process caused: exec format error`
