### ISSUE TITLE
Healthcheck unhealthy on multi-version server

### ISSUE THREAD

**Issue by voruti** [itzg/docker-minecraft-server#796]
I have three servers with type PAPER. All of them are working fine, but the healthchecks say they are "unhealthy".

**Screenshot from Portainer:**

![portainer-screenshot](https://user-images.githubusercontent.com/45130096/110531661-22551200-811c-11eb-8b26-e628985616a1.png)

**docker-compose.yml:**
```
networks:
  default:
    external:
      name: bungeecord_connector
services:
  vanilla:
    container_name: vanilla
    environment:
      EULA: "TRUE"
      TYPE: PAPER
    image: itzg/minecraft-server:latest
    stdin_open: true
    tty: true
    volumes:
    - ./data:/data:rw
    - /etc/timezone:/etc/timezone:ro
version: '3.0'
```
