### ISSUE TITLE
Unable to connect to RCON port

### ISSUE THREAD

**Issue by RolfKoenders** [itzg/docker-minecraft-server#800]
Hello!

First of all this docker image works great, i have ran multiple (variants of) servers without issues. However, i am now running into one that i am not able to solve yet.

I'm trying to run curseforge modpack Enigmatica6. At the start i noticed that i have to run the java8 tag of the image and have `USE_MODPACK_START_SCRIPT` set to false, otherwise it would not startup.
With those settings the server is running fine but i wanted to get RCON access. I tried to attach with the rcon-cli but no success so i saw that there is a nice web interface for it, added it to the compose file, as far as i can tell configured correctly. But that tool is also not able to connect to the rcon port.

Am i missing something in the configuration or am i using an outdated example?
Below is the compose file i'm using.

```yml
version: "3.3"

services:
  web:
    image: itzg/rcon
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: mc
      RWA_RCON_PORT: 28016
      RWA_RCON_PASSWORD: "admin"
    ports:
      - 4326:4326
      - 4327:4327
  mc:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "CURSEFORGE"
      MEMORY: "4G"
      CF_SERVER_MOD: "/data/Enigmatica6Server-0.4.3.zip"
      VERSION: "1.16.5"
      ENABLE_AUTOPAUSE: "TRUE"
      USE_MODPACK_START_SCRIPT: "false"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "admin"
      RCON_PORT: 28016
      DIFFICULTY: "easy"
      OPS: ""
    volumes:
      - ./data:/data
```

Thanks in advance!
