### ISSUE TITLE
OVERRIDE_WHITELIST and OVERRIDE_OPS doesn't seem to work. (might be user error)

### ISSUE THREAD

**Issue by ilmal** [itzg/docker-minecraft-server#806]
I'm running a minecraft server on a k8s cluster and are having some trouble with the OVERRIDE_WHITELIST and the OVERRIDE_OPS options. If I understand the options correctly the ops.json and the whitelist.json file should be recreated and only contain the users specified by the OPS and WHITELIST option. But in my case, I can only add user to the files. When I remove a user from my start yaml file the ops.json and whitelist.json files aren't updated. 

Here is my yaml file I use to start the server: (OBS, the names are changed)

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: null
spec:
  replicas: 1
  selector:
    matchLabels:
      app: null
  template:
    metadata:
      labels:
        app: null
    spec:
      volumes:
        - name: minecraft-pv-storage
          persistentVolumeClaim:
             claimName: custom_claim_name
      containers:
      - image: itzg/minecraft-server
        name: minecraft-server
        env:
        - name: TYPE
          value: "VANILLA"

        - name: EULA
          value: "TRUE"

        - name: MAX_PLAYERS
          value: "5"

        - name: VERSION
          value: latest

        - name: SERVER_NAME
          value: null

        - name: DIFFICULTY 
          value: normal

        - name:  WHITELIST
          value: null

        - name: OPS
          value: null

        - name: OVERRIDE_SERVER_PROPERTIES
          value: "true"

        - name: OVERRIDE_WHITELIST
          value: "true"

        - name: OVERRIDE_OPS
          value: "true"

        ports:
        - containerPort: 25565
          name: minecraft
          protocol: TCP
        volumeMounts:
          - mountPath: "/data"
            name: minecraft-pv-storage
```

Could an error be that the value true is "true" with quotes? Because I get an error compiling when deploying without the quotes.

Here is some logs from the server: 

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    4 1000     1000          4096 Mar 16 19:42 /data'
[init] Resolved version given latest into 1.16.5
[init] Resolving type given VANILLA
[init] Setting server-name to 'Server' in /data/server.properties
[init] Setting server-port to '25565' in /data/server.properties
[init] Setting motd to 'A Vanilla Minecraft Server powered by Docker' in /data/server.properties
[init] Setting enable-rcon to 'true' in /data/server.properties
[init] Setting rcon.password to 'minecraft' in /data/server.properties
[init] Setting rcon.port to '25575' in /data/server.properties
[init] Setting max-players to '5' in /data/server.properties
[init] Setting level-name to 'world' in /data/server.properties
[init] Setting online-mode to 'true' in /data/server.properties
[init] Setting difficulty to 'peaceful' in /data/server.properties
[init] log4j2.xml already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...

```
From this log, it seems like the properties are updated. But when it comes to the "Checking for JSON files" it seems like the server is just skipping past the files. 

Even though the OPS value is null, I have a ops.json file from a previous start when the OPS option had a user. And so this is my ops.json after a start with the OPS value set to null:

`[
  {
    "uuid": "***",
    "name": "MYUSERACCOUNT",
    "level": 4,
    "bypassesPlayerLimit": false
  }
]` 

Thanks for any help trying to solve this. As I pointed out in the title, I'm not sure is this is a user error or something else!
