### ISSUE TITLE
SPIGET_RESOURCES not used

### ISSUE THREAD

**Issue by xgonc** [itzg/docker-minecraft-server#834]
I'm trying to setup a server using docker compose. The config part of this server is:
```
    container_name: loginlobby-puromc
    image: itzg/minecraft-server:latest
    restart: always
    expose:
      - 25565
    env_file: loginlobby-puromc/.env
    volumes:
      - ./loginlobby-puromc/plugins:/data/plugins
      - ./loginlobby-puromc/worlds/world:/data/world
      - ./loginlobby-puromc/worlds/world_nether:/data/world_nether
      - ./loginlobby-puromc/worlds/world_the_end:/data/world_the_end
    networks:
      - mc_net
```

on the `.env` file I have, among other settings, this:  `SPIGET_RESOURCES="1364,52109"`

Those plugins are not being loaded. Any suggestion to solve the issue?

Thanks.
