### ISSUE TITLE
 [init] ERROR unable to locate installed forge server jar

### ISSUE THREAD

**Issue by traverseda** [itzg/docker-minecraft-server#842]
[_minecraft_mc.1.qwbe0w6vhbhawe5qhrzb3fsqi_logs.txt](https://github.com/itzg/docker-minecraft-server/files/6361192/_minecraft_mc.1.qwbe0w6vhbhawe5qhrzb3fsqi_logs.txt)

```yaml

version: '3.7'

services:
  mc:
    image: itzg/minecraft-server:java8
    volumes:
    - mods:/modpacks:ro
    - data:/data
    environment:
      EULA: "true"
      #NABLE_AUTOPAUSE: "TRUE"
      #VERSION: "1.12.2"
      #OVERRIDE_SERVER_PROPERTIES: "TRUE"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/Eternal+(ServerPack+1.3.7.1).zip
      DISABLE_HEALTHCHECK: "true"
      USE_MODPACK_START_SCRIPT: "false"
      DEBUG: "true"
    ports:
      - 25565:25565
volumes:
  mods:
  data:
```

Not sure what's going on here, I've included as much debug data as I could

**Comment by xchoice** [comment]
Hi, same error for me, this is my compose:

```
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java8
    container_name: titansII
    restart: unless-stopped
    ports:
      - 25565:25565
    volumes:
      - /srv/minecraft/craftTitansII:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      VERSION: 1.12.2
      EULA: "TRUE"
      MEMORY: 8G
      TYPE: CURSEFORGE
      CF_SERVER_MOD: CTTF_Server_1.41.zip
      JVM_DD_OPTS: -Dfml.readTimeout=360
      JVM_XX_OPTS: -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
      ONLINE_MODE: "false"
      USE_MODPACK_START_SCRIPT: "false"
      DIFFICULTY: "normal"
```
