### ISSUE TITLE
Property override not working with docker compose

### ISSUE THREAD

**Issue by BlueDragon709** [itzg/docker-minecraft-server#843]
Hi,

When i set the max players and MOTD of the server it won't set them.

```yml
version: "3.8"
services:
    mc:
        container_name: Roguelike_Modpack
        image: itzg/minecraft-server:java8-multiarch
        restart: unless-stopped
        environment:
          TZ: Europe/Amsterdam
          EULA: "TRUE"
          TYPE: "CURSEFORGE"
          OVERRIDE_SERVER_PROPERTIES: "TRUE"
          WHITELIST: "Player1,Player2"
          OPS: "Player1"
          MOTD: "New Beginnings V1.45"
          MAX_PLAYERS: "4"
          ALLOW_FLIGHT: "TRUE"
          MEMORY: "4G"
          CF_SERVER_MOD: "/modpacks/RAD-Serverpack-1.45.zip"
        ports:
            - "25565:25565"
        volumes:
            - /home/blue/roguelike_modpack:/data
            - /home/blue/modpacks:/modpacks
```

The other properties work as expected, but the MOTD and MAX_PLAYERS don't work.
How do I fix this.
