### ISSUE TITLE
The given Forge installer doesn't exist : forge-1.12.2-14.23.5.2854-installer.jar [SevTechAgesOfTheSky]

### ISSUE THREAD

**Issue by int128fly** [itzg/docker-minecraft-server#844]
docker-compose.yaml
```
version: '3.1'

services:
  sev-tech:
    image: itzg/minecraft-server:java8
    restart: on-failure:2
    ports: 
      - 25565:25565
    volumes: 
      - /home/workspaces/server-01/gameservers/Minecraft/SevTechAgesOfTheSky/data:/data
    environment: 
      - TYPE=FORGE
      - FORGE_INSTALLER=forge-1.12.2-14.23.5.2854-installer.jar
      - VERSION=1.12.2
      - EULA=TRUE

```

https://gyazo.com/d399221b20852c60699092a06882472b
https://gyazo.com/268c45893d0b30140aa84a2e1575634e

It was working a few months ago when I setup the SevTechAges server for my friends and I
Not sure if it something I'm doing wrong.
