### ISSUE TITLE
unzip: short read . for RAD CurseForge pack

### ISSUE THREAD

**Issue by JonathanBouligny** [itzg/docker-minecraft-server#857]
Compose File
```
version: '3.2'

services:
  mc:
    image: itzg/minecraft-server:java8
    volumes:
    - /home/appdata/minecraft/modpacks:/modpacks:ro
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/RAD-Serverpack-1.45.zip
      VERSION: 1.12.2
      FORGEVERSION: 14.23.5.2838
    ports:
      - 25565:25565
```

Saw this closed issue and tried this configuration
https://github.com/itzg/docker-minecraft-server/issues/608
```      INIT_MEMORY: "1G"
      MAX_MEMORY: "6G"
      VERSION: "1.12.2"
      TYPE: "FORGE"
      FORGEVERSION: "14.23.5.2838"
      GENERIC_PACK: "/modpacks/packname.zip"
```
and got this error 
```[init] ...trying http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2838-1.12.2/forge-1.12.2-14.23.5.2838-1.12.2-installer.jar
curl: (22) The requested URL returned error: 404
```
I see many issues with CurseForge packs with the container and then the packs themselves, do CurseForge packs not work well with the container or is it still just weird startup scripts?

EDIT: I tried to start the server manually on my machine and it seems that the server works. Also i tried the option to turn off the start script and it didnt work.
