### ISSUE TITLE
java: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Tyaeth** [itzg/docker-minecraft-server#862]
I'm trying to get this running on a Raspberry Pi 4b and I keep running into this error. I haven't seen any other issues reporting this error, so it's probably something that I'm doing wrong since I'm relatively new to Pi and way out of touch with Linux. 

OS is Raspbian GNU/Linux 10 (buster)
libseccomp2 version is updated to 2.5.1-1

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 3 1000 1000 4096 May 11 16:06 /data'
[init] Resolved version given 1.12.2 into 1.12.2
[init] Resolving type given FORGE
[init] Checking Forge version information.
[init] Downloading 1.12.2-14.23.5.2855-1.12.2
[init] ...trying http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2855-1.12.2/forge-1.12.2-14.23.5.2855-1.12.2-installer.jar
curl: (22) The requested URL returned error: 404
[init] ...trying http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2855/forge-1.12.2-14.23.5.2855-installer.jar
[init] Installing Forge 1.12.2-14.23.5.2855 using /tmp/forge-1.12.2-14.23.5.2855-installer.jar
java: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
java: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
java: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
[init] Forge failed to install after several tries.
```

And here's my docker-compose.yml:
```
version: "3.0"

services:
  pixelmon:
    image: itzg/minecraft-server:java8-multiarch
    container_name: mc_pixelmon
    hostname: mc_pixelmon
    restart: "unless-stopped"
    ports:
      - 25565:25565   
    volumes:
      - ./minecraft-data:/data
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: 1.12.2
      MEMORY: 2000m
    networks:
      - Minecraft
      
networks:
  Minecraft:
    driver: bridge
```
