### ISSUE TITLE
Forge download issue. 

### ISSUE THREAD

**Issue by tonymmm1** [itzg/docker-minecraft-server#889]
I was checking out the url for the forge installer and it seems to be behind a shortner and in a different syntax for the domain. 
https://adfoc.us/serve/sitelinks/?id=271228&url=https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-installer.jar.  The url is able to be stripped and link after the ampersand will work this syntax just needs to be reflected in the shell script.

logs:
```
minecraft    | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    2 1000     1000          4096 May 23 23:40 /data'
minecraft   | [init] Resolved version given 1.12.2 into 1.12.2
minecraft    | [init] Resolving type given FORGE
minecraft    | [init] Checking Forge version information.
minecraft    | [init] Downloading 1.12.2-14.23.5.2854-1.12.2
minecraft    | [init] ...trying http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2854-1.12.2/forge-1.12.2-14.23.5.2854-1.12.2-installer.jar
minecraft   | curl: (6) Could not resolve host: files.minecraftforge.net
minecraft    | [init] ...trying http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-installer.jar
minecraft    | curl: (6) Could not resolve host: files.minecraftforge.net
minecraft    | [init] Unable to compute URL for 1.12.2-14.23.5.2854-1.12.2
```

docker-compose.yml configuration
```
version: "3"
services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server:java8
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      EULA: "true"
      VERSION: 1.12.2
      TYPE: FORGE
      FORGEVERSION: 14.23.5.2854
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
    volumes:
      - ./data:/data
    restart: unless-stopped 
```
