### ISSUE TITLE
java8 with Forge on 1.12.2 spamming invalid ps command

### ISSUE THREAD

**Issue by radiden** [itzg/docker-minecraft-server#897]
While using this configuration:
```yaml
version: "3.5"

services:
    mc:
        container_name: minecraft-modded-rad
        image: itzg/minecraft-server:java8
        ports:
            - 25566:25565
        environment:
            - EULA=TRUE
            - ENABLE_AUTOPAUSE=TRUE
            - TYPE=FORGE
            - VERSION=1.12.2
            - FORGEVERSION=14.23.5.2854
            - MEMORY=4G
            - USE_AIKAR_FLAGS=TRUE
        volumes:
            - ./data:/data
        restart: unless-stopped
        stdin_open: true
        tty: true
```

The server while starting up will spam ps with x, which doesn't exist in the ps binary from busybox that alpine ships with:

![image](https://user-images.githubusercontent.com/28237353/119802479-db86e500-bede-11eb-926e-7d93b26b8da2.png)
