### ISSUE TITLE
GUI=FALSE doesn't fix Forge crash

### ISSUE THREAD

**Issue by 19wolf** [itzg/docker-minecraft-server#931]
[Compose](https://pastebin.com/a9D8C6Uh)

[Debug output](https://pastebin.com/q40jhsiB)

_Originally posted by @19wolf in https://github.com/itzg/docker-minecraft-server/issues/799#issuecomment-865459487_

**Comment by itzg** [comment]
Modpack server script is useless for automated startup. README says to run the installer manually??? Start script runs the installer but not the forge server jar???

![image](https://user-images.githubusercontent.com/988985/124398109-8e661200-dcd9-11eb-8aee-df9360dbb8b1.png)

Downloaded 25.5 and it doesn't even have a start script???

![image](https://user-images.githubusercontent.com/988985/124398142-beadb080-dcd9-11eb-88f9-00437f483938.png)

Works with `USE_MODPACK_START_SCRIPT=false` as shown here:

```
version: "3"

services: 
    minecraft-better:
        volumes: 
            - ./data:/data
            - ./modpacks:/modpacks:ro
        ports:
            - '25566:25565'
        environment:
            - EULA=TRUE
            - MAX_MEMORY=4G
            - TYPE=CURSEFORGE
            - CF_SERVER_MOD=/modpacks/Better+Minecraft+Server+Pack+[FORGE]+v23.5.zip
            - USE_MODPACK_START_SCRIPT=false
        image: itzg/minecraft-server:java8
```
