### ISSUE TITLE
custom world files location?

### ISSUE THREAD

**Issue by iuliandita** [itzg/docker-minecraft-server#947]
This is more of a question rather than an issue.
I set up a Minecraft server for my son, and he created this custom world he wants to play with his friends.
Where do I put these files? Where should I mount them?
I have a level.dat, a session.lock and a region folder filled with .mca files (all inside the ./mc directory).
I tried mapping this directory, but on server start, it creates a random new world...
I pruned everything and started from scratch, but it's the same behavior.
Thanks a bunch!

Here's my docker-compose file:

```
version: "3"

services:
  mc:
    ports:
      - "25565:25565"
      - "25575:25575"

    environment:
      EULA: "TRUE"
      TZ: "Europe/Berlin"
      ENABLE_AUTOPAUSE: "TRUE"
      OPS: "***"
      ICON: "***"
      OVERRIDE_ICON: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "***"
      OVERRIDE_SERVER_PROPERTIES: "true"
      MOTD: "***"
      GUI: "FALSE"

    image: itzg/minecraft-server:java16
    container_name: mc

    tty: true
    stdin_open: true
    restart: always

    volumes:
      - ./mc:/data

  backups:
    image: itzg/mc-backup
    container_name: mc-backup

    environment:
      BACKUP_INTERVAL: "24h"
      PRUNE_BACKUPS_DAYS: "7"
      INITIAL_DELAY: "120"
      RCON_HOST: "mc"
      RCON_PASSWORD: "***"
      BACKUP_METHOD: "tar"

    volumes:
      - ./mc:/data:ro
      - ./mc-backups:/backups

volumes:
  mc: {}
```
