### ISSUE TITLE
Invalid type: 'FTBA'

### ISSUE THREAD

**Issue by JustKato** [itzg/docker-minecraft-server#948]
Hey, seems like there's some kind of bug? I have attached my error.
![image](https://user-images.githubusercontent.com/13557697/124393634-05b09b80-dd04-11eb-8d7f-e8ca54c1cb15.png)

This is my config `(I used the asteriks to censor certain fields.)`:
```yml
version: "3"
# Other docker-compose examples in /examples

services:
  chunkbyte:
    image: itzg/minecraft-server
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 6G
        reservations:
          cpus: "0.1"
          memory: 4G
    ports:
      - "******:25565"
      - "******:25575"
    volumes:
      - "/home/kato/Raid/Servers/StoneBlock:/data"
    environment:
      EULA: "TRUE"
      TYPE: FTBA
      FTB_MODPACK_ID: "4"
      ENABLE_RCON: "TRUE"
      RCON_PASSWORD: "*******************"
      RCON_PORT: 25570
      INIT_MEMORY: "4G"
      MAX_MEMORY: "6G"
      USE_AIKAR_FLAGS: "TRUE"
      restart: unless-stopped
```
