### ISSUE TITLE
I can't run specific minecraft version with fabric server

### ISSUE THREAD

**Issue by OldBigBuddha** [itzg/docker-minecraft-server#964]
I was running fabric server for Minecraft 1.17 on my server. But when I re-build my docker-compose, my container boot with Minecraft 1.17.1.

This is my `docker-compose.yml`:
```yaml
version: "3"

services:
  mc-ksu:
    image: itzg/minecraft-server
    container_name: mc-ksu
    environment:
      EULA: "TRUE"
      MEMORY: "6G"
      TZ: "Asia/Tokyo"
      TYPE: "FABRIC"
      VERSION: "1.17"
    volumes:
      - ./data:/data
    tty: true
    stdin_open: true
    restart: always
    deploy:
      resources:
        limits:
          memory: 7.5G

  backup-ksu:
    image: itzg/mc-backup
    container_name: mc-ksu-backup
    environment:
      - RCON_HOST=mc-ksu
    depends_on:
      - mc-ksu
    volumes:
      - ./data:/data:ro
      - ./backups:/backups

networks:
  default:
    external:
      name: minecraft
```

And this is container logs:
```
mc-ksu        | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 10 1000 1000 4096 Jul 10 04:01 /data'
mc-ksu        | [init] Resolved version given 1.17 into 1.17
mc-ksu        | [init] Resolving type given FABRIC
mc-ksu        | [init] Checking Fabric version information.
mc-ksu        | [init] server.properties already created, skipping
mc-ksu        | [init] Checking for JSON files.
mc-ksu        | [init] Setting initial memory to 6G and max to 6G
mc-ksu        | [init] Starting the Minecraft server...
mc-ksu        | [04:21:13] [main/INFO]: Loading for game Minecraft 1.17.1
mc-ksu        | [04:21:13] [main/FATAL]: A critical error occurred
mc-ksu        | net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
mc-ksu        |  - Mod 'Lithium' (lithium) requires version 1.17 of mod 'Minecraft' (minecraft), but a non-matching version is present: 1.17.1!
mc-ksu        | 	 - You must install version 1.17 of 'Minecraft' (minecraft).
mc-ksu        | 	 - Mod 'Minecraft' (minecraft) v1.17.1 is being loaded from the user's mod directory.
mc-ksu        | 	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:342) ~[fabric-server-launch.jar:?]
mc-ksu        | 	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-server-launch.jar:?]
mc-ksu        | 	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-server-launch.jar:?]
mc-ksu        | 	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-server-launch.jar:?]
mc-ksu        | 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-server-launch.jar:?]
mc-ksu        | 	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
mc-ksu        | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
mc-ksu        | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
mc-ksu        | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
mc-ksu        | 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
mc-ksu        | 	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
mc-ksu        | 	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
mc-ksu        | 	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
mc-ksu        | 2021-07-10T04:21:13.824+0900	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}
mc-ksu        | 2021-07-10T04:21:13.824+0900	INFO	mc-server-runner	Done
```

Looks like running Minecraft 1.17.1( But I defined `VERSION: 1.17`!)

It was working fine in this configuration until a few days ago, how can I continue with 1.17 instead of updating the mod?
