### ISSUE TITLE
Can't restart Airplan(latest) server container because of environment variable error in "start-deployAirplane" script file

### ISSUE THREAD

**Issue by IceBlues** [itzg/docker-minecraft-server#979]
Windows 10, Docker Desktop 3.5.2, WSL 2 based engine
ImageVersion: latest(dbea19a356e9)

I create a Airplane Server using following docker-compose:

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "AIRPLANE"
      VERSION: "LATEST"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - "./minecraft-data:/data"
```

First initialization, everything is ok. But I found I can't restart using
`docker-compose start` or `docker-compose up -d` after stop container,
and get this error in logs:
```
[init] Using Airplane-1.17 branch
/start-deployAirplane: line 35: FORCE_REDOWNLOAD: unbound variable
```

code in start-deployAirplane
```
[35 line]  if [ ! -f "$SERVER" ] || isTrue "$FORCE_REDOWNLOAD"; then
```
so I try to delete judging about $FORCE_REDOWNLOAD and container can restart correctly.
I also try to add `FORCE_REDOWNLOAD` environment variable in my docker-compose.yml file and can fix it too. like this:

```
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "AIRPLANE"
      VERSION: "LATEST"
      MEMORY: "2G"
      FORCE_REDOWNLOAD: "false"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - "./minecraft-data:/data"
```

I checked the document and looks like the `FORCE_REDOWNLOAD` variable is not a forcible variable.
so, is there something wrong about ` FORCE_REDOWNLOAD`?
